/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_0072B950_mkey_0_pos_0072A200[] = {
	{ 0, 0, -1.8759f, 0 },
	{ 1, 0, -1.879f, 0 },
	{ 2, 0, -1.8862f, 0 },
	{ 3, 0, -1.8945f, 0 },
	{ 4, 0, -1.9007f, 0 },
	{ 5, 0, -1.9017f, 0 },
	{ 6, 0, -1.8945f, 0 },
	{ 7, 0, -1.8759f, 0 },
	{ 8, 0, -1.842f, 0 },
	{ 9, 0, -1.7942f, 0 },
	{ 10, 0, -1.7372f, 0 },
	{ 11, 0, -1.6759f, 0 },
	{ 12, 0, -1.615f, 0 },
	{ 13, 0, -1.5593f, 0 },
	{ 14, 0, -1.5135f, 0 },
	{ 15, 0, -1.4826f, 0 },
	{ 16, 0, -1.4712f, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_0_rot_0072A310[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0xFFF, 0 },
	{ 2, 0, 0x1FFF, 0 },
	{ 3, 0, 0x2FFF, 0 },
	{ 4, 0, 0x3FFF, 0 },
	{ 5, 0, 0x4FFF, 0 },
	{ 6, 0, 0x5FFF, 0 },
	{ 7, 0, 0x6FFF, 0 },
	{ 8, 0, 0x7FFF, 0 },
	{ 9, 0, 0x8FFF, 0 },
	{ 10, 0, 0x9FFF, 0 },
	{ 11, 0, 0xAFFF, 0 },
	{ 12, 0, 0xBFFF, 0 },
	{ 13, 0, 0xCFFF, 0 },
	{ 14, 0, 0xDFFF, 0 },
	{ 15, 0, 0xEFFF, 0 },
	{ 16, 0, 0xFFFF, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_1_rot_0072A420[] = {
	{ 0, 0, 0xFFFFCEF7, 0x88E },
	{ 16, 0, 0xFFFFCEF7, 0x88E }
};

NJS_MKEY_A animation_0072B950_mkey_11_rot_0072A440[] = {
	{ 0, 0xFFFFFF98, 0xB68, 0 },
	{ 16, 0xFFFFFF98, 0xB68, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_12_rot_0072A460[] = {
	{ 0, 0, 0xFFFFF60B, 0x87A7 },
	{ 1, 0, 0xFFFFF42F, 0x8677 },
	{ 2, 0, 0xFFFFEF41, 0x831F },
	{ 3, 0, 0xFFFFE891, 0x7DD1 },
	{ 4, 0, 0xFFFFE202, 0x7706 },
	{ 5, 0, 0xFFFFDD1E, 0x6FE6 },
	{ 6, 0, 0xFFFFDA3B, 0x6A23 },
	{ 7, 0, 0xFFFFD8FB, 0x675F },
	{ 8, 0, 0xFFFFD8BC, 0x67B3 },
	{ 9, 0, 0xFFFFD90B, 0x6A09 },
	{ 10, 0, 0xFFFFD9FE, 0x6E0A },
	{ 11, 0, 0xFFFFDBC4, 0x733E },
	{ 12, 0, 0xFFFFDE75, 0x78ED },
	{ 13, 0, 0xFFFFE1DF, 0x7E44 },
	{ 14, 0, 0xFFFFE565, 0x8290 },
	{ 15, 0, 0xFFFFE823, 0x855E },
	{ 16, 0, 0xFFFFE937, 0x8660 }
};

NJS_MKEY_A animation_0072B950_mkey_15_rot_0072A570[] = {
	{ 0, 0, 0xC02, 0xFFFF8854 },
	{ 1, 0, 0xBA0, 0xFFFF88EC },
	{ 2, 0, 0xAC8, 0xFFFF89EC },
	{ 3, 0, 0x9E0, 0xFFFF8A02 },
	{ 4, 0, 0x97A, 0xFFFF88CA },
	{ 5, 0, 0x9D0, 0xFFFF87C1 },
	{ 6, 0, 0xA50, 0xFFFF8774 },
	{ 7, 0, 0xA88, 0xFFFF87AD },
	{ 8, 0, 0xA36, 0xFFFF885D },
	{ 9, 0, 0x97E, 0xFFFF897C },
	{ 10, 0, 0x8C3, 0xFFFF8ADD },
	{ 11, 0, 0x883, 0xFFFF8C04 },
	{ 12, 0, 0x8C9, 0xFFFF8C29 },
	{ 13, 0, 0x938, 0xFFFF8B66 },
	{ 14, 0, 0x9E3, 0xFFFF8A2C },
	{ 15, 0, 0xAB7, 0xFFFF88FA },
	{ 16, 0, 0xB26, 0xFFFF886A }
};

NJS_MKEY_A animation_0072B950_mkey_19_rot_0072A680[] = {
	{ 0, 0, 0xFFFFF4D7, 0xFFFF8730 },
	{ 1, 0, 0xFFFFF261, 0xFFFF88A9 },
	{ 2, 0, 0xFFFFEC6B, 0xFFFF8B66 },
	{ 3, 0, 0xFFFFE7A9, 0xFFFF8BD7 },
	{ 4, 0, 0xFFFFE618, 0xFFFF8A44 },
	{ 5, 0, 0xFFFFE54A, 0xFFFF880E },
	{ 6, 0, 0xFFFFE4D9, 0xFFFF85D3 },
	{ 7, 0, 0xFFFFE4A9, 0xFFFF84C1 },
	{ 8, 0, 0xFFFFE533, 0xFFFF8524 },
	{ 9, 0, 0xFFFFE68B, 0xFFFF8662 },
	{ 10, 0, 0xFFFFE812, 0xFFFF881B },
	{ 11, 0, 0xFFFFE8F2, 0xFFFF8A3A },
	{ 12, 0, 0xFFFFE990, 0xFFFF8C2B },
	{ 13, 0, 0xFFFFEAB5, 0xFFFF8C98 },
	{ 14, 0, 0xFFFFEBF9, 0xFFFF8B84 },
	{ 15, 0, 0xFFFFED01, 0xFFFF89DA },
	{ 16, 0, 0xFFFFED70, 0xFFFF8902 }
};

NJS_MKEY_A animation_0072B950_mkey_25_rot_0072A790[] = {
	{ 0, 0, 0x2F9B, 0xFFFFAD1F },
	{ 1, 0, 0x2EAB, 0xFFFFB0C9 },
	{ 2, 0, 0x2BD9, 0xFFFFB877 },
	{ 3, 0, 0x278A, 0xFFFFBFB3 },
	{ 4, 0, 0x22E0, 0xFFFFC4D8 },
	{ 5, 0, 0x1EEE, 0xFFFFC812 },
	{ 6, 0, 0x1C51, 0xFFFFC9DC },
	{ 7, 0, 0x1B5E, 0xFFFFCA74 },
	{ 8, 0, 0x1BF4, 0xFFFFCA17 },
	{ 9, 0, 0x1D95, 0xFFFFC906 },
	{ 10, 0, 0x201F, 0xFFFFC72D },
	{ 11, 0, 0x2360, 0xFFFFC460 },
	{ 12, 0, 0x2704, 0xFFFFC061 },
	{ 13, 0, 0x2A87, 0xFFFFBB11 },
	{ 14, 0, 0x2D55, 0xFFFFB4E5 },
	{ 15, 0, 0x2F0A, 0xFFFFAF70 },
	{ 16, 0, 0x2F9B, 0xFFFFAD1F }
};

NJS_MKEY_A animation_0072B950_mkey_26_rot_0072A8A0[] = {
	{ 0, 0, 0xFFFFFD4C, 0xFFFFEDAF },
	{ 1, 0, 0xFFFFFE6B, 0xFFFFEDC8 },
	{ 2, 0, 0x50, 0xFFFFEE97 },
	{ 3, 0, 0x10B, 0xFFFFF05C },
	{ 4, 0, 0x76, 0xFFFFF287 },
	{ 5, 0, 0xFFFFFF82, 0xFFFFF46C },
	{ 6, 0, 0xFFFFFED1, 0xFFFFF5AB },
	{ 7, 0, 0xFFFFFE92, 0xFFFFF61D },
	{ 8, 0, 0xFFFFFEB9, 0xFFFFF5D7 },
	{ 9, 0, 0xFFFFFF27, 0xFFFFF511 },
	{ 10, 0, 0xFFFFFFD1, 0xFFFFF3DA },
	{ 11, 0, 0x90, 0xFFFFF24A },
	{ 12, 0, 0x107, 0xFFFFF098 },
	{ 13, 0, 0xBC, 0xFFFFEF17 },
	{ 14, 0, 0xFFFFFF88, 0xFFFFEE1A },
	{ 15, 0, 0xFFFFFE04, 0xFFFFEDBA },
	{ 16, 0, 0xFFFFFD4C, 0xFFFFEDAF }
};

NJS_MKEY_A animation_0072B950_mkey_27_rot_0072A9B0[] = {
	{ 0, 0, 0xFFFFF802, 0xFFFFEF82 },
	{ 1, 0, 0xFFFFF87A, 0xFFFFEF03 },
	{ 2, 0, 0xFFFFF905, 0xFFFFEE67 },
	{ 3, 0, 0xFFFFF87C, 0xFFFFEEFA },
	{ 4, 0, 0xFFFFF740, 0xFFFFF10B },
	{ 5, 0, 0xFFFFF66D, 0xFFFFF388 },
	{ 6, 0, 0xFFFFF632, 0xFFFFF551 },
	{ 7, 0, 0xFFFFF62F, 0xFFFFF5F6 },
	{ 8, 0, 0xFFFFF630, 0xFFFFF591 },
	{ 9, 0, 0xFFFFF645, 0xFFFFF474 },
	{ 10, 0, 0xFFFFF69F, 0xFFFFF2BD },
	{ 11, 0, 0xFFFFF762, 0xFFFFF0C4 },
	{ 12, 0, 0xFFFFF85C, 0xFFFFEF25 },
	{ 13, 0, 0xFFFFF8FB, 0xFFFFEE6B },
	{ 14, 0, 0xFFFFF8DE, 0xFFFFEE98 },
	{ 15, 0, 0xFFFFF851, 0xFFFFEF2F },
	{ 16, 0, 0xFFFFF802, 0xFFFFEF82 }
};

NJS_MKEY_A animation_0072B950_mkey_30_rot_0072AAC0[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_32_rot_0072AB00[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 16, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_31_rot_0072AAE0[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_0072B950_mkey_36_rot_0072AB20[] = {
	{ 0, 0, 0xFFFFF75D, 0xFFFFA305 },
	{ 1, 0, 0xFFFFF773, 0xFFFFA31C },
	{ 2, 0, 0xFFFFF7A5, 0xFFFFA351 },
	{ 3, 0, 0xFFFFF7DD, 0xFFFFA38C },
	{ 4, 0, 0xFFFFF805, 0xFFFFA3B7 },
	{ 5, 0, 0xFFFFF80C, 0xFFFFA3BE },
	{ 6, 0, 0xFFFFF7DD, 0xFFFFA38C },
	{ 7, 0, 0xFFFFF75D, 0xFFFFA305 },
	{ 8, 0, 0xFFFFF610, 0xFFFFA0DE },
	{ 9, 0, 0xFFFFF384, 0xFFFF9C5B },
	{ 10, 0, 0xFFFFEFA0, 0xFFFF9682 },
	{ 11, 0, 0xFFFFEA47, 0xFFFF923A },
	{ 12, 0, 0xFFFFE0A4, 0xFFFF9383 },
	{ 13, 0, 0xFFFFCFF6, 0xFFFFA42C },
	{ 14, 0, 0xFFFFCE4F, 0xFFFFE312 },
	{ 15, 0, 0xFFFFD7E2, 0xFFFFF357 },
	{ 16, 0, 0xFFFFDB27, 0xFFFFF5D8 }
};

NJS_MKEY_A animation_0072B950_mkey_37_rot_0072AC30[] = {
	{ 0, 0, 0xFFFFF9A7, 0xFFFFF8C2 },
	{ 1, 0, 0xFFFFF9B6, 0xFFFFF8E9 },
	{ 2, 0, 0xFFFFF9DA, 0xFFFFF941 },
	{ 3, 0, 0xFFFFFA01, 0xFFFFF9A2 },
	{ 4, 0, 0xFFFFFA1E, 0xFFFFF9E9 },
	{ 5, 0, 0xFFFFFA23, 0xFFFFF9F4 },
	{ 6, 0, 0xFFFFFA01, 0xFFFFF9A2 },
	{ 7, 0, 0xFFFFF9A7, 0xFFFFF8C2 },
	{ 8, 0, 0xFFFFF8B2, 0xFFFFF5E7 },
	{ 9, 0, 0xFFFFF742, 0xFFFFF00A },
	{ 10, 0, 0xFFFFF6B3, 0xFFFFE99C },
	{ 11, 0, 0xFFFFF783, 0xFFFFE681 },
	{ 12, 0, 0xFFFFF909, 0xFFFFE65B },
	{ 13, 0, 0xFFFFF89D, 0xFFFFE6B4 },
	{ 14, 0, 0xFFFFE2CA, 0xFFFFF8C2 },
	{ 15, 0, 0xFFFFDFBF, 0xFFFFFD8D },
	{ 16, 0, 0xFFFFDF66, 0xFFFFFC8F }
};

NJS_MKEY_A animation_0072B950_mkey_38_rot_0072AD40[] = {
	{ 0, 0, 0x148F, 0x7E0 },
	{ 1, 0, 0x146F, 0x804 },
	{ 2, 0, 0x1426, 0x851 },
	{ 3, 0, 0x13D3, 0x89E },
	{ 4, 0, 0x1396, 0x8D2 },
	{ 5, 0, 0x138C, 0x8DA },
	{ 6, 0, 0x13D3, 0x89E },
	{ 7, 0, 0x148F, 0x7E0 },
	{ 8, 0, 0x16AE, 0x42D },
	{ 9, 0, 0x177C, 0xFFFFF72F },
	{ 10, 0, 0x1168, 0xFFFFEA83 },
	{ 11, 0, 0xC3C, 0xFFFFE7F1 },
	{ 12, 0, 0x6D8, 0xFFFFE6D7 },
	{ 13, 0, 0xFFFFF9AA, 0xFFFFE84E },
	{ 14, 0, 0xFFFFEC98, 0x69A },
	{ 15, 0, 0xFFFFF414, 0xA21 },
	{ 16, 0, 0xFFFFF59D, 0x8A4 }
};

NJS_MKEY_A animation_0072B950_mkey_41_rot_0072AE50[] = {
	{ 0, 0x4A8F, 0xFFFFF70A, 0 },
	{ 1, 0x4B68, 0xFFFFF70A, 0 },
	{ 2, 0x4D63, 0xFFFFF70A, 0 },
	{ 3, 0x4FA6, 0xFFFFF70A, 0 },
	{ 4, 0x5158, 0xFFFFF70A, 0 },
	{ 5, 0x51A0, 0xFFFFF70A, 0 },
	{ 6, 0x4FA6, 0xFFFFF70A, 0 },
	{ 7, 0x4A8F, 0xFFFFF70A, 0 },
	{ 8, 0x4149, 0xFFFFF70A, 0 },
	{ 9, 0x3431, 0xFFFFF70A, 0 },
	{ 10, 0x2497, 0xFFFFF70A, 0 },
	{ 11, 0x13CB, 0xFFFFF70A, 0 },
	{ 12, 0x31C, 0xFFFFF70A, 0 },
	{ 13, 0xFFFFF3DB, 0xFFFFF70A, 0 },
	{ 14, 0xFFFFE755, 0xFFFFF70A, 0 },
	{ 15, 0xFFFFDEDB, 0xFFFFF70A, 0 },
	{ 16, 0xFFFFDBBE, 0xFFFFF70A, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_43_rot_0072AF80[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_42_rot_0072AF60[] = {
	{ 0, 0, 0xFFFFF70A, 0 },
	{ 16, 0, 0xFFFFF70A, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_46_rot_0072AFA0[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_47_rot_0072AFC0[] = {
	{ 0, 0xFFFFF720, 0x429, 0xFFFFAC70 },
	{ 1, 0xFFFFF720, 0x429, 0xFFFFAC8C },
	{ 2, 0xFFFFF720, 0x429, 0xFFFFACCF },
	{ 3, 0xFFFFF720, 0x429, 0xFFFFAD1C },
	{ 4, 0xFFFFF720, 0x429, 0xFFFFAD55 },
	{ 5, 0xFFFFF720, 0x429, 0xFFFFAD5F },
	{ 6, 0xFFFFF720, 0x429, 0xFFFFAD1C },
	{ 7, 0xFFFFF720, 0x429, 0xFFFFAC70 },
	{ 8, 0xFFFFF720, 0x429, 0xFFFFAB35 },
	{ 9, 0xFFFFF720, 0x429, 0xFFFFA97A },
	{ 10, 0xFFFFF720, 0x429, 0xFFFFA769 },
	{ 11, 0xFFFFF720, 0x429, 0xFFFFA530 },
	{ 12, 0xFFFFF720, 0x429, 0xFFFFA2FB },
	{ 13, 0xFFFFF720, 0x429, 0xFFFFA0F6 },
	{ 14, 0xFFFFF720, 0x429, 0xFFFF9F4D },
	{ 15, 0xFFFFF720, 0x429, 0xFFFF9E2E },
	{ 16, 0xFFFFF720, 0x429, 0xFFFF9DC5 }
};

NJS_MKEY_A animation_0072B950_mkey_48_rot_0072B0D0[] = {
	{ 0, 0, 0, 0x26D4 },
	{ 16, 0, 0, 0x26D4 }
};

NJS_MKEY_A animation_0072B950_mkey_49_rot_0072B0F0[] = {
	{ 0, 0, 0, 0x2A81 },
	{ 16, 0, 0, 0x2A81 }
};

NJS_MKEY_A animation_0072B950_mkey_52_rot_0072B110[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFCA39 },
	{ 1, 0x1C1C, 0xFFFFF772, 0xFFFFCA1F },
	{ 2, 0x1C1C, 0xFFFFF772, 0xFFFFC9E3 },
	{ 3, 0x1C1C, 0xFFFFF772, 0xFFFFC99F },
	{ 4, 0x1C1C, 0xFFFFF772, 0xFFFFC96C },
	{ 5, 0x1C1C, 0xFFFFF772, 0xFFFFC964 },
	{ 6, 0x1C1C, 0xFFFFF772, 0xFFFFC99F },
	{ 7, 0x1C1C, 0xFFFFF772, 0xFFFFCA39 },
	{ 8, 0x1C1C, 0xFFFFF772, 0xFFFFCB50 },
	{ 9, 0x1C1C, 0xFFFFF772, 0xFFFFCCDA },
	{ 10, 0x1C1C, 0xFFFFF772, 0xFFFFCEB0 },
	{ 11, 0x1C1C, 0xFFFFF772, 0xFFFFD0AA },
	{ 12, 0x1C1C, 0xFFFFF772, 0xFFFFD2A0 },
	{ 13, 0x1C1C, 0xFFFFF772, 0xFFFFD46C },
	{ 14, 0x1C1C, 0xFFFFF772, 0xFFFFD5E5 },
	{ 15, 0x1C1C, 0xFFFFF772, 0xFFFFD6E4 },
	{ 16, 0x1C1C, 0xFFFFF772, 0xFFFFD742 }
};

NJS_MKEY_A animation_0072B950_mkey_53_rot_0072B220[] = {
	{ 0, 0, 0, 0xFFFFEB39 },
	{ 1, 0, 0, 0xFFFFEB10 },
	{ 2, 0, 0, 0xFFFFEAB1 },
	{ 3, 0, 0, 0xFFFFEA45 },
	{ 4, 0, 0, 0xFFFFE9F3 },
	{ 5, 0, 0, 0xFFFFE9E6 },
	{ 6, 0, 0, 0xFFFFEA45 },
	{ 7, 0, 0, 0xFFFFEB39 },
	{ 8, 0, 0, 0xFFFFECF6 },
	{ 9, 0, 0, 0xFFFFEF6B },
	{ 10, 0, 0, 0xFFFFF257 },
	{ 11, 0, 0, 0xFFFFF57E },
	{ 12, 0, 0, 0xFFFFF89F },
	{ 13, 0, 0, 0xFFFFFB7B },
	{ 14, 0, 0, 0xFFFFFDD4 },
	{ 15, 0, 0, 0xFFFFFF6B },
	{ 16, 0, 0, 0 }
};

NJS_MKEY_A animation_0072B950_mkey_57_rot_0072B330[] = {
	{ 0, 0x1E26, 0xFFFFE503, 0xFFFF63F2 },
	{ 1, 0x1E26, 0xFFFFE503, 0xFFFF63C3 },
	{ 2, 0x1E26, 0xFFFFE503, 0xFFFF6355 },
	{ 3, 0x1E26, 0xFFFFE503, 0xFFFF62D8 },
	{ 4, 0x1E26, 0xFFFFE503, 0xFFFF627A },
	{ 5, 0x1E26, 0xFFFFE503, 0xFFFF626A },
	{ 6, 0x1E26, 0xFFFFE503, 0xFFFF62D8 },
	{ 7, 0x1E26, 0xFFFFE503, 0xFFFF63F2 },
	{ 8, 0x1E26, 0xFFFFE503, 0xFFFF65F5 },
	{ 9, 0x1E26, 0xFFFFE503, 0xFFFF68CC },
	{ 10, 0x1E26, 0xFFFFE503, 0xFFFF6C2F },
	{ 11, 0x1E26, 0xFFFFE503, 0xFFFF6FD3 },
	{ 12, 0x1E26, 0xFFFFE503, 0xFFFF7372 },
	{ 13, 0x1E26, 0xFFFFE503, 0xFFFF76C1 },
	{ 14, 0x1E26, 0xFFFFE503, 0xFFFF7979 },
	{ 15, 0x1E26, 0xFFFFE503, 0xFFFF7B4F },
	{ 16, 0x1E26, 0xFFFFE503, 0xFFFF7BFC }
};

NJS_MKEY_A animation_0072B950_mkey_58_rot_0072B440[] = {
	{ 0, 0, 0, 0x1889 },
	{ 16, 0, 0, 0x1889 }
};

NJS_MKEY_A animation_0072B950_mkey_59_rot_0072B460[] = {
	{ 0, 0, 0, 0x20EA },
	{ 16, 0, 0, 0x20EA }
};

NJS_MKEY_A animation_0072B950_mkey_62_rot_0072B480[] = {
	{ 0, 0x10B4, 0x3FE, 0x413 },
	{ 16, 0x10B4, 0x3FE, 0x413 }
};

NJS_MKEY_A animation_0072B950_mkey_63_rot_0072B4A0[] = {
	{ 0, 0, 0, 0xFFFFEAD1 },
	{ 16, 0, 0, 0xFFFFEAD1 }
};

NJS_MDATA2 animation_0072B950_mdat_0072B4C0[] = {
	{ animation_0072B950_mkey_0_pos_0072A200, animation_0072B950_mkey_0_rot_0072A310, LengthOfArray<Uint32>(animation_0072B950_mkey_0_pos_0072A200), LengthOfArray<Uint32>(animation_0072B950_mkey_0_rot_0072A310) },
	{ NULL, animation_0072B950_mkey_1_rot_0072A420, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_1_rot_0072A420) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_11_rot_0072A440, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_11_rot_0072A440) },
	{ NULL, animation_0072B950_mkey_12_rot_0072A460, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_12_rot_0072A460) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_15_rot_0072A570, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_15_rot_0072A570) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_19_rot_0072A680, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_19_rot_0072A680) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_25_rot_0072A790, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_25_rot_0072A790) },
	{ NULL, animation_0072B950_mkey_26_rot_0072A8A0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_26_rot_0072A8A0) },
	{ NULL, animation_0072B950_mkey_27_rot_0072A9B0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_27_rot_0072A9B0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_30_rot_0072AAC0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_30_rot_0072AAC0) },
	{ NULL, animation_0072B950_mkey_32_rot_0072AB00, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_32_rot_0072AB00) },
	{ NULL, animation_0072B950_mkey_31_rot_0072AAE0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_31_rot_0072AAE0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_36_rot_0072AB20, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_36_rot_0072AB20) },
	{ NULL, animation_0072B950_mkey_37_rot_0072AC30, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_37_rot_0072AC30) },
	{ NULL, animation_0072B950_mkey_38_rot_0072AD40, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_38_rot_0072AD40) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_41_rot_0072AE50, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_41_rot_0072AE50) },
	{ NULL, animation_0072B950_mkey_43_rot_0072AF80, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_43_rot_0072AF80) },
	{ NULL, animation_0072B950_mkey_42_rot_0072AF60, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_42_rot_0072AF60) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_46_rot_0072AFA0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_46_rot_0072AFA0) },
	{ NULL, animation_0072B950_mkey_47_rot_0072AFC0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_47_rot_0072AFC0) },
	{ NULL, animation_0072B950_mkey_48_rot_0072B0D0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_48_rot_0072B0D0) },
	{ NULL, animation_0072B950_mkey_49_rot_0072B0F0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_49_rot_0072B0F0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_52_rot_0072B110, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_52_rot_0072B110) },
	{ NULL, animation_0072B950_mkey_53_rot_0072B220, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_53_rot_0072B220) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_57_rot_0072B330, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_57_rot_0072B330) },
	{ NULL, animation_0072B950_mkey_58_rot_0072B440, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_58_rot_0072B440) },
	{ NULL, animation_0072B950_mkey_59_rot_0072B460, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_59_rot_0072B460) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072B950_mkey_62_rot_0072B480, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_62_rot_0072B480) },
	{ NULL, animation_0072B950_mkey_63_rot_0072B4A0, 0, LengthOfArray<Uint32>(animation_0072B950_mkey_63_rot_0072B4A0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbss1 = { animation_0072B950_mdat_0072B4C0, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbss1 = { AMY_OBJECTS[0], &motion_a_sbss1 };
