/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_00716578_mkey_0_pos_007147F8[] = {
	{ 0, -0.4415f, -2.0888f, 0 },
	{ 1, -0.4476f, -2.0728f, 0 },
	{ 2, -0.4634f, -2.0315f, 0 },
	{ 3, -0.4849f, -1.975f, 0 },
	{ 4, -0.5084f, -1.9134f, 0 },
	{ 5, -0.53f, -1.8569f, 0 },
	{ 6, -0.5457f, -1.8156f, 0 },
	{ 7, -0.5519f, -1.7996f, 0 },
	{ 8, -0.5481f, -1.8095f, 0 },
	{ 9, -0.5379f, -1.8361f, 0 },
	{ 10, -0.5232f, -1.8746f, 0 },
	{ 11, -0.5058f, -1.9202f, 0 },
	{ 12, -0.4875f, -1.9682f, 0 },
	{ 13, -0.4701f, -2.0138f, 0 },
	{ 14, -0.4554f, -2.0523f, 0 },
	{ 15, -0.4453f, -2.0789f, 0 },
	{ 16, -0.4415f, -2.0888f, 0 }
};

NJS_MKEY_A animation_00716578_mkey_1_rot_00714908[] = {
	{ 0, 0, 0xFFFFEAAB, 0x1184 },
	{ 16, 0, 0xFFFFEAAB, 0x1184 }
};

NJS_MKEY_A animation_00716578_mkey_12_rot_00714928[] = {
	{ 0, 0x2DA, 0xFFFFEA6C, 0x7D2F },
	{ 1, 0x2EB, 0xFFFFEA6E, 0x7CE4 },
	{ 2, 0x318, 0xFFFFEA75, 0x7C1F },
	{ 3, 0x355, 0xFFFFEA81, 0x7B0D },
	{ 4, 0x397, 0xFFFFEA92, 0x79E0 },
	{ 5, 0x3D4, 0xFFFFEAA5, 0x78C7 },
	{ 6, 0x401, 0xFFFFEAB6, 0x77F8 },
	{ 7, 0x413, 0xFFFFEABD, 0x77A7 },
	{ 8, 0x408, 0xFFFFEAB8, 0x77D9 },
	{ 9, 0x3EB, 0xFFFFEAAD, 0x785F },
	{ 10, 0x3C1, 0xFFFFEA9F, 0x791F },
	{ 11, 0x390, 0xFFFFEA90, 0x7A01 },
	{ 12, 0x35C, 0xFFFFEA83, 0x7AEC },
	{ 13, 0x32B, 0xFFFFEA78, 0x7BCA },
	{ 14, 0x301, 0xFFFFEA71, 0x7C82 },
	{ 15, 0x2E4, 0xFFFFEA6D, 0x7D01 },
	{ 16, 0x2DA, 0xFFFFEA6C, 0x7D2F }
};

NJS_MKEY_A animation_00716578_mkey_15_rot_00714A38[] = {
	{ 0, 0, 0xC66, 0xFFFF8544 },
	{ 1, 0, 0xC6B, 0xFFFF8562 },
	{ 2, 0, 0xC79, 0xFFFF85AF },
	{ 3, 0, 0xC8A, 0xFFFF861C },
	{ 4, 0, 0xC9A, 0xFFFF8696 },
	{ 5, 0, 0xCA6, 0xFFFF8708 },
	{ 6, 0, 0xCAC, 0xFFFF875C },
	{ 7, 0, 0xCAF, 0xFFFF877E },
	{ 8, 0, 0xCAD, 0xFFFF8769 },
	{ 9, 0, 0xCA9, 0xFFFF8732 },
	{ 10, 0, 0xCA2, 0xFFFF86E4 },
	{ 11, 0, 0xC98, 0xFFFF8688 },
	{ 12, 0, 0xC8C, 0xFFFF8629 },
	{ 13, 0, 0xC7F, 0xFFFF85D1 },
	{ 14, 0, 0xC72, 0xFFFF8588 },
	{ 15, 0, 0xC69, 0xFFFF8557 },
	{ 16, 0, 0xC66, 0xFFFF8544 }
};

NJS_MKEY_A animation_00716578_mkey_19_rot_00714B48[] = {
	{ 0, 0, 0xFFFFF4E6, 0xFFFF85D3 },
	{ 1, 0, 0xFFFFF4EF, 0xFFFF85EC },
	{ 2, 0, 0xFFFFF507, 0xFFFF862B },
	{ 3, 0, 0xFFFFF528, 0xFFFF8685 },
	{ 4, 0, 0xFFFFF54B, 0xFFFF86E8 },
	{ 5, 0, 0xFFFFF56B, 0xFFFF8746 },
	{ 6, 0, 0xFFFFF581, 0xFFFF878C },
	{ 7, 0, 0xFFFFF58A, 0xFFFF87A7 },
	{ 8, 0, 0xFFFFF585, 0xFFFF8797 },
	{ 9, 0, 0xFFFFF576, 0xFFFF8769 },
	{ 10, 0, 0xFFFFF561, 0xFFFF8729 },
	{ 11, 0, 0xFFFFF547, 0xFFFF86DD },
	{ 12, 0, 0xFFFFF52B, 0xFFFF8690 },
	{ 13, 0, 0xFFFFF511, 0xFFFF8647 },
	{ 14, 0, 0xFFFFF4FB, 0xFFFF860B },
	{ 15, 0, 0xFFFFF4EB, 0xFFFF85E2 },
	{ 16, 0, 0xFFFFF4E6, 0xFFFF85D3 }
};

NJS_MKEY_A animation_00716578_mkey_25_rot_00714C58[] = {
	{ 0, 0, 0x2A6D, 0xFFFFE10E },
	{ 16, 0, 0x2A6D, 0xFFFFE10E }
};

NJS_MKEY_A animation_00716578_mkey_26_rot_00714C78[] = {
	{ 0, 0, 0xD3, 0xFFFFEF92 },
	{ 1, 0, 0xEC, 0xFFFFEFC2 },
	{ 2, 0, 0x12C, 0xFFFFF040 },
	{ 3, 0, 0x186, 0xFFFFF0EF },
	{ 4, 0, 0x1E8, 0xFFFFF1B0 },
	{ 5, 0, 0x243, 0xFFFFF263 },
	{ 6, 0, 0x286, 0xFFFFF2E8 },
	{ 7, 0, 0x2A1, 0xFFFFF31C },
	{ 8, 0, 0x290, 0xFFFFF2FC },
	{ 9, 0, 0x265, 0xFFFFF2A6 },
	{ 10, 0, 0x227, 0xFFFFF22B },
	{ 11, 0, 0x1DD, 0xFFFFF19B },
	{ 12, 0, 0x190, 0xFFFFF104 },
	{ 13, 0, 0x148, 0xFFFFF077 },
	{ 14, 0, 0x10C, 0xFFFFF001 },
	{ 15, 0, 0xE2, 0xFFFFEFB0 },
	{ 16, 0, 0xD3, 0xFFFFEF92 }
};

NJS_MKEY_A animation_00716578_mkey_27_rot_00714D88[] = {
	{ 0, 0, 0x1E3, 0xFFFFE2EE },
	{ 1, 0, 0x21D, 0xFFFFE2FF },
	{ 2, 0, 0x2BD, 0xFFFFE332 },
	{ 3, 0, 0x3AB, 0xFFFFE38D },
	{ 4, 0, 0x4CC, 0xFFFFE40F },
	{ 5, 0, 0x5F3, 0xFFFFE4A9 },
	{ 6, 0, 0x6DD, 0xFFFFE530 },
	{ 7, 0, 0x73C, 0xFFFFE56A },
	{ 8, 0, 0x701, 0xFFFFE546 },
	{ 9, 0, 0x667, 0xFFFFE4EA },
	{ 10, 0, 0x594, 0xFFFFE475 },
	{ 11, 0, 0x4AB, 0xFFFFE3FF },
	{ 12, 0, 0x3C9, 0xFFFFE399 },
	{ 13, 0, 0x304, 0xFFFFE34C },
	{ 14, 0, 0x26B, 0xFFFFE317 },
	{ 15, 0, 0x207, 0xFFFFE2F9 },
	{ 16, 0, 0x1E3, 0xFFFFE2EE }
};

NJS_MKEY_A animation_00716578_mkey_30_rot_00714E98[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 1, 0xA7, 0x1953, 0 },
	{ 2, 0x257, 0x1A8C, 0 },
	{ 3, 0x4A6, 0x1C38, 0 },
	{ 4, 0x72A, 0x1E0A, 0 },
	{ 5, 0x979, 0x1FB6, 0 },
	{ 6, 0xB29, 0x20EF, 0 },
	{ 7, 0xBD0, 0x2168, 0 },
	{ 8, 0xB69, 0x211D, 0 },
	{ 9, 0xA53, 0x2054, 0 },
	{ 10, 0x8C0, 0x1F30, 0 },
	{ 11, 0x6E3, 0x1DD7, 0 },
	{ 12, 0x4ED, 0x1C6B, 0 },
	{ 13, 0x310, 0x1B12, 0 },
	{ 14, 0x17D, 0x19EE, 0 },
	{ 15, 0x67, 0x1925, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_00716578_mkey_32_rot_007150B8[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 1, 0, 0x1650, 0 },
	{ 2, 0, 0x1A45, 0 },
	{ 3, 0, 0x1FAE, 0 },
	{ 4, 0, 0x2594, 0 },
	{ 5, 0, 0x2AFD, 0 },
	{ 6, 0, 0x2EF3, 0 },
	{ 7, 0, 0x307B, 0 },
	{ 8, 0, 0x2F88, 0 },
	{ 9, 0, 0x2CFC, 0 },
	{ 10, 0, 0x294D, 0 },
	{ 11, 0, 0x24EE, 0 },
	{ 12, 0, 0x2055, 0 },
	{ 13, 0, 0x1BF6, 0 },
	{ 14, 0, 0x1846, 0 },
	{ 15, 0, 0x15BA, 0 },
	{ 16, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_00716578_mkey_31_rot_00714FA8[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 1, 0x1435, 0, 0xFFFFE7F7 },
	{ 2, 0x16F2, 0, 0xFFFFE7F7 },
	{ 3, 0x1AAF, 0, 0xFFFFE7F7 },
	{ 4, 0x1EC2, 0, 0xFFFFE7F7 },
	{ 5, 0x2280, 0, 0xFFFFE7F7 },
	{ 6, 0x253C, 0, 0xFFFFE7F7 },
	{ 7, 0x264C, 0, 0xFFFFE7F7 },
	{ 8, 0x25A4, 0, 0xFFFFE7F7 },
	{ 9, 0x23E1, 0, 0xFFFFE7F7 },
	{ 10, 0x2155, 0, 0xFFFFE7F7 },
	{ 11, 0x1E50, 0, 0xFFFFE7F7 },
	{ 12, 0x1B22, 0, 0xFFFFE7F7 },
	{ 13, 0x181D, 0, 0xFFFFE7F7 },
	{ 14, 0x1590, 0, 0xFFFFE7F7 },
	{ 15, 0x13CE, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_00716578_mkey_36_rot_007151C8[] = {
	{ 0, 0, 0xFFFFE8F9, 0xFFFFDCAA },
	{ 16, 0, 0xFFFFE8F9, 0xFFFFDCAA }
};

NJS_MKEY_A animation_00716578_mkey_37_rot_007151E8[] = {
	{ 0, 0, 0xFFFFE82D, 0xFFFFF61C },
	{ 1, 0, 0xFFFFE80A, 0xFFFFF65F },
	{ 2, 0, 0xFFFFE7B1, 0xFFFFF711 },
	{ 3, 0, 0xFFFFE737, 0xFFFFF80E },
	{ 4, 0, 0xFFFFE6B2, 0xFFFFF92E },
	{ 5, 0, 0xFFFFE637, 0xFFFFFA43 },
	{ 6, 0, 0xFFFFE5DE, 0xFFFFFB15 },
	{ 7, 0, 0xFFFFE5BB, 0xFFFFFB68 },
	{ 8, 0, 0xFFFFE5D1, 0xFFFFFB34 },
	{ 9, 0, 0xFFFFE60A, 0xFFFFFAAC },
	{ 10, 0, 0xFFFFE65D, 0xFFFFF9EB },
	{ 11, 0, 0xFFFFE6C0, 0xFFFFF90E },
	{ 12, 0, 0xFFFFE728, 0xFFFFF82D },
	{ 13, 0, 0xFFFFE78B, 0xFFFFF75F },
	{ 14, 0, 0xFFFFE7DE, 0xFFFFF6B7 },
	{ 15, 0, 0xFFFFE817, 0xFFFFF646 },
	{ 16, 0, 0xFFFFE82D, 0xFFFFF61C }
};

NJS_MKEY_A animation_00716578_mkey_38_rot_007152F8[] = {
	{ 0, 0, 0xFFFFE3DA, 0xFFFFEBAA },
	{ 1, 0, 0xFFFFE358, 0xFFFFEBE2 },
	{ 2, 0, 0xFFFFE204, 0xFFFFEC88 },
	{ 3, 0, 0xFFFFE02E, 0xFFFFEDA3 },
	{ 4, 0, 0xFFFFDE2E, 0xFFFFEF2F },
	{ 5, 0, 0xFFFFDC61, 0xFFFFF0FB },
	{ 6, 0, 0xFFFFDB1C, 0xFFFFF28F },
	{ 7, 0, 0xFFFFDAA1, 0xFFFFF33C },
	{ 8, 0, 0xFFFFDAED, 0xFFFFF2D0 },
	{ 9, 0, 0xFFFFDBBB, 0xFFFFF1BF },
	{ 10, 0, 0xFFFFDCEF, 0xFFFFF061 },
	{ 11, 0, 0xFFFFDE66, 0xFFFFEEFE },
	{ 12, 0, 0xFFFFDFF5, 0xFFFFEDC9 },
	{ 13, 0, 0xFFFFE172, 0xFFFFECD9 },
	{ 14, 0, 0xFFFFE2B0, 0xFFFFEC30 },
	{ 15, 0, 0xFFFFE38A, 0xFFFFEBCC },
	{ 16, 0, 0xFFFFE3DA, 0xFFFFEBAA }
};

NJS_MKEY_A animation_00716578_mkey_41_rot_00715408[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0xFFFFFF2B, 0x79, 0 },
	{ 2, 0xFFFFFD03, 0x1B2, 0 },
	{ 3, 0xFFFFFA12, 0x35E, 0 },
	{ 4, 0xFFFFF6DC, 0x530, 0 },
	{ 5, 0xFFFFF3EA, 0x6DC, 0 },
	{ 6, 0xFFFFF1C3, 0x815, 0 },
	{ 7, 0xFFFFF0ED, 0x88E, 0 },
	{ 8, 0xFFFFF172, 0x843, 0 },
	{ 9, 0xFFFFF2D4, 0x779, 0 },
	{ 10, 0xFFFFF4D6, 0x656, 0 },
	{ 11, 0xFFFFF737, 0x4FC, 0 },
	{ 12, 0xFFFFF9B7, 0x391, 0 },
	{ 13, 0xFFFFFC18, 0x237, 0 },
	{ 14, 0xFFFFFE19, 0x114, 0 },
	{ 15, 0xFFFFFF7C, 0x4B, 0 },
	{ 16, 0, 0, 0 }
};

NJS_MKEY_A animation_00716578_mkey_43_rot_00715628[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 1, 0xFFFFECF8, 0, 0 },
	{ 2, 0xFFFFEB2A, 0, 0 },
	{ 3, 0xFFFFE8B2, 0, 0 },
	{ 4, 0xFFFFE602, 0, 0 },
	{ 5, 0xFFFFE38B, 0, 0 },
	{ 6, 0xFFFFE1BD, 0, 0 },
	{ 7, 0xFFFFE10A, 0, 0 },
	{ 8, 0xFFFFE178, 0, 0 },
	{ 9, 0xFFFFE2A2, 0, 0 },
	{ 10, 0xFFFFE450, 0, 0 },
	{ 11, 0xFFFFE64E, 0, 0 },
	{ 12, 0xFFFFE867, 0, 0 },
	{ 13, 0xFFFFEA65, 0, 0 },
	{ 14, 0xFFFFEC13, 0, 0 },
	{ 15, 0xFFFFED3C, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_00716578_mkey_42_rot_00715518[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 1, 0, 0xFFFFE2F7, 0 },
	{ 2, 0, 0xFFFFE094, 0 },
	{ 3, 0, 0xFFFFDD51, 0 },
	{ 4, 0, 0xFFFFD9C2, 0 },
	{ 5, 0, 0xFFFFD67F, 0 },
	{ 6, 0, 0xFFFFD41C, 0 },
	{ 7, 0, 0xFFFFD32F, 0 },
	{ 8, 0, 0xFFFFD3C2, 0 },
	{ 9, 0, 0xFFFFD54B, 0 },
	{ 10, 0, 0xFFFFD784, 0 },
	{ 11, 0, 0xFFFFDA27, 0 },
	{ 12, 0, 0xFFFFDCEC, 0 },
	{ 13, 0, 0xFFFFDF8F, 0 },
	{ 14, 0, 0xFFFFE1C8, 0 },
	{ 15, 0, 0xFFFFE351, 0 },
	{ 16, 0, 0xFFFFE3E4, 0 }
};

NJS_MKEY_A animation_00716578_mkey_46_rot_00715738[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_00716578_mkey_47_rot_00715758[] = {
	{ 0, 0xFFFFFAE8, 0x37A, 0xFFFFAFC1 },
	{ 1, 0xFFFFFAF9, 0x37A, 0xFFFFAFD5 },
	{ 2, 0xFFFFFB24, 0x37B, 0xFFFFB00E },
	{ 3, 0xFFFFFB5F, 0x37C, 0xFFFFB068 },
	{ 4, 0xFFFFFB9D, 0x37D, 0xFFFFB0DB },
	{ 5, 0xFFFFFBD5, 0x37D, 0xFFFFB154 },
	{ 6, 0xFFFFFBFD, 0x37D, 0xFFFFB1B5 },
	{ 7, 0xFFFFFC0B, 0x37B, 0xFFFFB1D2 },
	{ 8, 0xFFFFFC03, 0x37D, 0xFFFFB1C5 },
	{ 9, 0xFFFFFBE9, 0x37D, 0xFFFFB184 },
	{ 10, 0xFFFFFBC3, 0x37D, 0xFFFFB12D },
	{ 11, 0xFFFFFB96, 0x37C, 0xFFFFB0CE },
	{ 12, 0xFFFFFB66, 0x37C, 0xFFFFB074 },
	{ 13, 0xFFFFFB37, 0x37B, 0xFFFFB028 },
	{ 14, 0xFFFFFB0F, 0x37B, 0xFFFFAFF0 },
	{ 15, 0xFFFFFAF2, 0x37A, 0xFFFFAFCD },
	{ 16, 0xFFFFFAE8, 0x37A, 0xFFFFAFC1 }
};

NJS_MKEY_A animation_00716578_mkey_48_rot_00715868[] = {
	{ 0, 0, 0, 0x25FF },
	{ 1, 0, 0, 0x25C4 },
	{ 2, 0, 0, 0x2529 },
	{ 3, 0, 0, 0x2451 },
	{ 4, 0, 0, 0x235C },
	{ 5, 0, 0, 0x2274 },
	{ 6, 0, 0, 0x21C6 },
	{ 7, 0, 0, 0x218B },
	{ 8, 0, 0, 0x21AB },
	{ 9, 0, 0, 0x221D },
	{ 10, 0, 0, 0x22BE },
	{ 11, 0, 0, 0x2378 },
	{ 12, 0, 0, 0x2436 },
	{ 13, 0, 0, 0x24E6 },
	{ 14, 0, 0, 0x2578 },
	{ 15, 0, 0, 0x25DA },
	{ 16, 0, 0, 0x25FF }
};

NJS_MKEY_A animation_00716578_mkey_49_rot_00715978[] = {
	{ 0, 0, 0, 0x289E },
	{ 1, 0, 0, 0x2850 },
	{ 2, 0, 0, 0x2785 },
	{ 3, 0, 0, 0x2669 },
	{ 4, 0, 0, 0x252A },
	{ 5, 0, 0, 0x23FD },
	{ 6, 0, 0, 0x231A },
	{ 7, 0, 0, 0x22CD },
	{ 8, 0, 0, 0x22F9 },
	{ 9, 0, 0, 0x238B },
	{ 10, 0, 0, 0x245C },
	{ 11, 0, 0, 0x254E },
	{ 12, 0, 0, 0x2646 },
	{ 13, 0, 0, 0x272D },
	{ 14, 0, 0, 0x27EC },
	{ 15, 0, 0, 0x286E },
	{ 16, 0, 0, 0x289E }
};

NJS_MKEY_A animation_00716578_mkey_52_rot_00715A88[] = {
	{ 0, 0x1184, 0xFFFFEA00, 0xFFFFBFA1 },
	{ 1, 0x1184, 0xFFFFEA68, 0xFFFFBF8F },
	{ 2, 0x1184, 0xFFFFEB74, 0xFFFFBF63 },
	{ 3, 0x1184, 0xFFFFECE3, 0xFFFFBF26 },
	{ 4, 0x1184, 0xFFFFEE73, 0xFFFFBEE3 },
	{ 5, 0x1184, 0xFFFFEFE1, 0xFFFFBEA6 },
	{ 6, 0x1184, 0xFFFFF0EE, 0xFFFFBE79 },
	{ 7, 0x1184, 0xFFFFF156, 0xFFFFBE68 },
	{ 8, 0x1184, 0xFFFFF115, 0xFFFFBE73 },
	{ 9, 0x1184, 0xFFFFF069, 0xFFFFBE8F },
	{ 10, 0x1184, 0xFFFFEF6F, 0xFFFFBEB9 },
	{ 11, 0x1184, 0xFFFFEE47, 0xFFFFBEEA },
	{ 12, 0x1184, 0xFFFFED0F, 0xFFFFBF1E },
	{ 13, 0x1184, 0xFFFFEBE7, 0xFFFFBF50 },
	{ 14, 0x1184, 0xFFFFEAED, 0xFFFFBF79 },
	{ 15, 0x1184, 0xFFFFEA41, 0xFFFFBF96 },
	{ 16, 0x1184, 0xFFFFEA00, 0xFFFFBFA1 }
};

NJS_MKEY_A animation_00716578_mkey_53_rot_00715B98[] = {
	{ 0, 0, 0, 0xFFFFF35F },
	{ 1, 0, 0, 0xFFFFF412 },
	{ 2, 0, 0, 0xFFFFF5E0 },
	{ 3, 0, 0, 0xFFFFF858 },
	{ 4, 0, 0, 0xFFFFFB08 },
	{ 5, 0, 0, 0xFFFFFD7F },
	{ 6, 0, 0, 0xFFFFFF4D },
	{ 7, 0, 0, 0 },
	{ 8, 0, 0, 0xFFFFFF92 },
	{ 9, 0, 0, 0xFFFFFE68 },
	{ 10, 0, 0, 0xFFFFFCBA },
	{ 11, 0, 0, 0xFFFFFABC },
	{ 12, 0, 0, 0xFFFFF8A3 },
	{ 13, 0, 0, 0xFFFFF6A5 },
	{ 14, 0, 0, 0xFFFFF4F7 },
	{ 15, 0, 0, 0xFFFFF3CE },
	{ 16, 0, 0, 0xFFFFF35F }
};

NJS_MKEY_A animation_00716578_mkey_57_rot_00715CA8[] = {
	{ 0, 0x14F1, 0xFFFFF5E5, 0xFFFF58C2 },
	{ 1, 0x14E4, 0xFFFFF5E2, 0xFFFF5944 },
	{ 2, 0x14BD, 0xFFFFF5DA, 0xFFFF5A95 },
	{ 3, 0x1483, 0xFFFFF5CE, 0xFFFF5C60 },
	{ 4, 0x143B, 0xFFFFF5C1, 0xFFFF5E53 },
	{ 5, 0x13F3, 0xFFFFF5B4, 0xFFFF601B },
	{ 6, 0x13BB, 0xFFFFF5AA, 0xFFFF6166 },
	{ 7, 0x13A4, 0xFFFFF5A6, 0xFFFF61E6 },
	{ 8, 0x13B2, 0xFFFFF5A9, 0xFFFF6197 },
	{ 9, 0x13D7, 0xFFFFF5AF, 0xFFFF60C2 },
	{ 10, 0x140B, 0xFFFFF5B8, 0xFFFF5F8D },
	{ 11, 0x1444, 0xFFFFF5C2, 0xFFFF5E1C },
	{ 12, 0x147B, 0xFFFFF5CD, 0xFFFF5C97 },
	{ 13, 0x14AC, 0xFFFFF5D6, 0xFFFF5B24 },
	{ 14, 0x14D1, 0xFFFFF5DE, 0xFFFF59EB },
	{ 15, 0x14E9, 0xFFFFF5E3, 0xFFFF5912 },
	{ 16, 0x14F1, 0xFFFFF5E5, 0xFFFF58C2 }
};

NJS_MKEY_A animation_00716578_mkey_58_rot_00715DB8[] = {
	{ 0, 0, 0, 0x2720 },
	{ 1, 0, 0, 0x2712 },
	{ 2, 0, 0, 0x26EB },
	{ 3, 0, 0, 0x26B0 },
	{ 4, 0, 0, 0x2668 },
	{ 5, 0, 0, 0x261F },
	{ 6, 0, 0, 0x25E6 },
	{ 7, 0, 0, 0x25CF },
	{ 8, 0, 0, 0x25DD },
	{ 9, 0, 0, 0x2603 },
	{ 10, 0, 0, 0x2637 },
	{ 11, 0, 0, 0x2671 },
	{ 12, 0, 0, 0x26A9 },
	{ 13, 0, 0, 0x26D9 },
	{ 14, 0, 0, 0x26FF },
	{ 15, 0, 0, 0x2717 },
	{ 16, 0, 0, 0x2720 }
};

NJS_MKEY_A animation_00716578_mkey_59_rot_00715EC8[] = {
	{ 0, 0, 0, 0x3720 },
	{ 1, 0, 0, 0x370B },
	{ 2, 0, 0, 0x36CF },
	{ 3, 0, 0, 0x3675 },
	{ 4, 0, 0, 0x3606 },
	{ 5, 0, 0, 0x3596 },
	{ 6, 0, 0, 0x353E },
	{ 7, 0, 0, 0x351B },
	{ 8, 0, 0, 0x3531 },
	{ 9, 0, 0, 0x356B },
	{ 10, 0, 0, 0x35BA },
	{ 11, 0, 0, 0x3613 },
	{ 12, 0, 0, 0x3669 },
	{ 13, 0, 0, 0x36B4 },
	{ 14, 0, 0, 0x36EE },
	{ 15, 0, 0, 0x3713 },
	{ 16, 0, 0, 0x3720 }
};

NJS_MKEY_A animation_00716578_mkey_62_rot_00715FD8[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF498 },
	{ 1, 0x10B4, 0x42C, 0xFFFFF453 },
	{ 2, 0x10B4, 0x4A3, 0xFFFFF3A0 },
	{ 3, 0x10B4, 0x546, 0xFFFFF2AB },
	{ 4, 0x10B4, 0x5F8, 0xFFFFF1A1 },
	{ 5, 0x10B4, 0x69B, 0xFFFFF0AD },
	{ 6, 0x10B4, 0x712, 0xFFFFEFFA },
	{ 7, 0x10B4, 0x740, 0xFFFFEFB4 },
	{ 8, 0x10B4, 0x723, 0xFFFFEFDF },
	{ 9, 0x10B4, 0x6D7, 0xFFFFF052 },
	{ 10, 0x10B4, 0x668, 0xFFFFF0F9 },
	{ 11, 0x10B4, 0x5E4, 0xFFFFF1BE },
	{ 12, 0x10B4, 0x55A, 0xFFFFF28E },
	{ 13, 0x10B4, 0x4D6, 0xFFFFF354 },
	{ 14, 0x10B4, 0x467, 0xFFFFF3FA },
	{ 15, 0x10B4, 0x41A, 0xFFFFF46D },
	{ 16, 0x10B4, 0x3FE, 0xFFFFF498 }
};

NJS_MDATA2 animation_00716578_mdat_007160E8[] = {
	{ animation_00716578_mkey_0_pos_007147F8, NULL, LengthOfArray<Uint32>(animation_00716578_mkey_0_pos_007147F8), 0 },
	{ NULL, animation_00716578_mkey_1_rot_00714908, 0, LengthOfArray<Uint32>(animation_00716578_mkey_1_rot_00714908) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_12_rot_00714928, 0, LengthOfArray<Uint32>(animation_00716578_mkey_12_rot_00714928) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_15_rot_00714A38, 0, LengthOfArray<Uint32>(animation_00716578_mkey_15_rot_00714A38) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_19_rot_00714B48, 0, LengthOfArray<Uint32>(animation_00716578_mkey_19_rot_00714B48) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_25_rot_00714C58, 0, LengthOfArray<Uint32>(animation_00716578_mkey_25_rot_00714C58) },
	{ NULL, animation_00716578_mkey_26_rot_00714C78, 0, LengthOfArray<Uint32>(animation_00716578_mkey_26_rot_00714C78) },
	{ NULL, animation_00716578_mkey_27_rot_00714D88, 0, LengthOfArray<Uint32>(animation_00716578_mkey_27_rot_00714D88) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_30_rot_00714E98, 0, LengthOfArray<Uint32>(animation_00716578_mkey_30_rot_00714E98) },
	{ NULL, animation_00716578_mkey_32_rot_007150B8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_32_rot_007150B8) },
	{ NULL, animation_00716578_mkey_31_rot_00714FA8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_31_rot_00714FA8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_36_rot_007151C8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_36_rot_007151C8) },
	{ NULL, animation_00716578_mkey_37_rot_007151E8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_37_rot_007151E8) },
	{ NULL, animation_00716578_mkey_38_rot_007152F8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_38_rot_007152F8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_41_rot_00715408, 0, LengthOfArray<Uint32>(animation_00716578_mkey_41_rot_00715408) },
	{ NULL, animation_00716578_mkey_43_rot_00715628, 0, LengthOfArray<Uint32>(animation_00716578_mkey_43_rot_00715628) },
	{ NULL, animation_00716578_mkey_42_rot_00715518, 0, LengthOfArray<Uint32>(animation_00716578_mkey_42_rot_00715518) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_46_rot_00715738, 0, LengthOfArray<Uint32>(animation_00716578_mkey_46_rot_00715738) },
	{ NULL, animation_00716578_mkey_47_rot_00715758, 0, LengthOfArray<Uint32>(animation_00716578_mkey_47_rot_00715758) },
	{ NULL, animation_00716578_mkey_48_rot_00715868, 0, LengthOfArray<Uint32>(animation_00716578_mkey_48_rot_00715868) },
	{ NULL, animation_00716578_mkey_49_rot_00715978, 0, LengthOfArray<Uint32>(animation_00716578_mkey_49_rot_00715978) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_52_rot_00715A88, 0, LengthOfArray<Uint32>(animation_00716578_mkey_52_rot_00715A88) },
	{ NULL, animation_00716578_mkey_53_rot_00715B98, 0, LengthOfArray<Uint32>(animation_00716578_mkey_53_rot_00715B98) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_57_rot_00715CA8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_57_rot_00715CA8) },
	{ NULL, animation_00716578_mkey_58_rot_00715DB8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_58_rot_00715DB8) },
	{ NULL, animation_00716578_mkey_59_rot_00715EC8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_59_rot_00715EC8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00716578_mkey_62_rot_00715FD8, 0, LengthOfArray<Uint32>(animation_00716578_mkey_62_rot_00715FD8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbfront1 = { animation_00716578_mdat_007160E8, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbfront1 = { AMY_OBJECTS[0], &motion_a_sbfront1 };
