/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_006F9C18_mkey_0_pos_006F8258[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 1, 0, -0.7898f, 0 },
	{ 2, 0, -0.9324f, 0 },
	{ 3, 0, -1.1319f, 0 },
	{ 4, 0, -1.3572f, 0 },
	{ 5, 0, -1.577f, 0 },
	{ 6, 0, -1.7603f, 0 },
	{ 7, 0, -1.8759f, 0 },
	{ 8, 0, -1.9322f, 0 },
	{ 9, 0, -1.9621f, 0 },
	{ 10, 0, -1.9709f, 0 },
	{ 11, 0, -1.9639f, 0 },
	{ 12, 0, -1.9463f, 0 },
	{ 13, 0, -1.9234f, 0 },
	{ 14, 0, -1.9005f, 0 },
	{ 15, 0, -1.8829f, 0 },
	{ 16, 0, -1.8759f, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_0_rot_006F8368[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0xFFF, 0 },
	{ 2, 0, 0x1FFF, 0 },
	{ 3, 0, 0x2FFF, 0 },
	{ 4, 0, 0x3FFF, 0 },
	{ 5, 0, 0x4FFF, 0 },
	{ 6, 0, 0x5FFF, 0 },
	{ 7, 0, 0x6FFF, 0 },
	{ 8, 0, 0x7FFF, 0 },
	{ 9, 0, 0x8FFF, 0 },
	{ 10, 0, 0x9FFF, 0 },
	{ 11, 0, 0xAFFF, 0 },
	{ 12, 0, 0xBFFF, 0 },
	{ 13, 0, 0xCFFF, 0 },
	{ 14, 0, 0xDFFF, 0 },
	{ 15, 0, 0xEFFF, 0 },
	{ 16, 0, 0xFFFF, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_1_rot_006F8478[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0, 0xFFFFE1E7, 0xAAB },
	{ 2, 0, 0xFFFFD545, 0xE97 },
	{ 3, 0, 0xFFFFCDBE, 0x10B4 },
	{ 4, 0, 0xFFFFCC4C, 0x107C },
	{ 5, 0, 0xFFFFCBD0, 0xFE5 },
	{ 6, 0, 0xFFFFCC14, 0xF04 },
	{ 7, 0, 0xFFFFCCE4, 0xDEF },
	{ 8, 0, 0xFFFFCE09, 0xCBD },
	{ 9, 0, 0xFFFFCF4E, 0xB84 },
	{ 10, 0, 0xFFFFD080, 0xA5A },
	{ 11, 0, 0xFFFFD168, 0x956 },
	{ 12, 0, 0xFFFFD1D1, 0x88E },
	{ 13, 0, 0xFFFFD16C, 0x837 },
	{ 14, 0, 0xFFFFD070, 0x84A },
	{ 15, 0, 0xFFFFCF6D, 0x87D },
	{ 16, 0, 0xFFFFCEF7, 0x88E }
};

NJS_MKEY_A animation_006F9C18_mkey_11_rot_006F8588[] = {
	{ 0, 0xFFFFFF98, 0xB68, 0 },
	{ 16, 0xFFFFFF98, 0xB68, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_12_rot_006F85A8[] = {
	{ 0, 0, 0xFFFFF60B, 0x87A7 },
	{ 1, 0, 0xFFFFF2E2, 0x84CF },
	{ 2, 0, 0xFFFFECB1, 0x7E9D },
	{ 3, 0, 0xFFFFE959, 0x7AE6 },
	{ 4, 0, 0xFFFFE9A8, 0x7BCB },
	{ 5, 0, 0xFFFFEA9C, 0x7D99 },
	{ 6, 0, 0xFFFFEC29, 0x8015 },
	{ 7, 0, 0xFFFFEE3B, 0x82FB },
	{ 8, 0, 0xFFFFF0A7, 0x85FE },
	{ 9, 0, 0xFFFFF332, 0x88D6 },
	{ 10, 0, 0xFFFFF596, 0x8B45 },
	{ 11, 0, 0xFFFFF794, 0x8D1E },
	{ 12, 0, 0xFFFFF8F6, 0x8E3E },
	{ 13, 0, 0xFFFFF8E1, 0x8D4D },
	{ 14, 0, 0xFFFFF794, 0x8A9D },
	{ 15, 0, 0xFFFFF65B, 0x8840 },
	{ 16, 0, 0xFFFFF60B, 0x87A7 }
};

NJS_MKEY_A animation_006F9C18_mkey_15_rot_006F86B8[] = {
	{ 0, 0, 0xC02, 0xFFFF8854 },
	{ 1, 0, 0xBCF, 0xFFFF87F8 },
	{ 2, 0, 0xB09, 0xFFFF86B7 },
	{ 3, 0, 0xAAB, 0xFFFF85EF },
	{ 4, 0, 0xB07, 0xFFFF862B },
	{ 5, 0, 0xBA4, 0xFFFF86CF },
	{ 6, 0, 0xC44, 0xFFFF8859 },
	{ 7, 0, 0xC2E, 0xFFFF8A74 },
	{ 8, 0, 0xB57, 0xFFFF8B7F },
	{ 9, 0, 0xA7B, 0xFFFF8B57 },
	{ 10, 0, 0xA0E, 0xFFFF8A9B },
	{ 11, 0, 0xA0E, 0xFFFF89DB },
	{ 12, 0, 0xA86, 0xFFFF899B },
	{ 13, 0, 0xB3E, 0xFFFF899E },
	{ 14, 0, 0xBCC, 0xFFFF8932 },
	{ 15, 0, 0xBFE, 0xFFFF8889 },
	{ 16, 0, 0xC02, 0xFFFF8854 }
};

NJS_MKEY_A animation_006F9C18_mkey_19_rot_006F87C8[] = {
	{ 0, 0, 0xFFFFF4D7, 0xFFFF8730 },
	{ 1, 0, 0xFFFFF4B5, 0xFFFF868D },
	{ 2, 0, 0xFFFFF564, 0xFFFF8537 },
	{ 3, 0, 0xFFFFF5D6, 0xFFFF84BF },
	{ 4, 0, 0xFFFFF424, 0xFFFF85C8 },
	{ 5, 0, 0xFFFFF1B3, 0xFFFF8758 },
	{ 6, 0, 0xFFFFEF46, 0xFFFF88D2 },
	{ 7, 0, 0xFFFFED71, 0xFFFF8A13 },
	{ 8, 0, 0xFFFFEBC3, 0xFFFF8BBC },
	{ 9, 0, 0xFFFFE799, 0xFFFF8A74 },
	{ 10, 0, 0xFFFFE8B8, 0xFFFF893D },
	{ 11, 0, 0xFFFFE993, 0xFFFF874B },
	{ 12, 0, 0xFFFFEA3A, 0xFFFF8660 },
	{ 13, 0, 0xFFFFEC8D, 0xFFFF87D7 },
	{ 14, 0, 0xFFFFF03B, 0xFFFF8954 },
	{ 15, 0, 0xFFFFF3B2, 0xFFFF8801 },
	{ 16, 0, 0xFFFFF4D7, 0xFFFF8730 }
};

NJS_MKEY_A animation_006F9C18_mkey_25_rot_006F88D8[] = {
	{ 0, 0, 0x2A6D, 0xFFFFE10E },
	{ 1, 0, 0x2B0A, 0xFFFFE38A },
	{ 2, 0, 0x2C33, 0xFFFFE818 },
	{ 3, 0, 0x2D5E, 0xFFFFE9C5 },
	{ 4, 0, 0x2E99, 0xFFFFE787 },
	{ 5, 0, 0x2FED, 0xFFFFE422 },
	{ 6, 0, 0x313A, 0xFFFFDF69 },
	{ 7, 0, 0x3255, 0xFFFFD947 },
	{ 8, 0, 0x3315, 0xFFFFD1E8 },
	{ 9, 0, 0x335C, 0xFFFFC9E4 },
	{ 10, 0, 0x3328, 0xFFFFC220 },
	{ 11, 0, 0x3293, 0xFFFFBB5E },
	{ 12, 0, 0x31CA, 0xFFFFB5FD },
	{ 13, 0, 0x30F8, 0xFFFFB200 },
	{ 14, 0, 0x3043, 0xFFFFAF45 },
	{ 15, 0, 0x2FC8, 0xFFFFADA9 },
	{ 16, 0, 0x2F9B, 0xFFFFAD1F }
};

NJS_MKEY_A animation_006F9C18_mkey_26_rot_006F89E8[] = {
	{ 0, 0, 0xD3, 0xFFFFEF92 },
	{ 1, 0, 0x1E4, 0xFFFFF013 },
	{ 2, 0, 0x3F8, 0xFFFFF15C },
	{ 3, 0, 0x578, 0xFFFFF25B },
	{ 4, 0, 0x62E, 0xFFFFF277 },
	{ 5, 0, 0x6BC, 0xFFFFF259 },
	{ 6, 0, 0x6F2, 0xFFFFF1EB },
	{ 7, 0, 0x6A1, 0xFFFFF128 },
	{ 8, 0, 0x5A8, 0xFFFFF02D },
	{ 9, 0, 0x420, 0xFFFFEF34 },
	{ 10, 0, 0x257, 0xFFFFEE76 },
	{ 11, 0, 0xAC, 0xFFFFEE03 },
	{ 12, 0, 0xFFFFFF57, 0xFFFFEDCA },
	{ 13, 0, 0xFFFFFE61, 0xFFFFEDB4 },
	{ 14, 0, 0xFFFFFDC2, 0xFFFFEDAE },
	{ 15, 0, 0xFFFFFD69, 0xFFFFEDAE },
	{ 16, 0, 0xFFFFFD4C, 0xFFFFEDAF }
};

NJS_MKEY_A animation_006F9C18_mkey_27_rot_006F8AF8[] = {
	{ 0, 0, 0x1E3, 0xFFFFE2EE },
	{ 1, 0, 0x3E8, 0xFFFFE28A },
	{ 2, 0, 0x824, 0xFFFFE27D },
	{ 3, 0, 0xACB, 0xFFFFE330 },
	{ 4, 0, 0xABF, 0xFFFFE3C6 },
	{ 5, 0, 0xA08, 0xFFFFE471 },
	{ 6, 0, 0x881, 0xFFFFE52A },
	{ 7, 0, 0x626, 0xFFFFE5F6 },
	{ 8, 0, 0x32C, 0xFFFFE6F1 },
	{ 9, 0, 5, 0xFFFFE835 },
	{ 10, 0, 0xFFFFFD3B, 0xFFFFE9BA },
	{ 11, 0, 0xFFFFFB1B, 0xFFFFEB51 },
	{ 12, 0, 0xFFFFF9AE, 0xFFFFECC5 },
	{ 13, 0, 0xFFFFF8D0, 0xFFFFEDF3 },
	{ 14, 0, 0xFFFFF853, 0xFFFFEECF },
	{ 15, 0, 0xFFFFF815, 0xFFFFEF54 },
	{ 16, 0, 0xFFFFF802, 0xFFFFEF82 }
};

NJS_MKEY_A animation_006F9C18_mkey_30_rot_006F8C08[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_32_rot_006F8C48[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 16, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_31_rot_006F8C28[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_006F9C18_mkey_36_rot_006F8C68[] = {
	{ 0, 0, 0xFFFFE8F9, 0xFFFFDCAA },
	{ 1, 0, 0xFFFFE423, 0xFFFFDFB0 },
	{ 2, 0, 0xFFFFD4AD, 0xFFFFEB14 },
	{ 3, 0, 0xFFFFC0E3, 0xFFFFCF11 },
	{ 4, 0, 0xFFFFE1B5, 0xFFFF9EAA },
	{ 5, 0, 0xFFFFF809, 0xFFFFA319 },
	{ 6, 0, 0xFFFFFF07, 0xFFFFA519 },
	{ 7, 0, 0xBE, 0xFFFFA599 },
	{ 8, 0, 0x79, 0xFFFFA557 },
	{ 9, 0, 0xFFFFFFAB, 0xFFFFA509 },
	{ 10, 0, 0xFFFFFE7E, 0xFFFFA4B1 },
	{ 11, 0, 0xFFFFFD13, 0xFFFFA454 },
	{ 12, 0, 0xFFFFFB89, 0xFFFFA3F6 },
	{ 13, 0, 0xFFFFFA04, 0xFFFFA39D },
	{ 14, 0, 0xFFFFF8AF, 0xFFFFA350 },
	{ 15, 0, 0xFFFFF7BB, 0xFFFFA319 },
	{ 16, 0, 0xFFFFF75D, 0xFFFFA305 }
};

NJS_MKEY_A animation_006F9C18_mkey_37_rot_006F8D78[] = {
	{ 0, 0, 0xFFFFEE74, 0xFFFFEBF0 },
	{ 1, 0, 0xFFFFE8B4, 0xFFFFE92F },
	{ 2, 0, 0xFFFFDD2C, 0xFFFFEC85 },
	{ 3, 0, 0xFFFFF3CF, 0xFFFFE3DB },
	{ 4, 0, 0xB4, 0xFFFFEF1B },
	{ 5, 0, 0xFFFFF64F, 0xFFFFF297 },
	{ 6, 0, 0xFFFFF629, 0xFFFFF5CA },
	{ 7, 0, 0xFFFFF6F1, 0xFFFFF744 },
	{ 8, 0, 0xFFFFF77B, 0xFFFFF7D0 },
	{ 9, 0, 0xFFFFF7E9, 0xFFFFF82C },
	{ 10, 0, 0xFFFFF845, 0xFFFFF867 },
	{ 11, 0, 0xFFFFF897, 0xFFFFF88D },
	{ 12, 0, 0xFFFFF8E4, 0xFFFFF8A5 },
	{ 13, 0, 0xFFFFF92B, 0xFFFFF8B3 },
	{ 14, 0, 0xFFFFF969, 0xFFFFF8BC },
	{ 15, 0, 0xFFFFF996, 0xFFFFF8C1 },
	{ 16, 0, 0xFFFFF9A7, 0xFFFFF8C2 }
};

NJS_MKEY_A animation_006F9C18_mkey_38_rot_006F8E88[] = {
	{ 0, 0, 0xFFFFEED4, 0xFFFFECC1 },
	{ 1, 0, 0xFFFFECAD, 0xFFFFEC7D },
	{ 2, 0, 0xFFFFE72A, 0xFFFFF5A4 },
	{ 3, 0, 0xFFFFF094, 0xFFFFE556 },
	{ 4, 0, 0x2238, 0xFFFFEFAD },
	{ 5, 0, 0x2047, 0x739 },
	{ 6, 0, 0x19D9, 0xA1D },
	{ 7, 0, 0x16C1, 0x993 },
	{ 8, 0, 0x1572, 0x8DA },
	{ 9, 0, 0x14B6, 0x869 },
	{ 10, 0, 0x1458, 0x825 },
	{ 11, 0, 0x1438, 0x7FF },
	{ 12, 0, 0x143C, 0x7EB },
	{ 13, 0, 0x1453, 0x7E2 },
	{ 14, 0, 0x146E, 0x7DF },
	{ 15, 0, 0x1485, 0x7DF },
	{ 16, 0, 0x148F, 0x7E0 }
};

NJS_MKEY_A animation_006F9C18_mkey_41_rot_006F8F98[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0xFFFFFECD, 0xFFFFF866, 0xFFFFFB5B },
	{ 2, 0xFFFFFE99, 0xFFFFEA0A, 0xFFFFF2B9 },
	{ 3, 0x47E, 0xFFFFE195, 0xFFFFEE13 },
	{ 4, 0x156E, 0xFFFFE437, 0xFFFFF0E0 },
	{ 5, 0x2CDA, 0xFFFFEBAC, 0xFFFFF70A },
	{ 6, 0x419B, 0xFFFFF372, 0xFFFFFD33 },
	{ 7, 0x4A8F, 0xFFFFF70A, 0 },
	{ 16, 0x4A8F, 0xFFFFF70A, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_43_rot_006F90B8[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_42_rot_006F9028[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 1, 0, 0xFFFFD94D, 0 },
	{ 2, 0, 0xFFFFC627, 0 },
	{ 3, 0, 0xFFFFBD63, 0 },
	{ 4, 0, 0xFFFFC7EF, 0 },
	{ 5, 0, 0xFFFFDB95, 0 },
	{ 6, 0, 0xFFFFEE8B, 0 },
	{ 7, 0, 0xFFFFF70A, 0 },
	{ 16, 0, 0xFFFFF70A, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_46_rot_006F90D8[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_006F9C18_mkey_47_rot_006F90F8[] = {
	{ 0, 0xFFFFFEB8, 0x20B, 0xFFFFB834 },
	{ 1, 0xFFFFFE4D, 0x229, 0xFFFFB78D },
	{ 2, 0xFFFFFD37, 0x277, 0xFFFFB5DF },
	{ 3, 0xFFFFFBBB, 0x2E1, 0xFFFFB392 },
	{ 4, 0xFFFFFA1D, 0x354, 0xFFFFB111 },
	{ 5, 0xFFFFF8A1, 0x3BE, 0xFFFFAEC5 },
	{ 6, 0xFFFFF78B, 0x40B, 0xFFFFAD16 },
	{ 7, 0xFFFFF720, 0x429, 0xFFFFAC70 },
	{ 16, 0xFFFFF720, 0x429, 0xFFFFAC70 }
};

NJS_MKEY_A animation_006F9C18_mkey_48_rot_006F9188[] = {
	{ 0, 0, 0, 0x172E },
	{ 1, 0, 0, 0x180C },
	{ 2, 0, 0, 0x1A48 },
	{ 3, 0, 0, 0x1D57 },
	{ 4, 0, 0, 0x20AB },
	{ 5, 0, 0, 0x23BA },
	{ 6, 0, 0, 0x25F6 },
	{ 7, 0, 0, 0x26D4 },
	{ 16, 0, 0, 0x26D4 }
};

NJS_MKEY_A animation_006F9C18_mkey_49_rot_006F9218[] = {
	{ 0, 0, 0, 0x154B },
	{ 1, 0, 0, 0x1678 },
	{ 2, 0, 0, 0x1980 },
	{ 3, 0, 0, 0x1DA4 },
	{ 4, 0, 0, 0x2228 },
	{ 5, 0, 0, 0x264D },
	{ 6, 0, 0, 0x2954 },
	{ 7, 0, 0, 0x2A81 },
	{ 16, 0, 0, 0x2A81 }
};

NJS_MKEY_A animation_006F9C18_mkey_52_rot_006F92A8[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFD539 },
	{ 1, 0x1C1C, 0xFFFFF772, 0xFFFFD519 },
	{ 2, 0x1C1C, 0xFFFFF772, 0xFFFFD4C0 },
	{ 3, 0x1C1C, 0xFFFFF772, 0xFFFFD435 },
	{ 4, 0x1C1C, 0xFFFFF772, 0xFFFFD381 },
	{ 5, 0x1C1C, 0xFFFFF772, 0xFFFFD2AC },
	{ 6, 0x1C1C, 0xFFFFF772, 0xFFFFD1BE },
	{ 7, 0x1C1C, 0xFFFFF772, 0xFFFFD0BF },
	{ 8, 0x1C1C, 0xFFFFF772, 0xFFFFCFB9 },
	{ 9, 0x1C1C, 0xFFFFF772, 0xFFFFCEB2 },
	{ 10, 0x1C1C, 0xFFFFF772, 0xFFFFCDB4 },
	{ 11, 0x1C1C, 0xFFFFF772, 0xFFFFCCC6 },
	{ 12, 0x1C1C, 0xFFFFF772, 0xFFFFCBF1 },
	{ 13, 0x1C1C, 0xFFFFF772, 0xFFFFCB3C },
	{ 14, 0x1C1C, 0xFFFFF772, 0xFFFFCAB2 },
	{ 15, 0x1C1C, 0xFFFFF772, 0xFFFFCA58 },
	{ 16, 0x1C1C, 0xFFFFF772, 0xFFFFCA39 }
};

NJS_MKEY_A animation_006F9C18_mkey_53_rot_006F93B8[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0, 0xFFFFFEDA },
	{ 2, 0, 0, 0xFFFFFBE2 },
	{ 3, 0, 0, 0xFFFFF7D3 },
	{ 4, 0, 0, 0xFFFFF367 },
	{ 5, 0, 0, 0xFFFFEF58 },
	{ 6, 0, 0, 0xFFFFEC60 },
	{ 7, 0, 0, 0xFFFFEB39 },
	{ 16, 0, 0, 0xFFFFEB39 }
};

NJS_MKEY_A animation_006F9C18_mkey_57_rot_006F9448[] = {
	{ 0, 0x654, 0xFFFFF8A3, 0xFFFF8526 },
	{ 1, 0xD64, 0xFFFFF5BD, 0xFFFF82CC },
	{ 2, 0x1BA8, 0xFFFFEFAC, 0xFFFF7D11 },
	{ 3, 0x26BC, 0xFFFFEA5E, 0xFFFF75F5 },
	{ 4, 0x2BC5, 0xFFFFE6AE, 0xFFFF6CC8 },
	{ 5, 0x2EF3, 0xFFFFE33C, 0xFFFF61BA },
	{ 6, 0x3076, 0xFFFFE096, 0xFFFF581C },
	{ 7, 0x307C, 0xFFFFDF4E, 0xFFFF533E },
	{ 8, 0x2F55, 0xFFFFDF2D, 0xFFFF52B8 },
	{ 9, 0x2D5F, 0xFFFFDF87, 0xFFFF53AD },
	{ 10, 0x2AD9, 0xFFFFE03C, 0xFFFF55BA },
	{ 11, 0x2806, 0xFFFFE12D, 0xFFFF587F },
	{ 12, 0x2524, 0xFFFFE23A, 0xFFFF5B9D },
	{ 13, 0x2276, 0xFFFFE342, 0xFFFF5EB1 },
	{ 14, 0x203C, 0xFFFFE426, 0xFFFF615C },
	{ 15, 0x1EB6, 0xFFFFE4C6, 0xFFFF633D },
	{ 16, 0x1E26, 0xFFFFE503, 0xFFFF63F2 }
};

NJS_MKEY_A animation_006F9C18_mkey_58_rot_006F9558[] = {
	{ 0, 0, 0, 0x1912 },
	{ 1, 0, 0, 0x190B },
	{ 2, 0, 0, 0x18F7 },
	{ 3, 0, 0, 0x18DD },
	{ 4, 0, 0, 0x18BF },
	{ 5, 0, 0, 0x18A5 },
	{ 6, 0, 0, 0x1891 },
	{ 16, 0, 0, 0x1889 }
};

NJS_MKEY_A animation_006F9C18_mkey_59_rot_006F95D8[] = {
	{ 0, 0, 0, 0x21C7 },
	{ 1, 0, 0, 0x21BB },
	{ 2, 0, 0, 0x219C },
	{ 3, 0, 0, 0x2170 },
	{ 4, 0, 0, 0x2141 },
	{ 5, 0, 0, 0x2116 },
	{ 6, 0, 0, 0x20F6 },
	{ 7, 0, 0, 0x20EA },
	{ 16, 0, 0, 0x20EA }
};

NJS_MKEY_A animation_006F9C18_mkey_62_rot_006F9668[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF843 },
	{ 1, 0x10B4, 0x3FE, 0xFFFFF399 },
	{ 2, 0x10B4, 0x3FE, 0xFFFFEB43 },
	{ 3, 0x10B4, 0x3FE, 0xFFFFE7BA },
	{ 4, 0x10B4, 0x3FE, 0xFFFFED1B },
	{ 5, 0x10B4, 0x3FE, 0xFFFFF6BF },
	{ 6, 0x10B4, 0x3FE, 0xFFFFFFF6 },
	{ 7, 0x10B4, 0x3FE, 0x413 },
	{ 16, 0x10B4, 0x3FE, 0x413 }
};

NJS_MKEY_A animation_006F9C18_mkey_63_rot_006F96F8[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0, 0xFFFFFED4 },
	{ 2, 0, 0, 0xFFFFFBCD },
	{ 3, 0, 0, 0xFFFFF7AA },
	{ 4, 0, 0, 0xFFFFF327 },
	{ 5, 0, 0, 0xFFFFEF04 },
	{ 6, 0, 0, 0xFFFFEBFD },
	{ 7, 0, 0, 0xFFFFEAD1 },
	{ 16, 0, 0, 0xFFFFEAD1 }
};

NJS_MDATA2 animation_006F9C18_mdat_006F9788[] = {
	{ animation_006F9C18_mkey_0_pos_006F8258, animation_006F9C18_mkey_0_rot_006F8368, LengthOfArray<Uint32>(animation_006F9C18_mkey_0_pos_006F8258), LengthOfArray<Uint32>(animation_006F9C18_mkey_0_rot_006F8368) },
	{ NULL, animation_006F9C18_mkey_1_rot_006F8478, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_1_rot_006F8478) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_11_rot_006F8588, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_11_rot_006F8588) },
	{ NULL, animation_006F9C18_mkey_12_rot_006F85A8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_12_rot_006F85A8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_15_rot_006F86B8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_15_rot_006F86B8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_19_rot_006F87C8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_19_rot_006F87C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_25_rot_006F88D8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_25_rot_006F88D8) },
	{ NULL, animation_006F9C18_mkey_26_rot_006F89E8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_26_rot_006F89E8) },
	{ NULL, animation_006F9C18_mkey_27_rot_006F8AF8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_27_rot_006F8AF8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_30_rot_006F8C08, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_30_rot_006F8C08) },
	{ NULL, animation_006F9C18_mkey_32_rot_006F8C48, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_32_rot_006F8C48) },
	{ NULL, animation_006F9C18_mkey_31_rot_006F8C28, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_31_rot_006F8C28) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_36_rot_006F8C68, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_36_rot_006F8C68) },
	{ NULL, animation_006F9C18_mkey_37_rot_006F8D78, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_37_rot_006F8D78) },
	{ NULL, animation_006F9C18_mkey_38_rot_006F8E88, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_38_rot_006F8E88) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_41_rot_006F8F98, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_41_rot_006F8F98) },
	{ NULL, animation_006F9C18_mkey_43_rot_006F90B8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_43_rot_006F90B8) },
	{ NULL, animation_006F9C18_mkey_42_rot_006F9028, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_42_rot_006F9028) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_46_rot_006F90D8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_46_rot_006F90D8) },
	{ NULL, animation_006F9C18_mkey_47_rot_006F90F8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_47_rot_006F90F8) },
	{ NULL, animation_006F9C18_mkey_48_rot_006F9188, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_48_rot_006F9188) },
	{ NULL, animation_006F9C18_mkey_49_rot_006F9218, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_49_rot_006F9218) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_52_rot_006F92A8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_52_rot_006F92A8) },
	{ NULL, animation_006F9C18_mkey_53_rot_006F93B8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_53_rot_006F93B8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_57_rot_006F9448, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_57_rot_006F9448) },
	{ NULL, animation_006F9C18_mkey_58_rot_006F9558, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_58_rot_006F9558) },
	{ NULL, animation_006F9C18_mkey_59_rot_006F95D8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_59_rot_006F95D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_006F9C18_mkey_62_rot_006F9668, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_62_rot_006F9668) },
	{ NULL, animation_006F9C18_mkey_63_rot_006F96F8, 0, LengthOfArray<Uint32>(animation_006F9C18_mkey_63_rot_006F96F8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbsa2 = { animation_006F9C18_mdat_006F9788, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbsa2 = { AMY_OBJECTS[0], &motion_a_sbsa2 };
