/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_00723508_mkey_0_pos_007214B8[] = {
	{ 0, 0, -2.5651f, -2.463f },
	{ 1, 0, -2.5425f, -2.4466f },
	{ 2, 0, -2.4787f, -2.4002f },
	{ 3, 0, -2.3796f, -2.328f },
	{ 4, 0, -2.251f, -2.2344f },
	{ 5, 0, -2.0988f, -2.1237f },
	{ 6, 0, -1.929f, -2.0001f },
	{ 7, 0, -1.7473f, -1.868f },
	{ 8, 0, -1.5598f, -1.7315f },
	{ 9, 0, -1.3723f, -1.5951f },
	{ 10, 0, -1.1907f, -1.4629f },
	{ 11, 0, -1.0209f, -1.3393f },
	{ 12, 0, -0.8687f, -1.2286f },
	{ 13, 0, -0.7401f, -1.135f },
	{ 14, 0, -0.641f, -1.0629f },
	{ 15, 0, -0.5771f, -1.0164f },
	{ 16, 0, -0.5546f, -1 }
};

NJS_MKEY_A animation_00723508_mkey_1_rot_007215C8[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0, 0xFFFFEAC7, 0x88E },
	{ 2, 0, 0xFFFFEB17, 0x88E },
	{ 3, 0, 0xFFFFEB92, 0x88E },
	{ 4, 0, 0xFFFFEC32, 0x88E },
	{ 5, 0, 0xFFFFECF0, 0x88E },
	{ 6, 0, 0xFFFFEDC3, 0x88E },
	{ 7, 0, 0xFFFFEEA5, 0x88E },
	{ 8, 0, 0xFFFFEF8F, 0x88E },
	{ 9, 0, 0xFFFFF078, 0x88E },
	{ 10, 0, 0xFFFFF15A, 0x88E },
	{ 11, 0, 0xFFFFF22E, 0x88E },
	{ 12, 0, 0xFFFFF2EB, 0x88E },
	{ 13, 0, 0xFFFFF38B, 0x88E },
	{ 14, 0, 0xFFFFF407, 0x88E },
	{ 15, 0, 0xFFFFF456, 0x88E },
	{ 16, 0, 0xFFFFF473, 0x88E }
};

NJS_MKEY_A animation_00723508_mkey_12_rot_007216D8[] = {
	{ 0, 0, 0xFFFFEAC7, 0x8875 },
	{ 1, 2, 0xFFFFEA70, 0x8864 },
	{ 2, 8, 0xFFFFE97E, 0x8835 },
	{ 3, 0x13, 0xFFFFE814, 0x87EC },
	{ 4, 0x20, 0xFFFFE657, 0x878E },
	{ 5, 0x30, 0xFFFFE46C, 0x871E },
	{ 6, 0x42, 0xFFFFE271, 0x86A2 },
	{ 7, 0x54, 0xFFFFE081, 0x861D },
	{ 8, 0x68, 0xFFFFDEB0, 0x8594 },
	{ 9, 0x7B, 0xFFFFDD09, 0x850B },
	{ 10, 0x8E, 0xFFFFDB94, 0x8488 },
	{ 11, 0xA0, 0xFFFFDA54, 0x840D },
	{ 12, 0xB0, 0xFFFFD94B, 0x839F },
	{ 13, 0xBD, 0xFFFFD87B, 0x8343 },
	{ 14, 0xC7, 0xFFFFD7E2, 0x82FC },
	{ 15, 0xCE, 0xFFFFD784, 0x82CF },
	{ 16, 0xD0, 0xFFFFD763, 0x82BE }
};

NJS_MKEY_A animation_00723508_mkey_15_rot_007217E8[] = {
	{ 0, 0, 0xB6A, 0xFFFF87C1 },
	{ 1, 0, 0xB54, 0xFFFF87EC },
	{ 2, 0, 0xB1B, 0xFFFF885F },
	{ 3, 0, 0xAD7, 0xFFFF8904 },
	{ 4, 0, 0xA9B, 0xFFFF89C5 },
	{ 5, 0, 0xA74, 0xFFFF8A8F },
	{ 6, 0, 0xA65, 0xFFFF8B56 },
	{ 7, 0, 0xA6C, 0xFFFF8C11 },
	{ 8, 0, 0xA81, 0xFFFF8CBC },
	{ 9, 0, 0xA9F, 0xFFFF8D56 },
	{ 10, 0, 0xABE, 0xFFFF8DDD },
	{ 11, 0, 0xADC, 0xFFFF8E51 },
	{ 12, 0, 0xAF6, 0xFFFF8EB2 },
	{ 13, 0, 0xB0A, 0xFFFF8EFF },
	{ 14, 0, 0xB19, 0xFFFF8F38 },
	{ 15, 0, 0xB22, 0xFFFF8F5C },
	{ 16, 0, 0xB25, 0xFFFF8F68 }
};

NJS_MKEY_A animation_00723508_mkey_19_rot_007218F8[] = {
	{ 0, 0, 0xFFFFF461, 0xFFFF87BF },
	{ 1, 0, 0xFFFFF425, 0xFFFF8807 },
	{ 2, 0, 0xFFFFF382, 0xFFFF88C8 },
	{ 3, 0, 0xFFFFF29B, 0xFFFF89DC },
	{ 4, 0, 0xFFFFF195, 0xFFFF8B19 },
	{ 5, 0, 0xFFFFF091, 0xFFFF8C55 },
	{ 6, 0, 0xFFFFEFA4, 0xFFFF8D76 },
	{ 7, 0, 0xFFFFEEDB, 0xFFFF8E69 },
	{ 8, 0, 0xFFFFEE37, 0xFFFF8F2B },
	{ 9, 0, 0xFFFFEDB5, 0xFFFF8FBE },
	{ 10, 0, 0xFFFFED50, 0xFFFF9029 },
	{ 11, 0, 0xFFFFED02, 0xFFFF9074 },
	{ 12, 0, 0xFFFFECC6, 0xFFFF90A5 },
	{ 13, 0, 0xFFFFEC9A, 0xFFFF90C5 },
	{ 14, 0, 0xFFFFEC7B, 0xFFFF90D8 },
	{ 15, 0, 0xFFFFEC69, 0xFFFF90E2 },
	{ 16, 0, 0xFFFFEC63, 0xFFFF90E5 }
};

NJS_MKEY_A animation_00723508_mkey_25_rot_00721A08[] = {
	{ 0, 0, 0x1958, 0xFFFFBA80 },
	{ 16, 0, 0x1958, 0xFFFFBA80 }
};

NJS_MKEY_A animation_00723508_mkey_26_rot_00721A28[] = {
	{ 0, 0, 0xFFFFF806, 0xFFFFF7A4 },
	{ 1, 0, 0xFFFFF7FE, 0xFFFFF773 },
	{ 2, 0, 0xFFFFF7E6, 0xFFFFF6EB },
	{ 3, 0, 0xFFFFF7C2, 0xFFFFF617 },
	{ 4, 0, 0xFFFFF795, 0xFFFFF505 },
	{ 5, 0, 0xFFFFF761, 0xFFFFF3C1 },
	{ 6, 0, 0xFFFFF72A, 0xFFFFF259 },
	{ 7, 0, 0xFFFFF6F2, 0xFFFFF0DB },
	{ 8, 0, 0xFFFFF6BD, 0xFFFFEF55 },
	{ 9, 0, 0xFFFFF68C, 0xFFFFEDD4 },
	{ 10, 0, 0xFFFFF660, 0xFFFFEC65 },
	{ 11, 0, 0xFFFFF63A, 0xFFFFEB14 },
	{ 12, 0, 0xFFFFF61B, 0xFFFFE9EB },
	{ 13, 0, 0xFFFFF603, 0xFFFFE8F4 },
	{ 14, 0, 0xFFFFF5F1, 0xFFFFE838 },
	{ 15, 0, 0xFFFFF5E6, 0xFFFFE7C1 },
	{ 16, 0, 0xFFFFF5E3, 0xFFFFE797 }
};

NJS_MKEY_A animation_00723508_mkey_27_rot_00721B38[] = {
	{ 0, 0, 0xFFFFF300, 0xFFFFFD8D },
	{ 1, 0, 0xFFFFF2DB, 0xFFFFFD3A },
	{ 2, 0, 0xFFFFF274, 0xFFFFFC4F },
	{ 3, 0, 0xFFFFF1DE, 0xFFFFFADB },
	{ 4, 0, 0xFFFFF12E, 0xFFFFF8EE },
	{ 5, 0, 0xFFFFF07F, 0xFFFFF6A6 },
	{ 6, 0, 0xFFFFEFE9, 0xFFFFF425 },
	{ 7, 0, 0xFFFFEF7B, 0xFFFFF198 },
	{ 8, 0, 0xFFFFEF3F, 0xFFFFEF2A },
	{ 9, 0, 0xFFFFEF31, 0xFFFFECFB },
	{ 10, 0, 0xFFFFEF47, 0xFFFFEB21 },
	{ 11, 0, 0xFFFFEF76, 0xFFFFE9A0 },
	{ 12, 0, 0xFFFFEFB0, 0xFFFFE877 },
	{ 13, 0, 0xFFFFEFEA, 0xFFFFE79C },
	{ 14, 0, 0xFFFFF01A, 0xFFFFE707 },
	{ 15, 0, 0xFFFFF03C, 0xFFFFE6AF },
	{ 16, 0, 0xFFFFF048, 0xFFFFE691 }
};

NJS_MKEY_A animation_00723508_mkey_30_rot_00721C48[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 1, 0xFFFFFFDB, 0x188A, 0xFFFFFFE0 },
	{ 2, 0xFFFFFF71, 0x17A9, 0xFFFFFF83 },
	{ 3, 0xFFFFFECC, 0x164B, 0xFFFFFEF3 },
	{ 4, 0xFFFFFDF7, 0x1486, 0xFFFFFE38 },
	{ 5, 0xFFFFFCFA, 0x126D, 0xFFFFFD5B },
	{ 6, 0xFFFFFBE0, 0x1016, 0xFFFFFC64 },
	{ 7, 0xFFFFFAB3, 0xD95, 0xFFFFFB5D },
	{ 8, 0xFFFFF97C, 0xB00, 0xFFFFFA4C },
	{ 9, 0xFFFFF844, 0x86A, 0xFFFFF93C },
	{ 10, 0xFFFFF717, 0x5EA, 0xFFFFF834 },
	{ 11, 0xFFFFF5FD, 0x392, 0xFFFFF73D },
	{ 12, 0xFFFFF500, 0x17A, 0xFFFFF660 },
	{ 13, 0xFFFFF42B, 0xFFFFFFB5, 0xFFFFF5A6 },
	{ 14, 0xFFFFF386, 0xFFFFFE57, 0xFFFFF516 },
	{ 15, 0xFFFFF31C, 0xFFFFFD76, 0xFFFFF4B9 },
	{ 16, 0xFFFFF2F7, 0xFFFFFD26, 0xFFFFF498 }
};

NJS_MKEY_A animation_00723508_mkey_32_rot_00721E68[] = {
	{ 0, 0, 0x3013, 0 },
	{ 1, 0, 0x2F9C, 0 },
	{ 2, 0, 0x2E4A, 0 },
	{ 3, 0, 0x2C3D, 0 },
	{ 4, 0, 0x2995, 0 },
	{ 5, 0, 0x2670, 0 },
	{ 6, 0, 0x22ED, 0 },
	{ 7, 0, 0x1F2C, 0 },
	{ 8, 0, 0x1B4C, 0 },
	{ 9, 0, 0x176C, 0 },
	{ 10, 0, 0x13AB, 0 },
	{ 11, 0, 0x1028, 0 },
	{ 12, 0, 0xD03, 0 },
	{ 13, 0, 0xA5A, 0 },
	{ 14, 0, 0x84D, 0 },
	{ 15, 0, 0x6FC, 0 },
	{ 16, 0, 0x684, 0 }
};

NJS_MKEY_A animation_00723508_mkey_31_rot_00721D58[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 1, 0x12DE, 0, 0xFFFFE7F7 },
	{ 2, 0x1214, 0, 0xFFFFE7F7 },
	{ 3, 0x10DB, 0, 0xFFFFE7F7 },
	{ 4, 0xF44, 0, 0xFFFFE7F7 },
	{ 5, 0xD62, 0, 0xFFFFE7F7 },
	{ 6, 0xB49, 0, 0xFFFFE7F7 },
	{ 7, 0x90A, 0, 0xFFFFE7F7 },
	{ 8, 0x6B8, 0, 0xFFFFE7F7 },
	{ 9, 0x467, 0, 0xFFFFE7F7 },
	{ 10, 0x228, 0, 0xFFFFE7F7 },
	{ 11, 0xF, 0, 0xFFFFE7F7 },
	{ 12, 0xFFFFFE2E, 0, 0xFFFFE7F7 },
	{ 13, 0xFFFFFC97, 0, 0xFFFFE7F7 },
	{ 14, 0xFFFFFB5E, 0, 0xFFFFE7F7 },
	{ 15, 0xFFFFFA94, 0, 0xFFFFE7F7 },
	{ 16, 0xFFFFFA4C, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_00723508_mkey_36_rot_00721F78[] = {
	{ 0, 0, 0xFFFFF6C8, 0xFFFFF90C },
	{ 1, 0, 0xFFFFF6D3, 0xFFFFF8CF },
	{ 2, 0, 0xFFFFF6F2, 0xFFFFF824 },
	{ 3, 0, 0xFFFFF723, 0xFFFFF720 },
	{ 4, 0, 0xFFFFF762, 0xFFFFF5D8 },
	{ 5, 0, 0xFFFFF7AE, 0xFFFFF463 },
	{ 6, 0, 0xFFFFF801, 0xFFFFF2D5 },
	{ 7, 0, 0xFFFFF859, 0xFFFFF140 },
	{ 8, 0, 0xFFFFF8B2, 0xFFFFEFB5 },
	{ 9, 0, 0xFFFFF909, 0xFFFFEE40 },
	{ 10, 0, 0xFFFFF95B, 0xFFFFECEA },
	{ 11, 0, 0xFFFFF9A5, 0xFFFFEBBC },
	{ 12, 0, 0xFFFFF9E5, 0xFFFFEABB },
	{ 13, 0, 0xFFFFFA19, 0xFFFFE9EA },
	{ 14, 0, 0xFFFFFA41, 0xFFFFE950 },
	{ 15, 0, 0xFFFFFA5A, 0xFFFFE8EF },
	{ 16, 0, 0xFFFFFA63, 0xFFFFE8CD }
};

NJS_MKEY_A animation_00723508_mkey_37_rot_00722088[] = {
	{ 0, 0, 0xFFFFEC5E, 0xFFFFFB19 },
	{ 1, 0, 0xFFFFEC55, 0xFFFFFADF },
	{ 2, 0, 0xFFFFEC3D, 0xFFFFFA3B },
	{ 3, 0, 0xFFFFEC24, 0xFFFFF93D },
	{ 4, 0, 0xFFFFEC16, 0xFFFFF7F8 },
	{ 5, 0, 0xFFFFEC20, 0xFFFFF682 },
	{ 6, 0, 0xFFFFEC48, 0xFFFFF4F6 },
	{ 7, 0, 0xFFFFEC90, 0xFFFFF36D },
	{ 8, 0, 0xFFFFECF1, 0xFFFFF1FE },
	{ 9, 0, 0xFFFFED64, 0xFFFFF0B6 },
	{ 10, 0, 0xFFFFEDDE, 0xFFFFEF9F },
	{ 11, 0, 0xFFFFEE55, 0xFFFFEEBA },
	{ 12, 0, 0xFFFFEEC2, 0xFFFFEE05 },
	{ 13, 0, 0xFFFFEF1F, 0xFFFFED7C },
	{ 14, 0, 0xFFFFEF65, 0xFFFFED1D },
	{ 15, 0, 0xFFFFEF92, 0xFFFFECE3 },
	{ 16, 0, 0xFFFFEFA2, 0xFFFFECD0 }
};

NJS_MKEY_A animation_00723508_mkey_38_rot_00722198[] = {
	{ 0, 0, 0xFFFFDC21, 0x130C },
	{ 1, 0, 0xFFFFDB88, 0x11B0 },
	{ 2, 0, 0xFFFFDA12, 0xD74 },
	{ 3, 0, 0xFFFFD8A1, 0x5F6 },
	{ 4, 0, 0xFFFFD872, 0xFFFFFBC6 },
	{ 5, 0, 0xFFFFDA5B, 0xFFFFF176 },
	{ 6, 0, 0xFFFFDE03, 0xFFFFE9A3 },
	{ 7, 0, 0xFFFFE262, 0xFFFFE4CD },
	{ 8, 0, 0xFFFFE6A6, 0xFFFFE237 },
	{ 9, 0, 0xFFFFEA62, 0xFFFFE10C },
	{ 10, 0, 0xFFFFED77, 0xFFFFE0B5 },
	{ 11, 0, 0xFFFFEFE8, 0xFFFFE0CF },
	{ 12, 0, 0xFFFFF1C7, 0xFFFFE11C },
	{ 13, 0, 0xFFFFF327, 0xFFFFE178 },
	{ 14, 0, 0xFFFFF41B, 0xFFFFE1CA },
	{ 15, 0, 0xFFFFF4AB, 0xFFFFE203 },
	{ 16, 0, 0xFFFFF4DC, 0xFFFFE217 }
};

NJS_MKEY_A animation_00723508_mkey_41_rot_007222A8[] = {
	{ 0, 0xFFFFD126, 0xFFFFF9E4, 0x54B },
	{ 1, 0xFFFFD126, 0xFFFFF9F7, 0x548 },
	{ 2, 0xFFFFD126, 0xFFFFFA2C, 0x53E },
	{ 3, 0xFFFFD126, 0xFFFFFA7E, 0x52F },
	{ 4, 0xFFFFD126, 0xFFFFFAE9, 0x51B },
	{ 5, 0xFFFFD126, 0xFFFFFB67, 0x503 },
	{ 6, 0xFFFFD126, 0xFFFFFBF4, 0x4E8 },
	{ 7, 0xFFFFD126, 0xFFFFFC8B, 0x4CC },
	{ 8, 0xFFFFD126, 0xFFFFFD26, 0x4AF },
	{ 9, 0xFFFFD126, 0xFFFFFDC2, 0x492 },
	{ 10, 0xFFFFD126, 0xFFFFFE59, 0x476 },
	{ 11, 0xFFFFD126, 0xFFFFFEE6, 0x45B },
	{ 12, 0xFFFFD126, 0xFFFFFF64, 0x443 },
	{ 13, 0xFFFFD126, 0xFFFFFFCF, 0x42F },
	{ 14, 0xFFFFD126, 0x20, 0x420 },
	{ 15, 0xFFFFD126, 0x55, 0x416 },
	{ 16, 0xFFFFD126, 0x68, 0x413 }
};

NJS_MKEY_A animation_00723508_mkey_43_rot_007224C8[] = {
	{ 0, 0xFFFFE2AB, 0, 0xFFFFF6A2 },
	{ 1, 0xFFFFE30A, 0, 0xFFFFF6A2 },
	{ 2, 0xFFFFE416, 0, 0xFFFFF6A2 },
	{ 3, 0xFFFFE5B6, 0, 0xFFFFF6A2 },
	{ 4, 0xFFFFE7D3, 0, 0xFFFFF6A2 },
	{ 5, 0xFFFFEA52, 0, 0xFFFFF6A2 },
	{ 6, 0xFFFFED1C, 0, 0xFFFFF6A2 },
	{ 7, 0xFFFFF017, 0, 0xFFFFF6A2 },
	{ 8, 0xFFFFF32B, 0, 0xFFFFF6A2 },
	{ 9, 0xFFFFF63F, 0, 0xFFFFF6A2 },
	{ 10, 0xFFFFF93A, 0, 0xFFFFF6A2 },
	{ 11, 0xFFFFFC04, 0, 0xFFFFF6A2 },
	{ 12, 0xFFFFFE83, 0, 0xFFFFF6A2 },
	{ 13, 0x9F, 0, 0xFFFFF6A2 },
	{ 14, 0x23F, 0, 0xFFFFF6A2 },
	{ 15, 0x34B, 0, 0xFFFFF6A2 },
	{ 16, 0x3AA, 0, 0xFFFFF6A2 }
};

NJS_MKEY_A animation_00723508_mkey_42_rot_007223B8[] = {
	{ 0, 0, 0xFFFFBA55, 0 },
	{ 1, 0, 0xFFFFBB29, 0 },
	{ 2, 0, 0xFFFFBD80, 0 },
	{ 3, 0, 0xFFFFC123, 0 },
	{ 4, 0, 0xFFFFC5DB, 0 },
	{ 5, 0, 0xFFFFCB6F, 0 },
	{ 6, 0, 0xFFFFD1AA, 0 },
	{ 7, 0, 0xFFFFD854, 0 },
	{ 8, 0, 0xFFFFDF34, 0 },
	{ 9, 0, 0xFFFFE615, 0 },
	{ 10, 0, 0xFFFFECBE, 0 },
	{ 11, 0, 0xFFFFF2F9, 0 },
	{ 12, 0, 0xFFFFF88E, 0 },
	{ 13, 0, 0xFFFFFD45, 0 },
	{ 14, 0, 0xE7, 0 },
	{ 15, 0, 0x33F, 0 },
	{ 16, 0, 0x413, 0 }
};

NJS_MKEY_A animation_00723508_mkey_46_rot_007225D8[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_00723508_mkey_47_rot_007225F8[] = {
	{ 0, 0x511, 0xFFFFFA8F, 0xFFFFCFED },
	{ 1, 0x518, 0xFFFFFA8E, 0xFFFFCF71 },
	{ 2, 0x529, 0xFFFFFA8D, 0xFFFFCE1A },
	{ 3, 0x53A, 0xFFFFFA8E, 0xFFFFCC19 },
	{ 4, 0x542, 0xFFFFFA94, 0xFFFFC9A7 },
	{ 5, 0x536, 0xFFFFFAA1, 0xFFFFC6FF },
	{ 6, 0x50C, 0xFFFFFAB9, 0xFFFFC45D },
	{ 7, 0x4C1, 0xFFFFFADC, 0xFFFFC1FB },
	{ 8, 0x457, 0xFFFFFB0C, 0xFFFFC009 },
	{ 9, 0x3D5, 0xFFFFFB49, 0xFFFFBEA9 },
	{ 10, 0x345, 0xFFFFFB90, 0xFFFFBDEF },
	{ 11, 0x2B5, 0xFFFFFBE0, 0xFFFFBDDB },
	{ 12, 0x22E, 0xFFFFFC32, 0xFFFFBE61 },
	{ 13, 0x1BB, 0xFFFFFC80, 0xFFFFBF52 },
	{ 14, 0x162, 0xFFFFFCC2, 0xFFFFC079 },
	{ 15, 0x127, 0xFFFFFCEE, 0xFFFFC192 },
	{ 16, 0x112, 0xFFFFFCFE, 0xFFFFC209 }
};

NJS_MKEY_A animation_00723508_mkey_48_rot_00722708[] = {
	{ 0, 0, 0, 0x1E21 },
	{ 1, 0, 0, 0x1E38 },
	{ 2, 0, 0, 0x1E71 },
	{ 3, 0, 0, 0x1EB4 },
	{ 4, 0, 0, 0x1EE5 },
	{ 5, 0, 0, 0x1EE7 },
	{ 6, 0, 0, 0x1EA3 },
	{ 7, 0, 0, 0x1E07 },
	{ 8, 0, 0, 0x1D08 },
	{ 9, 0, 0, 0x1BA7 },
	{ 10, 0, 0, 0x19E9 },
	{ 11, 0, 0, 0x17E7 },
	{ 12, 0, 0, 0x15A6 },
	{ 13, 0, 0, 0x1384 },
	{ 14, 0, 0, 0x115F },
	{ 15, 0, 0, 0xFAD },
	{ 16, 0, 0, 0xF06 }
};

NJS_MKEY_A animation_00723508_mkey_49_rot_00722818[] = {
	{ 0, 0, 0, 0x1D8E },
	{ 1, 0, 0, 0x1DA9 },
	{ 2, 0, 0, 0x1DEB },
	{ 3, 0, 0, 0x1E3A },
	{ 4, 0, 0, 0x1E73 },
	{ 5, 0, 0, 0x1E76 },
	{ 6, 0, 0, 0x1E26 },
	{ 7, 0, 0, 0x1D6F },
	{ 8, 0, 0, 0x1C43 },
	{ 9, 0, 0, 0x1AA3 },
	{ 10, 0, 0, 0x1896 },
	{ 11, 0, 0, 0x1624 },
	{ 12, 0, 0, 0x137F },
	{ 13, 0, 0, 0x1096 },
	{ 14, 0, 0, 0xE37 },
	{ 15, 0, 0, 0xC5B },
	{ 16, 0, 0, 0xB97 }
};

NJS_MKEY_A animation_00723508_mkey_52_rot_00722928[] = {
	{ 0, 0x1C1C, 0xFFFFF01D, 0xFFFFD25F },
	{ 1, 0x1C1C, 0xFFFFF020, 0xFFFFD298 },
	{ 2, 0x1C1C, 0xFFFFF02A, 0xFFFFD33A },
	{ 3, 0x1C1C, 0xFFFFF03A, 0xFFFFD436 },
	{ 4, 0x1C1C, 0xFFFFF04E, 0xFFFFD57D },
	{ 5, 0x1C1C, 0xFFFFF065, 0xFFFFD700 },
	{ 6, 0x1C1C, 0xFFFFF080, 0xFFFFD8B0 },
	{ 7, 0x1C1C, 0xFFFFF09C, 0xFFFFDA7D },
	{ 8, 0x1C1C, 0xFFFFF0B9, 0xFFFFDC5A },
	{ 9, 0x1C1C, 0xFFFFF0D6, 0xFFFFDE37 },
	{ 10, 0x1C1C, 0xFFFFF0F3, 0xFFFFE004 },
	{ 11, 0x1C1C, 0xFFFFF10D, 0xFFFFE1B4 },
	{ 12, 0x1C1C, 0xFFFFF125, 0xFFFFE337 },
	{ 13, 0x1C1C, 0xFFFFF139, 0xFFFFE47E },
	{ 14, 0x1C1C, 0xFFFFF148, 0xFFFFE57A },
	{ 15, 0x1C1C, 0xFFFFF152, 0xFFFFE61C },
	{ 16, 0x1C1C, 0xFFFFF156, 0xFFFFE655 }
};

NJS_MKEY_A animation_00723508_mkey_56_rot_00722A38[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0x4F, 0 },
	{ 2, 0, 0x130, 0 },
	{ 3, 0, 0x28E, 0 },
	{ 4, 0, 0x454, 0 },
	{ 5, 0, 0x66D, 0 },
	{ 6, 0, 0x8C4, 0 },
	{ 7, 0, 0xB44, 0 },
	{ 8, 0, 0xDDA, 0 },
	{ 9, 0, 0x106F, 0 },
	{ 10, 0, 0x12F0, 0 },
	{ 11, 0, 0x1547, 0 },
	{ 12, 0, 0x1760, 0 },
	{ 13, 0, 0x1926, 0 },
	{ 14, 0, 0x1A83, 0 },
	{ 15, 0, 0x1B64, 0 },
	{ 16, 0, 0x1BB4, 0 }
};

NJS_MKEY_A animation_00723508_mkey_57_rot_00722B48[] = {
	{ 0, 0x309F, 0xFFFFEB06, 0xFFFF5717 },
	{ 1, 0x2FC3, 0xFFFFEB2B, 0xFFFF581F },
	{ 2, 0x2D57, 0xFFFFEB99, 0xFFFF5ABE },
	{ 3, 0x299D, 0xFFFFEC52, 0xFFFF5E3F },
	{ 4, 0x24E3, 0xFFFFED5B, 0xFFFF6229 },
	{ 5, 0x1F84, 0xFFFFEEB8, 0xFFFF6647 },
	{ 6, 0x19DD, 0xFFFFF069, 0xFFFF6A80 },
	{ 7, 0x1448, 0xFFFFF269, 0xFFFF6EC7 },
	{ 8, 0xF19, 0xFFFFF4B7, 0xFFFF72FA },
	{ 9, 0xA78, 0xFFFFF727, 0xFFFF7747 },
	{ 10, 0x693, 0xFFFFF9B1, 0xFFFF7B87 },
	{ 11, 0x379, 0xFFFFFC36, 0xFFFF7F9F },
	{ 12, 0x127, 0xFFFFFE92, 0xFFFF8390 },
	{ 13, 0xFFFFFF8D, 0xA2, 0xFFFF8724 },
	{ 14, 0xFFFFFE8F, 0x243, 0xFFFF8A1F },
	{ 15, 0xFFFFFE0B, 0x354, 0xFFFF8C21 },
	{ 16, 0xFFFFFDE2, 0x3B5, 0xFFFF8CE3 }
};

NJS_MKEY_A animation_00723508_mkey_58_rot_00722C58[] = {
	{ 0, 0, 0, 0x2477 },
	{ 3, 0, 0, 0x244B },
	{ 4, 0, 0, 0x2400 },
	{ 5, 0, 0, 0x2378 },
	{ 6, 0, 0, 0x22A6 },
	{ 7, 0, 0, 0x2184 },
	{ 8, 0, 0, 0x2059 },
	{ 9, 0, 0, 0x1E90 },
	{ 10, 0, 0, 0x1C8C },
	{ 11, 0, 0, 0x1A6B },
	{ 12, 0, 0, 0x1832 },
	{ 13, 0, 0, 0x1615 },
	{ 14, 0, 0, 0x1441 },
	{ 15, 0, 0, 0x1320 },
	{ 16, 0, 0, 0x12A2 }
};

NJS_MKEY_A animation_00723508_mkey_59_rot_00722D48[] = {
	{ 0, 0, 0, 0x3308 },
	{ 1, 0, 0, 0x3307 },
	{ 2, 0, 0, 0x32F8 },
	{ 3, 0, 0, 0x32C6 },
	{ 4, 0, 0, 0x3254 },
	{ 5, 0, 0, 0x3186 },
	{ 6, 0, 0, 0x3049 },
	{ 7, 0, 0, 0x2E92 },
	{ 8, 0, 0, 0x2C22 },
	{ 9, 0, 0, 0x2995 },
	{ 10, 0, 0, 0x26B6 },
	{ 11, 0, 0, 0x23AD },
	{ 12, 0, 0, 0x208D },
	{ 13, 0, 0, 0x1D92 },
	{ 14, 0, 0, 0x1B04 },
	{ 15, 0, 0, 0x1912 },
	{ 16, 0, 0, 0x1869 }
};

NJS_MKEY_A animation_00723508_mkey_62_rot_00722E58[] = {
	{ 0, 0x23DA, 0xFFFFFAA0, 0xFFFFF500 },
	{ 1, 0x23DA, 0xFFFFFA87, 0xFFFFF509 },
	{ 2, 0x23DA, 0xFFFFFA42, 0xFFFFF520 },
	{ 3, 0x23DA, 0xFFFFF9D6, 0xFFFFF544 },
	{ 4, 0x23DA, 0xFFFFF949, 0xFFFFF572 },
	{ 5, 0x23DA, 0xFFFFF8A4, 0xFFFFF5AA },
	{ 6, 0x23DA, 0xFFFFF7EB, 0xFFFFF5E7 },
	{ 7, 0x23DA, 0xFFFFF725, 0xFFFFF629 },
	{ 8, 0x23DA, 0xFFFFF659, 0xFFFFF66D },
	{ 9, 0x23DA, 0xFFFFF58C, 0xFFFFF6B1 },
	{ 10, 0x23DA, 0xFFFFF4C6, 0xFFFFF6F3 },
	{ 11, 0x23DA, 0xFFFFF40D, 0xFFFFF731 },
	{ 12, 0x23DA, 0xFFFFF368, 0xFFFFF768 },
	{ 13, 0x23DA, 0xFFFFF2DB, 0xFFFFF797 },
	{ 14, 0x23DA, 0xFFFFF26F, 0xFFFFF7BB },
	{ 15, 0x23DA, 0xFFFFF22A, 0xFFFFF7D2 },
	{ 16, 0x23DA, 0xFFFFF211, 0xFFFFF7DA }
};

NJS_MKEY_A animation_00723508_mkey_67_rot_00722F68[] = {
	{ 0, 0, 0xEAC, 0xFFFFE647 },
	{ 1, 0, 0xE35, 0xFFFFE617 },
	{ 2, 0, 0xCE3, 0xFFFFE594 },
	{ 3, 0, 0xADC, 0xFFFFE4D0 },
	{ 4, 0, 0x84A, 0xFFFFE3DE },
	{ 5, 0, 0x55B, 0xFFFFE2D3 },
	{ 6, 0, 0x240, 0xFFFFE1BE },
	{ 7, 0, 0xFFFFFF29, 0xFFFFE0AC },
	{ 8, 0, 0xFFFFFC3A, 0xFFFFDFA8 },
	{ 9, 0, 0xFFFFF98E, 0xFFFFDEB7 },
	{ 10, 0, 0xFFFFF735, 0xFFFFDDE0 },
	{ 11, 0, 0xFFFFF537, 0xFFFFDD25 },
	{ 12, 0, 0xFFFFF395, 0xFFFFDC87 },
	{ 13, 0, 0xFFFFF24F, 0xFFFFDC09 },
	{ 14, 0, 0xFFFFF162, 0xFFFFDBAC },
	{ 15, 0, 0xFFFFF0D1, 0xFFFFDB72 },
	{ 16, 0, 0xFFFFF09F, 0xFFFFDB5E }
};

NJS_MDATA2 animation_00723508_mdat_00723078[] = {
	{ animation_00723508_mkey_0_pos_007214B8, NULL, LengthOfArray<Uint32>(animation_00723508_mkey_0_pos_007214B8), 0 },
	{ NULL, animation_00723508_mkey_1_rot_007215C8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_1_rot_007215C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_12_rot_007216D8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_12_rot_007216D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_15_rot_007217E8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_15_rot_007217E8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_19_rot_007218F8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_19_rot_007218F8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_25_rot_00721A08, 0, LengthOfArray<Uint32>(animation_00723508_mkey_25_rot_00721A08) },
	{ NULL, animation_00723508_mkey_26_rot_00721A28, 0, LengthOfArray<Uint32>(animation_00723508_mkey_26_rot_00721A28) },
	{ NULL, animation_00723508_mkey_27_rot_00721B38, 0, LengthOfArray<Uint32>(animation_00723508_mkey_27_rot_00721B38) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_30_rot_00721C48, 0, LengthOfArray<Uint32>(animation_00723508_mkey_30_rot_00721C48) },
	{ NULL, animation_00723508_mkey_32_rot_00721E68, 0, LengthOfArray<Uint32>(animation_00723508_mkey_32_rot_00721E68) },
	{ NULL, animation_00723508_mkey_31_rot_00721D58, 0, LengthOfArray<Uint32>(animation_00723508_mkey_31_rot_00721D58) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_36_rot_00721F78, 0, LengthOfArray<Uint32>(animation_00723508_mkey_36_rot_00721F78) },
	{ NULL, animation_00723508_mkey_37_rot_00722088, 0, LengthOfArray<Uint32>(animation_00723508_mkey_37_rot_00722088) },
	{ NULL, animation_00723508_mkey_38_rot_00722198, 0, LengthOfArray<Uint32>(animation_00723508_mkey_38_rot_00722198) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_41_rot_007222A8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_41_rot_007222A8) },
	{ NULL, animation_00723508_mkey_43_rot_007224C8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_43_rot_007224C8) },
	{ NULL, animation_00723508_mkey_42_rot_007223B8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_42_rot_007223B8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_46_rot_007225D8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_46_rot_007225D8) },
	{ NULL, animation_00723508_mkey_47_rot_007225F8, 0, LengthOfArray<Uint32>(animation_00723508_mkey_47_rot_007225F8) },
	{ NULL, animation_00723508_mkey_48_rot_00722708, 0, LengthOfArray<Uint32>(animation_00723508_mkey_48_rot_00722708) },
	{ NULL, animation_00723508_mkey_49_rot_00722818, 0, LengthOfArray<Uint32>(animation_00723508_mkey_49_rot_00722818) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_52_rot_00722928, 0, LengthOfArray<Uint32>(animation_00723508_mkey_52_rot_00722928) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_56_rot_00722A38, 0, LengthOfArray<Uint32>(animation_00723508_mkey_56_rot_00722A38) },
	{ NULL, animation_00723508_mkey_57_rot_00722B48, 0, LengthOfArray<Uint32>(animation_00723508_mkey_57_rot_00722B48) },
	{ NULL, animation_00723508_mkey_58_rot_00722C58, 0, LengthOfArray<Uint32>(animation_00723508_mkey_58_rot_00722C58) },
	{ NULL, animation_00723508_mkey_59_rot_00722D48, 0, LengthOfArray<Uint32>(animation_00723508_mkey_59_rot_00722D48) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_62_rot_00722E58, 0, LengthOfArray<Uint32>(animation_00723508_mkey_62_rot_00722E58) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00723508_mkey_67_rot_00722F68, 0, LengthOfArray<Uint32>(animation_00723508_mkey_67_rot_00722F68) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sblstop0 = { animation_00723508_mdat_00723078, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sblstop0 = { AMY_OBJECTS[0], &motion_a_sblstop0 };
