/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_0070AF58_mkey_0_pos_00709368[] = {
	{ 0, 0, -0.3016f, 0 },
	{ 1, 0, -0.3108f, 0 },
	{ 2, 0, -0.3347f, 0 },
	{ 3, 0, -0.3673f, 0 },
	{ 4, 0, -0.4028f, 0 },
	{ 5, 0, -0.4354f, 0 },
	{ 6, 0, -0.4592f, 0 },
	{ 7, 0, -0.4684f, 0 },
	{ 8, 0, -0.4627f, 0 },
	{ 9, 0, -0.4474f, 0 },
	{ 10, 0, -0.4252f, 0 },
	{ 11, 0, -0.3989f, 0 },
	{ 12, 0, -0.3712f, 0 },
	{ 13, 0, -0.3448f, 0 },
	{ 14, 0, -0.3226f, 0 },
	{ 15, 0, -0.3073f, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_1_rot_00709468[] = {
	{ 0, 0, 0xFFFFD4AB, 0 },
	{ 1, 0, 0xFFFFD47D, 0x33 },
	{ 2, 0, 0xFFFFD406, 0xBA },
	{ 3, 0, 0xFFFFD363, 0x171 },
	{ 4, 0, 0xFFFFD2B1, 0x239 },
	{ 5, 0, 0xFFFFD20E, 0x2F0 },
	{ 6, 0, 0xFFFFD197, 0x376 },
	{ 7, 0, 0xFFFFD169, 0x3AA },
	{ 8, 0, 0xFFFFD185, 0x38A },
	{ 9, 0, 0xFFFFD1D2, 0x334 },
	{ 10, 0, 0xFFFFD241, 0x2B7 },
	{ 11, 0, 0xFFFFD2C4, 0x223 },
	{ 12, 0, 0xFFFFD34F, 0x187 },
	{ 13, 0, 0xFFFFD3D3, 0xF3 },
	{ 14, 0, 0xFFFFD442, 0x76 },
	{ 15, 0, 0xFFFFD48E, 0x20 }
};

NJS_MKEY_A animation_0070AF58_mkey_12_rot_00709568[] = {
	{ 0, 0, 0xFFFFE166, 0x8794 },
	{ 1, 0, 0xFFFFE164, 0x8772 },
	{ 2, 0, 0xFFFFE15E, 0x871B },
	{ 3, 0, 0xFFFFE157, 0x86A3 },
	{ 4, 0, 0xFFFFE150, 0x861F },
	{ 5, 0, 0xFFFFE14A, 0x85A6 },
	{ 6, 0, 0xFFFFE147, 0x854D },
	{ 7, 0, 0xFFFFE145, 0x852A },
	{ 8, 0, 0xFFFFE146, 0x853F },
	{ 9, 0, 0xFFFFE149, 0x8579 },
	{ 10, 0, 0xFFFFE14C, 0x85CC },
	{ 11, 0, 0xFFFFE151, 0x862E },
	{ 12, 0, 0xFFFFE156, 0x8694 },
	{ 13, 0, 0xFFFFE15C, 0x86F5 },
	{ 14, 0, 0xFFFFE161, 0x8747 },
	{ 15, 0, 0xFFFFE165, 0x877F }
};

NJS_MKEY_A animation_0070AF58_mkey_19_rot_00709668[] = {
	{ 0, 0, 0xFFFFECF9, 0xFFFF8C03 },
	{ 1, 0, 0xFFFFECE7, 0xFFFF8BFB },
	{ 2, 0, 0xFFFFECB7, 0xFFFF8BE6 },
	{ 3, 0, 0xFFFFEC77, 0xFFFF8BC7 },
	{ 4, 0, 0xFFFFEC32, 0xFFFF8BA4 },
	{ 5, 0, 0xFFFFEBF3, 0xFFFF8B80 },
	{ 6, 0, 0xFFFFEBC5, 0xFFFF8B65 },
	{ 7, 0, 0xFFFFEBB3, 0xFFFF8B5A },
	{ 8, 0, 0xFFFFEBBE, 0xFFFF8B61 },
	{ 9, 0, 0xFFFFEBDB, 0xFFFF8B73 },
	{ 10, 0, 0xFFFFEC06, 0xFFFF8B8C },
	{ 11, 0, 0xFFFFEC39, 0xFFFF8BA8 },
	{ 12, 0, 0xFFFFEC70, 0xFFFF8BC4 },
	{ 13, 0, 0xFFFFECA3, 0xFFFF8BDD },
	{ 14, 0, 0xFFFFECCF, 0xFFFF8BF1 },
	{ 15, 0, 0xFFFFECEE, 0xFFFF8BFE }
};

NJS_MKEY_A animation_0070AF58_mkey_25_rot_00709768[] = {
	{ 0, 0, 0x1CF9, 0xFFFFD476 },
	{ 1, 0, 0x1D2F, 0xFFFFD4B2 },
	{ 2, 0, 0x1DBC, 0xFFFFD553 },
	{ 3, 0, 0x1E80, 0xFFFFD63B },
	{ 4, 0, 0x1F59, 0xFFFFD74B },
	{ 5, 0, 0x2024, 0xFFFFD858 },
	{ 6, 0, 0x20BB, 0xFFFFD929 },
	{ 7, 0, 0x20F5, 0xFFFFD97D },
	{ 8, 0, 0x20D1, 0xFFFFD949 },
	{ 9, 0, 0x2070, 0xFFFFD8C0 },
	{ 10, 0, 0x1FE5, 0xFFFFD802 },
	{ 11, 0, 0x1F41, 0xFFFFD72C },
	{ 12, 0, 0x1E97, 0xFFFFD658 },
	{ 13, 0, 0x1DF9, 0xFFFFD59A },
	{ 14, 0, 0x1D75, 0xFFFFD501 },
	{ 15, 0, 0x1D1B, 0xFFFFD49B }
};

NJS_MKEY_A animation_0070AF58_mkey_26_rot_00709868[] = {
	{ 0, 0, 0xFFFFF70D, 0xFFFFEEE2 },
	{ 1, 0, 0xFFFFF71C, 0xFFFFEEC1 },
	{ 2, 0, 0xFFFFF749, 0xFFFFEE6C },
	{ 3, 0, 0xFFFFF792, 0xFFFFEDF6 },
	{ 4, 0, 0xFFFFF7F5, 0xFFFFED77 },
	{ 5, 0, 0xFFFFF862, 0xFFFFED05 },
	{ 6, 0, 0xFFFFF8BF, 0xFFFFECB4 },
	{ 7, 0, 0xFFFFF8E6, 0xFFFFEC96 },
	{ 8, 0, 0xFFFFF8CD, 0xFFFFECA9 },
	{ 9, 0, 0xFFFFF88F, 0xFFFFECDC },
	{ 10, 0, 0xFFFFF83E, 0xFFFFED28 },
	{ 11, 0, 0xFFFFF7E9, 0xFFFFED85 },
	{ 12, 0, 0xFFFFF79C, 0xFFFFEDE8 },
	{ 13, 0, 0xFFFFF75E, 0xFFFFEE47 },
	{ 14, 0, 0xFFFFF731, 0xFFFFEE97 },
	{ 15, 0, 0xFFFFF716, 0xFFFFEECE }
};

NJS_MKEY_A animation_0070AF58_mkey_27_rot_00709968[] = {
	{ 0, 0, 0xFFFFF6BE, 0xFFFFEB2B },
	{ 1, 0, 0xFFFFF6C5, 0xFFFFEAE1 },
	{ 2, 0, 0xFFFFF6DC, 0xFFFFEA1A },
	{ 3, 0, 0xFFFFF708, 0xFFFFE8FA },
	{ 4, 0, 0xFFFFF74C, 0xFFFFE7A7 },
	{ 5, 0, 0xFFFFF7A0, 0xFFFFE658 },
	{ 6, 0, 0xFFFFF7ED, 0xFFFFE554 },
	{ 7, 0, 0xFFFFF80E, 0xFFFFE4EC },
	{ 8, 0, 0xFFFFF7F9, 0xFFFFE52D },
	{ 9, 0, 0xFFFFF7C5, 0xFFFFE5D7 },
	{ 10, 0, 0xFFFFF783, 0xFFFFE6C3 },
	{ 11, 0, 0xFFFFF743, 0xFFFFE7CE },
	{ 12, 0, 0xFFFFF70E, 0xFFFFE8D6 },
	{ 13, 0, 0xFFFFF6E8, 0xFFFFE9C3 },
	{ 14, 0, 0xFFFFF6CF, 0xFFFFEA80 },
	{ 15, 0, 0xFFFFF6C2, 0xFFFFEAFD }
};

NJS_MKEY_A animation_0070AF58_mkey_30_rot_00709A68[] = {
	{ 0, 0, 0xB68, 0 },
	{ 15, 0, 0xB68, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_32_rot_00709B88[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 1, 0, 0x13B7, 0 },
	{ 2, 0, 0x10FB, 0 },
	{ 3, 0, 0xD3D, 0 },
	{ 4, 0, 0x92A, 0 },
	{ 5, 0, 0x56D, 0 },
	{ 6, 0, 0x2B0, 0 },
	{ 7, 0, 0x1A1, 0 },
	{ 8, 0, 0x249, 0 },
	{ 9, 0, 0x40B, 0 },
	{ 10, 0, 0x698, 0 },
	{ 11, 0, 0x99D, 0 },
	{ 12, 0, 0xCCB, 0 },
	{ 13, 0, 0xFD0, 0 },
	{ 14, 0, 0x125C, 0 },
	{ 15, 0, 0x141F, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_31_rot_00709A88[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 1, 0x1216, 0, 0xFFFFE7F7 },
	{ 2, 0xF5A, 0, 0xFFFFE7F7 },
	{ 3, 0xB9C, 0, 0xFFFFE7F7 },
	{ 4, 0x789, 0, 0xFFFFE7F7 },
	{ 5, 0x3CB, 0, 0xFFFFE7F7 },
	{ 6, 0x10F, 0, 0xFFFFE7F7 },
	{ 7, 0, 0, 0xFFFFE7F7 },
	{ 8, 0xA8, 0, 0xFFFFE7F7 },
	{ 9, 0x26A, 0, 0xFFFFE7F7 },
	{ 10, 0x4F6, 0, 0xFFFFE7F7 },
	{ 11, 0x7FC, 0, 0xFFFFE7F7 },
	{ 12, 0xB29, 0, 0xFFFFE7F7 },
	{ 13, 0xE2F, 0, 0xFFFFE7F7 },
	{ 14, 0x10BB, 0, 0xFFFFE7F7 },
	{ 15, 0x127E, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_0070AF58_mkey_36_rot_00709C88[] = {
	{ 0, 0, 0xFFFFF1BA, 0xFFFFD824 },
	{ 1, 0, 0xFFFFF1A6, 0xFFFFD867 },
	{ 2, 0, 0xFFFFF171, 0xFFFFD918 },
	{ 3, 0, 0xFFFFF127, 0xFFFFDA17 },
	{ 4, 0, 0xFFFFF0D5, 0xFFFFDB40 },
	{ 5, 0, 0xFFFFF087, 0xFFFFDC62 },
	{ 6, 0, 0xFFFFF04D, 0xFFFFDD43 },
	{ 7, 0, 0xFFFFF037, 0xFFFFDD9C },
	{ 8, 0, 0xFFFFF045, 0xFFFFDD65 },
	{ 9, 0, 0xFFFFF06A, 0xFFFFDCD2 },
	{ 10, 0, 0xFFFFF09F, 0xFFFFDC06 },
	{ 11, 0, 0xFFFFF0DE, 0xFFFFDB1E },
	{ 12, 0, 0xFFFFF11E, 0xFFFFDA37 },
	{ 13, 0, 0xFFFFF15A, 0xFFFFD966 },
	{ 14, 0, 0xFFFFF18C, 0xFFFFD8BE },
	{ 15, 0, 0xFFFFF1AD, 0xFFFFD84D }
};

NJS_MKEY_A animation_0070AF58_mkey_37_rot_00709D88[] = {
	{ 0, 0, 0xFFFFF593, 0xFFFFEE05 },
	{ 1, 0, 0xFFFFF566, 0xFFFFEDE4 },
	{ 2, 0, 0xFFFFF4EC, 0xFFFFED8F },
	{ 3, 0, 0xFFFFF436, 0xFFFFED1B },
	{ 4, 0, 0xFFFFF35C, 0xFFFFEC9D },
	{ 5, 0, 0xFFFFF27F, 0xFFFFEC2C },
	{ 6, 0, 0xFFFFF1CF, 0xFFFFEBDC },
	{ 7, 0, 0xFFFFF188, 0xFFFFEBBD },
	{ 8, 0, 0xFFFFF1B4, 0xFFFFEBD0 },
	{ 9, 0, 0xFFFFF228, 0xFFFFEC03 },
	{ 10, 0, 0xFFFFF2C6, 0xFFFFEC4F },
	{ 11, 0, 0xFFFFF375, 0xFFFFECAB },
	{ 12, 0, 0xFFFFF41F, 0xFFFFED0D },
	{ 13, 0, 0xFFFFF4B5, 0xFFFFED6B },
	{ 14, 0, 0xFFFFF52A, 0xFFFFEDBA },
	{ 15, 0, 0xFFFFF577, 0xFFFFEDF0 }
};

NJS_MKEY_A animation_0070AF58_mkey_38_rot_00709E88[] = {
	{ 0, 0, 0xFFFFFD64, 0xFFFFE84B },
	{ 1, 0, 0xFFFFFD35, 0xFFFFE7FD },
	{ 2, 0, 0xFFFFFCB1, 0xFFFFE72E },
	{ 3, 0, 0xFFFFFBE4, 0xFFFFE602 },
	{ 4, 0, 0xFFFFFADF, 0xFFFFE4A7 },
	{ 5, 0, 0xFFFFF9C8, 0xFFFFE356 },
	{ 6, 0, 0xFFFFF8E0, 0xFFFFE254 },
	{ 7, 0, 0xFFFFF87F, 0xFFFFE1ED },
	{ 8, 0, 0xFFFFF8BC, 0xFFFFE22D },
	{ 9, 0, 0xFFFFF956, 0xFFFFE2D5 },
	{ 10, 0, 0xFFFFFA24, 0xFFFFE3C1 },
	{ 11, 0, 0xFFFFFAFE, 0xFFFFE4CF },
	{ 12, 0, 0xFFFFFBCA, 0xFFFFE5DD },
	{ 13, 0, 0xFFFFFC74, 0xFFFFE6D2 },
	{ 14, 0, 0xFFFFFCF5, 0xFFFFE798 },
	{ 15, 0, 0xFFFFFD47, 0xFFFFE81B }
};

NJS_MKEY_A animation_0070AF58_mkey_41_rot_00709F88[] = {
	{ 0, 0xFFFFE8C7, 0x4E3, 0 },
	{ 15, 0xFFFFE8C7, 0x4E3, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_43_rot_0070A0A8[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 1, 0xFFFFEEA9, 0, 0 },
	{ 2, 0xFFFFF139, 0, 0 },
	{ 3, 0xFFFFF4B9, 0, 0 },
	{ 4, 0xFFFFF88A, 0, 0 },
	{ 5, 0xFFFFFC0A, 0, 0 },
	{ 6, 0xFFFFFE9A, 0, 0 },
	{ 7, 0xFFFFFF98, 0, 0 },
	{ 8, 0xFFFFFEFB, 0, 0 },
	{ 9, 0xFFFFFD55, 0, 0 },
	{ 10, 0xFFFFFAF2, 0, 0 },
	{ 11, 0xFFFFF81E, 0, 0 },
	{ 12, 0xFFFFF525, 0, 0 },
	{ 13, 0xFFFFF251, 0, 0 },
	{ 14, 0xFFFFEFEE, 0, 0 },
	{ 15, 0xFFFFEE48, 0, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_42_rot_00709FA8[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 1, 0, 0xFFFFE4D1, 0 },
	{ 2, 0, 0xFFFFE733, 0 },
	{ 3, 0, 0xFFFFEA77, 0 },
	{ 4, 0, 0xFFFFEE05, 0 },
	{ 5, 0, 0xFFFFF148, 0 },
	{ 6, 0, 0xFFFFF3AB, 0 },
	{ 7, 0, 0xFFFFF498, 0 },
	{ 8, 0, 0xFFFFF405, 0 },
	{ 9, 0, 0xFFFFF27C, 0 },
	{ 10, 0, 0xFFFFF043, 0 },
	{ 11, 0, 0xFFFFEDA1, 0 },
	{ 12, 0, 0xFFFFEADB, 0 },
	{ 13, 0, 0xFFFFE838, 0 },
	{ 14, 0, 0xFFFFE5FF, 0 },
	{ 15, 0, 0xFFFFE476, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_46_rot_0070A1A8[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 15, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_0070AF58_mkey_47_rot_0070A1C8[] = {
	{ 0, 0xFFFFFACA, 0x8DF, 0xFFFFB3B7 },
	{ 1, 0xFFFFFAD2, 0x8AF, 0xFFFFB35D },
	{ 2, 0xFFFFFAEA, 0x837, 0xFFFFB27B },
	{ 3, 0xFFFFFB15, 0x794, 0xFFFFB156 },
	{ 4, 0xFFFFFB4D, 0x6E6, 0xFFFFB02A },
	{ 5, 0xFFFFFB8A, 0x649, 0xFFFFAF26 },
	{ 6, 0xFFFFFBBB, 0x5D8, 0xFFFFAE74 },
	{ 7, 0xFFFFFBCF, 0x5AC, 0xFFFFAE2F },
	{ 8, 0xFFFFFBC3, 0x5C7, 0xFFFFAE5A },
	{ 9, 0xFFFFFBA2, 0x610, 0xFFFFAECC },
	{ 10, 0xFFFFFB76, 0x679, 0xFFFFAF75 },
	{ 11, 0xFFFFFB47, 0x6F9, 0xFFFFB04A },
	{ 12, 0xFFFFFB1B, 0x781, 0xFFFFB134 },
	{ 13, 0xFFFFFAF7, 0x804, 0xFFFFB21D },
	{ 14, 0xFFFFFADD, 0x873, 0xFFFFB2EB },
	{ 15, 0xFFFFFACE, 0x8C1, 0xFFFFB37F }
};

NJS_MKEY_A animation_0070AF58_mkey_48_rot_0070A2C8[] = {
	{ 0, 0, 0, 0x15D1 },
	{ 1, 0, 0, 0x1613 },
	{ 2, 0, 0, 0x16B6 },
	{ 3, 0, 0, 0x178D },
	{ 4, 0, 0, 0x186B },
	{ 5, 0, 0, 0x192F },
	{ 6, 0, 0, 0x19AF },
	{ 7, 0, 0, 0x19E3 },
	{ 8, 0, 0, 0x19C3 },
	{ 9, 0, 0, 0x196B },
	{ 10, 0, 0, 0x18F2 },
	{ 11, 0, 0, 0x1853 },
	{ 12, 0, 0, 0x17A6 },
	{ 13, 0, 0, 0x16FA },
	{ 14, 0, 0, 0x1664 },
	{ 15, 0, 0, 0x15FA }
};

NJS_MKEY_A animation_0070AF58_mkey_49_rot_0070A3C8[] = {
	{ 0, 0, 0, 0x13B2 },
	{ 1, 0, 0, 0x13FE },
	{ 2, 0, 0, 0x14BE },
	{ 3, 0, 0, 0x15BA },
	{ 4, 0, 0, 0x16C0 },
	{ 5, 0, 0, 0x17A5 },
	{ 6, 0, 0, 0x1851 },
	{ 7, 0, 0, 0x188F },
	{ 8, 0, 0, 0x1869 },
	{ 9, 0, 0, 0x1801 },
	{ 10, 0, 0, 0x175F },
	{ 11, 0, 0, 0x16A4 },
	{ 12, 0, 0, 0x15D8 },
	{ 13, 0, 0, 0x150E },
	{ 14, 0, 0, 0x145E },
	{ 15, 0, 0, 0x13E1 }
};

NJS_MKEY_A animation_0070AF58_mkey_52_rot_0070A4C8[] = {
	{ 0, 0x1C1C, 0xFFFFF6A2, 0xFFFFE0A1 },
	{ 1, 0x1C1C, 0xFFFFF6A2, 0xFFFFE07F },
	{ 2, 0x1C1C, 0xFFFFF6A2, 0xFFFFE025 },
	{ 3, 0x1C1C, 0xFFFFF6A2, 0xFFFFDFAB },
	{ 4, 0x1C1C, 0xFFFFF6A2, 0xFFFFDF26 },
	{ 5, 0x1C1C, 0xFFFFF6A2, 0xFFFFDEAB },
	{ 6, 0x1C1C, 0xFFFFF6A2, 0xFFFFDE52 },
	{ 7, 0x1C1C, 0xFFFFF6A2, 0xFFFFDE2F },
	{ 8, 0x1C1C, 0xFFFFF6A2, 0xFFFFDE45 },
	{ 9, 0x1C1C, 0xFFFFF6A2, 0xFFFFDE7E },
	{ 10, 0x1C1C, 0xFFFFF6A2, 0xFFFFDED2 },
	{ 11, 0x1C1C, 0xFFFFF6A2, 0xFFFFDF34 },
	{ 12, 0x1C1C, 0xFFFFF6A2, 0xFFFFDF9C },
	{ 13, 0x1C1C, 0xFFFFF6A2, 0xFFFFDFFF },
	{ 14, 0x1C1C, 0xFFFFF6A2, 0xFFFFE052 },
	{ 15, 0x1C1C, 0xFFFFF6A2, 0xFFFFE08C }
};

NJS_MKEY_A animation_0070AF58_mkey_57_rot_0070A5C8[] = {
	{ 0, 0x643, 0xFFFFF578, 0xFFFF9FDF },
	{ 1, 0x67F, 0xFFFFF543, 0xFFFF9F73 },
	{ 2, 0x71A, 0xFFFFF4B9, 0xFFFF9E6E },
	{ 3, 0x7FC, 0xFFFFF401, 0xFFFF9D03 },
	{ 4, 0x8FE, 0xFFFFF33D, 0xFFFF9B83 },
	{ 5, 0x9F7, 0xFFFFF28D, 0xFFFF9A2D },
	{ 6, 0xAB3, 0xFFFFF20F, 0xFFFF9938 },
	{ 7, 0xAFD, 0xFFFFF1DE, 0xFFFF98DA },
	{ 8, 0xACF, 0xFFFFF1FC, 0xFFFF9914 },
	{ 9, 0xA55, 0xFFFFF24D, 0xFFFF99B0 },
	{ 10, 0x9A8, 0xFFFFF2C4, 0xFFFF9A97 },
	{ 11, 0x8E1, 0xFFFFF353, 0xFFFF9BAD },
	{ 12, 0x818, 0xFFFFF3EC, 0xFFFF9CD8 },
	{ 13, 0x760, 0xFFFFF47F, 0xFFFF9DFB },
	{ 14, 0x6CA, 0xFFFFF4FD, 0xFFFF9EF7 },
	{ 15, 0x668, 0xFFFFF557, 0xFFFF9F9C }
};

NJS_MKEY_A animation_0070AF58_mkey_58_rot_0070A6C8[] = {
	{ 0, 0, 0, 0x12E8 },
	{ 1, 0, 0, 0x1328 },
	{ 2, 0, 0, 0x139C },
	{ 3, 0, 0, 0x146A },
	{ 4, 0, 0, 0x1540 },
	{ 5, 0, 0, 0x15FC },
	{ 6, 0, 0, 0x167E },
	{ 7, 0, 0, 0x16B0 },
	{ 8, 0, 0, 0x1691 },
	{ 9, 0, 0, 0x163F },
	{ 10, 0, 0, 0x15C2 },
	{ 11, 0, 0, 0x1529 },
	{ 12, 0, 0, 0x1482 },
	{ 13, 0, 0, 0x13DE },
	{ 14, 0, 0, 0x134E },
	{ 15, 0, 0, 0x1310 }
};

NJS_MKEY_A animation_0070AF58_mkey_59_rot_0070A7C8[] = {
	{ 0, 0, 0, 0x18C7 },
	{ 1, 0, 0, 0x191D },
	{ 2, 0, 0, 0x1A1E },
	{ 3, 0, 0, 0x1B3D },
	{ 4, 0, 0, 0x1C68 },
	{ 5, 0, 0, 0x1D6E },
	{ 6, 0, 0, 0x1E29 },
	{ 7, 0, 0, 0x1E70 },
	{ 8, 0, 0, 0x1E44 },
	{ 9, 0, 0, 0x1DCC },
	{ 10, 0, 0, 0x1D1D },
	{ 11, 0, 0, 0x1C48 },
	{ 12, 0, 0, 0x1B5F },
	{ 13, 0, 0, 0x1A79 },
	{ 14, 0, 0, 0x19B1 },
	{ 15, 0, 0, 0x18FD }
};

NJS_MKEY_A animation_0070AF58_mkey_62_rot_0070A8C8[] = {
	{ 0, 0x10B4, 0xC8C, 0xFFFFF639 },
	{ 1, 0x10B4, 0xC9D, 0xFFFFF5FA },
	{ 2, 0x10B4, 0xCCA, 0xFFFFF556 },
	{ 3, 0x10B4, 0xD07, 0xFFFFF476 },
	{ 4, 0x10B4, 0xD4A, 0xFFFFF381 },
	{ 5, 0x10B4, 0xD87, 0xFFFFF2A1 },
	{ 6, 0x10B4, 0xDB4, 0xFFFFF1FD },
	{ 7, 0x10B4, 0xDC5, 0xFFFFF1BE },
	{ 8, 0x10B4, 0xDBA, 0xFFFFF1E5 },
	{ 9, 0x10B4, 0xD9D, 0xFFFFF24F },
	{ 10, 0x10B4, 0xD74, 0xFFFFF2E7 },
	{ 11, 0x10B4, 0xD42, 0xFFFFF39C },
	{ 12, 0x10B4, 0xD0E, 0xFFFFF45B },
	{ 13, 0x10B4, 0xCDD, 0xFFFFF510 },
	{ 14, 0x10B4, 0xCB3, 0xFFFFF5A8 },
	{ 15, 0x10B4, 0xC97, 0xFFFFF612 }
};

NJS_MKEY_A animation_0070AF58_mkey_67_rot_0070A9C8[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0xB, 0xFFFFE53B },
	{ 2, 0, 0x28, 0xFFFFE64A },
	{ 3, 0, 0x51, 0xFFFFE7CD },
	{ 4, 0, 0x81, 0xFFFFE988 },
	{ 5, 0, 0xAE, 0xFFFFEB31 },
	{ 6, 0, 0xD0, 0xFFFFEC73 },
	{ 7, 0, 0xDD, 0xFFFFECF2 },
	{ 8, 0, 0xD5, 0xFFFFECA3 },
	{ 9, 0, 0xBF, 0xFFFFEBD2 },
	{ 10, 0, 0xA0, 0xFFFFEAAA },
	{ 11, 0, 0x7B, 0xFFFFE956 },
	{ 12, 0, 0x56, 0xFFFFE7FD },
	{ 13, 0, 0x34, 0xFFFFE6C1 },
	{ 14, 0, 0x19, 0xFFFFE5C0 },
	{ 15, 0, 6, 0xFFFFE513 }
};

NJS_MDATA2 animation_0070AF58_mdat_0070AAC8[] = {
	{ animation_0070AF58_mkey_0_pos_00709368, NULL, LengthOfArray<Uint32>(animation_0070AF58_mkey_0_pos_00709368), 0 },
	{ NULL, animation_0070AF58_mkey_1_rot_00709468, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_1_rot_00709468) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_12_rot_00709568, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_12_rot_00709568) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_19_rot_00709668, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_19_rot_00709668) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_25_rot_00709768, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_25_rot_00709768) },
	{ NULL, animation_0070AF58_mkey_26_rot_00709868, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_26_rot_00709868) },
	{ NULL, animation_0070AF58_mkey_27_rot_00709968, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_27_rot_00709968) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_30_rot_00709A68, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_30_rot_00709A68) },
	{ NULL, animation_0070AF58_mkey_32_rot_00709B88, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_32_rot_00709B88) },
	{ NULL, animation_0070AF58_mkey_31_rot_00709A88, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_31_rot_00709A88) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_36_rot_00709C88, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_36_rot_00709C88) },
	{ NULL, animation_0070AF58_mkey_37_rot_00709D88, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_37_rot_00709D88) },
	{ NULL, animation_0070AF58_mkey_38_rot_00709E88, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_38_rot_00709E88) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_41_rot_00709F88, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_41_rot_00709F88) },
	{ NULL, animation_0070AF58_mkey_43_rot_0070A0A8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_43_rot_0070A0A8) },
	{ NULL, animation_0070AF58_mkey_42_rot_00709FA8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_42_rot_00709FA8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_46_rot_0070A1A8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_46_rot_0070A1A8) },
	{ NULL, animation_0070AF58_mkey_47_rot_0070A1C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_47_rot_0070A1C8) },
	{ NULL, animation_0070AF58_mkey_48_rot_0070A2C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_48_rot_0070A2C8) },
	{ NULL, animation_0070AF58_mkey_49_rot_0070A3C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_49_rot_0070A3C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_52_rot_0070A4C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_52_rot_0070A4C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_57_rot_0070A5C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_57_rot_0070A5C8) },
	{ NULL, animation_0070AF58_mkey_58_rot_0070A6C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_58_rot_0070A6C8) },
	{ NULL, animation_0070AF58_mkey_59_rot_0070A7C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_59_rot_0070A7C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_62_rot_0070A8C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_62_rot_0070A8C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070AF58_mkey_67_rot_0070A9C8, 0, LengthOfArray<Uint32>(animation_0070AF58_mkey_67_rot_0070A9C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbwait0 = { animation_0070AF58_mdat_0070AAC8, 16, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbwait0 = { AMY_OBJECTS[0], &motion_a_sbwait0 };
