/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_007214A0_mkey_0_pos_0071F740[] = {
	{ 0, 0, -2.4437f, 2.6106f },
	{ 1, 0, -2.4271f, 2.5925f },
	{ 2, 0, -2.3804f, 2.5414f },
	{ 3, 0, -2.3078f, 2.4619f },
	{ 4, 0, -2.2136f, 2.3589f },
	{ 5, 0, -2.1021f, 2.237f },
	{ 6, 0, -1.9777f, 2.101f },
	{ 7, 0, -1.8446f, 1.9555f },
	{ 8, 0, -1.7073f, 1.8053f },
	{ 9, 0, -1.5699f, 1.6551f },
	{ 10, 0, -1.4369f, 1.5096f },
	{ 11, 0, -1.3125f, 1.3735f },
	{ 12, 0, -1.201f, 1.2516f },
	{ 13, 0, -1.1068f, 1.1486f },
	{ 14, 0, -1.0342f, 1.0692f },
	{ 15, 0, -0.9874f, 1.0181f },
	{ 16, 0, -0.9709f, 1 }
};

NJS_MKEY_A animation_007214A0_mkey_1_rot_0071F850[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0, 0xFFFFEA74, 0x88E },
	{ 2, 0, 0xFFFFE9D9, 0x88E },
	{ 3, 0, 0xFFFFE8E7, 0x88E },
	{ 4, 0, 0xFFFFE7AD, 0x88E },
	{ 5, 0, 0xFFFFE63A, 0x88E },
	{ 6, 0, 0xFFFFE49C, 0x88E },
	{ 7, 0, 0xFFFFE2E1, 0x88E },
	{ 8, 0, 0xFFFFE118, 0x88E },
	{ 9, 0, 0xFFFFDF4F, 0x88E },
	{ 10, 0, 0xFFFFDD94, 0x88E },
	{ 11, 0, 0xFFFFDBF6, 0x88E },
	{ 12, 0, 0xFFFFDA83, 0x88E },
	{ 13, 0, 0xFFFFD949, 0x88E },
	{ 14, 0, 0xFFFFD858, 0x88E },
	{ 15, 0, 0xFFFFD7BC, 0x88E },
	{ 16, 0, 0xFFFFD785, 0x88E }
};

NJS_MKEY_A animation_007214A0_mkey_12_rot_0071F960[] = {
	{ 0, 0, 0xFFFFEAC7, 0x8875 },
	{ 1, 0x2B, 0xFFFFEB31, 0x887A },
	{ 2, 0xA5, 0xFFFFEC62, 0x8889 },
	{ 3, 0x164, 0xFFFFEE48, 0x88A0 },
	{ 4, 0x25A, 0xFFFFF0D4, 0x88BD },
	{ 5, 0x37F, 0xFFFFF3F0, 0x88DF },
	{ 6, 0x4C5, 0xFFFFF77F, 0x8903 },
	{ 7, 0x621, 0xFFFFFB58, 0x892A },
	{ 8, 0x789, 0xFFFFFF4D, 0x8950 },
	{ 9, 0x8F1, 0x328, 0x8976 },
	{ 10, 0xA4E, 0x6BF, 0x8999 },
	{ 11, 0xB94, 0x9EF, 0x89B9 },
	{ 12, 0xCB8, 0xCA1, 0x89D5 },
	{ 13, 0xDAF, 0xEC8, 0x89EC },
	{ 14, 0xE6D, 0x105B, 0x89FE },
	{ 15, 0xEE7, 0x1156, 0x8A09 },
	{ 16, 0xF13, 0x11AC, 0x8A0D }
};

NJS_MKEY_A animation_007214A0_mkey_15_rot_0071FA70[] = {
	{ 0, 0, 0xB6A, 0xFFFF87C1 },
	{ 1, 0, 0xBBB, 0xFFFF881E },
	{ 2, 0, 0xC94, 0xFFFF8913 },
	{ 3, 0, 0xDCD, 0xFFFF8A68 },
	{ 4, 0, 0xF32, 0xFFFF8BD7 },
	{ 5, 0, 0x107E, 0xFFFF8D13 },
	{ 6, 0, 0x1166, 0xFFFF8DD4 },
	{ 7, 0, 0x11AA, 0xFFFF8DF6 },
	{ 8, 0, 0x1140, 0xFFFF8DCF },
	{ 9, 0, 0x106F, 0xFFFF8DBF },
	{ 10, 0, 0xF79, 0xFFFF8DCE },
	{ 11, 0, 0xE8C, 0xFFFF8DF5 },
	{ 12, 0, 0xDC4, 0xFFFF8E2C },
	{ 13, 0, 0xD2B, 0xFFFF8E67 },
	{ 14, 0, 0xCC1, 0xFFFF8E9E },
	{ 15, 0, 0xC83, 0xFFFF8EC6 },
	{ 16, 0, 0xC6E, 0xFFFF8ED6 }
};

NJS_MKEY_A animation_007214A0_mkey_19_rot_0071FB80[] = {
	{ 0, 0, 0xFFFFF461, 0xFFFF87BF },
	{ 1, 0, 0xFFFFF462, 0xFFFF880B },
	{ 2, 0, 0xFFFFF463, 0xFFFF88D7 },
	{ 3, 0, 0xFFFFF46E, 0xFFFF8A02 },
	{ 4, 0, 0xFFFFF489, 0xFFFF8B65 },
	{ 5, 0, 0xFFFFF4BA, 0xFFFF8CD3 },
	{ 6, 0, 0xFFFFF4FB, 0xFFFF8E17 },
	{ 7, 0, 0xFFFFF53D, 0xFFFF8F01 },
	{ 8, 0, 0xFFFFF569, 0xFFFF8F85 },
	{ 9, 0, 0xFFFFF578, 0xFFFF8FC0 },
	{ 10, 0, 0xFFFFF56C, 0xFFFF8FC4 },
	{ 11, 0, 0xFFFFF54B, 0xFFFF8FA8 },
	{ 12, 0, 0xFFFFF51F, 0xFFFF8F7D },
	{ 13, 0, 0xFFFFF4F0, 0xFFFF8F53 },
	{ 14, 0, 0xFFFFF4C6, 0xFFFF8F30 },
	{ 15, 0, 0xFFFFF4A7, 0xFFFF8F19 },
	{ 16, 0, 0xFFFFF49B, 0xFFFF8F11 }
};

NJS_MKEY_A animation_007214A0_mkey_25_rot_0071FC90[] = {
	{ 0, 0, 0x2D2E, 0xFFFFDD27 },
	{ 1, 0, 0x2CC1, 0xFFFFDD44 },
	{ 2, 0, 0x2B8E, 0xFFFFDD92 },
	{ 3, 0, 0x29AB, 0xFFFFDDFC },
	{ 4, 0, 0x2733, 0xFFFFDE70 },
	{ 5, 0, 0x2444, 0xFFFFDEE3 },
	{ 6, 0, 0x2104, 0xFFFFDF4C },
	{ 7, 0, 0x1D9D, 0xFFFFDFA9 },
	{ 8, 0, 0x1A3A, 0xFFFFDFF8 },
	{ 9, 0, 0x1700, 0xFFFFE03B },
	{ 10, 0, 0x140F, 0xFFFFE073 },
	{ 11, 0, 0x117B, 0xFFFFE0A0 },
	{ 12, 0, 0xF50, 0xFFFFE0C4 },
	{ 13, 0, 0xD97, 0xFFFFE0DF },
	{ 14, 0, 0xC53, 0xFFFFE0F3 },
	{ 15, 0, 0xB8B, 0xFFFFE0FF },
	{ 16, 0, 0xB45, 0xFFFFE103 }
};

NJS_MKEY_A animation_007214A0_mkey_26_rot_0071FDA0[] = {
	{ 0, 0, 0xEB2, 0xFFFFF6E2 },
	{ 1, 0, 0xED1, 0xFFFFF6C1 },
	{ 2, 0, 0xF22, 0xFFFFF661 },
	{ 3, 0, 0xF8E, 0xFFFFF5C2 },
	{ 4, 0, 0xFF5, 0xFFFFF4E9 },
	{ 5, 0, 0x102F, 0xFFFFF3DB },
	{ 6, 0, 0x1012, 0xFFFFF2A8 },
	{ 7, 0, 0xF7E, 0xFFFFF16B },
	{ 8, 0, 0xE64, 0xFFFFF041 },
	{ 9, 0, 0xCD3, 0xFFFFEF47 },
	{ 10, 0, 0xAF4, 0xFFFFEE8D },
	{ 11, 0, 0x8FF, 0xFFFFEE14 },
	{ 12, 0, 0x729, 0xFFFFEDD1 },
	{ 13, 0, 0x59A, 0xFFFFEDB4 },
	{ 14, 0, 0x46C, 0xFFFFEDAD },
	{ 15, 0, 0x3AF, 0xFFFFEDAF },
	{ 16, 0, 0x36C, 0xFFFFEDB1 }
};

NJS_MKEY_A animation_007214A0_mkey_27_rot_0071FEB0[] = {
	{ 0, 0, 0x1D70, 0xFFFFF613 },
	{ 1, 0, 0x1DA6, 0xFFFFF5E8 },
	{ 2, 0, 0x1E3F, 0xFFFFF560 },
	{ 3, 0, 0x1F2A, 0xFFFFF45B },
	{ 4, 0, 0x204E, 0xFFFFF2AE },
	{ 5, 0, 0x2186, 0xFFFFF023 },
	{ 6, 0, 0x2295, 0xFFFFEC8E },
	{ 7, 0, 0x231E, 0xFFFFE7F6 },
	{ 8, 0, 0x22B5, 0xFFFFE2CA },
	{ 9, 0, 0x20FA, 0xFFFFDDF1 },
	{ 10, 0, 0x1DCD, 0xFFFFDA6A },
	{ 11, 0, 0x1963, 0xFFFFD8C2 },
	{ 12, 0, 0x1448, 0xFFFFD8D7 },
	{ 13, 0, 0xF4C, 0xFFFFDA0D },
	{ 14, 0, 0xB3A, 0xFFFFDB9C },
	{ 15, 0, 0x89A, 0xFFFFDCDA },
	{ 16, 0, 0x7B0, 0xFFFFDD54 }
};

NJS_MKEY_A animation_007214A0_mkey_30_rot_0071FFC0[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 1, 0x3E, 0x18BA, 0 },
	{ 2, 0xED, 0x1861, 0 },
	{ 3, 0x1FE, 0x17D6, 0 },
	{ 4, 0x35F, 0x1722, 0 },
	{ 5, 0x502, 0x164D, 0 },
	{ 6, 0x6D5, 0x155F, 0 },
	{ 7, 0x8C8, 0x1460, 0 },
	{ 8, 0xACC, 0x135A, 0 },
	{ 9, 0xCCF, 0x1253, 0 },
	{ 10, 0xEC2, 0x1155, 0 },
	{ 11, 0x1095, 0x1067, 0 },
	{ 12, 0x1238, 0xF92, 0 },
	{ 13, 0x1399, 0xEDE, 0 },
	{ 14, 0x14AA, 0xE53, 0 },
	{ 15, 0x1559, 0xDF9, 0 },
	{ 16, 0x1598, 0xDDA, 0 }
};

NJS_MKEY_A animation_007214A0_mkey_32_rot_007200F0[] = {
	{ 0, 0, 0x35C7, 0 },
	{ 1, 0, 0x3552, 0 },
	{ 2, 0, 0x3407, 0 },
	{ 3, 0, 0x3205, 0 },
	{ 4, 0, 0x2F6A, 0 },
	{ 5, 0, 0x2C54, 0 },
	{ 6, 0, 0x28E3, 0 },
	{ 7, 0, 0x2535, 0 },
	{ 8, 0, 0x2168, 0 },
	{ 9, 0, 0x1D9C, 0 },
	{ 10, 0, 0x19ED, 0 },
	{ 11, 0, 0x167C, 0 },
	{ 12, 0, 0x1367, 0 },
	{ 13, 0, 0x10CC, 0 },
	{ 14, 0, 0xEC9, 0 },
	{ 15, 0, 0xD7E, 0 },
	{ 16, 0, 0xD09, 0 }
};

NJS_MKEY_A animation_007214A0_mkey_31_rot_007200D0[] = {
	{ 0, 0, 0x95E, 0xFFFFE7F7 },
	{ 16, 0, 0x95E, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_007214A0_mkey_36_rot_00720200[] = {
	{ 0, 0, 0xFFFFE648, 0xFFFFD063 },
	{ 1, 0, 0xFFFFE5D1, 0xFFFFD08A },
	{ 2, 0, 0xFFFFE4A1, 0xFFFFD0E1 },
	{ 3, 0, 0xFFFFE309, 0xFFFFD13F },
	{ 4, 0, 0xFFFFE152, 0xFFFFD178 },
	{ 5, 0, 0xFFFFDFB3, 0xFFFFD15D },
	{ 6, 0, 0xFFFFDE5B, 0xFFFFD0BA },
	{ 7, 0, 0xFFFFDD72, 0xFFFFCF52 },
	{ 8, 0, 0xFFFFDCE6, 0xFFFFCCBD },
	{ 9, 0, 0xFFFFDC98, 0xFFFFC8D6 },
	{ 10, 0, 0xFFFFDCAD, 0xFFFFC3D2 },
	{ 11, 0, 0xFFFFDD48, 0xFFFFBE15 },
	{ 12, 0, 0xFFFFDE70, 0xFFFFB840 },
	{ 13, 0, 0xFFFFDFFC, 0xFFFFB300 },
	{ 14, 0, 0xFFFFE196, 0xFFFFAEDF },
	{ 15, 0, 0xFFFFE2D3, 0xFFFFAC36 },
	{ 16, 0, 0xFFFFE34E, 0xFFFFAB44 }
};

NJS_MKEY_A animation_007214A0_mkey_37_rot_00720310[] = {
	{ 0, 0, 0xFFFFF6C6, 0xFFFFF88C },
	{ 1, 0, 0xFFFFF67F, 0xFFFFF91E },
	{ 2, 0, 0xFFFFF5C1, 0xFFFFFA9F },
	{ 3, 0, 0xFFFFF4A5, 0xFFFFFCBF },
	{ 4, 0, 0xFFFFF34A, 0xFFFFFF1A },
	{ 5, 0, 0xFFFFF1CC, 0x129 },
	{ 6, 0, 0xFFFFF044, 0x24B },
	{ 7, 0, 0xFFFFEEDE, 0x1A4 },
	{ 8, 0, 0xFFFFEE0E, 0xFFFFFD17 },
	{ 9, 0, 0xFFFFEF75, 0xFFFFF380 },
	{ 10, 0, 0xFFFFF51B, 0xFFFFE821 },
	{ 11, 0, 0xFFFFFD64, 0xFFFFE060 },
	{ 12, 0, 0x49A, 0xFFFFDDE0 },
	{ 13, 0, 0x92F, 0xFFFFE082 },
	{ 14, 0, 0xB38, 0xFFFFE64A },
	{ 15, 0, 0xB57, 0xFFFFEC0B },
	{ 16, 0, 0xB01, 0xFFFFEEA7 }
};

NJS_MKEY_A animation_007214A0_mkey_38_rot_00720420[] = {
	{ 0, 0, 0xFFFFF47F, 0xFFFFFAC6 },
	{ 1, 0, 0xFFFFF39C, 0xFFFFFB85 },
	{ 2, 0, 0xFFFFF159, 0xFFFFFD95 },
	{ 3, 0, 0xFFFFEE69, 0xA9 },
	{ 4, 0, 0xFFFFEB8B, 0x40D },
	{ 5, 0, 0xFFFFE905, 0x6B5 },
	{ 6, 0, 0xFFFFE661, 0x79A },
	{ 7, 0, 0xFFFFE2D5, 0x52C },
	{ 8, 0, 0xFFFFDE52, 0xFFFFF771 },
	{ 9, 0, 0xFFFFE5FF, 0xFFFFDE51 },
	{ 10, 0, 0xFFFFF783, 0xFFFFD8DE },
	{ 11, 0, 0x15E, 0xFFFFDEE0 },
	{ 12, 0, 0x4C2, 0xFFFFE554 },
	{ 13, 0, 0x5B0, 0xFFFFE9BD },
	{ 14, 0, 0x548, 0xFFFFED7A },
	{ 15, 0, 0x35A, 0xFFFFF15E },
	{ 16, 0, 0x1CC, 0xFFFFF382 }
};

NJS_MKEY_A animation_007214A0_mkey_41_rot_00720530[] = {
	{ 0, 0xFFFFC68E, 0, 0 },
	{ 1, 0xFFFFC7A5, 0x3F, 0x20 },
	{ 2, 0xFFFFCAB9, 0xF2, 0x7D },
	{ 3, 0xFFFFCF81, 0x207, 0x10D },
	{ 4, 0xFFFFD5B5, 0x370, 0x1C8 },
	{ 5, 0xFFFFDD0B, 0x51A, 0x2A5 },
	{ 6, 0xFFFFE53C, 0x6F6, 0x39C },
	{ 7, 0xFFFFEDFF, 0x8F2, 0x4A3 },
	{ 8, 0xFFFFF70A, 0xB00, 0x5B4 },
	{ 9, 0x14, 0xD0D, 0x6C4 },
	{ 10, 0x8D6, 0xF0A, 0x7CC },
	{ 11, 0x1107, 0x10E6, 0x8C3 },
	{ 12, 0x185E, 0x1290, 0x9A0 },
	{ 13, 0x1E92, 0x13F8, 0xA5A },
	{ 14, 0x235A, 0x150E, 0xAEA },
	{ 15, 0x266E, 0x15C1, 0xB47 },
	{ 16, 0x2785, 0x1600, 0xB68 }
};

NJS_MKEY_A animation_007214A0_mkey_43_rot_00720750[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_007214A0_mkey_42_rot_00720640[] = {
	{ 0, 0, 0xFFFFD4D0, 0 },
	{ 1, 0, 0xFFFFD532, 0 },
	{ 2, 0, 0xFFFFD644, 0 },
	{ 3, 0, 0xFFFFD7EF, 0 },
	{ 4, 0, 0xFFFFDA19, 0 },
	{ 5, 0, 0xFFFFDCA8, 0 },
	{ 6, 0, 0xFFFFDF84, 0 },
	{ 7, 0, 0xFFFFE292, 0 },
	{ 8, 0, 0xFFFFE5B9, 0 },
	{ 9, 0, 0xFFFFE8E0, 0 },
	{ 10, 0, 0xFFFFEBEE, 0 },
	{ 11, 0, 0xFFFFEECA, 0 },
	{ 12, 0, 0xFFFFF159, 0 },
	{ 13, 0, 0xFFFFF383, 0 },
	{ 14, 0, 0xFFFFF52E, 0 },
	{ 15, 0, 0xFFFFF640, 0 },
	{ 16, 0, 0xFFFFF6A2, 0 }
};

NJS_MKEY_A animation_007214A0_mkey_46_rot_00720770[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_007214A0_mkey_47_rot_00720790[] = {
	{ 0, 0xFFFFE3ED, 0x10EF, 0xFFFF8C99 },
	{ 1, 0xFFFFE454, 0x10BF, 0xFFFF8CDB },
	{ 2, 0xFFFFE576, 0x103D, 0xFFFF8D99 },
	{ 3, 0xFFFFE733, 0xF7B, 0xFFFF8ED0 },
	{ 4, 0xFFFFE968, 0xE8E, 0xFFFF907C },
	{ 5, 0xFFFFEBED, 0xD88, 0xFFFF929D },
	{ 6, 0xFFFFEE96, 0xC79, 0xFFFF952C },
	{ 7, 0xFFFFF139, 0xB6D, 0xFFFF9820 },
	{ 8, 0xFFFFF3B2, 0xA6E, 0xFFFF9B6A },
	{ 9, 0xFFFFF5E5, 0x97F, 0xFFFF9EE9 },
	{ 10, 0xFFFFF7C4, 0x8AA, 0xFFFFA285 },
	{ 11, 0xFFFFF956, 0x7FC, 0xFFFFA652 },
	{ 12, 0xFFFFFA96, 0x76F, 0xFFFFAA07 },
	{ 13, 0xFFFFFB8C, 0x703, 0xFFFFAD73 },
	{ 14, 0xFFFFFC3E, 0x6B8, 0xFFFFB059 },
	{ 15, 0xFFFFFCAC, 0x68B, 0xFFFFB253 },
	{ 16, 0xFFFFFCD3, 0x67C, 0xFFFFB316 }
};

NJS_MKEY_A animation_007214A0_mkey_48_rot_007208A0[] = {
	{ 0, 0, 0, 0x25CA },
	{ 2, 0, 0, 0x25C7 },
	{ 3, 0, 0, 0x25AE },
	{ 4, 0, 0, 0x256E },
	{ 5, 0, 0, 0x24F1 },
	{ 6, 0, 0, 0x242B },
	{ 7, 0, 0, 0x2310 },
	{ 8, 0, 0, 0x219E },
	{ 9, 0, 0, 0x1FED },
	{ 10, 0, 0, 0x1E42 },
	{ 11, 0, 0, 0x1BEF },
	{ 12, 0, 0, 0x1986 },
	{ 13, 0, 0, 0x1736 },
	{ 14, 0, 0, 0x1525 },
	{ 15, 0, 0, 0x13DB },
	{ 16, 0, 0, 0x1345 }
};

NJS_MKEY_A animation_007214A0_mkey_49_rot_007209A0[] = {
	{ 0, 0, 0, 0x2859 },
	{ 2, 0, 0, 0x2854 },
	{ 3, 0, 0, 0x2834 },
	{ 4, 0, 0, 0x27DE },
	{ 5, 0, 0, 0x273B },
	{ 6, 0, 0, 0x2637 },
	{ 7, 0, 0, 0x24C6 },
	{ 8, 0, 0, 0x22E8 },
	{ 9, 0, 0, 0x20A8 },
	{ 10, 0, 0, 0x1DB4 },
	{ 11, 0, 0, 0x1AF8 },
	{ 12, 0, 0, 0x1821 },
	{ 13, 0, 0, 0x1555 },
	{ 14, 0, 0, 0x12E8 },
	{ 15, 0, 0, 0x10F5 },
	{ 16, 0, 0, 0x1052 }
};

NJS_MKEY_A animation_007214A0_mkey_52_rot_00720AA0[] = {
	{ 0, 0x1C1C, 0xFFFFF2F7, 0xFFFFC142 },
	{ 1, 0x1C1C, 0xFFFFF30A, 0xFFFFC12A },
	{ 2, 0x1C1C, 0xFFFFF340, 0xFFFFC0FA },
	{ 3, 0x1C1C, 0xFFFFF393, 0xFFFFC0D2 },
	{ 4, 0x1C1C, 0xFFFFF3FB, 0xFFFFC0D4 },
	{ 5, 0x1C1C, 0xFFFFF473, 0xFFFFC122 },
	{ 6, 0x1C1C, 0xFFFFF4F3, 0xFFFFC1DC },
	{ 7, 0x1C1C, 0xFFFFF577, 0xFFFFC324 },
	{ 8, 0x1C1C, 0xFFFFF60F, 0xFFFFC53A },
	{ 9, 0x1C1C, 0xFFFFF6CB, 0xFFFFC816 },
	{ 10, 0x1C1C, 0xFFFFF79B, 0xFFFFCB72 },
	{ 11, 0x1C1C, 0xFFFFF873, 0xFFFFCF0A },
	{ 12, 0x1C1C, 0xFFFFF943, 0xFFFFD298 },
	{ 13, 0x1C1C, 0xFFFFF9FD, 0xFFFFD5D4 },
	{ 14, 0x1C1C, 0xFFFFFA93, 0xFFFFD87B },
	{ 15, 0x1C1C, 0xFFFFFAF8, 0xFFFFDA45 },
	{ 16, 0x1C1C, 0xFFFFFB1D, 0xFFFFDAED }
};

NJS_MKEY_A animation_007214A0_mkey_57_rot_00720BB0[] = {
	{ 0, 0xFFFFF8C3, 0x676, 0xFFFF6DA7 },
	{ 1, 0xFFFFF915, 0x628, 0xFFFF6DE2 },
	{ 2, 0xFFFFF9FF, 0x54E, 0xFFFF6E8C },
	{ 3, 0xFFFFFB6D, 0x400, 0xFFFF6FA0 },
	{ 4, 0xFFFFFD4C, 0x259, 0xFFFF711B },
	{ 5, 0xFFFFFF80, 0x6E, 0xFFFF72FD },
	{ 6, 0x1E8, 0xFFFFFE59, 0xFFFF7547 },
	{ 7, 0x45C, 0xFFFFFC2B, 0xFFFF77F8 },
	{ 8, 0x6B4, 0xFFFFF9F7, 0xFFFF7B0C },
	{ 9, 0x8C9, 0xFFFFF7CE, 0xFFFF7E78 },
	{ 10, 0xA80, 0xFFFFF5C3, 0xFFFF8218 },
	{ 11, 0xBC4, 0xFFFFF3E2, 0xFFFF85E3 },
	{ 12, 0xC97, 0xFFFFF239, 0xFFFF899D },
	{ 13, 0xD09, 0xFFFFF0DA, 0xFFFF8D06 },
	{ 14, 0xD34, 0xFFFFEFCF, 0xFFFF8FD5 },
	{ 15, 0xD39, 0xFFFFEF26, 0xFFFF91BB },
	{ 16, 0xD37, 0xFFFFEEEA, 0xFFFF926B }
};

NJS_MKEY_A animation_007214A0_mkey_58_rot_00720CC0[] = {
	{ 0, 0, 0, 0x1DD4 },
	{ 1, 0, 0, 0x1DE6 },
	{ 2, 0, 0, 0x1E16 },
	{ 3, 0, 0, 0x1E53 },
	{ 4, 0, 0, 0x1E88 },
	{ 5, 0, 0, 0x1EA2 },
	{ 6, 0, 0, 0x1E8E },
	{ 7, 0, 0, 0x1E40 },
	{ 8, 0, 0, 0x1DB2 },
	{ 9, 0, 0, 0x1CE3 },
	{ 10, 0, 0, 0x1BE6 },
	{ 11, 0, 0, 0x1AB8 },
	{ 12, 0, 0, 0x1975 },
	{ 13, 0, 0, 0x183A },
	{ 14, 0, 0, 0x172C },
	{ 15, 0, 0, 0x1672 },
	{ 16, 0, 0, 0x162D }
};

NJS_MKEY_A animation_007214A0_mkey_59_rot_00720DD0[] = {
	{ 0, 0, 0, 0x2888 },
	{ 1, 0, 0, 0x28A3 },
	{ 2, 0, 0, 0x28E7 },
	{ 3, 0, 0, 0x293D },
	{ 4, 0, 0, 0x2989 },
	{ 5, 0, 0, 0x29AE },
	{ 6, 0, 0, 0x2992 },
	{ 7, 0, 0, 0x2923 },
	{ 8, 0, 0, 0x2858 },
	{ 9, 0, 0, 0x2733 },
	{ 10, 0, 0, 0x25CB },
	{ 11, 0, 0, 0x2419 },
	{ 12, 0, 0, 0x2251 },
	{ 13, 0, 0, 0x2098 },
	{ 14, 0, 0, 0x1F1D },
	{ 15, 0, 0, 0x1E14 },
	{ 16, 0, 0, 0x1DB3 }
};

NJS_MKEY_A animation_007214A0_mkey_62_rot_00720EE0[] = {
	{ 0, 0x54B, 0x185D, 0xFFFFE655 },
	{ 16, 0x54B, 0x185D, 0xFFFFE655 }
};

NJS_MKEY_A animation_007214A0_mkey_67_rot_00720F00[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0xFFFFFFB8, 0xFFFFE4A4 },
	{ 2, 0, 0xFFFFFEEA, 0xFFFFE41A },
	{ 3, 0, 0xFFFFFDA6, 0xFFFFE341 },
	{ 4, 0, 0xFFFFFBFB, 0xFFFFE223 },
	{ 5, 0, 0xFFFFF9FC, 0xFFFFE0C8 },
	{ 6, 0, 0xFFFFF7C0, 0xFFFFDF3B },
	{ 7, 0, 0xFFFFF55E, 0xFFFFDD88 },
	{ 8, 0, 0xFFFFF2F4, 0xFFFFDBBE },
	{ 9, 0, 0xFFFFF09D, 0xFFFFD9EB },
	{ 10, 0, 0xFFFFEE70, 0xFFFFD820 },
	{ 11, 0, 0xFFFFEC80, 0xFFFFD66F },
	{ 12, 0, 0xFFFFEADC, 0xFFFFD4E8 },
	{ 13, 0, 0xFFFFE98B, 0xFFFFD39D },
	{ 14, 0, 0xFFFFE892, 0xFFFFD29E },
	{ 15, 0, 0xFFFFE7F8, 0xFFFFD1FA },
	{ 16, 0, 0xFFFFE7C3, 0xFFFFD1C0 }
};

NJS_MDATA2 animation_007214A0_mdat_00721010[] = {
	{ animation_007214A0_mkey_0_pos_0071F740, NULL, LengthOfArray<Uint32>(animation_007214A0_mkey_0_pos_0071F740), 0 },
	{ NULL, animation_007214A0_mkey_1_rot_0071F850, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_1_rot_0071F850) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_12_rot_0071F960, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_12_rot_0071F960) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_15_rot_0071FA70, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_15_rot_0071FA70) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_19_rot_0071FB80, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_19_rot_0071FB80) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_25_rot_0071FC90, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_25_rot_0071FC90) },
	{ NULL, animation_007214A0_mkey_26_rot_0071FDA0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_26_rot_0071FDA0) },
	{ NULL, animation_007214A0_mkey_27_rot_0071FEB0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_27_rot_0071FEB0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_30_rot_0071FFC0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_30_rot_0071FFC0) },
	{ NULL, animation_007214A0_mkey_32_rot_007200F0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_32_rot_007200F0) },
	{ NULL, animation_007214A0_mkey_31_rot_007200D0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_31_rot_007200D0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_36_rot_00720200, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_36_rot_00720200) },
	{ NULL, animation_007214A0_mkey_37_rot_00720310, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_37_rot_00720310) },
	{ NULL, animation_007214A0_mkey_38_rot_00720420, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_38_rot_00720420) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_41_rot_00720530, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_41_rot_00720530) },
	{ NULL, animation_007214A0_mkey_43_rot_00720750, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_43_rot_00720750) },
	{ NULL, animation_007214A0_mkey_42_rot_00720640, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_42_rot_00720640) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_46_rot_00720770, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_46_rot_00720770) },
	{ NULL, animation_007214A0_mkey_47_rot_00720790, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_47_rot_00720790) },
	{ NULL, animation_007214A0_mkey_48_rot_007208A0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_48_rot_007208A0) },
	{ NULL, animation_007214A0_mkey_49_rot_007209A0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_49_rot_007209A0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_52_rot_00720AA0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_52_rot_00720AA0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_57_rot_00720BB0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_57_rot_00720BB0) },
	{ NULL, animation_007214A0_mkey_58_rot_00720CC0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_58_rot_00720CC0) },
	{ NULL, animation_007214A0_mkey_59_rot_00720DD0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_59_rot_00720DD0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_62_rot_00720EE0, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_62_rot_00720EE0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007214A0_mkey_67_rot_00720F00, 0, LengthOfArray<Uint32>(animation_007214A0_mkey_67_rot_00720F00) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbrstop0 = { animation_007214A0_mdat_00721010, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbrstop0 = { AMY_OBJECTS[0], &motion_a_sbrstop0 };
