/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_00727208_mkey_0_pos_007253A8[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 1, 0, -0.7546f, 0 },
	{ 2, 0, -0.8088f, 0 },
	{ 3, 0, -0.893f, 0 },
	{ 4, 0, -1.0023f, 0 },
	{ 5, 0, -1.1316f, 0 },
	{ 6, 0, -1.2759f, 0 },
	{ 7, 0, -1.4302f, 0 },
	{ 8, 0, -1.5895f, 0 },
	{ 9, 0, -1.7489f, 0 },
	{ 10, 0, -1.9032f, 0 },
	{ 11, 0, -2.0475f, 0 },
	{ 12, 0, -2.1768f, 0 },
	{ 13, 0, -2.286f, 0 },
	{ 14, 0, -2.3703f, 0 },
	{ 15, 0, -2.4245f, 0 },
	{ 16, 0, -2.4437f, 0 }
};

NJS_MKEY_A animation_00727208_mkey_1_rot_007254B8[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0x23, 0xFFFFEAC4, 0x87B },
	{ 2, 0x86, 0xFFFFEB09, 0x846 },
	{ 3, 0x120, 0xFFFFEB75, 0x7F4 },
	{ 4, 0x1E8, 0xFFFFEC01, 0x789 },
	{ 5, 0x2D5, 0xFFFFECA7, 0x70B },
	{ 6, 0x3DE, 0xFFFFED60, 0x67E },
	{ 7, 0x4F8, 0xFFFFEE26, 0x5E7 },
	{ 8, 0x61C, 0xFFFFEEF2, 0x54B },
	{ 9, 0x740, 0xFFFFEFBF, 0x4B0 },
	{ 10, 0x85B, 0xFFFFF085, 0x419 },
	{ 11, 0x963, 0xFFFFF13E, 0x38C },
	{ 12, 0xA50, 0xFFFFF1E3, 0x30E },
	{ 13, 0xB18, 0xFFFFF26F, 0x2A3 },
	{ 14, 0xBB2, 0xFFFFF2DB, 0x251 },
	{ 15, 0xC15, 0xFFFFF321, 0x21C },
	{ 16, 0xC39, 0xFFFFF33A, 0x209 }
};

NJS_MKEY_A animation_00727208_mkey_12_rot_007255C8[] = {
	{ 0, 0, 0xFFFFEAC7, 0x8875 },
	{ 1, 0, 0xFFFFEA73, 0x8892 },
	{ 2, 0, 0xFFFFE98F, 0x88DD },
	{ 3, 0, 0xFFFFE83E, 0x8946 },
	{ 4, 0, 0xFFFFE6A7, 0x89BB },
	{ 5, 0, 0xFFFFE4EB, 0x8A2B },
	{ 6, 0, 0xFFFFE32A, 0x8A84 },
	{ 7, 0, 0xFFFFE17D, 0x8AB1 },
	{ 8, 0, 0xFFFFDFF8, 0x8A9C },
	{ 9, 0, 0xFFFFDEAD, 0x8A2D },
	{ 10, 0, 0xFFFFDD65, 0x8902 },
	{ 11, 0, 0xFFFFDBFC, 0x86F0 },
	{ 12, 0, 0xFFFFDAA1, 0x843E },
	{ 13, 0, 0xFFFFD97B, 0x8149 },
	{ 14, 0, 0xFFFFD8A2, 0x7E86 },
	{ 15, 0, 0xFFFFD820, 0x7C7C },
	{ 16, 0, 0xFFFFD7F3, 0x7BB1 }
};

NJS_MKEY_A animation_00727208_mkey_15_rot_007256D8[] = {
	{ 0, 0, 0xB6A, 0xFFFF87C1 },
	{ 1, 0, 0xB86, 0xFFFF87CC },
	{ 2, 0, 0xBCB, 0xFFFF87E8 },
	{ 3, 0, 0xC23, 0xFFFF880E },
	{ 4, 0, 0xC76, 0xFFFF8839 },
	{ 5, 0, 0xCB4, 0xFFFF885E },
	{ 6, 0, 0xCD2, 0xFFFF8878 },
	{ 7, 0, 0xCCE, 0xFFFF887F },
	{ 8, 0, 0xCAD, 0xFFFF8870 },
	{ 9, 0, 0xC78, 0xFFFF884B },
	{ 10, 0, 0xC26, 0xFFFF880A },
	{ 11, 0, 0xBCE, 0xFFFF87C9 },
	{ 12, 0, 0xB90, 0xFFFF87B9 },
	{ 13, 0, 0xB6E, 0xFFFF87E9 },
	{ 14, 0, 0xB5C, 0xFFFF8844 },
	{ 15, 0, 0xB4F, 0xFFFF889D },
	{ 16, 0, 0xB49, 0xFFFF88C4 }
};

NJS_MKEY_A animation_00727208_mkey_19_rot_007257E8[] = {
	{ 0, 0, 0xFFFFF461, 0xFFFF87BF },
	{ 1, 0, 0xFFFFF405, 0xFFFF87B7 },
	{ 2, 0, 0xFFFFF313, 0xFFFF87A6 },
	{ 3, 0, 0xFFFFF1CB, 0xFFFF8795 },
	{ 4, 0, 0xFFFFF06F, 0xFFFF878B },
	{ 5, 0, 0xFFFFEF32, 0xFFFF878F },
	{ 6, 0, 0xFFFFEE2E, 0xFFFF87A6 },
	{ 7, 0, 0xFFFFED68, 0xFFFF87D3 },
	{ 8, 0, 0xFFFFECD5, 0xFFFF8819 },
	{ 9, 0, 0xFFFFEC61, 0xFFFF8878 },
	{ 10, 0, 0xFFFFEBD6, 0xFFFF8917 },
	{ 11, 0, 0xFFFFEB27, 0xFFFF89DA },
	{ 12, 0, 0xFFFFEA6B, 0xFFFF8A78 },
	{ 13, 0, 0xFFFFE9AC, 0xFFFF8AD0 },
	{ 14, 0, 0xFFFFE8FD, 0xFFFF8AE6 },
	{ 15, 0, 0xFFFFE87A, 0xFFFF8AD7 },
	{ 16, 0, 0xFFFFE846, 0xFFFF8ACB }
};

NJS_MKEY_A animation_00727208_mkey_25_rot_007258F8[] = {
	{ 0, 0, 0x2A6D, 0xFFFFE10E },
	{ 1, 0, 0x2A61, 0xFFFFE109 },
	{ 2, 0, 0x2A41, 0xFFFFE0FB },
	{ 3, 0, 0x2A13, 0xFFFFE0E8 },
	{ 4, 0, 0x29DC, 0xFFFFE0D1 },
	{ 5, 0, 0x29A2, 0xFFFFE0BA },
	{ 6, 0, 0x2968, 0xFFFFE0A3 },
	{ 7, 0, 0x2931, 0xFFFFE08D },
	{ 8, 0, 0x28FF, 0xFFFFE07A },
	{ 9, 0, 0x28D2, 0xFFFFE069 },
	{ 10, 0, 0x28AB, 0xFFFFE05B },
	{ 11, 0, 0x288A, 0xFFFFE04E },
	{ 12, 0, 0x286F, 0xFFFFE044 },
	{ 13, 0, 0x2859, 0xFFFFE03C },
	{ 14, 0, 0x284A, 0xFFFFE037 },
	{ 16, 0, 0x283D, 0xFFFFE032 }
};

NJS_MKEY_A animation_00727208_mkey_26_rot_007259F8[] = {
	{ 0, 0, 0xD3, 0xFFFFEF92 },
	{ 1, 0, 0x105, 0xFFFFEFC5 },
	{ 2, 0, 0x18E, 0xFFFFF052 },
	{ 3, 0, 0x257, 0xFFFFF11F },
	{ 4, 0, 0x349, 0xFFFFF214 },
	{ 5, 0, 0x44F, 0xFFFFF31C },
	{ 6, 0, 0x555, 0xFFFFF424 },
	{ 7, 0, 0x651, 0xFFFFF521 },
	{ 8, 0, 0x739, 0xFFFFF60A },
	{ 9, 0, 0x809, 0xFFFFF6DD },
	{ 10, 0, 0x8BF, 0xFFFFF795 },
	{ 11, 0, 0x959, 0xFFFFF832 },
	{ 12, 0, 0x9D8, 0xFFFFF8B4 },
	{ 13, 0, 0xA3C, 0xFFFFF91B },
	{ 14, 0, 0xA85, 0xFFFFF966 },
	{ 15, 0, 0xAB2, 0xFFFFF995 },
	{ 16, 0, 0xAC2, 0xFFFFF9A5 }
};

NJS_MKEY_A animation_00727208_mkey_27_rot_00725B08[] = {
	{ 0, 0, 0x1E3, 0xFFFFE2EE },
	{ 1, 0, 0x243, 0xFFFFE310 },
	{ 2, 0, 0x35B, 0xFFFFE377 },
	{ 3, 0, 0x51D, 0xFFFFE436 },
	{ 4, 0, 0x776, 0xFFFFE55B },
	{ 5, 0, 0xA42, 0xFFFFE6F2 },
	{ 6, 0, 0xD4A, 0xFFFFE8F4 },
	{ 7, 0, 0x104E, 0xFFFFEB4C },
	{ 8, 0, 0x1313, 0xFFFFEDD6 },
	{ 9, 0, 0x1574, 0xFFFFF068 },
	{ 10, 0, 0x1763, 0xFFFFF2DB },
	{ 11, 0, 0x18E2, 0xFFFFF511 },
	{ 12, 0, 0x19FF, 0xFFFFF6F5 },
	{ 13, 0, 0x1ACB, 0xFFFFF87A },
	{ 14, 0, 0x1B53, 0xFFFFF999 },
	{ 15, 0, 0x1BA2, 0xFFFFFA4B },
	{ 16, 0, 0x1BBD, 0xFFFFFA89 }
};

NJS_MKEY_A animation_00727208_mkey_30_rot_00725C18[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_00727208_mkey_32_rot_00725D48[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 1, 0, 0x1526, 0 },
	{ 2, 0, 0x1632, 0 },
	{ 3, 0, 0x17D3, 0 },
	{ 4, 0, 0x19EF, 0 },
	{ 5, 0, 0x1C6E, 0 },
	{ 6, 0, 0x1F38, 0 },
	{ 7, 0, 0x2233, 0 },
	{ 8, 0, 0x2547, 0 },
	{ 9, 0, 0x285B, 0 },
	{ 10, 0, 0x2B56, 0 },
	{ 11, 0, 0x2E20, 0 },
	{ 12, 0, 0x309F, 0 },
	{ 13, 0, 0x32BC, 0 },
	{ 14, 0, 0x345C, 0 },
	{ 15, 0, 0x3569, 0 },
	{ 16, 0, 0x35C7, 0 }
};

NJS_MKEY_A animation_00727208_mkey_31_rot_00725C38[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 1, 0x12EF, 0x1A, 0xFFFFE7F7 },
	{ 2, 0x1253, 0x67, 0xFFFFE7F7 },
	{ 3, 0x1161, 0xDD, 0xFFFFE7F7 },
	{ 4, 0x1028, 0x176, 0xFFFFE7F7 },
	{ 5, 0xEB5, 0x22C, 0xFFFFE7F7 },
	{ 6, 0xD17, 0x2F7, 0xFFFFE7F7 },
	{ 7, 0xB5C, 0x3CF, 0xFFFFE7F7 },
	{ 8, 0x993, 0x4AF, 0xFFFFE7F7 },
	{ 9, 0x7C9, 0x58F, 0xFFFFE7F7 },
	{ 10, 0x60F, 0x667, 0xFFFFE7F7 },
	{ 11, 0x470, 0x732, 0xFFFFE7F7 },
	{ 12, 0x2FD, 0x7E8, 0xFFFFE7F7 },
	{ 13, 0x1C4, 0x881, 0xFFFFE7F7 },
	{ 14, 0xD2, 0x8F7, 0xFFFFE7F7 },
	{ 15, 0x37, 0x944, 0xFFFFE7F7 },
	{ 16, 0, 0x95E, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_00727208_mkey_36_rot_00725E58[] = {
	{ 0, 0, 0xFFFFE8F9, 0xFFFFDCAA },
	{ 1, 0, 0xFFFFE8FD, 0xFFFFDC6A },
	{ 2, 0, 0xFFFFE90B, 0xFFFFDBBD },
	{ 3, 0, 0xFFFFE920, 0xFFFFDACC },
	{ 4, 0, 0xFFFFE93C, 0xFFFFD9BA },
	{ 5, 0, 0xFFFFE95B, 0xFFFFD8A6 },
	{ 6, 0, 0xFFFFE97B, 0xFFFFD7A1 },
	{ 7, 0, 0xFFFFE99B, 0xFFFFD6B6 },
	{ 8, 0, 0xFFFFE9B9, 0xFFFFD5E8 },
	{ 9, 0, 0xFFFFE9D4, 0xFFFFD538 },
	{ 10, 0, 0xFFFFE9EB, 0xFFFFD4A5 },
	{ 11, 0, 0xFFFFEA00, 0xFFFFD42B },
	{ 12, 0, 0xFFFFEA10, 0xFFFFD3CA },
	{ 13, 0, 0xFFFFEA1E, 0xFFFFD37E },
	{ 14, 0, 0xFFFFEA27, 0xFFFFD348 },
	{ 15, 0, 0xFFFFEA2D, 0xFFFFD327 },
	{ 16, 0, 0xFFFFEA2F, 0xFFFFD31C }
};

NJS_MKEY_A animation_00727208_mkey_37_rot_00725F68[] = {
	{ 0, 0, 0xFFFFEE74, 0xFFFFEBF0 },
	{ 1, 0, 0xFFFFEEC1, 0xFFFFEC51 },
	{ 2, 0, 0xFFFFEF8D, 0xFFFFED55 },
	{ 3, 0, 0xFFFFF0A7, 0xFFFFEEC0 },
	{ 4, 0, 0xFFFFF1DD, 0xFFFFF05B },
	{ 5, 0, 0xFFFFF30C, 0xFFFFF1F9 },
	{ 6, 0, 0xFFFFF420, 0xFFFFF37F },
	{ 7, 0, 0xFFFFF511, 0xFFFFF4DF },
	{ 8, 0, 0xFFFFF5DD, 0xFFFFF613 },
	{ 9, 0, 0xFFFFF687, 0xFFFFF71B },
	{ 10, 0, 0xFFFFF711, 0xFFFFF7F8 },
	{ 11, 0, 0xFFFFF780, 0xFFFFF8AE },
	{ 12, 0, 0xFFFFF7D8, 0xFFFFF940 },
	{ 13, 0, 0xFFFFF81A, 0xFFFFF9B1 },
	{ 14, 0, 0xFFFFF849, 0xFFFFFA01 },
	{ 15, 0, 0xFFFFF866, 0xFFFFFA33 },
	{ 16, 0, 0xFFFFF870, 0xFFFFFA44 }
};

NJS_MKEY_A animation_00727208_mkey_38_rot_00726078[] = {
	{ 0, 0, 0xFFFFEED4, 0xFFFFECC1 },
	{ 1, 0, 0xFFFFEEF9, 0xFFFFED1C },
	{ 2, 0, 0xFFFFEF63, 0xFFFFEE1B },
	{ 3, 0, 0xFFFFF00F, 0xFFFFEF98 },
	{ 4, 0, 0xFFFFF0EE, 0xFFFFF162 },
	{ 5, 0, 0xFFFFF1EA, 0xFFFFF347 },
	{ 6, 0, 0xFFFFF2EB, 0xFFFFF51E },
	{ 7, 0, 0xFFFFF3DF, 0xFFFFF6CB },
	{ 8, 0, 0xFFFFF4B8, 0xFFFFF840 },
	{ 9, 0, 0xFFFFF573, 0xFFFFF97B },
	{ 10, 0, 0xFFFFF60E, 0xFFFFFA7F },
	{ 11, 0, 0xFFFFF68C, 0xFFFFFB50 },
	{ 12, 0, 0xFFFFF6F0, 0xFFFFFBF5 },
	{ 13, 0, 0xFFFFF73C, 0xFFFFFC72 },
	{ 14, 0, 0xFFFFF771, 0xFFFFFCCB },
	{ 15, 0, 0xFFFFF792, 0xFFFFFD01 },
	{ 16, 0, 0xFFFFF79D, 0xFFFFFD13 }
};

NJS_MKEY_A animation_00727208_mkey_41_rot_00726188[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0xFFFFFF5B, 0, 0 },
	{ 2, 0xFFFFFD89, 0, 0 },
	{ 3, 0xFFFFFAB3, 0, 0 },
	{ 4, 0xFFFFF707, 0, 0 },
	{ 5, 0xFFFFF2AE, 0, 0 },
	{ 6, 0xFFFFEDD3, 0, 0 },
	{ 7, 0xFFFFE8A3, 0, 0 },
	{ 8, 0xFFFFE347, 0, 0 },
	{ 9, 0xFFFFDDEC, 0, 0 },
	{ 10, 0xFFFFD8BB, 0, 0 },
	{ 11, 0xFFFFD3E1, 0, 0 },
	{ 12, 0xFFFFCF88, 0, 0 },
	{ 13, 0xFFFFCBDB, 0, 0 },
	{ 14, 0xFFFFC906, 0, 0 },
	{ 15, 0xFFFFC733, 0, 0 },
	{ 16, 0xFFFFC68E, 0, 0 }
};

NJS_MKEY_A animation_00727208_mkey_43_rot_007263A8[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_00727208_mkey_42_rot_00726298[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 1, 0, 0xFFFFE3B8, 0 },
	{ 2, 0, 0xFFFFE33E, 0 },
	{ 3, 0, 0xFFFFE27F, 0 },
	{ 4, 0, 0xFFFFE189, 0 },
	{ 5, 0, 0xFFFFE065, 0 },
	{ 6, 0, 0xFFFFDF1F, 0 },
	{ 7, 0, 0xFFFFDDC2, 0 },
	{ 8, 0, 0xFFFFDC5A, 0 },
	{ 9, 0, 0xFFFFDAF2, 0 },
	{ 10, 0, 0xFFFFD996, 0 },
	{ 11, 0, 0xFFFFD850, 0 },
	{ 12, 0, 0xFFFFD72B, 0 },
	{ 13, 0, 0xFFFFD635, 0 },
	{ 14, 0, 0xFFFFD576, 0 },
	{ 15, 0, 0xFFFFD4FC, 0 },
	{ 16, 0, 0xFFFFD4D0, 0 }
};

NJS_MKEY_A animation_00727208_mkey_46_rot_007263C8[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_00727208_mkey_47_rot_007263E8[] = {
	{ 0, 0xFFFFFEB9, 0x20B, 0xFFFFB83E },
	{ 1, 0xFFFFFEA8, 0x21A, 0xFFFFB7D7 },
	{ 2, 0xFFFFFE74, 0x243, 0xFFFFB6C0 },
	{ 3, 0xFFFFFE1D, 0x287, 0xFFFFB534 },
	{ 4, 0xFFFFFD9B, 0x2E4, 0xFFFFB364 },
	{ 5, 0xFFFFFCE8, 0x359, 0xFFFFB17E },
	{ 6, 0xFFFFFC03, 0x3E7, 0xFFFFAFC4 },
	{ 7, 0xFFFFFAE3, 0x487, 0xFFFFAE14 },
	{ 8, 0xFFFFF98E, 0x538, 0xFFFFAC9F },
	{ 9, 0xFFFFF80A, 0x5F1, 0xFFFFAB57 },
	{ 10, 0xFFFFF669, 0x6AD, 0xFFFFAA4B },
	{ 11, 0xFFFFF4C2, 0x767, 0xFFFFA979 },
	{ 12, 0xFFFFF32F, 0x815, 0xFFFFA8DC },
	{ 13, 0xFFFFF1CC, 0x8B0, 0xFFFFA86E },
	{ 14, 0xFFFFF0B4, 0x92C, 0xFFFFA826 },
	{ 15, 0xFFFFEFFD, 0x97E, 0xFFFFA7FD },
	{ 16, 0xFFFFEFBC, 0x99C, 0xFFFFA7F0 }
};

NJS_MKEY_A animation_00727208_mkey_48_rot_007264F8[] = {
	{ 0, 0, 0, 0x1725 },
	{ 1, 0, 0, 0x178E },
	{ 2, 0, 0, 0x18A9 },
	{ 3, 0, 0, 0x1A37 },
	{ 4, 0, 0, 0x1C18 },
	{ 5, 0, 0, 0x1E18 },
	{ 6, 0, 0, 0x1FA2 },
	{ 7, 0, 0, 0x2164 },
	{ 8, 0, 0, 0x22F2 },
	{ 9, 0, 0, 0x2450 },
	{ 10, 0, 0, 0x256D },
	{ 11, 0, 0, 0x2648 },
	{ 12, 0, 0, 0x26E6 },
	{ 13, 0, 0, 0x274E },
	{ 14, 0, 0, 0x278D },
	{ 15, 0, 0, 0x27AD },
	{ 16, 0, 0, 0x27B7 }
};

NJS_MKEY_A animation_00727208_mkey_49_rot_00726608[] = {
	{ 0, 0, 0, 0x1541 },
	{ 1, 0, 0, 0x15BC },
	{ 2, 0, 0, 0x1708 },
	{ 3, 0, 0, 0x18F2 },
	{ 4, 0, 0, 0x1B29 },
	{ 5, 0, 0, 0x1D83 },
	{ 6, 0, 0, 0x2048 },
	{ 7, 0, 0, 0x229A },
	{ 8, 0, 0, 0x249F },
	{ 9, 0, 0, 0x2668 },
	{ 10, 0, 0, 0x27DE },
	{ 11, 0, 0, 0x28FF },
	{ 12, 0, 0, 0x29D0 },
	{ 13, 0, 0, 0x2A5A },
	{ 14, 0, 0, 0x2AAD },
	{ 15, 0, 0, 0x2AD8 },
	{ 16, 0, 0, 0x2AE5 }
};

NJS_MKEY_A animation_00727208_mkey_52_rot_00726718[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFD539 },
	{ 1, 0x1C1C, 0xFFFFF77E, 0xFFFFD45E },
	{ 2, 0x1C1C, 0xFFFFF79A, 0xFFFFD242 },
	{ 3, 0x1C1C, 0xFFFFF7BD, 0xFFFFCF96 },
	{ 4, 0x1C1C, 0xFFFFF7DE, 0xFFFFCD0A },
	{ 5, 0x1C1C, 0xFFFFF800, 0xFFFFCA96 },
	{ 6, 0x1C1C, 0xFFFFF81C, 0xFFFFC7B9 },
	{ 7, 0x1C1C, 0xFFFFF813, 0xFFFFC3D5 },
	{ 8, 0x1C1C, 0xFFFFF705, 0xFFFFC278 },
	{ 9, 0x1C1C, 0xFFFFF717, 0xFFFFC194 },
	{ 10, 0x1C1C, 0xFFFFF984, 0xFFFFC059 },
	{ 11, 0x1C1C, 0xFFFFFCAD, 0xFFFFBEF0 },
	{ 12, 0x1C1C, 0x2A, 0xFFFFBD7D },
	{ 13, 0x1C1C, 0x396, 0xFFFFBC21 },
	{ 14, 0x1C1C, 0x687, 0xFFFFBAFE },
	{ 15, 0x1C1C, 0x897, 0xFFFFBA37 },
	{ 16, 0x1C1C, 0x95E, 0xFFFFB9ED }
};

NJS_MKEY_A animation_00727208_mkey_57_rot_00726828[] = {
	{ 0, 0x654, 0xFFFFF8A3, 0xFFFF8526 },
	{ 1, 0x64F, 0xFFFFF8BD, 0xFFFF84CE },
	{ 2, 0x63C, 0xFFFFF906, 0xFFFF83D7 },
	{ 3, 0x617, 0xFFFFF97A, 0xFFFF8263 },
	{ 4, 0x5D4, 0xFFFFFA13, 0xFFFF8097 },
	{ 5, 0x56C, 0xFFFFFAC9, 0xFFFF7EA0 },
	{ 6, 0x4DB, 0xFFFFFB99, 0xFFFF7C84 },
	{ 7, 0x41C, 0xFFFFFC7B, 0xFFFF7A6A },
	{ 8, 0x332, 0xFFFFFD67, 0xFFFF7867 },
	{ 9, 0x224, 0xFFFFFE56, 0xFFFF76A9 },
	{ 10, 0x100, 0xFFFFFF41, 0xFFFF7507 },
	{ 11, 0xFFFFFFD5, 0x1F, 0xFFFF73A3 },
	{ 12, 0xFFFFFEB5, 0xE8, 0xFFFF7280 },
	{ 13, 0xFFFFFDB4, 0x194, 0xFFFF71A0 },
	{ 14, 0xFFFFFCE7, 0x21A, 0xFFFF7100 },
	{ 15, 0xFFFFFC60, 0x270, 0xFFFF709F },
	{ 16, 0xFFFFFC30, 0x28E, 0xFFFF707E }
};

NJS_MKEY_A animation_00727208_mkey_58_rot_00726938[] = {
	{ 0, 0, 0, 0x1912 },
	{ 1, 0, 0, 0x1944 },
	{ 2, 0, 0, 0x19CC },
	{ 3, 0, 0, 0x1A97 },
	{ 4, 0, 0, 0x1B8B },
	{ 5, 0, 0, 0x1C92 },
	{ 6, 0, 0, 0x1DA9 },
	{ 7, 0, 0, 0x1EB9 },
	{ 8, 0, 0, 0x1FB5 },
	{ 9, 0, 0, 0x204A },
	{ 10, 0, 0, 0x2105 },
	{ 11, 0, 0, 0x219E },
	{ 12, 0, 0, 0x2214 },
	{ 13, 0, 0, 0x2269 },
	{ 14, 0, 0, 0x22A3 },
	{ 15, 0, 0, 0x22C5 },
	{ 16, 0, 0, 0x22D0 }
};

NJS_MKEY_A animation_00727208_mkey_59_rot_00726A48[] = {
	{ 0, 0, 0, 0x21C7 },
	{ 1, 0, 0, 0x220D },
	{ 2, 0, 0, 0x22CC },
	{ 3, 0, 0, 0x23EA },
	{ 4, 0, 0, 0x254B },
	{ 5, 0, 0, 0x26BF },
	{ 6, 0, 0, 0x284C },
	{ 7, 0, 0, 0x29CE },
	{ 8, 0, 0, 0x2B36 },
	{ 9, 0, 0, 0x2CBD },
	{ 10, 0, 0, 0x2DD4 },
	{ 11, 0, 0, 0x2EB8 },
	{ 12, 0, 0, 0x2F69 },
	{ 13, 0, 0, 0x2FED },
	{ 14, 0, 0, 0x3045 },
	{ 15, 0, 0, 0x3077 },
	{ 16, 0, 0, 0x3088 }
};

NJS_MKEY_A animation_00727208_mkey_62_rot_00726B58[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF843 },
	{ 1, 0x10BE, 0x40A, 0xFFFFF817 },
	{ 2, 0x10D4, 0x43D, 0xFFFFF79C },
	{ 3, 0x10EA, 0x4AC, 0xFFFFF6E3 },
	{ 4, 0x10F4, 0x56C, 0xFFFFF5F8 },
	{ 5, 0x1100, 0x6F1, 0xFFFFF48D },
	{ 6, 0x10FF, 0x8FB, 0xFFFFF2C3 },
	{ 7, 0x10B4, 0xA94, 0xFFFFF14E },
	{ 8, 0xFBE, 0xADB, 0xFFFFF0C2 },
	{ 9, 0xE66, 0xABB, 0xFFFFF0B2 },
	{ 10, 0xCF7, 0xB0C, 0xFFFFF09F },
	{ 11, 0xB4D, 0xB71, 0xFFFFF092 },
	{ 12, 0x993, 0xBDD, 0xFFFFF08A },
	{ 13, 0x7F2, 0xC46, 0xFFFFF086 },
	{ 14, 0x695, 0xC9F, 0xFFFFF085 },
	{ 15, 0x5A5, 0xCDD, 0xFFFFF085 },
	{ 16, 0x54B, 0xCF4, 0xFFFFF085 }
};

NJS_MKEY_A animation_00727208_mkey_67_rot_00726C68[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0x17, 0xFFFFE59A },
	{ 2, 0, 0x56, 0xFFFFE7AC },
	{ 3, 0, 0xB0, 0xFFFFEAA8 },
	{ 4, 0, 0x116, 0xFFFFEE17 },
	{ 5, 0, 0x176, 0xFFFFF163 },
	{ 6, 0, 0x1BD, 0xFFFFF3DC },
	{ 7, 0, 0x1D8, 0xFFFFF4D4 },
	{ 8, 0, 0x1C7, 0xFFFFF43B },
	{ 9, 0, 0x19A, 0xFFFFF2A1 },
	{ 10, 0, 0x158, 0xFFFFF058 },
	{ 11, 0, 0x10A, 0xFFFFEDB4 },
	{ 12, 0, 0xBB, 0xFFFFEB06 },
	{ 13, 0, 0x71, 0xFFFFE896 },
	{ 14, 0, 0x36, 0xFFFFE69E },
	{ 15, 0, 0xE, 0xFFFFE54E },
	{ 16, 0, 0, 0xFFFFE4D4 }
};

NJS_MDATA2 animation_00727208_mdat_00726D78[] = {
	{ animation_00727208_mkey_0_pos_007253A8, NULL, LengthOfArray<Uint32>(animation_00727208_mkey_0_pos_007253A8), 0 },
	{ NULL, animation_00727208_mkey_1_rot_007254B8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_1_rot_007254B8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_12_rot_007255C8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_12_rot_007255C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_15_rot_007256D8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_15_rot_007256D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_19_rot_007257E8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_19_rot_007257E8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_25_rot_007258F8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_25_rot_007258F8) },
	{ NULL, animation_00727208_mkey_26_rot_007259F8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_26_rot_007259F8) },
	{ NULL, animation_00727208_mkey_27_rot_00725B08, 0, LengthOfArray<Uint32>(animation_00727208_mkey_27_rot_00725B08) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_30_rot_00725C18, 0, LengthOfArray<Uint32>(animation_00727208_mkey_30_rot_00725C18) },
	{ NULL, animation_00727208_mkey_32_rot_00725D48, 0, LengthOfArray<Uint32>(animation_00727208_mkey_32_rot_00725D48) },
	{ NULL, animation_00727208_mkey_31_rot_00725C38, 0, LengthOfArray<Uint32>(animation_00727208_mkey_31_rot_00725C38) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_36_rot_00725E58, 0, LengthOfArray<Uint32>(animation_00727208_mkey_36_rot_00725E58) },
	{ NULL, animation_00727208_mkey_37_rot_00725F68, 0, LengthOfArray<Uint32>(animation_00727208_mkey_37_rot_00725F68) },
	{ NULL, animation_00727208_mkey_38_rot_00726078, 0, LengthOfArray<Uint32>(animation_00727208_mkey_38_rot_00726078) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_41_rot_00726188, 0, LengthOfArray<Uint32>(animation_00727208_mkey_41_rot_00726188) },
	{ NULL, animation_00727208_mkey_43_rot_007263A8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_43_rot_007263A8) },
	{ NULL, animation_00727208_mkey_42_rot_00726298, 0, LengthOfArray<Uint32>(animation_00727208_mkey_42_rot_00726298) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_46_rot_007263C8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_46_rot_007263C8) },
	{ NULL, animation_00727208_mkey_47_rot_007263E8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_47_rot_007263E8) },
	{ NULL, animation_00727208_mkey_48_rot_007264F8, 0, LengthOfArray<Uint32>(animation_00727208_mkey_48_rot_007264F8) },
	{ NULL, animation_00727208_mkey_49_rot_00726608, 0, LengthOfArray<Uint32>(animation_00727208_mkey_49_rot_00726608) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_52_rot_00726718, 0, LengthOfArray<Uint32>(animation_00727208_mkey_52_rot_00726718) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_57_rot_00726828, 0, LengthOfArray<Uint32>(animation_00727208_mkey_57_rot_00726828) },
	{ NULL, animation_00727208_mkey_58_rot_00726938, 0, LengthOfArray<Uint32>(animation_00727208_mkey_58_rot_00726938) },
	{ NULL, animation_00727208_mkey_59_rot_00726A48, 0, LengthOfArray<Uint32>(animation_00727208_mkey_59_rot_00726A48) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_62_rot_00726B58, 0, LengthOfArray<Uint32>(animation_00727208_mkey_62_rot_00726B58) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00727208_mkey_67_rot_00726C68, 0, LengthOfArray<Uint32>(animation_00727208_mkey_67_rot_00726C68) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbleft0 = { animation_00727208_mdat_00726D78, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbleft0 = { AMY_OBJECTS[0], &motion_a_sbleft0 };
