/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_007103C0_mkey_0_pos_0070E820[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 1, 0.0198f, -0.7567f, 0 },
	{ 2, 0.0708f, -0.8116f, 0 },
	{ 3, 0.1406f, -0.8868f, 0 },
	{ 4, 0.2166f, -0.9686f, 0 },
	{ 5, 0.2864f, -1.0438f, 0 },
	{ 6, 0.3374f, -1.0987f, 0 },
	{ 7, 0.3572f, -1.12f, 0 },
	{ 8, 0.3449f, -1.1069f, 0 },
	{ 9, 0.3121f, -1.0715f, 0 },
	{ 10, 0.2646f, -1.0203f, 0 },
	{ 11, 0.2082f, -0.9596f, 0 },
	{ 12, 0.1489f, -0.8958f, 0 },
	{ 13, 0.0926f, -0.8351f, 0 },
	{ 14, 0.0451f, -0.7839f, 0 },
	{ 15, 0.0122f, -0.7486f, 0 },
	{ 16, 0, -0.7354f, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_1_rot_0070E930[] = {
	{ 0, 0, 0xFFFFEAAB, 0xFFFFFEC8 },
	{ 16, 0, 0xFFFFEAAB, 0xFFFFFEC8 }
};

NJS_MKEY_A animation_007103C0_mkey_12_rot_0070E950[] = {
	{ 0, 0, 0xFFFFECE5, 0x9583 },
	{ 1, 0, 0xFFFFECCE, 0x9520 },
	{ 2, 0, 0xFFFFEC94, 0x941B },
	{ 3, 0, 0xFFFFEC46, 0x92AC },
	{ 4, 0, 0xFFFFEBF6, 0x910E },
	{ 5, 0, 0xFFFFEBB1, 0x8F85 },
	{ 6, 0, 0xFFFFEB81, 0x8E5F },
	{ 7, 0, 0xFFFFEB6F, 0x8DEB },
	{ 8, 0, 0xFFFFEB7A, 0x8E33 },
	{ 9, 0, 0xFFFFEB98, 0x8EF1 },
	{ 10, 0, 0xFFFFEBC6, 0x9001 },
	{ 11, 0, 0xFFFFEBFE, 0x913C },
	{ 12, 0, 0xFFFFEC3D, 0x927F },
	{ 13, 0, 0xFFFFEC7B, 0x93AA },
	{ 14, 0, 0xFFFFECB1, 0x949F },
	{ 15, 0, 0xFFFFECD7, 0x9546 },
	{ 16, 0, 0xFFFFECE5, 0x9583 }
};

NJS_MKEY_A animation_007103C0_mkey_15_rot_0070EA60[] = {
	{ 0, 0, 0xB36, 0xFFFF8EAB },
	{ 1, 0, 0xB43, 0xFFFF8E9D },
	{ 2, 0, 0xB68, 0xFFFF8E73 },
	{ 3, 0, 0xB9A, 0xFFFF8E2F },
	{ 4, 0, 0xBD3, 0xFFFF8DD6 },
	{ 5, 0, 0xC08, 0xFFFF8D75 },
	{ 6, 0, 0xC2F, 0xFFFF8D26 },
	{ 7, 0, 0xC3F, 0xFFFF8D06 },
	{ 8, 0, 0xC35, 0xFFFF8D1A },
	{ 9, 0, 0xC1C, 0xFFFF8D4E },
	{ 10, 0, 0xBF7, 0xFFFF8D95 },
	{ 11, 0, 0xBCC, 0xFFFF8DE0 },
	{ 12, 0, 0xBA0, 0xFFFF8E26 },
	{ 13, 0, 0xB77, 0xFFFF8E60 },
	{ 14, 0, 0xB55, 0xFFFF8E89 },
	{ 15, 0, 0xB3E, 0xFFFF8EA2 },
	{ 16, 0, 0xB36, 0xFFFF8EAB }
};

NJS_MKEY_A animation_007103C0_mkey_19_rot_0070EB70[] = {
	{ 0, 0, 0xFFFFF442, 0xFFFF8F0C },
	{ 1, 0, 0xFFFFF430, 0xFFFF8EF5 },
	{ 2, 0, 0xFFFFF403, 0xFFFF8EB5 },
	{ 3, 0, 0xFFFFF3CC, 0xFFFF8E50 },
	{ 4, 0, 0xFFFFF39B, 0xFFFF8DD3 },
	{ 5, 0, 0xFFFFF377, 0xFFFF8D51 },
	{ 6, 0, 0xFFFFF365, 0xFFFF8CEB },
	{ 7, 0, 0xFFFFF360, 0xFFFF8CC1 },
	{ 8, 0, 0xFFFFF363, 0xFFFF8CDB },
	{ 9, 0, 0xFFFFF36D, 0xFFFF8D1E },
	{ 10, 0, 0xFFFFF381, 0xFFFF8D7B },
	{ 11, 0, 0xFFFFF3A0, 0xFFFF8DE1 },
	{ 12, 0, 0xFFFFF3C6, 0xFFFF8E43 },
	{ 13, 0, 0xFFFFF3F1, 0xFFFF8E97 },
	{ 14, 0, 0xFFFFF419, 0xFFFF8ED6 },
	{ 15, 0, 0xFFFFF437, 0xFFFF8EFE },
	{ 16, 0, 0xFFFFF442, 0xFFFF8F0C }
};

NJS_MKEY_A animation_007103C0_mkey_25_rot_0070EC80[] = {
	{ 0, 0, 0x32E6, 0xFFFFF2CA },
	{ 1, 0, 0x32C7, 0xFFFFF1B1 },
	{ 2, 0, 0x326B, 0xFFFFEEF8 },
	{ 3, 0, 0x31D9, 0xFFFFEB83 },
	{ 4, 0, 0x3124, 0xFFFFE819 },
	{ 5, 0, 0x306C, 0xFFFFE548 },
	{ 6, 0, 0x2FDE, 0xFFFFE367 },
	{ 7, 0, 0x2FA5, 0xFFFFE2B6 },
	{ 8, 0, 0x2FC9, 0xFFFFE323 },
	{ 9, 0, 0x3025, 0xFFFFE450 },
	{ 10, 0, 0x30A7, 0xFFFFE621 },
	{ 11, 0, 0x3139, 0xFFFFE874 },
	{ 12, 0, 0x31C6, 0xFFFFEB1E },
	{ 13, 0, 0x3240, 0xFFFFEDDB },
	{ 14, 0, 0x329B, 0xFFFFF053 },
	{ 15, 0, 0x32D3, 0xFFFFF21C },
	{ 16, 0, 0x32E6, 0xFFFFF2CA }
};

NJS_MKEY_A animation_007103C0_mkey_26_rot_0070ED90[] = {
	{ 0, 0, 0xAC7, 0xFFFFFEF7 },
	{ 1, 0, 0xAAC, 0xFFFFFE82 },
	{ 2, 0, 0xA53, 0xFFFFFD64 },
	{ 3, 0, 0x9B5, 0xFFFFFC04 },
	{ 4, 0, 0x8E6, 0xFFFFFABB },
	{ 5, 0, 0x814, 0xFFFFF9BE },
	{ 6, 0, 0x775, 0xFFFFF921 },
	{ 7, 0, 0x737, 0xFFFFF8EB },
	{ 8, 0, 0x75E, 0xFFFFF90C },
	{ 9, 0, 0x7C5, 0xFFFFF96C },
	{ 10, 0, 0x857, 0xFFFFFA08 },
	{ 11, 0, 0x8FE, 0xFFFFFADC },
	{ 12, 0, 0x99F, 0xFFFFFBDD },
	{ 13, 0, 0xA25, 0xFFFFFCF1 },
	{ 14, 0, 0xA83, 0xFFFFFDF1 },
	{ 15, 0, 0xAB7, 0xFFFFFEAE },
	{ 16, 0, 0xAC7, 0xFFFFFEF7 }
};

NJS_MKEY_A animation_007103C0_mkey_27_rot_0070EEA0[] = {
	{ 0, 0, 0x153E, 0xFFFFFEF7 },
	{ 1, 0, 0x151D, 0xFFFFFDF7 },
	{ 2, 0, 0x1494, 0xFFFFFB84 },
	{ 3, 0, 0x1373, 0xFFFFF88C },
	{ 4, 0, 0x11D8, 0xFFFFF5E0 },
	{ 5, 0, 0x1029, 0xFFFFF3F1 },
	{ 6, 0, 0xEDF, 0xFFFFF2D1 },
	{ 7, 0, 0xE5D, 0xFFFFF271 },
	{ 8, 0, 0xEAD, 0xFFFFF2AB },
	{ 9, 0, 0xF84, 0xFFFFF358 },
	{ 10, 0, 0x10B3, 0xFFFFF47E },
	{ 11, 0, 0x1209, 0xFFFFF624 },
	{ 12, 0, 0x134A, 0xFFFFF839 },
	{ 13, 0, 0x1445, 0xFFFFFA8A },
	{ 14, 0, 0x14E2, 0xFFFFFCBA },
	{ 15, 0, 0x152B, 0xFFFFFE58 },
	{ 16, 0, 0x153E, 0xFFFFFEF7 }
};

NJS_MKEY_A animation_007103C0_mkey_30_rot_0070EFB0[] = {
	{ 0, 0x3426, 0x18DA, 0 },
	{ 1, 0x3483, 0x18DA, 0xFFFFFEF7 },
	{ 2, 0x3571, 0x18DA, 0xFFFFFC49 },
	{ 3, 0x36B7, 0x18DA, 0xFFFFF8A0 },
	{ 4, 0x381A, 0x18DA, 0xFFFFF4A3 },
	{ 5, 0x3960, 0x18DA, 0xFFFFF0FA },
	{ 6, 0x3A4F, 0x18DA, 0xFFFFEE4C },
	{ 7, 0x3AAB, 0x18DA, 0xFFFFED43 },
	{ 8, 0x3A72, 0x18DA, 0xFFFFEDE7 },
	{ 9, 0x39D8, 0x18DA, 0xFFFFEFA0 },
	{ 10, 0x38FA, 0x18DA, 0xFFFFF21F },
	{ 11, 0x37F3, 0x18DA, 0xFFFFF513 },
	{ 12, 0x36DE, 0x18DA, 0xFFFFF830 },
	{ 13, 0x35D7, 0x18DA, 0xFFFFFB25 },
	{ 14, 0x34F9, 0x18DA, 0xFFFFFDA3 },
	{ 15, 0x345F, 0x18DA, 0xFFFFFF5C },
	{ 16, 0x3426, 0x18DA, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_32_rot_0070F0E0[] = {
	{ 0, 0, 0x2C00, 0 },
	{ 16, 0, 0x2C00, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_31_rot_0070F0C0[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_007103C0_mkey_36_rot_0070F100[] = {
	{ 0, 0, 0xFFFFE73C, 0xFFFFF8F7 },
	{ 1, 0, 0xFFFFE750, 0xFFFFF83D },
	{ 2, 0, 0xFFFFE78B, 0xFFFFF665 },
	{ 3, 0, 0xFFFFE7E9, 0xFFFFF3F3 },
	{ 4, 0, 0xFFFFE860, 0xFFFFF163 },
	{ 5, 0, 0xFFFFE8D9, 0xFFFFEF25 },
	{ 6, 0, 0xFFFFE937, 0xFFFFED94 },
	{ 7, 0, 0xFFFFE95D, 0xFFFFECFC },
	{ 8, 0, 0xFFFFE946, 0xFFFFED59 },
	{ 9, 0, 0xFFFFE908, 0xFFFFEE59 },
	{ 10, 0, 0xFFFFE8B2, 0xFFFFEFD6 },
	{ 11, 0, 0xFFFFE852, 0xFFFFF1AA },
	{ 12, 0, 0xFFFFE7F5, 0xFFFFF3A9 },
	{ 13, 0, 0xFFFFE7A7, 0xFFFFF59F },
	{ 14, 0, 0xFFFFE76C, 0xFFFFF752 },
	{ 15, 0, 0xFFFFE748, 0xFFFFF884 },
	{ 16, 0, 0xFFFFE73C, 0xFFFFF8F7 }
};

NJS_MKEY_A animation_007103C0_mkey_37_rot_0070F210[] = {
	{ 0, 0, 0xFFFFE6C5, 0x556 },
	{ 1, 0, 0xFFFFE6BE, 0x4BE },
	{ 2, 0, 0xFFFFE6C3, 0x335 },
	{ 3, 0, 0xFFFFE6FF, 0x129 },
	{ 4, 0, 0xFFFFE77F, 0xFFFFFF11 },
	{ 5, 0, 0xFFFFE825, 0xFFFFFD50 },
	{ 6, 0, 0xFFFFE8B7, 0xFFFFFC27 },
	{ 7, 0, 0xFFFFE8F4, 0xFFFFFBBC },
	{ 8, 0, 0xFFFFE8CE, 0xFFFFFBFE },
	{ 9, 0, 0xFFFFE86C, 0xFFFFFCB7 },
	{ 10, 0, 0xFFFFE7ED, 0xFFFFFDD7 },
	{ 11, 0, 0xFFFFE76E, 0xFFFFFF4A },
	{ 12, 0, 0xFFFFE70A, 0xEC },
	{ 13, 0, 0xFFFFE6CF, 0x28F },
	{ 14, 0, 0xFFFFE6BC, 0x3FA },
	{ 15, 0, 0xFFFFE6C0, 0x4F8 },
	{ 16, 0, 0xFFFFE6C5, 0x556 }
};

NJS_MKEY_A animation_007103C0_mkey_38_rot_0070F320[] = {
	{ 0, 0, 0xFFFFE87C, 0x83E },
	{ 1, 0, 0xFFFFE82F, 0x789 },
	{ 2, 0, 0xFFFFE789, 0x5A1 },
	{ 3, 0, 0xFFFFE6FB, 0x2E2 },
	{ 4, 0, 0xFFFFE6D7, 0xFFFFFFE2 },
	{ 5, 0, 0xFFFFE71D, 0xFFFFFD43 },
	{ 6, 0, 0xFFFFE787, 0xFFFFFB80 },
	{ 7, 0, 0xFFFFE7BB, 0xFFFFFADC },
	{ 8, 0, 0xFFFFE79A, 0xFFFFFB41 },
	{ 9, 0, 0xFFFFE74D, 0xFFFFFC5B },
	{ 10, 0, 0xFFFFE6FD, 0xFFFFFE0F },
	{ 11, 0, 0xFFFFE6D5, 0x34 },
	{ 12, 0, 0xFFFFE6F1, 0x28D },
	{ 13, 0, 0xFFFFE751, 0x4C8 },
	{ 14, 0, 0xFFFFE7D6, 0x69B },
	{ 15, 0, 0xFFFFE84B, 0x7CF },
	{ 16, 0, 0xFFFFE87C, 0x83E }
};

NJS_MKEY_A animation_007103C0_mkey_41_rot_0070F430[] = {
	{ 0, 0xFFFFD4D0, 0, 0 },
	{ 1, 0xFFFFD36A, 0xFFFFFF93, 0xFFFFFF76 },
	{ 2, 0xFFFFCFCE, 0xFFFFFE78, 0xFFFFFE10 },
	{ 3, 0xFFFFCADF, 0xFFFFFCF5, 0xFFFFFC27 },
	{ 4, 0xFFFFC57F, 0xFFFFFB4F, 0xFFFFFA12 },
	{ 5, 0xFFFFC090, 0xFFFFF9CC, 0xFFFFF82A },
	{ 6, 0xFFFFBCF4, 0xFFFFF8B1, 0xFFFFF6C4 },
	{ 7, 0xFFFFBB8E, 0xFFFFF843, 0xFFFFF639 },
	{ 8, 0xFFFFBC6B, 0xFFFFF887, 0xFFFFF68F },
	{ 9, 0xFFFFBEBE, 0xFFFFF93D, 0xFFFFF775 },
	{ 10, 0xFFFFC21A, 0xFFFFFA45, 0xFFFFF8C2 },
	{ 11, 0xFFFFC616, 0xFFFFFB7D, 0xFFFFFA4D },
	{ 12, 0xFFFFCA48, 0xFFFFFCC6, 0xFFFFFBED },
	{ 13, 0xFFFFCE44, 0xFFFFFDFF, 0xFFFFFD78 },
	{ 14, 0xFFFFD1A0, 0xFFFFFF06, 0xFFFFFEC5 },
	{ 15, 0xFFFFD3F3, 0xFFFFFFBD, 0xFFFFFFAB },
	{ 16, 0xFFFFD4D0, 0, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_43_rot_0070F560[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_42_rot_0070F540[] = {
	{ 0, 0, 0xFFFFCD7B, 0 },
	{ 16, 0, 0xFFFFCD7B, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_46_rot_0070F580[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_007103C0_mkey_47_rot_0070F5A0[] = {
	{ 0, 0xFFFFFDD6, 0x97A, 0xFFFFCBC0 },
	{ 1, 0xFFFFFD48, 0x93B, 0xFFFFC93E },
	{ 2, 0xFFFFFC56, 0x89E, 0xFFFFC499 },
	{ 3, 0xFFFFFB92, 0x7D1, 0xFFFFC019 },
	{ 4, 0xFFFFFB0F, 0x6F4, 0xFFFFBC1D },
	{ 5, 0xFFFFFACF, 0x62E, 0xFFFFB903 },
	{ 6, 0xFFFFFABB, 0x5A0, 0xFFFFB6F7 },
	{ 7, 0xFFFFFAB9, 0x569, 0xFFFFB636 },
	{ 8, 0xFFFFFABA, 0x58B, 0xFFFFB6AD },
	{ 9, 0xFFFFFAC2, 0x5E6, 0xFFFFB7F5 },
	{ 10, 0xFFFFFADE, 0x66B, 0xFFFFB9F1 },
	{ 11, 0xFFFFFB1A, 0x70C, 0xFFFFBC84 },
	{ 12, 0xFFFFFB7F, 0x7B8, 0xFFFFBF9E },
	{ 13, 0xFFFFFC0F, 0x85E, 0xFFFFC316 },
	{ 14, 0xFFFFFCC2, 0x8ED, 0xFFFFC6BF },
	{ 15, 0xFFFFFD79, 0x953, 0xFFFFCA20 },
	{ 16, 0xFFFFFDD6, 0x97A, 0xFFFFCBC0 }
};

NJS_MKEY_A animation_007103C0_mkey_48_rot_0070F6B0[] = {
	{ 0, 0, 0, 0xA59 },
	{ 1, 0, 0, 0xCC7 },
	{ 2, 0, 0, 0x1122 },
	{ 3, 0, 0, 0x154F },
	{ 4, 0, 0, 0x1929 },
	{ 5, 0, 0, 0x1C2F },
	{ 6, 0, 0, 0x1E3C },
	{ 7, 0, 0, 0x1EFF },
	{ 8, 0, 0, 0x1E87 },
	{ 9, 0, 0, 0x1D3C },
	{ 10, 0, 0, 0x1B44 },
	{ 11, 0, 0, 0x18C4 },
	{ 12, 0, 0, 0x15C5 },
	{ 13, 0, 0, 0x1296 },
	{ 14, 0, 0, 0xF18 },
	{ 15, 0, 0, 0xBEC },
	{ 16, 0, 0, 0xA59 }
};

NJS_MKEY_A animation_007103C0_mkey_49_rot_0070F7C0[] = {
	{ 0, 0, 0, 0x67B },
	{ 1, 0, 0, 0x8F9 },
	{ 2, 0, 0, 0xDF5 },
	{ 3, 0, 0, 0x1319 },
	{ 4, 0, 0, 0x179E },
	{ 5, 0, 0, 0x1B44 },
	{ 6, 0, 0, 0x1DAD },
	{ 7, 0, 0, 0x1E92 },
	{ 8, 0, 0, 0x1E05 },
	{ 9, 0, 0, 0x1C80 },
	{ 10, 0, 0, 0x1A2E },
	{ 11, 0, 0, 0x1728 },
	{ 12, 0, 0, 0x13A3 },
	{ 13, 0, 0, 0xF93 },
	{ 14, 0, 0, 0xBAB },
	{ 15, 0, 0, 0x818 },
	{ 16, 0, 0, 0x67B }
};

NJS_MKEY_A animation_007103C0_mkey_52_rot_0070F8D0[] = {
	{ 0, 0x1C1C, 0xFFFFF35F, 0xFFFFDE2F },
	{ 1, 0x1CB8, 0xFFFFF3B6, 0xFFFFDD20 },
	{ 2, 0x1E4B, 0xFFFFF495, 0xFFFFDA64 },
	{ 3, 0x2071, 0xFFFFF5C7, 0xFFFFD6A6 },
	{ 4, 0x22C8, 0xFFFFF714, 0xFFFFD293 },
	{ 5, 0x24EE, 0xFFFFF845, 0xFFFFCED5 },
	{ 6, 0x2681, 0xFFFFF925, 0xFFFFCC19 },
	{ 7, 0x271D, 0xFFFFF97C, 0xFFFFCB09 },
	{ 8, 0x26BC, 0xFFFFF946, 0xFFFFCBB1 },
	{ 9, 0x25B9, 0xFFFFF8B6, 0xFFFFCD74 },
	{ 10, 0x2442, 0xFFFFF7E6, 0xFFFFD000 },
	{ 11, 0x2286, 0xFFFFF6EF, 0xFFFFD305 },
	{ 12, 0x20B3, 0xFFFFF5EC, 0xFFFFD633 },
	{ 13, 0x1EF6, 0xFFFFF4F5, 0xFFFFD938 },
	{ 14, 0x1D80, 0xFFFFF425, 0xFFFFDBC5 },
	{ 15, 0x1C7D, 0xFFFFF395, 0xFFFFDD87 },
	{ 16, 0x1C1C, 0xFFFFF35F, 0xFFFFDE2F }
};

NJS_MKEY_A animation_007103C0_mkey_57_rot_0070F9E0[] = {
	{ 0, 0x3BB, 0xFFFFFC92, 0xFFFF89CA },
	{ 1, 0x3D8, 0xFFFFFC75, 0xFFFF8987 },
	{ 2, 0x421, 0xFFFFFC29, 0xFFFF88E0 },
	{ 3, 0x482, 0xFFFFFBC1, 0xFFFF8806 },
	{ 4, 0x4E7, 0xFFFFFB4F, 0xFFFF8728 },
	{ 5, 0x53E, 0xFFFFFAE6, 0xFFFF866A },
	{ 6, 0x57B, 0xFFFFFA99, 0xFFFF85DD },
	{ 7, 0x591, 0xFFFFFA7B, 0xFFFF85AC },
	{ 8, 0x584, 0xFFFFFA8E, 0xFFFF85CA },
	{ 9, 0x55E, 0xFFFFFAC0, 0xFFFF861C },
	{ 10, 0x523, 0xFFFFFB07, 0xFFFF86A4 },
	{ 11, 0x4DC, 0xFFFFFB5C, 0xFFFF873F },
	{ 12, 0x48E, 0xFFFFFBB5, 0xFFFF87ED },
	{ 13, 0x440, 0xFFFFFC09, 0xFFFF889A },
	{ 14, 0x3FD, 0xFFFFFC4F, 0xFFFF8933 },
	{ 15, 0x3CD, 0xFFFFFC80, 0xFFFF89A1 },
	{ 16, 0x3BB, 0xFFFFFC92, 0xFFFF89CA }
};

NJS_MKEY_A animation_007103C0_mkey_58_rot_0070FAF0[] = {
	{ 0, 0, 0, 0x1D77 },
	{ 1, 0, 0, 0x1D69 },
	{ 2, 0, 0, 0x1D41 },
	{ 3, 0, 0, 0x1D02 },
	{ 4, 0, 0, 0x1CB1 },
	{ 5, 0, 0, 0x1C5C },
	{ 6, 0, 0, 0x1C21 },
	{ 7, 0, 0, 0x1C05 },
	{ 8, 0, 0, 0x1C16 },
	{ 9, 0, 0, 0x1C44 },
	{ 10, 0, 0, 0x1C78 },
	{ 11, 0, 0, 0x1CBB },
	{ 12, 0, 0, 0x1CFA },
	{ 13, 0, 0, 0x1D2F },
	{ 14, 0, 0, 0x1D56 },
	{ 15, 0, 0, 0x1D6F },
	{ 16, 0, 0, 0x1D77 }
};

NJS_MKEY_A animation_007103C0_mkey_59_rot_0070FC00[] = {
	{ 0, 0, 0, 0x2805 },
	{ 1, 0, 0, 0x27F1 },
	{ 2, 0, 0, 0x27B8 },
	{ 3, 0, 0, 0x275E },
	{ 4, 0, 0, 0x26EC },
	{ 5, 0, 0, 0x2673 },
	{ 6, 0, 0, 0x261E },
	{ 7, 0, 0, 0x25F6 },
	{ 8, 0, 0, 0x260F },
	{ 9, 0, 0, 0x2650 },
	{ 10, 0, 0, 0x269A },
	{ 11, 0, 0, 0x26F9 },
	{ 12, 0, 0, 0x2753 },
	{ 13, 0, 0, 0x279E },
	{ 14, 0, 0, 0x27D6 },
	{ 15, 0, 0, 0x27F9 },
	{ 16, 0, 0, 0x2805 }
};

NJS_MKEY_A animation_007103C0_mkey_62_rot_0070FD10[] = {
	{ 0, 0x10B4, 0x18C, 0xFFFFEAD1 },
	{ 1, 0x10B4, 0x1E3, 0xFFFFEB7E },
	{ 2, 0x10B4, 0x2C2, 0xFFFFED3D },
	{ 3, 0x10B4, 0x3F4, 0xFFFFEFA0 },
	{ 4, 0x10B4, 0x541, 0xFFFFF23A },
	{ 5, 0x10B4, 0x672, 0xFFFFF49E },
	{ 6, 0x10B4, 0x752, 0xFFFFF65D },
	{ 7, 0x10B4, 0x7A8, 0xFFFFF70A },
	{ 8, 0x10B4, 0x773, 0xFFFFF69F },
	{ 9, 0x10B4, 0x6E3, 0xFFFFF57F },
	{ 10, 0x10B4, 0x613, 0xFFFFF3DF },
	{ 11, 0x10B4, 0x51C, 0xFFFFF1F1 },
	{ 12, 0x10B4, 0x418, 0xFFFFEFEA },
	{ 13, 0x10B4, 0x321, 0xFFFFEDFC },
	{ 14, 0x10B4, 0x251, 0xFFFFEC5C },
	{ 15, 0x10B4, 0x1C2, 0xFFFFEB3C },
	{ 16, 0x10B4, 0x18C, 0xFFFFEAD1 }
};

NJS_MKEY_A animation_007103C0_mkey_67_rot_0070FE20[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0xFFFFFFFC, 0xFFFFE5CD },
	{ 2, 0, 0xFFFFFFEE, 0xFFFFE87E },
	{ 3, 0, 0xFFFFFFDA, 0xFFFFEC9C },
	{ 4, 0, 0xFFFFFFC1, 0xFFFFF1AC },
	{ 5, 0, 0xFFFFFFAA, 0xFFFFF6CF },
	{ 6, 0, 0xFFFFFF98, 0xFFFFFACC },
	{ 7, 0, 0xFFFFFF91, 0xFFFFFC62 },
	{ 8, 0, 0xFFFFFF96, 0xFFFFFB66 },
	{ 9, 0, 0xFFFFFFA1, 0xFFFFF8CD },
	{ 10, 0, 0xFFFFFFB1, 0xFFFFF529 },
	{ 11, 0, 0xFFFFFFC4, 0xFFFFF116 },
	{ 12, 0, 0xFFFFFFD7, 0xFFFFED23 },
	{ 13, 0, 0xFFFFFFE8, 0xFFFFE9B9 },
	{ 14, 0, 0xFFFFFFF5, 0xFFFFE71A },
	{ 15, 0, 0xFFFFFFFE, 0xFFFFE56D },
	{ 16, 0, 0, 0xFFFFE4D4 }
};

NJS_MDATA2 animation_007103C0_mdat_0070FF30[] = {
	{ animation_007103C0_mkey_0_pos_0070E820, NULL, LengthOfArray<Uint32>(animation_007103C0_mkey_0_pos_0070E820), 0 },
	{ NULL, animation_007103C0_mkey_1_rot_0070E930, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_1_rot_0070E930) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_12_rot_0070E950, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_12_rot_0070E950) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_15_rot_0070EA60, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_15_rot_0070EA60) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_19_rot_0070EB70, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_19_rot_0070EB70) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_25_rot_0070EC80, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_25_rot_0070EC80) },
	{ NULL, animation_007103C0_mkey_26_rot_0070ED90, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_26_rot_0070ED90) },
	{ NULL, animation_007103C0_mkey_27_rot_0070EEA0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_27_rot_0070EEA0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_30_rot_0070EFB0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_30_rot_0070EFB0) },
	{ NULL, animation_007103C0_mkey_32_rot_0070F0E0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_32_rot_0070F0E0) },
	{ NULL, animation_007103C0_mkey_31_rot_0070F0C0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_31_rot_0070F0C0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_36_rot_0070F100, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_36_rot_0070F100) },
	{ NULL, animation_007103C0_mkey_37_rot_0070F210, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_37_rot_0070F210) },
	{ NULL, animation_007103C0_mkey_38_rot_0070F320, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_38_rot_0070F320) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_41_rot_0070F430, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_41_rot_0070F430) },
	{ NULL, animation_007103C0_mkey_43_rot_0070F560, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_43_rot_0070F560) },
	{ NULL, animation_007103C0_mkey_42_rot_0070F540, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_42_rot_0070F540) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_46_rot_0070F580, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_46_rot_0070F580) },
	{ NULL, animation_007103C0_mkey_47_rot_0070F5A0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_47_rot_0070F5A0) },
	{ NULL, animation_007103C0_mkey_48_rot_0070F6B0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_48_rot_0070F6B0) },
	{ NULL, animation_007103C0_mkey_49_rot_0070F7C0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_49_rot_0070F7C0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_52_rot_0070F8D0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_52_rot_0070F8D0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_57_rot_0070F9E0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_57_rot_0070F9E0) },
	{ NULL, animation_007103C0_mkey_58_rot_0070FAF0, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_58_rot_0070FAF0) },
	{ NULL, animation_007103C0_mkey_59_rot_0070FC00, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_59_rot_0070FC00) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_62_rot_0070FD10, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_62_rot_0070FD10) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007103C0_mkey_67_rot_0070FE20, 0, LengthOfArray<Uint32>(animation_007103C0_mkey_67_rot_0070FE20) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbdown1 = { animation_007103C0_mdat_0070FF30, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbdown1 = { AMY_OBJECTS[0], &motion_a_sbdown1 };
