/* NINJA Motion
 *
 * Generated by DataToolbox
 *
 */

NJS_MKEY_F animation_007147E0_mkey_0_pos_007133E0[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 1, 0, -0.7479f, 0 },
	{ 2, 0, -0.7802f, 0 },
	{ 3, 0, -0.8243f, 0 },
	{ 4, 0, -0.8724f, 0 },
	{ 5, 0, -0.9165f, 0 },
	{ 6, 0, -0.9487f, 0 },
	{ 7, 0, -0.9613f, 0 },
	{ 8, 0, -0.9535f, 0 },
	{ 9, 0, -0.9327f, 0 },
	{ 10, 0, -0.9027f, 0 },
	{ 11, 0, -0.8671f, 0 },
	{ 12, 0, -0.8296f, 0 },
	{ 13, 0, -0.7939f, 0 },
	{ 14, 0, -0.7639f, 0 },
	{ 15, 0, -0.7431f, 0 },
	{ 16, 0, -0.7354f, 0 }
};

NJS_MKEY_A animation_007147E0_mkey_1_rot_007134F0[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0, 0xFFFFEAAB, 0x8DF },
	{ 2, 0, 0xFFFFEAAB, 0x9AF },
	{ 3, 0, 0xFFFFEAAB, 0xACD },
	{ 4, 0, 0xFFFFEAAB, 0xC03 },
	{ 5, 0, 0xFFFFEAAB, 0xD21 },
	{ 6, 0, 0xFFFFEAAB, 0xDF1 },
	{ 7, 0, 0xFFFFEAAB, 0xE42 },
	{ 8, 0, 0xFFFFEAAB, 0xE10 },
	{ 9, 0, 0xFFFFEAAB, 0xD8A },
	{ 10, 0, 0xFFFFEAAB, 0xCC7 },
	{ 11, 0, 0xFFFFEAAB, 0xBE1 },
	{ 12, 0, 0xFFFFEAAB, 0xAEF },
	{ 13, 0, 0xFFFFEAAB, 0xA08 },
	{ 14, 0, 0xFFFFEAAB, 0x946 },
	{ 15, 0, 0xFFFFEAAB, 0x8C0 },
	{ 16, 0, 0xFFFFEAAB, 0x88E }
};

NJS_MKEY_A animation_007147E0_mkey_12_rot_00713600[] = {
	{ 0, 0, 0xFFFFEAC7, 0x8875 },
	{ 1, 0, 0xFFFFEAC0, 0x882E },
	{ 2, 0, 0xFFFFEAB0, 0x8774 },
	{ 3, 0, 0xFFFFEA9C, 0x8670 },
	{ 4, 0, 0xFFFFEA89, 0x854C },
	{ 5, 0, 0xFFFFEA7B, 0x843A },
	{ 6, 0, 0xFFFFEA72, 0x836E },
	{ 7, 0, 0xFFFFEA6F, 0x831E },
	{ 8, 0, 0xFFFFEA71, 0x834F },
	{ 9, 0, 0xFFFFEA76, 0x83D4 },
	{ 10, 0, 0xFFFFEA7F, 0x8491 },
	{ 11, 0, 0xFFFFEA8B, 0x856D },
	{ 12, 0, 0xFFFFEA9A, 0x8650 },
	{ 13, 0, 0xFFFFEAAA, 0x8723 },
	{ 14, 0, 0xFFFFEAB8, 0x87D2 },
	{ 15, 0, 0xFFFFEAC3, 0x8849 },
	{ 16, 0, 0xFFFFEAC7, 0x8875 }
};

NJS_MKEY_A animation_007147E0_mkey_15_rot_00713710[] = {
	{ 0, 0, 0xB6A, 0xFFFF87C1 },
	{ 1, 0, 0xB7D, 0xFFFF87BA },
	{ 2, 0, 0xBAF, 0xFFFF87A8 },
	{ 3, 0, 0xBF4, 0xFFFF878D },
	{ 4, 0, 0xC40, 0xFFFF876E },
	{ 5, 0, 0xC86, 0xFFFF8750 },
	{ 6, 0, 0xCBA, 0xFFFF873A },
	{ 7, 0, 0xCCE, 0xFFFF8731 },
	{ 8, 0, 0xCC1, 0xFFFF8737 },
	{ 9, 0, 0xCA0, 0xFFFF8745 },
	{ 10, 0, 0xC70, 0xFFFF875A },
	{ 11, 0, 0xC37, 0xFFFF8771 },
	{ 12, 0, 0xBFC, 0xFFFF878A },
	{ 13, 0, 0xBC4, 0xFFFF879F },
	{ 14, 0, 0xB96, 0xFFFF87B1 },
	{ 15, 0, 0xB76, 0xFFFF87BD },
	{ 16, 0, 0xB6A, 0xFFFF87C1 }
};

NJS_MKEY_A animation_007147E0_mkey_19_rot_00713820[] = {
	{ 0, 0, 0xFFFFF461, 0xFFFF87BF },
	{ 1, 0, 0xFFFFF461, 0xFFFF87B1 },
	{ 2, 0, 0xFFFFF460, 0xFFFF878B },
	{ 3, 0, 0xFFFFF463, 0xFFFF8754 },
	{ 4, 0, 0xFFFFF46C, 0xFFFF8715 },
	{ 5, 0, 0xFFFFF47A, 0xFFFF86DA },
	{ 6, 0, 0xFFFFF487, 0xFFFF86AD },
	{ 7, 0, 0xFFFFF48C, 0xFFFF869B },
	{ 8, 0, 0xFFFFF489, 0xFFFF86A6 },
	{ 9, 0, 0xFFFFF480, 0xFFFF86C3 },
	{ 10, 0, 0xFFFFF475, 0xFFFF86EC },
	{ 11, 0, 0xFFFFF46B, 0xFFFF871C },
	{ 12, 0, 0xFFFFF464, 0xFFFF874D },
	{ 13, 0, 0xFFFFF461, 0xFFFF877A },
	{ 14, 0, 0xFFFFF460, 0xFFFF879E },
	{ 15, 0, 0xFFFFF461, 0xFFFF87B6 },
	{ 16, 0, 0xFFFFF461, 0xFFFF87BF }
};

NJS_MKEY_A animation_007147E0_mkey_25_rot_00713930[] = {
	{ 0, 0, 0x2A6D, 0xFFFFE10E },
	{ 16, 0, 0x2A6D, 0xFFFFE10E }
};

NJS_MKEY_A animation_007147E0_mkey_26_rot_00713950[] = {
	{ 0, 0, 0xD3, 0xFFFFEF92 },
	{ 16, 0, 0xD3, 0xFFFFEF92 }
};

NJS_MKEY_A animation_007147E0_mkey_27_rot_00713970[] = {
	{ 0, 0, 0x1E3, 0xFFFFE2EE },
	{ 16, 0, 0x1E3, 0xFFFFE2EE }
};

NJS_MKEY_A animation_007147E0_mkey_30_rot_00713990[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_007147E0_mkey_32_rot_007139D0[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 16, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_007147E0_mkey_31_rot_007139B0[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_007147E0_mkey_36_rot_007139F0[] = {
	{ 0, 0, 0xFFFFE8F9, 0xFFFFDCAA },
	{ 16, 0, 0xFFFFE8F9, 0xFFFFDCAA }
};

NJS_MKEY_A animation_007147E0_mkey_37_rot_00713A10[] = {
	{ 0, 0, 0xFFFFEE74, 0xFFFFEBF0 },
	{ 16, 0, 0xFFFFEE74, 0xFFFFEBF0 }
};

NJS_MKEY_A animation_007147E0_mkey_38_rot_00713A30[] = {
	{ 0, 0, 0xFFFFEED4, 0xFFFFECC1 },
	{ 16, 0, 0xFFFFEED4, 0xFFFFECC1 }
};

NJS_MKEY_A animation_007147E0_mkey_43_rot_00713A70[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_007147E0_mkey_42_rot_00713A50[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 16, 0, 0xFFFFE3E4, 0 }
};

NJS_MKEY_A animation_007147E0_mkey_46_rot_00713A90[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_007147E0_mkey_47_rot_00713AB0[] = {
	{ 0, 0xFFFFFEBA, 0x20C, 0xFFFFB851 },
	{ 1, 0xFFFFFED6, 0x1D6, 0xFFFFB7D4 },
	{ 2, 0xFFFFFF25, 0x14C, 0xFFFFB696 },
	{ 3, 0xFFFFFF99, 0x94, 0xFFFFB4F2 },
	{ 4, 0x21, 0xFFFFFFD3, 0xFFFFB33A },
	{ 5, 0xA9, 0xFFFFFF27, 0xFFFFB1B0 },
	{ 6, 0x111, 0xFFFFFEAD, 0xFFFFB097 },
	{ 7, 0x13A, 0xFFFFFE7E, 0xFFFFB02B },
	{ 8, 0x121, 0xFFFFFE9B, 0xFFFFB06E },
	{ 9, 0xDD, 0xFFFFFEE9, 0xFFFFB121 },
	{ 10, 0x7E, 0xFFFFFF5C, 0xFFFFB22A },
	{ 11, 0x12, 0xFFFFFFE8, 0xFFFFB36A },
	{ 12, 0xFFFFFFA7, 0x7E, 0xFFFFB4C0 },
	{ 13, 0xFFFFFF48, 0x111, 0xFFFFB611 },
	{ 14, 0xFFFFFEFC, 0x191, 0xFFFFB735 },
	{ 15, 0xFFFFFECB, 0x1EA, 0xFFFFB803 },
	{ 16, 0xFFFFFEBA, 0x20C, 0xFFFFB851 }
};

NJS_MKEY_A animation_007147E0_mkey_48_rot_00713BC0[] = {
	{ 0, 0, 0, 0x1713 },
	{ 1, 0, 0, 0x1760 },
	{ 2, 0, 0, 0x1820 },
	{ 3, 0, 0, 0x191A },
	{ 4, 0, 0, 0x1A13 },
	{ 5, 0, 0, 0x1AF4 },
	{ 6, 0, 0, 0x1B93 },
	{ 7, 0, 0, 0x1BCF },
	{ 8, 0, 0, 0x1BAA },
	{ 9, 0, 0, 0x1B45 },
	{ 10, 0, 0, 0x1AAF },
	{ 11, 0, 0, 0x19F7 },
	{ 12, 0, 0, 0x1937 },
	{ 13, 0, 0, 0x1870 },
	{ 14, 0, 0, 0x17C0 },
	{ 15, 0, 0, 0x1743 },
	{ 16, 0, 0, 0x1713 }
};

NJS_MKEY_A animation_007147E0_mkey_49_rot_00713CD0[] = {
	{ 0, 0, 0, 0x152C },
	{ 1, 0, 0, 0x1586 },
	{ 2, 0, 0, 0x1667 },
	{ 3, 0, 0, 0x178D },
	{ 4, 0, 0, 0x18C7 },
	{ 5, 0, 0, 0x19D1 },
	{ 6, 0, 0, 0x1A8B },
	{ 7, 0, 0, 0x1AD2 },
	{ 8, 0, 0, 0x1AA6 },
	{ 9, 0, 0, 0x1A2F },
	{ 10, 0, 0, 0x197F },
	{ 11, 0, 0, 0x18A6 },
	{ 12, 0, 0, 0x17B0 },
	{ 13, 0, 0, 0x16C5 },
	{ 14, 0, 0, 0x15F7 },
	{ 15, 0, 0, 0x1564 },
	{ 16, 0, 0, 0x152C }
};

NJS_MKEY_A animation_007147E0_mkey_52_rot_00713DE0[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFD539 },
	{ 1, 0x1C1C, 0xFFFFF77E, 0xFFFFD4E8 },
	{ 2, 0x1C1C, 0xFFFFF79C, 0xFFFFD417 },
	{ 3, 0x1C1C, 0xFFFFF7C4, 0xFFFFD2FA },
	{ 4, 0x1C1C, 0xFFFFF7F1, 0xFFFFD1C3 },
	{ 5, 0x1C1C, 0xFFFFF819, 0xFFFFD0A6 },
	{ 6, 0x1C1C, 0xFFFFF837, 0xFFFFCFD5 },
	{ 7, 0x1C1C, 0xFFFFF843, 0xFFFFCF85 },
	{ 8, 0x1C1C, 0xFFFFF83C, 0xFFFFCFB7 },
	{ 9, 0x1C1C, 0xFFFFF828, 0xFFFFD03D },
	{ 10, 0x1C1C, 0xFFFFF80D, 0xFFFFD0FF },
	{ 11, 0x1C1C, 0xFFFFF7EC, 0xFFFFD1E5 },
	{ 12, 0x1C1C, 0xFFFFF7C9, 0xFFFFD2D8 },
	{ 13, 0x1C1C, 0xFFFFF7A8, 0xFFFFD3BE },
	{ 14, 0x1C1C, 0xFFFFF78C, 0xFFFFD480 },
	{ 15, 0x1C1C, 0xFFFFF779, 0xFFFFD507 },
	{ 16, 0x1C1C, 0xFFFFF772, 0xFFFFD539 }
};

NJS_MKEY_A animation_007147E0_mkey_57_rot_00713EF0[] = {
	{ 0, 0x64D, 0xFFFFF89D, 0xFFFF854F },
	{ 1, 0x672, 0xFFFFF885, 0xFFFF84A0 },
	{ 2, 0x6D2, 0xFFFFF849, 0xFFFF82E0 },
	{ 3, 0x753, 0xFFFFF7FD, 0xFFFF807E },
	{ 4, 0x7DD, 0xFFFFF7B0, 0xFFFF7DE8 },
	{ 5, 0x858, 0xFFFFF771, 0xFFFF7B8A },
	{ 6, 0x8AF, 0xFFFFF746, 0xFFFF79D1 },
	{ 7, 0x8D0, 0xFFFFF736, 0xFFFF7926 },
	{ 8, 0x8BC, 0xFFFFF740, 0xFFFF7990 },
	{ 9, 0x884, 0xFFFFF75B, 0xFFFF7AAB },
	{ 10, 0x832, 0xFFFFF784, 0xFFFF7C47 },
	{ 11, 0x7CE, 0xFFFFF7B8, 0xFFFF7E30 },
	{ 12, 0x762, 0xFFFFF7F4, 0xFFFF8035 },
	{ 13, 0x6FB, 0xFFFFF831, 0xFFFF8221 },
	{ 14, 0x6A2, 0xFFFFF867, 0xFFFF83C2 },
	{ 15, 0x664, 0xFFFFF88E, 0xFFFF84E3 },
	{ 16, 0x64D, 0xFFFFF89D, 0xFFFF854F }
};

NJS_MKEY_A animation_007147E0_mkey_58_rot_00714000[] = {
	{ 0, 0, 0, 0x18F2 },
	{ 1, 0, 0, 0x191E },
	{ 2, 0, 0, 0x198C },
	{ 3, 0, 0, 0x1A1B },
	{ 4, 0, 0, 0x1AAF },
	{ 5, 0, 0, 0x1B2F },
	{ 6, 0, 0, 0x1B86 },
	{ 7, 0, 0, 0x1BA8 },
	{ 8, 0, 0, 0x1B93 },
	{ 9, 0, 0, 0x1B5D },
	{ 10, 0, 0, 0x1B08 },
	{ 11, 0, 0, 0x1A9F },
	{ 12, 0, 0, 0x1A2C },
	{ 13, 0, 0, 0x19B9 },
	{ 14, 0, 0, 0x1955 },
	{ 15, 0, 0, 0x190D },
	{ 16, 0, 0, 0x18F2 }
};

NJS_MKEY_A animation_007147E0_mkey_59_rot_00714110[] = {
	{ 0, 0, 0, 0x219A },
	{ 1, 0, 0, 0x21D8 },
	{ 2, 0, 0, 0x2272 },
	{ 3, 0, 0, 0x233C },
	{ 4, 0, 0, 0x240C },
	{ 5, 0, 0, 0x24C1 },
	{ 6, 0, 0, 0x2543 },
	{ 7, 0, 0, 0x2573 },
	{ 8, 0, 0, 0x2555 },
	{ 9, 0, 0, 0x2501 },
	{ 10, 0, 0, 0x2489 },
	{ 11, 0, 0, 0x23F5 },
	{ 12, 0, 0, 0x2353 },
	{ 13, 0, 0, 0x22B2 },
	{ 14, 0, 0, 0x2225 },
	{ 15, 0, 0, 0x21C0 },
	{ 16, 0, 0, 0x219A }
};

NJS_MKEY_A animation_007147E0_mkey_62_rot_00714220[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF843 },
	{ 16, 0x10B4, 0x3FE, 0xFFFFF843 }
};

NJS_MKEY_A animation_007147E0_mkey_67_rot_00714240[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0x13, 0xFFFFE579 },
	{ 2, 0, 0x47, 0xFFFFE730 },
	{ 3, 0, 0x91, 0xFFFFE9A4 },
	{ 4, 0, 0xE5, 0xFFFFEC73 },
	{ 5, 0, 0x135, 0xFFFFEF23 },
	{ 6, 0, 0x16F, 0xFFFFF128 },
	{ 7, 0, 0x186, 0xFFFFF1F3 },
	{ 8, 0, 0x178, 0xFFFFF175 },
	{ 9, 0, 0x152, 0xFFFFF026 },
	{ 10, 0, 0x11C, 0xFFFFEE49 },
	{ 11, 0, 0xDC, 0xFFFFEC22 },
	{ 12, 0, 0x9A, 0xFFFFE9F2 },
	{ 13, 0, 0x5E, 0xFFFFE7F1 },
	{ 14, 0, 0x2D, 0xFFFFE651 },
	{ 15, 0, 0xC, 0xFFFFE53A },
	{ 16, 0, 0, 0xFFFFE4D4 }
};

NJS_MDATA2 animation_007147E0_mdat_00714350[] = {
	{ animation_007147E0_mkey_0_pos_007133E0, NULL, LengthOfArray<Uint32>(animation_007147E0_mkey_0_pos_007133E0), 0 },
	{ NULL, animation_007147E0_mkey_1_rot_007134F0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_1_rot_007134F0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_12_rot_00713600, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_12_rot_00713600) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_15_rot_00713710, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_15_rot_00713710) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_19_rot_00713820, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_19_rot_00713820) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_25_rot_00713930, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_25_rot_00713930) },
	{ NULL, animation_007147E0_mkey_26_rot_00713950, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_26_rot_00713950) },
	{ NULL, animation_007147E0_mkey_27_rot_00713970, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_27_rot_00713970) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_30_rot_00713990, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_30_rot_00713990) },
	{ NULL, animation_007147E0_mkey_32_rot_007139D0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_32_rot_007139D0) },
	{ NULL, animation_007147E0_mkey_31_rot_007139B0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_31_rot_007139B0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_36_rot_007139F0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_36_rot_007139F0) },
	{ NULL, animation_007147E0_mkey_37_rot_00713A10, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_37_rot_00713A10) },
	{ NULL, animation_007147E0_mkey_38_rot_00713A30, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_38_rot_00713A30) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_43_rot_00713A70, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_43_rot_00713A70) },
	{ NULL, animation_007147E0_mkey_42_rot_00713A50, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_42_rot_00713A50) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_46_rot_00713A90, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_46_rot_00713A90) },
	{ NULL, animation_007147E0_mkey_47_rot_00713AB0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_47_rot_00713AB0) },
	{ NULL, animation_007147E0_mkey_48_rot_00713BC0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_48_rot_00713BC0) },
	{ NULL, animation_007147E0_mkey_49_rot_00713CD0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_49_rot_00713CD0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_52_rot_00713DE0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_52_rot_00713DE0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_57_rot_00713EF0, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_57_rot_00713EF0) },
	{ NULL, animation_007147E0_mkey_58_rot_00714000, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_58_rot_00714000) },
	{ NULL, animation_007147E0_mkey_59_rot_00714110, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_59_rot_00714110) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_62_rot_00714220, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_62_rot_00714220) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_007147E0_mkey_67_rot_00714240, 0, LengthOfArray<Uint32>(animation_007147E0_mkey_67_rot_00714240) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbfront0 = { animation_007147E0_mdat_00714350, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbfront0{ AMY_OBJECTS[0], &motion_a_sbfront0 };
