/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_0070CB80_mkey_0_pos_0070AF70[] = {
	{ 0, 0, -0.3016f, 0 },
	{ 1, 0, -0.3065f, 0 },
	{ 2, 0, -0.3202f, 0 },
	{ 3, 0, -0.3416f, 0 },
	{ 4, 0, -0.3694f, 0 },
	{ 5, 0, -0.4022f, 0 },
	{ 6, 0, -0.4388f, 0 },
	{ 7, 0, -0.478f, 0 },
	{ 8, 0, -0.5185f, 0 },
	{ 9, 0, -0.5589f, 0 },
	{ 10, 0, -0.5981f, 0 },
	{ 11, 0, -0.6348f, 0 },
	{ 12, 0, -0.6676f, 0 },
	{ 13, 0, -0.6954f, 0 },
	{ 14, 0, -0.7168f, 0 },
	{ 15, 0, -0.7305f, 0 },
	{ 16, 0, -0.7354f, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_1_rot_0070B080[] = {
	{ 0, 0, 0xFFFFD4AB, 0 },
	{ 1, 0, 0xFFFFD4EA, 0x18 },
	{ 2, 0, 0xFFFFD59D, 0x5E },
	{ 3, 0, 0xFFFFD6B3, 0xCA },
	{ 4, 0, 0xFFFFD81B, 0x156 },
	{ 5, 0, 0xFFFFD9C5, 0x1FC },
	{ 6, 0, 0xFFFFDBA1, 0x2B5 },
	{ 7, 0, 0xFFFFDD9E, 0x37A },
	{ 8, 0, 0xFFFFDFAB, 0x447 },
	{ 9, 0, 0xFFFFE1B8, 0x513 },
	{ 10, 0, 0xFFFFE3B5, 0x5D9 },
	{ 11, 0, 0xFFFFE591, 0x692 },
	{ 12, 0, 0xFFFFE73B, 0x738 },
	{ 13, 0, 0xFFFFE8A3, 0x7C4 },
	{ 14, 0, 0xFFFFE9B9, 0x830 },
	{ 15, 0, 0xFFFFEA6C, 0x875 },
	{ 16, 0, 0xFFFFEAAB, 0x88E }
};

NJS_MKEY_A animation_0070CB80_mkey_12_rot_0070B190[] = {
	{ 0, 0, 0xFFFFE166, 0x8794 },
	{ 1, 0, 0xFFFFE19D, 0x8696 },
	{ 2, 0, 0xFFFFE23C, 0x8410 },
	{ 3, 0, 0xFFFFE341, 0x80BB },
	{ 4, 0, 0xFFFFE493, 0x7D51 },
	{ 5, 0, 0xFFFFE5FD, 0x7A72 },
	{ 6, 0, 0xFFFFE73C, 0x7899 },
	{ 7, 0, 0xFFFFE810, 0x7821 },
	{ 8, 0, 0xFFFFE88B, 0x7903 },
	{ 9, 0, 0xFFFFE8EB, 0x7AC5 },
	{ 10, 0, 0xFFFFE93E, 0x7D1B },
	{ 11, 0, 0xFFFFE990, 0x7FBB },
	{ 12, 0, 0xFFFFE9E5, 0x825D },
	{ 13, 0, 0xFFFFEA38, 0x84C1 },
	{ 14, 0, 0xFFFFEA80, 0x86B1 },
	{ 15, 0, 0xFFFFEAB4, 0x87FC },
	{ 16, 0, 0xFFFFEAC7, 0x8875 }
};

NJS_MKEY_A animation_0070CB80_mkey_15_rot_0070B2A0[] = {
	{ 0, 0, 0xAE7, 0xFFFF8A7F },
	{ 1, 0, 0xAFD, 0xFFFF8AC4 },
	{ 2, 0, 0xB20, 0xFFFF8B72 },
	{ 3, 0, 0xB1E, 0xFFFF8C55 },
	{ 4, 0, 0xAE0, 0xFFFF8D34 },
	{ 5, 0, 0xA7A, 0xFFFF8DE0 },
	{ 6, 0, 0xA19, 0xFFFF8E40 },
	{ 7, 0, 0x9EE, 0xFFFF8E46 },
	{ 8, 0, 0xA02, 0xFFFF8DF0 },
	{ 9, 0, 0xA3B, 0xFFFF8D53 },
	{ 10, 0, 0xA84, 0xFFFF8C7B },
	{ 11, 0, 0xACE, 0xFFFF8B7B },
	{ 12, 0, 0xB0C, 0xFFFF8A6B },
	{ 13, 0, 0xB3A, 0xFFFF8967 },
	{ 14, 0, 0xB56, 0xFFFF888D },
	{ 15, 0, 0xB65, 0xFFFF87F8 },
	{ 16, 0, 0xB6A, 0xFFFF87C1 }
};

NJS_MKEY_A animation_0070CB80_mkey_19_rot_0070B3B0[] = {
	{ 0, 0, 0xFFFFECF9, 0xFFFF8C03 },
	{ 1, 0, 0xFFFFED26, 0xFFFF8C14 },
	{ 2, 0, 0xFFFFED92, 0xFFFF8C4D },
	{ 3, 0, 0xFFFFEE0D, 0xFFFF8CB7 },
	{ 4, 0, 0xFFFFEE78, 0xFFFF8D49 },
	{ 5, 0, 0xFFFFEECC, 0xFFFF8DE4 },
	{ 6, 0, 0xFFFFEF1B, 0xFFFF8E5C },
	{ 7, 0, 0xFFFFEF7D, 0xFFFF8E81 },
	{ 8, 0, 0xFFFFF00A, 0xFFFF8E44 },
	{ 9, 0, 0xFFFFF0C2, 0xFFFF8DB8 },
	{ 10, 0, 0xFFFFF18C, 0xFFFF8CE5 },
	{ 11, 0, 0xFFFFF253, 0xFFFF8BDE },
	{ 12, 0, 0xFFFFF305, 0xFFFF8ABC },
	{ 13, 0, 0xFFFFF397, 0xFFFF899F },
	{ 14, 0, 0xFFFFF405, 0xFFFF88AA },
	{ 15, 0, 0xFFFFF449, 0xFFFF87FF },
	{ 16, 0, 0xFFFFF461, 0xFFFF87BF }
};

NJS_MKEY_A animation_0070CB80_mkey_25_rot_0070B4C0[] = {
	{ 0, 0, 0x1CF9, 0xFFFFD476 },
	{ 1, 0, 0x1D21, 0xFFFFD48E },
	{ 2, 0, 0x1D92, 0xFFFFD4D2 },
	{ 3, 0, 0x1E41, 0xFFFFD540 },
	{ 4, 0, 0x1F25, 0xFFFFD5D4 },
	{ 5, 0, 0x2034, 0xFFFFD68D },
	{ 6, 0, 0x2162, 0xFFFFD768 },
	{ 7, 0, 0x22A3, 0xFFFFD864 },
	{ 8, 0, 0x23ED, 0xFFFFD97C },
	{ 9, 0, 0x2532, 0xFFFFDAAA },
	{ 10, 0, 0x2669, 0xFFFFDBE6 },
	{ 11, 0, 0x2785, 0xFFFFDD24 },
	{ 12, 0, 0x287F, 0xFFFFDE55 },
	{ 13, 0, 0x294C, 0xFFFFDF67 },
	{ 14, 0, 0x29E8, 0xFFFFE045 },
	{ 15, 0, 0x2A4A, 0xFFFFE0D9 },
	{ 16, 0, 0x2A6D, 0xFFFFE10E }
};

NJS_MKEY_A animation_0070CB80_mkey_26_rot_0070B5D0[] = {
	{ 0, 0, 0xFFFFF70D, 0xFFFFEEE2 },
	{ 1, 0, 0xFFFFF71C, 0xFFFFEEDA },
	{ 2, 0, 0xFFFFF749, 0xFFFFEEC4 },
	{ 3, 0, 0xFFFFF794, 0xFFFFEEA4 },
	{ 4, 0, 0xFFFFF7FD, 0xFFFFEE7E },
	{ 5, 0, 0xFFFFF886, 0xFFFFEE59 },
	{ 6, 0, 0xFFFFF930, 0xFFFFEE3A },
	{ 7, 0, 0xFFFFF9FA, 0xFFFFEE27 },
	{ 8, 0, 0xFFFFFADF, 0xFFFFEE25 },
	{ 9, 0, 0xFFFFFBD8, 0xFFFFEE36 },
	{ 10, 0, 0xFFFFFCDB, 0xFFFFEE5A },
	{ 11, 0, 0xFFFFFDDC, 0xFFFFEE90 },
	{ 12, 0, 0xFFFFFECD, 0xFFFFEED2 },
	{ 13, 0, 0xFFFFFF9E, 0xFFFFEF17 },
	{ 14, 0, 0x42, 0xFFFFEF55 },
	{ 15, 0, 0xAD, 0xFFFFEF81 },
	{ 16, 0, 0xD3, 0xFFFFEF92 }
};

NJS_MKEY_A animation_0070CB80_mkey_27_rot_0070B6E0[] = {
	{ 0, 0, 0xFFFFF6BE, 0xFFFFEB2B },
	{ 1, 0, 0xFFFFF6C7, 0xFFFFEB0D },
	{ 2, 0, 0xFFFFF6E4, 0xFFFFEABA },
	{ 3, 0, 0xFFFFF715, 0xFFFFEA38 },
	{ 4, 0, 0xFFFFF760, 0xFFFFE98D },
	{ 5, 0, 0xFFFFF7CB, 0xFFFFE8C1 },
	{ 6, 0, 0xFFFFF85B, 0xFFFFE7DF },
	{ 7, 0, 0xFFFFF915, 0xFFFFE6F2 },
	{ 8, 0, 0xFFFFF9FB, 0xFFFFE606 },
	{ 9, 0, 0xFFFFFB0C, 0xFFFFE52B },
	{ 10, 0, 0xFFFFFC41, 0xFFFFE46D },
	{ 11, 0, 0xFFFFFD8A, 0xFFFFE3D5 },
	{ 12, 0, 0xFFFFFED4, 0xFFFFE368 },
	{ 13, 0, 3, 0xFFFFE324 },
	{ 14, 0, 0xFE, 0xFFFFE300 },
	{ 15, 0, 0x1A6, 0xFFFFE2F2 },
	{ 16, 0, 0x1E3, 0xFFFFE2EE }
};

NJS_MKEY_A animation_0070CB80_mkey_30_rot_0070B7F0[] = {
	{ 0, 0, 0xB68, 0 },
	{ 1, 0xFE, 0xCAB, 0 },
	{ 2, 0x38D, 0xFF2, 0 },
	{ 3, 0x70E, 0x147A, 0 },
	{ 4, 0xADF, 0x1983, 0 },
	{ 5, 0xE5F, 0x1E49, 0 },
	{ 6, 0x10EF, 0x220B, 0 },
	{ 7, 0x11ED, 0x2406, 0 },
	{ 8, 0x114F, 0x244E, 0 },
	{ 9, 0xFAA, 0x23A1, 0 },
	{ 10, 0xD47, 0x223F, 0 },
	{ 11, 0xA73, 0x2067, 0 },
	{ 12, 0x779, 0x1E57, 0 },
	{ 13, 0x4A5, 0x1C4F, 0 },
	{ 14, 0x243, 0x1A8D, 0 },
	{ 15, 0x9D, 0x1951, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_32_rot_0070B920[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 16, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_31_rot_0070B900[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_0070CB80_mkey_36_rot_0070B940[] = {
	{ 0, 0, 0xFFFFF1BA, 0xFFFFD824 },
	{ 1, 0, 0xFFFFF1AA, 0xFFFFD82B },
	{ 2, 0, 0xFFFFF17D, 0xFFFFD840 },
	{ 3, 0, 0xFFFFF135, 0xFFFFD862 },
	{ 4, 0, 0xFFFFF0D3, 0xFFFFD890 },
	{ 5, 0, 0xFFFFF058, 0xFFFFD8CA },
	{ 6, 0, 0xFFFFEFC5, 0xFFFFD911 },
	{ 7, 0, 0xFFFFEF1B, 0xFFFFD964 },
	{ 8, 0, 0xFFFFEE5D, 0xFFFFD9C2 },
	{ 9, 0, 0xFFFFED8D, 0xFFFFDA2B },
	{ 10, 0, 0xFFFFECB1, 0xFFFFDA9C },
	{ 11, 0, 0xFFFFEBD0, 0xFFFFDB13 },
	{ 12, 0, 0xFFFFEAF6, 0xFFFFDB89 },
	{ 13, 0, 0xFFFFEA30, 0xFFFFDBF8 },
	{ 14, 0, 0xFFFFE98D, 0xFFFFDC54 },
	{ 15, 0, 0xFFFFE920, 0xFFFFDC93 },
	{ 16, 0, 0xFFFFE8F9, 0xFFFFDCAA }
};

NJS_MKEY_A animation_0070CB80_mkey_37_rot_0070BA50[] = {
	{ 0, 0, 0xFFFFF593, 0xFFFFEE05 },
	{ 1, 0, 0xFFFFF587, 0xFFFFEDFE },
	{ 2, 0, 0xFFFFF564, 0xFFFFEDED },
	{ 3, 0, 0xFFFFF52D, 0xFFFFEDD1 },
	{ 4, 0, 0xFFFFF4E0, 0xFFFFEDAC },
	{ 5, 0, 0xFFFFF47F, 0xFFFFED80 },
	{ 6, 0, 0xFFFFF40B, 0xFFFFED4D },
	{ 7, 0, 0xFFFFF382, 0xFFFFED16 },
	{ 8, 0, 0xFFFFF2E8, 0xFFFFECDD },
	{ 9, 0, 0xFFFFF23E, 0xFFFFECA5 },
	{ 10, 0, 0xFFFFF189, 0xFFFFEC71 },
	{ 11, 0, 0xFFFFF0CF, 0xFFFFEC44 },
	{ 12, 0, 0xFFFFF01A, 0xFFFFEC20 },
	{ 13, 0, 0xFFFFEF75, 0xFFFFEC08 },
	{ 14, 0, 0xFFFFEEEE, 0xFFFFEBF9 },
	{ 15, 0, 0xFFFFEE94, 0xFFFFEBF2 },
	{ 16, 0, 0xFFFFEE74, 0xFFFFEBF0 }
};

NJS_MKEY_A animation_0070CB80_mkey_38_rot_0070BB60[] = {
	{ 0, 0, 0xFFFFFD64, 0xFFFFE84B },
	{ 1, 0, 0xFFFFFD4B, 0xFFFFE849 },
	{ 2, 0, 0xFFFFFD03, 0xFFFFE845 },
	{ 3, 0, 0xFFFFFC8E, 0xFFFFE840 },
	{ 4, 0, 0xFFFFFBED, 0xFFFFE83E },
	{ 5, 0, 0xFFFFFB1F, 0xFFFFE841 },
	{ 6, 0, 0xFFFFFA25, 0xFFFFE84F },
	{ 7, 0, 0xFFFFF900, 0xFFFFE86D },
	{ 8, 0, 0xFFFFF7B4, 0xFFFFE8A3 },
	{ 9, 0, 0xFFFFF648, 0xFFFFE8F5 },
	{ 10, 0, 0xFFFFF4CA, 0xFFFFE969 },
	{ 11, 0, 0xFFFFF34B, 0xFFFFE9FF },
	{ 12, 0, 0xFFFFF1E1, 0xFFFFEAAF },
	{ 13, 0, 0xFFFFF0A5, 0xFFFFEB69 },
	{ 14, 0, 0xFFFFEFAD, 0xFFFFEC15 },
	{ 15, 0, 0xFFFFEF0D, 0xFFFFEC92 },
	{ 16, 0, 0xFFFFEED4, 0xFFFFECC1 }
};

NJS_MKEY_A animation_0070CB80_mkey_41_rot_0070BC70[] = {
	{ 0, 0xFFFFE8C7, 0x4E3, 0 },
	{ 1, 0xFFFFE920, 0x3C1, 0 },
	{ 2, 0xFFFFEA0F, 0xD2, 0 },
	{ 3, 0xFFFFEB6E, 0xFFFFFCCC, 0 },
	{ 4, 0xFFFFED16, 0xFFFFF85F, 0 },
	{ 5, 0xFFFFEEDF, 0xFFFFF441, 0 },
	{ 6, 0xFFFFF0A2, 0xFFFFF126, 0 },
	{ 7, 0xFFFFF239, 0xFFFFEFC1, 0 },
	{ 8, 0xFFFFF3D8, 0xFFFFF012, 0 },
	{ 9, 0xFFFFF5B8, 0xFFFFF16F, 0 },
	{ 10, 0xFFFFF7BB, 0xFFFFF38F, 0 },
	{ 11, 0xFFFFF9C3, 0xFFFFF627, 0 },
	{ 12, 0xFFFFFBB1, 0xFFFFF8ED, 0 },
	{ 13, 0xFFFFFD66, 0xFFFFFB96, 0 },
	{ 14, 0xFFFFFEC4, 0xFFFFFDD9, 0 },
	{ 15, 0xFFFFFFAC, 0xFFFFFF6A, 0 },
	{ 16, 0, 0, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_43_rot_0070BDA0[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_42_rot_0070BD80[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 16, 0, 0xFFFFE3E4, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_46_rot_0070BDC0[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_0070CB80_mkey_47_rot_0070BDE0[] = {
	{ 0, 0xFFFFFACC, 0x8E0, 0xFFFFB3C0 },
	{ 1, 0xFFFFFAD4, 0x8CE, 0xFFFFB3D0 },
	{ 2, 0xFFFFFAEB, 0x89B, 0xFFFFB3FD },
	{ 3, 0xFFFFFB12, 0x84A, 0xFFFFB442 },
	{ 4, 0xFFFFFB47, 0x7E0, 0xFFFFB499 },
	{ 5, 0xFFFFFB89, 0x761, 0xFFFFB4FF },
	{ 6, 0xFFFFFBD7, 0x6D1, 0xFFFFB56D },
	{ 7, 0xFFFFFC2F, 0x635, 0xFFFFB5DF },
	{ 8, 0xFFFFFC8E, 0x591, 0xFFFFB64F },
	{ 9, 0xFFFFFCF1, 0x4EC, 0xFFFFB6BA },
	{ 10, 0xFFFFFD54, 0x44A, 0xFFFFB71C },
	{ 11, 0xFFFFFDB2, 0x3B1, 0xFFFFB773 },
	{ 12, 0xFFFFFE07, 0x328, 0xFFFFB7BD },
	{ 13, 0xFFFFFE50, 0x2B4, 0xFFFFB7F8 },
	{ 14, 0xFFFFFE88, 0x25A, 0xFFFFB823 },
	{ 15, 0xFFFFFEAC, 0x220, 0xFFFFB83E },
	{ 16, 0xFFFFFEB9, 0x20C, 0xFFFFB848 }
};

NJS_MKEY_A animation_0070CB80_mkey_48_rot_0070BEF0[] = {
	{ 0, 0, 0, 0x15C9 },
	{ 1, 0, 0, 0x15D2 },
	{ 2, 0, 0, 0x15EA },
	{ 3, 0, 0, 0x160D },
	{ 4, 0, 0, 0x1637 },
	{ 5, 0, 0, 0x1664 },
	{ 6, 0, 0, 0x1690 },
	{ 7, 0, 0, 0x16B8 },
	{ 8, 0, 0, 0x16DA },
	{ 9, 0, 0, 0x16F5 },
	{ 10, 0, 0, 0x1708 },
	{ 11, 0, 0, 0x1715 },
	{ 16, 0, 0, 0x171C }
};

NJS_MKEY_A animation_0070CB80_mkey_49_rot_0070BFC0[] = {
	{ 0, 0, 0, 0x13A8 },
	{ 1, 0, 0, 0x13B2 },
	{ 2, 0, 0, 0x13CE },
	{ 3, 0, 0, 0x13F8 },
	{ 4, 0, 0, 0x1429 },
	{ 5, 0, 0, 0x145E },
	{ 6, 0, 0, 0x1491 },
	{ 7, 0, 0, 0x14C0 },
	{ 8, 0, 0, 0x14E8 },
	{ 9, 0, 0, 0x1508 },
	{ 10, 0, 0, 0x151F },
	{ 11, 0, 0, 0x152E },
	{ 16, 0, 0, 0x1536 }
};

NJS_MKEY_A animation_0070CB80_mkey_52_rot_0070C090[] = {
	{ 0, 0x1C1C, 0xFFFFF6A2, 0xFFFFE0A1 },
	{ 1, 0x1C1C, 0xFFFFF6A4, 0xFFFFE080 },
	{ 2, 0x1C1C, 0xFFFFF6AB, 0xFFFFE024 },
	{ 3, 0x1C1C, 0xFFFFF6B5, 0xFFFFDF94 },
	{ 4, 0x1C1C, 0xFFFFF6C2, 0xFFFFDED9 },
	{ 5, 0x1C1C, 0xFFFFF6D2, 0xFFFFDDFC },
	{ 6, 0x1C1C, 0xFFFFF6E4, 0xFFFFDD05 },
	{ 7, 0x1C1C, 0xFFFFF6F6, 0xFFFFDBFD },
	{ 8, 0x1C1C, 0xFFFFF70A, 0xFFFFDAED },
	{ 9, 0x1C1C, 0xFFFFF71D, 0xFFFFD9DD },
	{ 10, 0x1C1C, 0xFFFFF730, 0xFFFFD8D5 },
	{ 11, 0x1C1C, 0xFFFFF742, 0xFFFFD7DE },
	{ 12, 0x1C1C, 0xFFFFF752, 0xFFFFD701 },
	{ 13, 0x1C1C, 0xFFFFF75F, 0xFFFFD646 },
	{ 14, 0x1C1C, 0xFFFFF769, 0xFFFFD5B6 },
	{ 15, 0x1C1C, 0xFFFFF770, 0xFFFFD55A },
	{ 16, 0x1C1C, 0xFFFFF772, 0xFFFFD539 }
};

NJS_MKEY_A animation_0070CB80_mkey_57_rot_0070C1A0[] = {
	{ 0, 0x641, 0xFFFFF576, 0xFFFF9FE9 },
	{ 1, 0x651, 0xFFFFF56F, 0xFFFF9F95 },
	{ 2, 0x67E, 0xFFFFF55C, 0xFFFF9EA9 },
	{ 3, 0x6BB, 0xFFFFF542, 0xFFFF9D47 },
	{ 4, 0x707, 0xFFFFF52E, 0xFFFF9B6E },
	{ 5, 0x753, 0xFFFFF527, 0xFFFF9943 },
	{ 6, 0x795, 0xFFFFF534, 0xFFFF96DC },
	{ 7, 0x7C3, 0xFFFFF55B, 0xFFFF9454 },
	{ 8, 0x7D7, 0xFFFFF59C, 0xFFFF91C4 },
	{ 9, 0x7CF, 0xFFFFF5F7, 0xFFFF8F43 },
	{ 10, 0x7AA, 0xFFFFF667, 0xFFFF8CE8 },
	{ 11, 0x76E, 0xFFFFF6E5, 0xFFFF8AC4 },
	{ 12, 0x723, 0xFFFFF766, 0xFFFF88E8 },
	{ 13, 0x6D6, 0xFFFFF7DF, 0xFFFF8762 },
	{ 14, 0x691, 0xFFFFF843, 0xFFFF863C },
	{ 15, 0x661, 0xFFFFF886, 0xFFFF8582 },
	{ 16, 0x64F, 0xFFFFF89F, 0xFFFF8541 }
};

NJS_MKEY_A animation_0070CB80_mkey_58_rot_0070C2B0[] = {
	{ 0, 0, 0, 0x12E0 },
	{ 1, 0, 0, 0x12FC },
	{ 2, 0, 0, 0x134B },
	{ 3, 0, 0, 0x1395 },
	{ 4, 0, 0, 0x1423 },
	{ 5, 0, 0, 0x14C0 },
	{ 6, 0, 0, 0x1564 },
	{ 7, 0, 0, 0x1605 },
	{ 8, 0, 0, 0x169B },
	{ 9, 0, 0, 0x1727 },
	{ 10, 0, 0, 0x17A2 },
	{ 11, 0, 0, 0x180B },
	{ 12, 0, 0, 0x1861 },
	{ 13, 0, 0, 0x18A4 },
	{ 14, 0, 0, 0x18D5 },
	{ 15, 0, 0, 0x18F3 },
	{ 16, 0, 0, 0x18FD }
};

NJS_MKEY_A animation_0070CB80_mkey_59_rot_0070C3C0[] = {
	{ 0, 0, 0, 0x18BC },
	{ 1, 0, 0, 0x18E2 },
	{ 2, 0, 0, 0x194C },
	{ 3, 0, 0, 0x1A14 },
	{ 4, 0, 0, 0x1ADA },
	{ 5, 0, 0, 0x1BB6 },
	{ 6, 0, 0, 0x1C9A },
	{ 7, 0, 0, 0x1D7B },
	{ 8, 0, 0, 0x1E52 },
	{ 9, 0, 0, 0x1F16 },
	{ 10, 0, 0, 0x1FC2 },
	{ 11, 0, 0, 0x2055 },
	{ 12, 0, 0, 0x20CE },
	{ 13, 0, 0, 0x212D },
	{ 14, 0, 0, 0x2171 },
	{ 15, 0, 0, 0x219B },
	{ 16, 0, 0, 0x21A9 }
};

NJS_MKEY_A animation_0070CB80_mkey_62_rot_0070C4D0[] = {
	{ 0, 0x10B4, 0xC8C, 0xFFFFF639 },
	{ 1, 0x10B4, 0xC73, 0xFFFFF63F },
	{ 2, 0x10B4, 0xC2E, 0xFFFFF650 },
	{ 3, 0x10B4, 0xBC2, 0xFFFFF669 },
	{ 4, 0x10B4, 0xB36, 0xFFFFF68B },
	{ 5, 0x10B4, 0xA90, 0xFFFFF6B2 },
	{ 6, 0x10B4, 0x9D7, 0xFFFFF6DE },
	{ 7, 0x10B4, 0x911, 0xFFFFF70D },
	{ 8, 0x10B4, 0x845, 0xFFFFF73E },
	{ 9, 0x10B4, 0x779, 0xFFFFF76F },
	{ 10, 0x10B4, 0x6B3, 0xFFFFF79E },
	{ 11, 0x10B4, 0x5FA, 0xFFFFF7CA },
	{ 12, 0x10B4, 0x554, 0xFFFFF7F1 },
	{ 13, 0x10B4, 0x4C8, 0xFFFFF813 },
	{ 14, 0x10B4, 0x45C, 0xFFFFF82C },
	{ 15, 0x10B4, 0x416, 0xFFFFF83D },
	{ 16, 0x10B4, 0x3FE, 0xFFFFF843 }
};

NJS_MKEY_A animation_0070CB80_mkey_67_rot_0070C5E0[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0x10F, 0xFFFFE59B },
	{ 2, 0, 0x3A3, 0xFFFFE781 },
	{ 3, 0, 0x6CD, 0xFFFFE9DF },
	{ 4, 0, 0x9C9, 0xFFFFEC2E },
	{ 5, 0, 0xC23, 0xFFFFEE13 },
	{ 6, 0, 0xDA7, 0xFFFFEF57 },
	{ 7, 0, 0xE32, 0xFFFFEFCE },
	{ 8, 0, 0xDDC, 0xFFFFEF84 },
	{ 9, 0, 0xCEC, 0xFFFFEEB9 },
	{ 10, 0, 0xB71, 0xFFFFED81 },
	{ 11, 0, 0x97B, 0xFFFFEBF0 },
	{ 12, 0, 0x727, 0xFFFFEA24 },
	{ 13, 0, 0x4AC, 0xFFFFE845 },
	{ 14, 0, 0x25D, 0xFFFFE690 },
	{ 15, 0, 0xA8, 0xFFFFE550 },
	{ 16, 0, 0, 0xFFFFE4D4 }
};

NJS_MDATA2 animation_0070CB80_mdat_0070C6F0[] = {
	{ animation_0070CB80_mkey_0_pos_0070AF70, NULL, LengthOfArray<Uint32>(animation_0070CB80_mkey_0_pos_0070AF70), 0 },
	{ NULL, animation_0070CB80_mkey_1_rot_0070B080, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_1_rot_0070B080) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_12_rot_0070B190, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_12_rot_0070B190) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_15_rot_0070B2A0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_15_rot_0070B2A0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_19_rot_0070B3B0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_19_rot_0070B3B0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_25_rot_0070B4C0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_25_rot_0070B4C0) },
	{ NULL, animation_0070CB80_mkey_26_rot_0070B5D0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_26_rot_0070B5D0) },
	{ NULL, animation_0070CB80_mkey_27_rot_0070B6E0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_27_rot_0070B6E0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_30_rot_0070B7F0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_30_rot_0070B7F0) },
	{ NULL, animation_0070CB80_mkey_32_rot_0070B920, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_32_rot_0070B920) },
	{ NULL, animation_0070CB80_mkey_31_rot_0070B900, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_31_rot_0070B900) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_36_rot_0070B940, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_36_rot_0070B940) },
	{ NULL, animation_0070CB80_mkey_37_rot_0070BA50, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_37_rot_0070BA50) },
	{ NULL, animation_0070CB80_mkey_38_rot_0070BB60, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_38_rot_0070BB60) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_41_rot_0070BC70, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_41_rot_0070BC70) },
	{ NULL, animation_0070CB80_mkey_43_rot_0070BDA0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_43_rot_0070BDA0) },
	{ NULL, animation_0070CB80_mkey_42_rot_0070BD80, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_42_rot_0070BD80) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_46_rot_0070BDC0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_46_rot_0070BDC0) },
	{ NULL, animation_0070CB80_mkey_47_rot_0070BDE0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_47_rot_0070BDE0) },
	{ NULL, animation_0070CB80_mkey_48_rot_0070BEF0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_48_rot_0070BEF0) },
	{ NULL, animation_0070CB80_mkey_49_rot_0070BFC0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_49_rot_0070BFC0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_52_rot_0070C090, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_52_rot_0070C090) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_57_rot_0070C1A0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_57_rot_0070C1A0) },
	{ NULL, animation_0070CB80_mkey_58_rot_0070C2B0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_58_rot_0070C2B0) },
	{ NULL, animation_0070CB80_mkey_59_rot_0070C3C0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_59_rot_0070C3C0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_62_rot_0070C4D0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_62_rot_0070C4D0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070CB80_mkey_67_rot_0070C5E0, 0, LengthOfArray<Uint32>(animation_0070CB80_mkey_67_rot_0070C5E0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbwait1 = { animation_0070CB80_mdat_0070C6F0, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbwait1 = { AMY_OBJECTS[0], &motion_a_sbwait1 };
