/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_00725390_mkey_0_pos_00723520[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 1, 0, -0.7559f, 0 },
	{ 2, 0, -0.814f, 0 },
	{ 3, 0, -0.9042f, 0 },
	{ 4, 0, -1.0213f, 0 },
	{ 5, 0, -1.1598f, 0 },
	{ 6, 0, -1.3143f, 0 },
	{ 7, 0, -1.4796f, 0 },
	{ 8, 0, -1.6502f, 0 },
	{ 9, 0, -1.8209f, 0 },
	{ 10, 0, -1.9862f, 0 },
	{ 11, 0, -2.1407f, 0 },
	{ 12, 0, -2.2792f, 0 },
	{ 13, 0, -2.3962f, 0 },
	{ 14, 0, -2.4865f, 0 },
	{ 15, 0, -2.5446f, 0 },
	{ 16, 0, -2.5651f, 0 }
};

NJS_MKEY_A animation_00725390_mkey_1_rot_00723630[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0xFFFFFF9C, 0xFFFFEAAB, 0x8DA },
	{ 2, 0xFFFFFE7F, 0xFFFFEAAB, 0x9B1 },
	{ 3, 0xFFFFFCC5, 0xFFFFEAAB, 0xB00 },
	{ 4, 0xFFFFFA87, 0xFFFFEAAB, 0xCB1 },
	{ 5, 0xFFFFF7E0, 0xFFFFEAAB, 0xEB2 },
	{ 6, 0xFFFFF4EA, 0xFFFFEAAB, 0x10EF },
	{ 7, 0xFFFFF1C0, 0xFFFFEAAB, 0x1353 },
	{ 8, 0xFFFFEE7C, 0xFFFFEAAB, 0x15CC },
	{ 9, 0xFFFFEB37, 0xFFFFEAAB, 0x1844 },
	{ 10, 0xFFFFE80D, 0xFFFFEAAB, 0x1AA8 },
	{ 11, 0xFFFFE517, 0xFFFFEAAB, 0x1CE5 },
	{ 12, 0xFFFFE270, 0xFFFFEAAB, 0x1EE6 },
	{ 13, 0xFFFFE032, 0xFFFFEAAB, 0x2098 },
	{ 14, 0xFFFFDE78, 0xFFFFEAAB, 0x21E6 },
	{ 15, 0xFFFFDD5B, 0xFFFFEAAB, 0x22BD },
	{ 16, 0xFFFFDCF7, 0xFFFFEAAB, 0x2309 }
};

NJS_MKEY_A animation_00725390_mkey_12_rot_00723740[] = {
	{ 0, 0, 0xFFFFEAC7, 0x8875 },
	{ 1, 0, 0xFFFFEB68, 0x8840 },
	{ 2, 0, 0xFFFFED18, 0x87AD },
	{ 3, 0, 0xFFFFEF81, 0x86CF },
	{ 4, 0, 0xFFFFF24E, 0x85BB },
	{ 5, 0, 0xFFFFF531, 0x8480 },
	{ 6, 0, 0xFFFFF7ED, 0x8325 },
	{ 7, 0, 0xFFFFFA57, 0x81AB },
	{ 8, 0, 0xFFFFFC55, 0x800B },
	{ 9, 0, 0xFFFFFDD6, 0x7E37 },
	{ 10, 0, 0xFFFFFF0B, 0x7B79 },
	{ 11, 0, 0x2A, 0x7794 },
	{ 12, 0, 0x128, 0x732D },
	{ 13, 0, 0x1F5, 0x6EEB },
	{ 14, 0, 0x288, 0x6B5F },
	{ 15, 0, 0x2E0, 0x68FA },
	{ 16, 0, 0x2FD, 0x6817 }
};

NJS_MKEY_A animation_00725390_mkey_15_rot_00723850[] = {
	{ 0, 0, 0xB6A, 0xFFFF87C1 },
	{ 1, 0, 0xC90, 0xFFFF87E8 },
	{ 2, 0, 0xF7B, 0xFFFF882B },
	{ 3, 0, 0x12F4, 0xFFFF883A },
	{ 4, 0, 0x153D, 0xFFFF87E5 },
	{ 5, 0, 0x15F8, 0xFFFF8751 },
	{ 6, 0, 0x15E9, 0xFFFF86D4 },
	{ 7, 0, 0x1562, 0xFFFF869D },
	{ 8, 0, 0x14BC, 0xFFFF86B6 },
	{ 9, 0, 0x1439, 0xFFFF8717 },
	{ 10, 0, 0x13E3, 0xFFFF87C6 },
	{ 11, 0, 0x1392, 0xFFFF889C },
	{ 12, 0, 0x133C, 0xFFFF8957 },
	{ 13, 0, 0x12E2, 0xFFFF89CD },
	{ 14, 0, 0x128E, 0xFFFF89F9 },
	{ 15, 0, 0x124F, 0xFFFF89F7 },
	{ 16, 0, 0x1236, 0xFFFF89F0 }
};

NJS_MKEY_A animation_00725390_mkey_19_rot_00723960[] = {
	{ 0, 0, 0xFFFFF461, 0xFFFF87BF },
	{ 1, 0, 0xFFFFF42F, 0xFFFF87AE },
	{ 2, 0, 0xFFFFF3C1, 0xFFFF878E },
	{ 3, 0, 0xFFFFF36C, 0xFFFF8778 },
	{ 4, 0, 0xFFFFF350, 0xFFFF87B8 },
	{ 5, 0, 0xFFFFF2B0, 0xFFFF8870 },
	{ 6, 0, 0xFFFFF188, 0xFFFF893F },
	{ 7, 0, 0xFFFFF07A, 0xFFFF89D6 },
	{ 8, 0, 0xFFFFF042, 0xFFFF89C9 },
	{ 9, 0, 0xFFFFF18A, 0xFFFF8929 },
	{ 10, 0, 0xFFFFF354, 0xFFFF8799 },
	{ 11, 0, 0xFFFFF454, 0xFFFF85D5 },
	{ 12, 0, 0xFFFFF493, 0xFFFF855F },
	{ 13, 0, 0xFFFFF46C, 0xFFFF860A },
	{ 14, 0, 0xFFFFF42A, 0xFFFF8725 },
	{ 15, 0, 0xFFFFF3F5, 0xFFFF8817 },
	{ 16, 0, 0xFFFFF3E1, 0xFFFF887A }
};

NJS_MKEY_A animation_00725390_mkey_25_rot_00723A70[] = {
	{ 0, 0, 0x2A6D, 0xFFFFE10E },
	{ 1, 0, 0x2A5B, 0xFFFFE051 },
	{ 2, 0, 0x2A21, 0xFFFFDE3E },
	{ 3, 0, 0x29B0, 0xFFFFDB19 },
	{ 4, 0, 0x28F5, 0xFFFFD734 },
	{ 5, 0, 0x27E6, 0xFFFFD2EB },
	{ 6, 0, 0x2682, 0xFFFFCE99 },
	{ 7, 0, 0x24DA, 0xFFFFCA89 },
	{ 8, 0, 0x2306, 0xFFFFC6E8 },
	{ 9, 0, 0x2124, 0xFFFFC3CA },
	{ 10, 0, 0x1F51, 0xFFFFC130 },
	{ 11, 0, 0x1DA5, 0xFFFFBF13 },
	{ 12, 0, 0x1C30, 0xFFFFBD67 },
	{ 13, 0, 0x1AFE, 0xFFFFBC22 },
	{ 14, 0, 0x1A1A, 0xFFFFBB3C },
	{ 15, 0, 0x198B, 0xFFFFBAB0 },
	{ 16, 0, 0x1958, 0xFFFFBA80 }
};

NJS_MKEY_A animation_00725390_mkey_26_rot_00723B80[] = {
	{ 0, 0, 0xD3, 0xFFFFEF92 },
	{ 1, 0, 0x89, 0xFFFFEF7D },
	{ 2, 0, 0xFFFFFFBA, 0xFFFFEF50 },
	{ 3, 0, 0xFFFFFE7D, 0xFFFFEF2F },
	{ 4, 0, 0xFFFFFCF8, 0xFFFFEF41 },
	{ 5, 0, 0xFFFFFB62, 0xFFFFEFA2 },
	{ 6, 0, 0xFFFFF9F1, 0xFFFFF056 },
	{ 7, 0, 0xFFFFF8CC, 0xFFFFF14B },
	{ 8, 0, 0xFFFFF804, 0xFFFFF263 },
	{ 9, 0, 0xFFFFF795, 0xFFFFF380 },
	{ 10, 0, 0xFFFFF76B, 0xFFFFF48B },
	{ 11, 0, 0xFFFFF770, 0xFFFFF577 },
	{ 12, 0, 0xFFFFF790, 0xFFFFF63C },
	{ 13, 0, 0xFFFFF7BA, 0xFFFFF6D6 },
	{ 14, 0, 0xFFFFF7E1, 0xFFFFF747 },
	{ 15, 0, 0xFFFFF7FC, 0xFFFFF78C },
	{ 16, 0, 0xFFFFF806, 0xFFFFF7A4 }
};

NJS_MKEY_A animation_00725390_mkey_27_rot_00723C90[] = {
	{ 0, 0, 0x1E3, 0xFFFFE2EE },
	{ 1, 0, 0x140, 0xFFFFE333 },
	{ 2, 0, 0xFFFFFF87, 0xFFFFE404 },
	{ 3, 0, 0xFFFFFD16, 0xFFFFE56A },
	{ 4, 0, 0xFFFFFA5C, 0xFFFFE76A },
	{ 5, 0, 0xFFFFF7C1, 0xFFFFE9F4 },
	{ 6, 0, 0xFFFFF595, 0xFFFFECDC },
	{ 7, 0, 0xFFFFF3FF, 0xFFFFEFE4 },
	{ 8, 0, 0xFFFFF2FF, 0xFFFFF2D2 },
	{ 9, 0, 0xFFFFF27B, 0xFFFFF575 },
	{ 10, 0, 0xFFFFF250, 0xFFFFF7B8 },
	{ 11, 0, 0xFFFFF25B, 0xFFFFF993 },
	{ 12, 0, 0xFFFFF281, 0xFFFFFB09 },
	{ 13, 0, 0xFFFFF2AF, 0xFFFFFC24 },
	{ 14, 0, 0xFFFFF2D9, 0xFFFFFCEB },
	{ 15, 0, 0xFFFFF2F6, 0xFFFFFD63 },
	{ 16, 0, 0xFFFFF300, 0xFFFFFD8D }
};

NJS_MKEY_A animation_00725390_mkey_30_rot_00723DA0[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_00725390_mkey_32_rot_00723DE0[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 1, 0, 0x1515, 0 },
	{ 2, 0, 0x15F3, 0 },
	{ 3, 0, 0x174C, 0 },
	{ 4, 0, 0x190B, 0 },
	{ 5, 0, 0x1B1C, 0 },
	{ 6, 0, 0x1D6A, 0 },
	{ 7, 0, 0x1FE1, 0 },
	{ 8, 0, 0x226D, 0 },
	{ 9, 0, 0x24F9, 0 },
	{ 10, 0, 0x2770, 0 },
	{ 11, 0, 0x29BE, 0 },
	{ 12, 0, 0x2BCF, 0 },
	{ 13, 0, 0x2D8E, 0 },
	{ 14, 0, 0x2EE7, 0 },
	{ 15, 0, 0x2FC5, 0 },
	{ 16, 0, 0x3013, 0 }
};

NJS_MKEY_A animation_00725390_mkey_31_rot_00723DC0[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_00725390_mkey_36_rot_00723EF0[] = {
	{ 0, 0, 0xFFFFE8F9, 0xFFFFDCAA },
	{ 1, 0, 0xFFFFE8A4, 0xFFFFDCD8 },
	{ 2, 0, 0xFFFFE7B2, 0xFFFFDD5D },
	{ 3, 0, 0xFFFFE636, 0xFFFFDE38 },
	{ 4, 0, 0xFFFFE443, 0xFFFFDF6C },
	{ 5, 0, 0xFFFFE1F0, 0xFFFFE101 },
	{ 6, 0, 0xFFFFDF5C, 0xFFFFE2FE },
	{ 7, 0, 0xFFFFDCA7, 0xFFFFE570 },
	{ 8, 0, 0xFFFFD9FA, 0xFFFFE85B },
	{ 9, 0, 0xFFFFD779, 0xFFFFEBBF },
	{ 10, 0, 0xFFFFD544, 0xFFFFEF8B },
	{ 11, 0, 0xFFFFD371, 0xFFFFF395 },
	{ 12, 0, 0xFFFFD208, 0xFFFFF79D },
	{ 13, 0, 0xFFFFD104, 0xFFFFFB4F },
	{ 14, 0, 0xFFFFD05A, 0xFFFFFE4F },
	{ 15, 0, 0xFFFFCFFB, 0x4C },
	{ 16, 0, 0xFFFFCFDC, 0x103 }
};

NJS_MKEY_A animation_00725390_mkey_37_rot_00724000[] = {
	{ 0, 0, 0xFFFFEE74, 0xFFFFEBF0 },
	{ 1, 0, 0xFFFFEE4D, 0xFFFFEBFB },
	{ 2, 0, 0xFFFFEDE1, 0xFFFFEC20 },
	{ 3, 0, 0xFFFFED40, 0xFFFFEC6D },
	{ 4, 0, 0xFFFFEC79, 0xFFFFECF3 },
	{ 5, 0, 0xFFFFEBA3, 0xFFFFEDC7 },
	{ 6, 0, 0xFFFFEAD1, 0xFFFFEEFA },
	{ 7, 0, 0xFFFFEA18, 0xFFFFF093 },
	{ 8, 0, 0xFFFFE987, 0xFFFFF292 },
	{ 9, 0, 0xFFFFE929, 0xFFFFF4E6 },
	{ 10, 0, 0xFFFFE905, 0xFFFFF773 },
	{ 11, 0, 0xFFFFE91E, 0xFFFFFA0F },
	{ 12, 0, 0xFFFFE96D, 0xFFFFFC89 },
	{ 13, 0, 0xFFFFE9DE, 0xFFFFFEAD },
	{ 14, 0, 0xFFFFEA56, 0x50 },
	{ 15, 0, 0xFFFFEAB2, 0x15A },
	{ 16, 0, 0xFFFFEAD5, 0x1B7 }
};

NJS_MKEY_A animation_00725390_mkey_38_rot_00724110[] = {
	{ 0, 0, 0xFFFFEED4, 0xFFFFECC1 },
	{ 1, 0, 0xFFFFEEAA, 0xFFFFECF5 },
	{ 2, 0, 0xFFFFEE38, 0xFFFFED91 },
	{ 3, 0, 0xFFFFED99, 0xFFFFEE9B },
	{ 4, 0, 0xFFFFECEC, 0xFFFFF01B },
	{ 5, 0, 0xFFFFEC51, 0xFFFFF214 },
	{ 6, 0, 0xFFFFEBE5, 0xFFFFF478 },
	{ 7, 0, 0xFFFFEBC1, 0xFFFFF730 },
	{ 8, 0, 0xFFFFEBF1, 0xFFFFFA16 },
	{ 9, 0, 0xFFFFEC79, 0xFFFFFD03 },
	{ 10, 0, 0xFFFFED53, 0xFFFFFFCB },
	{ 11, 0, 0xFFFFEE6C, 0x247 },
	{ 12, 0, 0xFFFFEFA7, 0x45B },
	{ 13, 0, 0xFFFFF0DC, 0x5F2 },
	{ 14, 0, 0xFFFFF1E1, 0x70B },
	{ 15, 0, 0xFFFFF291, 0x7AF },
	{ 16, 0, 0xFFFFF2D1, 0x7E5 }
};

NJS_MKEY_A animation_00725390_mkey_41_rot_00724220[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0xFFFFFF7A, 0xFFFFFFEF, 0xF },
	{ 2, 0xFFFFFDFD, 0xFFFFFFBD, 0x3A },
	{ 3, 0xFFFFFBAE, 0xFFFFFF70, 0x7D },
	{ 4, 0xFFFFF8AE, 0xFFFFFF0C, 0xD3 },
	{ 5, 0xFFFFF523, 0xFFFFFE96, 0x13A },
	{ 6, 0xFFFFF12D, 0xFFFFFE11, 0x1AD },
	{ 7, 0xFFFFECF2, 0xFFFFFD84, 0x227 },
	{ 8, 0xFFFFE893, 0xFFFFFCF2, 0x2A5 },
	{ 9, 0xFFFFE434, 0xFFFFFC60, 0x324 },
	{ 10, 0xFFFFDFF9, 0xFFFFFBD3, 0x39E },
	{ 11, 0xFFFFDC04, 0xFFFFFB4F, 0x411 },
	{ 12, 0xFFFFD878, 0xFFFFFAD8, 0x478 },
	{ 13, 0xFFFFD579, 0xFFFFFA74, 0x4CE },
	{ 14, 0xFFFFD329, 0xFFFFFA27, 0x511 },
	{ 15, 0xFFFFD1AC, 0xFFFFF9F6, 0x53C },
	{ 16, 0xFFFFD126, 0xFFFFF9E4, 0x54B }
};

NJS_MKEY_A animation_00725390_mkey_43_rot_00724440[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 1, 0xFFFFED8B, 0, 0xFFFFFFE6 },
	{ 2, 0xFFFFED32, 0, 0xFFFFFF99 },
	{ 3, 0xFFFFECA7, 0, 0xFFFFFF23 },
	{ 4, 0xFFFFEBF3, 0, 0xFFFFFE8A },
	{ 5, 0xFFFFEB1E, 0, 0xFFFFFDD4 },
	{ 6, 0xFFFFEA30, 0, 0xFFFFFD09 },
	{ 7, 0xFFFFE931, 0, 0xFFFFFC31 },
	{ 8, 0xFFFFE82B, 0, 0xFFFFFB51 },
	{ 9, 0xFFFFE724, 0, 0xFFFFFA71 },
	{ 10, 0xFFFFE626, 0, 0xFFFFF999 },
	{ 11, 0xFFFFE538, 0, 0xFFFFF8CE },
	{ 12, 0xFFFFE463, 0, 0xFFFFF818 },
	{ 13, 0xFFFFE3AF, 0, 0xFFFFF77F },
	{ 14, 0xFFFFE324, 0, 0xFFFFF709 },
	{ 15, 0xFFFFE2CA, 0, 0xFFFFF6BC },
	{ 16, 0xFFFFE2AB, 0, 0xFFFFF6A2 }
};

NJS_MKEY_A animation_00725390_mkey_42_rot_00724330[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 1, 0, 0xFFFFE36C, 0 },
	{ 2, 0, 0xFFFFE21B, 0 },
	{ 3, 0, 0xFFFFE00E, 0 },
	{ 4, 0, 0xFFFFDD65, 0 },
	{ 5, 0, 0xFFFFDA40, 0 },
	{ 6, 0, 0xFFFFD6BD, 0 },
	{ 7, 0, 0xFFFFD2FC, 0 },
	{ 8, 0, 0xFFFFCF1C, 0 },
	{ 9, 0, 0xFFFFCB3C, 0 },
	{ 10, 0, 0xFFFFC77B, 0 },
	{ 11, 0, 0xFFFFC3F8, 0 },
	{ 12, 0, 0xFFFFC0D3, 0 },
	{ 13, 0, 0xFFFFBE2B, 0 },
	{ 14, 0, 0xFFFFBC1E, 0 },
	{ 15, 0, 0xFFFFBACC, 0 },
	{ 16, 0, 0xFFFFBA55, 0 }
};

NJS_MKEY_A animation_00725390_mkey_46_rot_00724550[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_00725390_mkey_47_rot_00724570[] = {
	{ 0, 0xFFFFFEB9, 0x20C, 0xFFFFB848 },
	{ 1, 0xFFFFFEA2, 0x222, 0xFFFFB7A1 },
	{ 2, 0xFFFFFE5E, 0x261, 0xFFFFB5D9 },
	{ 3, 0xFFFFFDEC, 0x2BE, 0xFFFFB341 },
	{ 4, 0xFFFFFD4B, 0x331, 0xFFFFB020 },
	{ 5, 0xFFFFFC7C, 0x3AF, 0xFFFFACBA },
	{ 6, 0xFFFFFB85, 0x434, 0xFFFFA96B },
	{ 7, 0xFFFFFA68, 0x4B4, 0xFFFFA62B },
	{ 8, 0xFFFFF92B, 0x52C, 0xFFFFA31F },
	{ 9, 0xFFFFF7DA, 0x59A, 0xFFFFA06F },
	{ 10, 0xFFFFF680, 0x5FF, 0xFFFF9E2A },
	{ 11, 0xFFFFF52B, 0x65C, 0xFFFF9C59 },
	{ 12, 0xFFFFF3E8, 0x6AF, 0xFFFF9AF6 },
	{ 13, 0xFFFFF2CB, 0x6F7, 0xFFFF99F9 },
	{ 14, 0xFFFFF1E6, 0x732, 0xFFFF9953 },
	{ 15, 0xFFFFF14F, 0x759, 0xFFFF98F5 },
	{ 16, 0xFFFFF119, 0x767, 0xFFFF98D7 }
};

NJS_MKEY_A animation_00725390_mkey_48_rot_00724680[] = {
	{ 0, 0, 0, 0x171C },
	{ 1, 0, 0, 0x178E },
	{ 2, 0, 0, 0x18C3 },
	{ 3, 0, 0, 0x1A75 },
	{ 4, 0, 0, 0x1C81 },
	{ 5, 0, 0, 0x1EAF },
	{ 6, 0, 0, 0x2061 },
	{ 7, 0, 0, 0x224D },
	{ 8, 0, 0, 0x241E },
	{ 9, 0, 0, 0x25BA },
	{ 10, 0, 0, 0x271A },
	{ 11, 0, 0, 0x2838 },
	{ 12, 0, 0, 0x291C },
	{ 13, 0, 0, 0x29C5 },
	{ 14, 0, 0, 0x2A3A },
	{ 15, 0, 0, 0x2A7E },
	{ 16, 0, 0, 0x2A95 }
};

NJS_MKEY_A animation_00725390_mkey_49_rot_00724790[] = {
	{ 0, 0, 0, 0x1536 },
	{ 1, 0, 0, 0x15BC },
	{ 2, 0, 0, 0x1727 },
	{ 3, 0, 0, 0x193B },
	{ 4, 0, 0, 0x1BA4 },
	{ 5, 0, 0, 0x1E34 },
	{ 6, 0, 0, 0x2141 },
	{ 7, 0, 0, 0x23C9 },
	{ 8, 0, 0, 0x2626 },
	{ 9, 0, 0, 0x2842 },
	{ 10, 0, 0, 0x2A14 },
	{ 11, 0, 0, 0x2B99 },
	{ 12, 0, 0, 0x2CCA },
	{ 13, 0, 0, 0x2DAF },
	{ 14, 0, 0, 0x2E4D },
	{ 15, 0, 0, 0x2EA9 },
	{ 16, 0, 0, 0x2EC8 }
};

NJS_MKEY_A animation_00725390_mkey_52_rot_007248A0[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFD539 },
	{ 1, 0x1C1C, 0xFFFFF7C1, 0xFFFFD4DD },
	{ 2, 0x1C1C, 0xFFFFF888, 0xFFFFD3EE },
	{ 3, 0x1C1C, 0xFFFFF990, 0xFFFFD2A5 },
	{ 4, 0x1C1C, 0xFFFFFAA3, 0xFFFFD13A },
	{ 5, 0x1C1C, 0xFFFFFB8A, 0xFFFFCFE4 },
	{ 6, 0x1C1C, 0xFFFFFC0E, 0xFFFFCEDB },
	{ 7, 0x1C1C, 0xFFFFFBF8, 0xFFFFCE58 },
	{ 8, 0x1C1C, 0xFFFFFB33, 0xFFFFCE57 },
	{ 9, 0x1C1C, 0xFFFFF9EB, 0xFFFFCEA3 },
	{ 10, 0x1C1C, 0xFFFFF849, 0xFFFFCF26 },
	{ 11, 0x1C1C, 0xFFFFF675, 0xFFFFCFCD },
	{ 12, 0x1C1C, 0xFFFFF49B, 0xFFFFD084 },
	{ 13, 0x1C1C, 0xFFFFF2E1, 0xFFFFD135 },
	{ 14, 0x1C1C, 0xFFFFF173, 0xFFFFD1CD },
	{ 15, 0x1C1C, 0xFFFFF079, 0xFFFFD237 },
	{ 16, 0x1C1C, 0xFFFFF01D, 0xFFFFD25F }
};

NJS_MKEY_A animation_00725390_mkey_57_rot_007249B0[] = {
	{ 0, 0x652, 0xFFFFF8A1, 0xFFFF8534 },
	{ 1, 0x656, 0xFFFFF8B7, 0xFFFF849B },
	{ 2, 0x666, 0xFFFFF8EF, 0xFFFF82F0 },
	{ 3, 0x686, 0xFFFFF935, 0xFFFF806B },
	{ 4, 0x6C4, 0xFFFFF973, 0xFFFF7D47 },
	{ 5, 0x72F, 0xFFFFF993, 0xFFFF79C8 },
	{ 6, 0x7E1, 0xFFFFF98A, 0xFFFF760F },
	{ 7, 0x8E4, 0xFFFFF94A, 0xFFFF727B },
	{ 8, 0xA4F, 0xFFFFF8E0, 0xFFFF6F0B },
	{ 9, 0xC1B, 0xFFFFF853, 0xFFFF6C04 },
	{ 10, 0xE39, 0xFFFFF7B1, 0xFFFF698D },
	{ 11, 0x1088, 0xFFFFF70D, 0xFFFF67BE },
	{ 12, 0x12DB, 0xFFFFF675, 0xFFFF669F },
	{ 13, 0x14FC, 0xFFFFF5F5, 0xFFFF661E },
	{ 14, 0x16B6, 0xFFFFF595, 0xFFFF6610 },
	{ 15, 0x17D9, 0xFFFFF559, 0xFFFF6634 },
	{ 16, 0x1841, 0xFFFFF544, 0xFFFF664A }
};

NJS_MKEY_A animation_00725390_mkey_58_rot_00724AC0[] = {
	{ 0, 0, 0, 0x1908 },
	{ 1, 0, 0, 0x194A },
	{ 2, 0, 0, 0x1A02 },
	{ 3, 0, 0, 0x1B13 },
	{ 4, 0, 0, 0x1C5F },
	{ 5, 0, 0, 0x1DCA },
	{ 6, 0, 0, 0x1F4F },
	{ 7, 0, 0, 0x208A },
	{ 8, 0, 0, 0x21FD },
	{ 9, 0, 0, 0x2357 },
	{ 10, 0, 0, 0x2493 },
	{ 11, 0, 0, 0x25A5 },
	{ 12, 0, 0, 0x268C },
	{ 13, 0, 0, 0x2741 },
	{ 14, 0, 0, 0x27C3 },
	{ 15, 0, 0, 0x2812 },
	{ 16, 0, 0, 0x282D }
};

NJS_MKEY_A animation_00725390_mkey_59_rot_00724BD0[] = {
	{ 0, 0, 0, 0x21B8 },
	{ 1, 0, 0, 0x2216 },
	{ 2, 0, 0, 0x2318 },
	{ 3, 0, 0, 0x2499 },
	{ 4, 0, 0, 0x2676 },
	{ 5, 0, 0, 0x287A },
	{ 6, 0, 0, 0x2AA6 },
	{ 7, 0, 0, 0x2D1C },
	{ 8, 0, 0, 0x2F46 },
	{ 9, 0, 0, 0x3154 },
	{ 10, 0, 0, 0x3333 },
	{ 11, 0, 0, 0x34DB },
	{ 12, 0, 0, 0x363D },
	{ 13, 0, 0, 0x3754 },
	{ 14, 0, 0, 0x381C },
	{ 15, 0, 0, 0x3896 },
	{ 16, 0, 0, 0x38C0 }
};

NJS_MKEY_A animation_00725390_mkey_62_rot_00724CE0[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF843 },
	{ 1, 0x1099, 0x473, 0xFFFFF80B },
	{ 2, 0x1059, 0x5A2, 0xFFFFF776 },
	{ 3, 0x1011, 0x744, 0xFFFFF6A1 },
	{ 4, 0xFDB, 0x910, 0xFFFFF5A6 },
	{ 5, 0xFD2, 0xABF, 0xFFFFF4A1 },
	{ 6, 0x1011, 0xC08, 0xFFFFF3B0 },
	{ 7, 0x10B4, 0xCA5, 0xFFFFF2EC },
	{ 8, 0x11DD, 0xC96, 0xFFFFF241 },
	{ 9, 0x1380, 0xC20, 0xFFFFF18A },
	{ 10, 0x1573, 0xB60, 0xFFFFF0D1 },
	{ 11, 0x178C, 0xA72, 0xFFFFF01E },
	{ 12, 0x19A2, 0x970, 0xFFFFEF78 },
	{ 13, 0x1B8B, 0x877, 0xFFFFEEE8 },
	{ 14, 0x1D1B, 0x7A3, 0xFFFFEE77 },
	{ 15, 0x1E2A, 0x70F, 0xFFFFEE2E },
	{ 16, 0x1E8E, 0x6D8, 0xFFFFEE13 }
};

NJS_MKEY_A animation_00725390_mkey_67_rot_00724DF0[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0xFFFFFFF6, 0xFFFFE545 },
	{ 2, 0, 0xFFFFFFE0, 0xFFFFE66C },
	{ 3, 0, 0xFFFFFFCF, 0xFFFFE80C },
	{ 4, 0, 0xFFFFFFD2, 0xFFFFE9E2 },
	{ 5, 0, 0xFFFFFFFB, 0xFFFFEBA6 },
	{ 6, 0, 0x5D, 0xFFFFED07 },
	{ 7, 0, 0x10A, 0xFFFFEDB1 },
	{ 8, 0, 0x228, 0xFFFFEDA0 },
	{ 9, 0, 0x3BA, 0xFFFFED19 },
	{ 10, 0, 0x5A1, 0xFFFFEC34 },
	{ 11, 0, 0x7B4, 0xFFFFEB0E },
	{ 12, 0, 0x9CA, 0xFFFFE9C5 },
	{ 13, 0, 0xBB2, 0xFFFFE87D },
	{ 14, 0, 0xD40, 0xFFFFE75F },
	{ 15, 0, 0xE4B, 0xFFFFE694 },
	{ 16, 0, 0xEAC, 0xFFFFE647 }
};

NJS_MDATA2 animation_00725390_mdat_00724F00[] = {
	{ animation_00725390_mkey_0_pos_00723520, NULL, LengthOfArray<Uint32>(animation_00725390_mkey_0_pos_00723520), 0 },
	{ NULL, animation_00725390_mkey_1_rot_00723630, 0, LengthOfArray<Uint32>(animation_00725390_mkey_1_rot_00723630) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_12_rot_00723740, 0, LengthOfArray<Uint32>(animation_00725390_mkey_12_rot_00723740) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_15_rot_00723850, 0, LengthOfArray<Uint32>(animation_00725390_mkey_15_rot_00723850) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_19_rot_00723960, 0, LengthOfArray<Uint32>(animation_00725390_mkey_19_rot_00723960) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_25_rot_00723A70, 0, LengthOfArray<Uint32>(animation_00725390_mkey_25_rot_00723A70) },
	{ NULL, animation_00725390_mkey_26_rot_00723B80, 0, LengthOfArray<Uint32>(animation_00725390_mkey_26_rot_00723B80) },
	{ NULL, animation_00725390_mkey_27_rot_00723C90, 0, LengthOfArray<Uint32>(animation_00725390_mkey_27_rot_00723C90) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_30_rot_00723DA0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_30_rot_00723DA0) },
	{ NULL, animation_00725390_mkey_32_rot_00723DE0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_32_rot_00723DE0) },
	{ NULL, animation_00725390_mkey_31_rot_00723DC0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_31_rot_00723DC0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_36_rot_00723EF0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_36_rot_00723EF0) },
	{ NULL, animation_00725390_mkey_37_rot_00724000, 0, LengthOfArray<Uint32>(animation_00725390_mkey_37_rot_00724000) },
	{ NULL, animation_00725390_mkey_38_rot_00724110, 0, LengthOfArray<Uint32>(animation_00725390_mkey_38_rot_00724110) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_41_rot_00724220, 0, LengthOfArray<Uint32>(animation_00725390_mkey_41_rot_00724220) },
	{ NULL, animation_00725390_mkey_43_rot_00724440, 0, LengthOfArray<Uint32>(animation_00725390_mkey_43_rot_00724440) },
	{ NULL, animation_00725390_mkey_42_rot_00724330, 0, LengthOfArray<Uint32>(animation_00725390_mkey_42_rot_00724330) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_46_rot_00724550, 0, LengthOfArray<Uint32>(animation_00725390_mkey_46_rot_00724550) },
	{ NULL, animation_00725390_mkey_47_rot_00724570, 0, LengthOfArray<Uint32>(animation_00725390_mkey_47_rot_00724570) },
	{ NULL, animation_00725390_mkey_48_rot_00724680, 0, LengthOfArray<Uint32>(animation_00725390_mkey_48_rot_00724680) },
	{ NULL, animation_00725390_mkey_49_rot_00724790, 0, LengthOfArray<Uint32>(animation_00725390_mkey_49_rot_00724790) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_52_rot_007248A0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_52_rot_007248A0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_57_rot_007249B0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_57_rot_007249B0) },
	{ NULL, animation_00725390_mkey_58_rot_00724AC0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_58_rot_00724AC0) },
	{ NULL, animation_00725390_mkey_59_rot_00724BD0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_59_rot_00724BD0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_62_rot_00724CE0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_62_rot_00724CE0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00725390_mkey_67_rot_00724DF0, 0, LengthOfArray<Uint32>(animation_00725390_mkey_67_rot_00724DF0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbright0 = { animation_00725390_mdat_00724F00, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbright0 = { AMY_OBJECTS[0], &motion_a_sbright0 };
