/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_00719A78_mkey_0_pos_00718004[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 16, 0, -0.7354f, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_1_rot_00718028[] = {
	{ 0, 0, 0xFFFFD169, 0xFFFFEC0A },
	{ 1, 0, 0xFFFFD1B1, 0xFFFFEC5C },
	{ 2, 0, 0xFFFFD27E, 0xFFFFED43 },
	{ 3, 0, 0xFFFFD3BD, 0xFFFFEEAB },
	{ 4, 0, 0xFFFFD55B, 0xFFFFF07E },
	{ 5, 0, 0xFFFFD744, 0xFFFFF2A7 },
	{ 6, 0, 0xFFFFD967, 0xFFFFF510 },
	{ 7, 0, 0xFFFFDBAF, 0xFFFFF7A3 },
	{ 8, 0, 0xFFFFDE0A, 0xFFFFFA4C },
	{ 9, 0, 0xFFFFE065, 0xFFFFFCF5 },
	{ 10, 0, 0xFFFFE2AD, 0xFFFFFF89 },
	{ 11, 0, 0xFFFFE4CF, 0x1F0 },
	{ 12, 0, 0xFFFFE6B9, 0x419 },
	{ 13, 0, 0xFFFFE856, 0x5EC },
	{ 14, 0, 0xFFFFE995, 0x754 },
	{ 15, 0, 0xFFFFEA63, 0x83C },
	{ 16, 0, 0xFFFFEAAB, 0x88E }
};

NJS_MKEY_A animation_00719A78_mkey_12_rot_00718138[] = {
	{ 0, 0, 0xFFFFEB55, 0x7326 },
	{ 1, 0, 0xFFFFEB4F, 0x7354 },
	{ 2, 0, 0xFFFFEB3D, 0x73D7 },
	{ 3, 0, 0xFFFFEB22, 0x74A9 },
	{ 4, 0, 0xFFFFEB00, 0x75C2 },
	{ 5, 0, 0xFFFFEADC, 0x771E },
	{ 6, 0, 0xFFFFEAB7, 0x78B6 },
	{ 7, 0, 0xFFFFEA97, 0x7A82 },
	{ 8, 0, 0xFFFFEA7D, 0x7C75 },
	{ 9, 0, 0xFFFFEA6E, 0x7E82 },
	{ 10, 0, 0xFFFFEA6A, 0x8095 },
	{ 11, 0, 0xFFFFEA72, 0x829A },
	{ 12, 0, 0xFFFFEA82, 0x8477 },
	{ 13, 0, 0xFFFFEA99, 0x8614 },
	{ 14, 0, 0xFFFFEAAF, 0x8758 },
	{ 15, 0, 0xFFFFEAC0, 0x882A },
	{ 16, 0, 0xFFFFEAC7, 0x8875 }
};

NJS_MKEY_A animation_00719A78_mkey_15_rot_00718248[] = {
	{ 0, 0, 0xC4F, 0xFFFF8745 },
	{ 1, 0, 0xC4D, 0xFFFF8767 },
	{ 2, 0, 0xC46, 0xFFFF87C1 },
	{ 3, 0, 0xC3C, 0xFFFF8845 },
	{ 4, 0, 0xC2F, 0xFFFF88DD },
	{ 5, 0, 0xC22, 0xFFFF8974 },
	{ 6, 0, 0xC15, 0xFFFF89F6 },
	{ 7, 0, 0xC09, 0xFFFF8A53 },
	{ 8, 0, 0xBFD, 0xFFFF8A7E },
	{ 9, 0, 0xBF0, 0xFFFF8A71 },
	{ 10, 0, 0xBE0, 0xFFFF8A30 },
	{ 11, 0, 0xBCC, 0xFFFF89C5 },
	{ 12, 0, 0xBB5, 0xFFFF893F },
	{ 13, 0, 0xB9B, 0xFFFF88B4 },
	{ 14, 0, 0xB83, 0xFFFF8838 },
	{ 15, 0, 0xB71, 0xFFFF87E1 },
	{ 16, 0, 0xB6A, 0xFFFF87C1 }
};

NJS_MKEY_A animation_00719A78_mkey_19_rot_00718358[] = {
	{ 0, 0, 0xFFFFF330, 0xFFFF86D5 },
	{ 1, 0, 0xFFFFF331, 0xFFFF86F0 },
	{ 2, 0, 0xFFFFF334, 0xFFFF873B },
	{ 3, 0, 0xFFFFF33C, 0xFFFF87A8 },
	{ 4, 0, 0xFFFFF34B, 0xFFFF8826 },
	{ 5, 0, 0xFFFFF362, 0xFFFF88A5 },
	{ 6, 0, 0xFFFFF381, 0xFFFF8914 },
	{ 7, 0, 0xFFFFF3A8, 0xFFFF8966 },
	{ 8, 0, 0xFFFFF3D2, 0xFFFF8992 },
	{ 9, 0, 0xFFFFF3FC, 0xFFFF8995 },
	{ 10, 0, 0xFFFFF422, 0xFFFF896F },
	{ 11, 0, 0xFFFFF440, 0xFFFF8929 },
	{ 12, 0, 0xFFFFF453, 0xFFFF88CD },
	{ 13, 0, 0xFFFFF45E, 0xFFFF886C },
	{ 14, 0, 0xFFFFF462, 0xFFFF8814 },
	{ 15, 0, 0xFFFFF462, 0xFFFF87D6 },
	{ 16, 0, 0xFFFFF461, 0xFFFF87BF }
};

NJS_MKEY_A animation_00719A78_mkey_25_rot_00718468[] = {
	{ 0, 0, 0x2F56, 0xFFFFCDD9 },
	{ 1, 0, 0x2FA9, 0xFFFFCE5D },
	{ 2, 0, 0x3080, 0xFFFFCFDE },
	{ 3, 0, 0x31A9, 0xFFFFD26C },
	{ 4, 0, 0x32E5, 0xFFFFD618 },
	{ 5, 0, 0x33EC, 0xFFFFDAB1 },
	{ 6, 0, 0x347A, 0xFFFFDF5A },
	{ 7, 0, 0x3464, 0xFFFFE284 },
	{ 8, 0, 0x33AE, 0xFFFFE3D2 },
	{ 9, 0, 0x3285, 0xFFFFE42A },
	{ 10, 0, 0x3115, 0xFFFFE3E4 },
	{ 11, 0, 0x2F85, 0xFFFFE34F },
	{ 12, 0, 0x2DF9, 0xFFFFE2A5 },
	{ 13, 0, 0x2C94, 0xFFFFE206 },
	{ 14, 0, 0x2B73, 0xFFFFE185 },
	{ 15, 0, 0x2AB3, 0xFFFFE12E },
	{ 16, 0, 0x2A6D, 0xFFFFE10E }
};

NJS_MKEY_A animation_00719A78_mkey_26_rot_00718578[] = {
	{ 0, 0, 0xFFFFFC9C, 0xFFFFEFA0 },
	{ 1, 0, 0xFFFFFCE0, 0xFFFFEF71 },
	{ 2, 0, 0xFFFFFDAE, 0xFFFFEEFA },
	{ 3, 0, 0xFFFFFF15, 0xFFFFEE64 },
	{ 4, 0, 0x123, 0xFFFFEDE7 },
	{ 5, 0, 0x3B2, 0xFFFFEDC6 },
	{ 6, 0, 0x62B, 0xFFFFEE19 },
	{ 7, 0, 0x79E, 0xFFFFEE89 },
	{ 8, 0, 0x7D0, 0xFFFFEEBF },
	{ 9, 0, 0x744, 0xFFFFEECE },
	{ 10, 0, 0x63A, 0xFFFFEECE },
	{ 11, 0, 0x4F3, 0xFFFFEED9 },
	{ 12, 0, 0x3A8, 0xFFFFEEF8 },
	{ 13, 0, 0x282, 0xFFFFEF27 },
	{ 14, 0, 0x19C, 0xFFFFEF5A },
	{ 15, 0, 0x108, 0xFFFFEF82 },
	{ 16, 0, 0xD3, 0xFFFFEF92 }
};

NJS_MKEY_A animation_00719A78_mkey_27_rot_00718688[] = {
	{ 0, 0, 0xFFFFFC83, 0xFFFFEA9F },
	{ 1, 0, 0xFFFFFCD2, 0xFFFFEA3C },
	{ 2, 0, 0xFFFFFDC2, 0xFFFFE933 },
	{ 3, 0, 0xFFFFFF72, 0xFFFFE7B7 },
	{ 4, 0, 0x208, 0xFFFFE60F },
	{ 5, 0, 0x571, 0xFFFFE498 },
	{ 6, 0, 0x902, 0xFFFFE399 },
	{ 7, 0, 0xB5A, 0xFFFFE2FF },
	{ 8, 0, 0xBF2, 0xFFFFE26A },
	{ 9, 0, 0xB6E, 0xFFFFE1C3 },
	{ 10, 0, 0xA16, 0xFFFFE140 },
	{ 11, 0, 0x844, 0xFFFFE111 },
	{ 12, 0, 0x653, 0xFFFFE140 },
	{ 13, 0, 0x48B, 0xFFFFE1B7 },
	{ 14, 0, 0x322, 0xFFFFE247 },
	{ 15, 0, 0x237, 0xFFFFE2BE },
	{ 16, 0, 0x1E3, 0xFFFFE2EE }
};

NJS_MKEY_A animation_00719A78_mkey_30_rot_00718798[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 16, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_32_rot_007187D8[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 16, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_31_rot_007187B8[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_00719A78_mkey_36_rot_007187F8[] = {
	{ 0, 0, 0xFFFFF5E3, 0xFFFFE2A1 },
	{ 1, 0, 0xFFFFF56B, 0xFFFFE31C },
	{ 2, 0, 0xFFFFF42F, 0xFFFFE462 },
	{ 3, 0, 0xFFFFF26E, 0xFFFFE634 },
	{ 4, 0, 0xFFFFF06D, 0xFFFFE850 },
	{ 5, 0, 0xFFFFEE72, 0xFFFFEA63 },
	{ 6, 0, 0xFFFFECBF, 0xFFFFEC0C },
	{ 7, 0, 0xFFFFEB93, 0xFFFFECD5 },
	{ 8, 0, 0xFFFFEAD1, 0xFFFFECA3 },
	{ 9, 0, 0xFFFFEA29, 0xFFFFEBBA },
	{ 10, 0, 0xFFFFE999, 0xFFFFEA25 },
	{ 11, 0, 0xFFFFE927, 0xFFFFE7F3 },
	{ 12, 0, 0xFFFFE8DB, 0xFFFFE542 },
	{ 13, 0, 0xFFFFE8BC, 0xFFFFE252 },
	{ 14, 0, 0xFFFFE8C7, 0xFFFFDF8C },
	{ 15, 0, 0xFFFFE8E7, 0xFFFFDD79 },
	{ 16, 0, 0xFFFFE8F9, 0xFFFFDCAA }
};

NJS_MKEY_A animation_00719A78_mkey_37_rot_00718908[] = {
	{ 0, 0, 0xFFFFF2CE, 0xFFFFE3BE },
	{ 1, 0, 0xFFFFF231, 0xFFFFE407 },
	{ 2, 0, 0xFFFFF084, 0xFFFFE4F8 },
	{ 3, 0, 0xFFFFEE08, 0xFFFFE6D8 },
	{ 4, 0, 0xFFFFEB35, 0xFFFFE9DA },
	{ 5, 0, 0xFFFFE8B5, 0xFFFFEDBB },
	{ 6, 0, 0xFFFFE70F, 0xFFFFF189 },
	{ 7, 0, 0xFFFFE659, 0xFFFFF3EA },
	{ 8, 0, 0xFFFFE639, 0xFFFFF495 },
	{ 9, 0, 0xFFFFE667, 0xFFFFF445 },
	{ 10, 0, 0xFFFFE6E9, 0xFFFFF328 },
	{ 11, 0, 0xFFFFE7D2, 0xFFFFF183 },
	{ 12, 0, 0xFFFFE92A, 0xFFFFEFAC },
	{ 13, 0, 0xFFFFEAD9, 0xFFFFEE04 },
	{ 14, 0, 0xFFFFEC93, 0xFFFFECD1 },
	{ 15, 0, 0xFFFFEDEC, 0xFFFFEC26 },
	{ 16, 0, 0xFFFFEE74, 0xFFFFEBF0 }
};

NJS_MKEY_A animation_00719A78_mkey_38_rot_00718A18[] = {
	{ 0, 0, 0xFFFFFDE3, 0xFFFFE5AA },
	{ 1, 0, 0xFFFFFCE6, 0xFFFFE53A },
	{ 2, 0, 0xFFFFF9E6, 0xFFFFE44F },
	{ 3, 0, 0xFFFFF4A0, 0xFFFFE3E5 },
	{ 4, 0, 0xFFFFED73, 0xFFFFE59C },
	{ 5, 0, 0xFFFFE66D, 0xFFFFEAE9 },
	{ 6, 0, 0xFFFFE245, 0xFFFFF293 },
	{ 7, 0, 0xFFFFE12F, 0xFFFFF804 },
	{ 8, 0, 0xFFFFE158, 0xFFFFF9AC },
	{ 9, 0, 0xFFFFE1E8, 0xFFFFF938 },
	{ 10, 0, 0xFFFFE2E3, 0xFFFFF735 },
	{ 11, 0, 0xFFFFE47A, 0xFFFFF453 },
	{ 12, 0, 0xFFFFE6C1, 0xFFFFF161 },
	{ 13, 0, 0xFFFFE97A, 0xFFFFEF0C },
	{ 14, 0, 0xFFFFEC1F, 0xFFFFED9B },
	{ 15, 0, 0xFFFFEE14, 0xFFFFECEF },
	{ 16, 0, 0xFFFFEED4, 0xFFFFECC1 }
};

NJS_MKEY_A animation_00719A78_mkey_43_rot_00718B48[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_42_rot_00718B28[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 16, 0, 0xFFFFE3E4, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_46_rot_00718B68[] = {
	{ 0, 0, 0xFFFFEA72, 0 },
	{ 1, 0, 0xFFFFEA87, 0 },
	{ 2, 0, 0xFFFFEAC3, 0 },
	{ 3, 0, 0xFFFFEB1F, 0 },
	{ 4, 0, 0xFFFFEB98, 0 },
	{ 5, 0, 0xFFFFEC26, 0 },
	{ 6, 0, 0xFFFFECC4, 0 },
	{ 7, 0, 0xFFFFED6E, 0 },
	{ 8, 0, 0xFFFFEE1D, 0 },
	{ 9, 0, 0xFFFFEECC, 0 },
	{ 10, 0, 0xFFFFEF76, 0 },
	{ 11, 0, 0xFFFFF014, 0 },
	{ 12, 0, 0xFFFFF0A2, 0 },
	{ 13, 0, 0xFFFFF11A, 0 },
	{ 14, 0, 0xFFFFF177, 0 },
	{ 15, 0, 0xFFFFF1B3, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_47_rot_00718C78[] = {
	{ 0, 0xFFFFD497, 0x2088, 0xFFFF9C80 },
	{ 1, 0xFFFFD550, 0x2054, 0xFFFF9DB4 },
	{ 2, 0xFFFFD75B, 0x1FB8, 0xFFFFA0D2 },
	{ 3, 0xFFFFDA7A, 0x1EAD, 0xFFFFA4F7 },
	{ 4, 0xFFFFDE5E, 0x1D29, 0xFFFFA961 },
	{ 5, 0xFFFFE2B3, 0x1B2C, 0xFFFFAD8F },
	{ 6, 0xFFFFE729, 0x18BD, 0xFFFFB137 },
	{ 7, 0xFFFFEB7F, 0x15F2, 0xFFFFB431 },
	{ 8, 0xFFFFEF88, 0x12E9, 0xFFFFB66F },
	{ 9, 0xFFFFF325, 0xFC6, 0xFFFFB7F9 },
	{ 10, 0xFFFFF648, 0xCAE, 0xFFFFB8E0 },
	{ 11, 0xFFFFF8E9, 0x9C8, 0xFFFFB940 },
	{ 12, 0xFFFFFB06, 0x733, 0xFFFFB93A },
	{ 13, 0xFFFFFCA6, 0x50E, 0xFFFFB8F9 },
	{ 14, 0xFFFFFDCB, 0x36E, 0xFFFFB8A2 },
	{ 15, 0xFFFFFE7C, 0x267, 0xFFFFB85A },
	{ 16, 0xFFFFFEB9, 0x20B, 0xFFFFB83E }
};

NJS_MKEY_A animation_00719A78_mkey_48_rot_00718D88[] = {
	{ 0, 0, 0, 0x1CA5 },
	{ 2, 0, 0, 0x1CA1 },
	{ 3, 0, 0, 0x1C96 },
	{ 4, 0, 0, 0x1C7C },
	{ 5, 0, 0, 0x1C4E },
	{ 6, 0, 0, 0x1C06 },
	{ 7, 0, 0, 0x1BA3 },
	{ 8, 0, 0, 0x1B25 },
	{ 9, 0, 0, 0x1A91 },
	{ 10, 0, 0, 0x19EE },
	{ 11, 0, 0, 0x1943 },
	{ 12, 0, 0, 0x18A6 },
	{ 13, 0, 0, 0x180F },
	{ 14, 0, 0, 0x1794 },
	{ 15, 0, 0, 0x1743 },
	{ 16, 0, 0, 0x1725 }
};

NJS_MKEY_A animation_00719A78_mkey_49_rot_00718E88[] = {
	{ 0, 0, 0, 0x1BCE },
	{ 2, 0, 0, 0x1BCA },
	{ 3, 0, 0, 0x1BBD },
	{ 4, 0, 0, 0x1B9E },
	{ 5, 0, 0, 0x1B68 },
	{ 6, 0, 0, 0x1B13 },
	{ 7, 0, 0, 0x1A9F },
	{ 8, 0, 0, 0x1A0B },
	{ 9, 0, 0, 0x195C },
	{ 10, 0, 0, 0x189B },
	{ 11, 0, 0, 0x17D2 },
	{ 12, 0, 0, 0x1705 },
	{ 13, 0, 0, 0x1653 },
	{ 14, 0, 0, 0x15C3 },
	{ 15, 0, 0, 0x1563 },
	{ 16, 0, 0, 0x1541 }
};

NJS_MKEY_A animation_00719A78_mkey_52_rot_00718F88[] = {
	{ 0, 0x1C1C, 0xFFFFEA68, 0xFFFFE930 },
	{ 1, 0x1C1C, 0xFFFFEA8E, 0xFFFFE8F6 },
	{ 2, 0x1C1C, 0xFFFFEAF8, 0xFFFFE854 },
	{ 3, 0x1C1C, 0xFFFFEB9D, 0xFFFFE758 },
	{ 4, 0x1C1C, 0xFFFFEC72, 0xFFFFE611 },
	{ 5, 0x1C1C, 0xFFFFED6F, 0xFFFFE48E },
	{ 6, 0x1C1C, 0xFFFFEE89, 0xFFFFE2DE },
	{ 7, 0x1C1C, 0xFFFFEFB6, 0xFFFFE111 },
	{ 8, 0x1C1C, 0xFFFFF0ED, 0xFFFFDF34 },
	{ 9, 0x1C1C, 0xFFFFF225, 0xFFFFDD58 },
	{ 10, 0x1C1C, 0xFFFFF352, 0xFFFFDB8A },
	{ 11, 0x1C1C, 0xFFFFF46C, 0xFFFFD9DA },
	{ 12, 0x1C1C, 0xFFFFF569, 0xFFFFD857 },
	{ 13, 0x1C1C, 0xFFFFF63E, 0xFFFFD710 },
	{ 14, 0x1C1C, 0xFFFFF6E3, 0xFFFFD614 },
	{ 15, 0x1C1C, 0xFFFFF74D, 0xFFFFD572 },
	{ 16, 0x1C1C, 0xFFFFF772, 0xFFFFD539 }
};

NJS_MKEY_A animation_00719A78_mkey_56_rot_00719098[] = {
	{ 0, 0, 0xE38, 0 },
	{ 1, 0, 0xE0F, 0 },
	{ 2, 0, 0xD9C, 0 },
	{ 3, 0, 0xCE8, 0 },
	{ 4, 0, 0xBFF, 0 },
	{ 5, 0, 0xAEC, 0 },
	{ 6, 0, 0x9B8, 0 },
	{ 7, 0, 0x86F, 0 },
	{ 8, 0, 0x71C, 0 },
	{ 9, 0, 0x5C8, 0 },
	{ 10, 0, 0x47F, 0 },
	{ 11, 0, 0x34C, 0 },
	{ 12, 0, 0x238, 0 },
	{ 13, 0, 0x14F, 0 },
	{ 14, 0, 0x9C, 0 },
	{ 15, 0, 0x28, 0 },
	{ 16, 0, 0, 0 }
};

NJS_MKEY_A animation_00719A78_mkey_57_rot_007191A8[] = {
	{ 0, 0xFFFFFB8A, 0x542, 0xFFFFAABF },
	{ 1, 0xFFFFFBB5, 0x50A, 0xFFFFAA55 },
	{ 2, 0xFFFFFC31, 0x46B, 0xFFFFA927 },
	{ 3, 0xFFFFFCF2, 0x37C, 0xFFFFA74F },
	{ 4, 0xFFFFFDED, 0x252, 0xFFFFA4E5 },
	{ 5, 0xFFFFFF14, 0x103, 0xFFFFA203 },
	{ 6, 0x53, 0xFFFFFFA6, 0xFFFF9EC0 },
	{ 7, 0x199, 0xFFFFFE4D, 0xFFFF9B3D },
	{ 8, 0x2CF, 0xFFFFFD0A, 0xFFFF9797 },
	{ 9, 0x3E1, 0xFFFFFBE8, 0xFFFF93F5 },
	{ 10, 0x4C1, 0xFFFFFAF1, 0xFFFF907C },
	{ 11, 0x569, 0xFFFFFA29, 0xFFFF8D4E },
	{ 12, 0x5DB, 0xFFFFF98F, 0xFFFF8A8B },
	{ 13, 0x61E, 0xFFFFF921, 0xFFFF884A },
	{ 14, 0x640, 0xFFFFF8D8, 0xFFFF869D },
	{ 15, 0x64E, 0xFFFFF8AE, 0xFFFF8591 },
	{ 16, 0x652, 0xFFFFF8A1, 0xFFFF8534 }
};

NJS_MKEY_A animation_00719A78_mkey_58_rot_007192B8[] = {
	{ 0, 0, 0, 0x18FA },
	{ 1, 0, 0, 0x1910 },
	{ 2, 0, 0, 0x194C },
	{ 3, 0, 0, 0x19A2 },
	{ 4, 0, 0, 0x1A05 },
	{ 5, 0, 0, 0x1A66 },
	{ 6, 0, 0, 0x1AB9 },
	{ 7, 0, 0, 0x1AF2 },
	{ 8, 0, 0, 0x1B0A },
	{ 9, 0, 0, 0x1AFD },
	{ 10, 0, 0, 0x1ACD },
	{ 11, 0, 0, 0x1A80 },
	{ 12, 0, 0, 0x1A1F },
	{ 13, 0, 0, 0x19BA },
	{ 14, 0, 0, 0x1960 },
	{ 15, 0, 0, 0x191F },
	{ 16, 0, 0, 0x1908 }
};

NJS_MKEY_A animation_00719A78_mkey_59_rot_007193C8[] = {
	{ 0, 0, 0, 0x21A5 },
	{ 1, 0, 0, 0x21C4 },
	{ 2, 0, 0, 0x2219 },
	{ 3, 0, 0, 0x2292 },
	{ 4, 0, 0, 0x231D },
	{ 5, 0, 0, 0x23A6 },
	{ 6, 0, 0, 0x241A },
	{ 7, 0, 0, 0x246B },
	{ 8, 0, 0, 0x248C },
	{ 9, 0, 0, 0x247A },
	{ 10, 0, 0, 0x2436 },
	{ 11, 0, 0, 0x23C9 },
	{ 12, 0, 0, 0x2342 },
	{ 13, 0, 0, 0x22B3 },
	{ 14, 0, 0, 0x2234 },
	{ 15, 0, 0, 0x21DA },
	{ 16, 0, 0, 0x21B8 }
};

NJS_MKEY_A animation_00719A78_mkey_62_rot_007194D8[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF569 },
	{ 1, 0x10B4, 0x3FE, 0xFFFFF571 },
	{ 2, 0x10B4, 0x3FE, 0xFFFFF588 },
	{ 3, 0x10B4, 0x3FE, 0xFFFFF5AC },
	{ 4, 0x10B4, 0x3FE, 0xFFFFF5DB },
	{ 5, 0x10B4, 0x3FE, 0xFFFFF612 },
	{ 6, 0x10B4, 0x3FE, 0xFFFFF650 },
	{ 7, 0x10B4, 0x3FE, 0xFFFFF692 },
	{ 8, 0x10B4, 0x3FE, 0xFFFFF6D6 },
	{ 9, 0x10B4, 0x3FE, 0xFFFFF71A },
	{ 10, 0x10B4, 0x3FE, 0xFFFFF75C },
	{ 11, 0x10B4, 0x3FE, 0xFFFFF799 },
	{ 12, 0x10B4, 0x3FE, 0xFFFFF7D1 },
	{ 13, 0x10B4, 0x3FE, 0xFFFFF7FF },
	{ 14, 0x10B4, 0x3FE, 0xFFFFF823 },
	{ 15, 0x10B4, 0x3FE, 0xFFFFF83B },
	{ 16, 0x10B4, 0x3FE, 0xFFFFF843 }
};

NJS_MDATA2 animation_00719A78_mdat_007195E8[] = {
	{ animation_00719A78_mkey_0_pos_00718004, NULL, LengthOfArray<Uint32>(animation_00719A78_mkey_0_pos_00718004), 0 },
	{ NULL, animation_00719A78_mkey_1_rot_00718028, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_1_rot_00718028) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_12_rot_00718138, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_12_rot_00718138) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_15_rot_00718248, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_15_rot_00718248) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_19_rot_00718358, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_19_rot_00718358) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_25_rot_00718468, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_25_rot_00718468) },
	{ NULL, animation_00719A78_mkey_26_rot_00718578, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_26_rot_00718578) },
	{ NULL, animation_00719A78_mkey_27_rot_00718688, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_27_rot_00718688) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_30_rot_00718798, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_30_rot_00718798) },
	{ NULL, animation_00719A78_mkey_32_rot_007187D8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_32_rot_007187D8) },
	{ NULL, animation_00719A78_mkey_31_rot_007187B8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_31_rot_007187B8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_36_rot_007187F8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_36_rot_007187F8) },
	{ NULL, animation_00719A78_mkey_37_rot_00718908, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_37_rot_00718908) },
	{ NULL, animation_00719A78_mkey_38_rot_00718A18, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_38_rot_00718A18) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_43_rot_00718B48, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_43_rot_00718B48) },
	{ NULL, animation_00719A78_mkey_42_rot_00718B28, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_42_rot_00718B28) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_46_rot_00718B68, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_46_rot_00718B68) },
	{ NULL, animation_00719A78_mkey_47_rot_00718C78, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_47_rot_00718C78) },
	{ NULL, animation_00719A78_mkey_48_rot_00718D88, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_48_rot_00718D88) },
	{ NULL, animation_00719A78_mkey_49_rot_00718E88, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_49_rot_00718E88) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_52_rot_00718F88, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_52_rot_00718F88) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_56_rot_00719098, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_56_rot_00719098) },
	{ NULL, animation_00719A78_mkey_57_rot_007191A8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_57_rot_007191A8) },
	{ NULL, animation_00719A78_mkey_58_rot_007192B8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_58_rot_007192B8) },
	{ NULL, animation_00719A78_mkey_59_rot_007193C8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_59_rot_007193C8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00719A78_mkey_62_rot_007194D8, 0, LengthOfArray<Uint32>(animation_00719A78_mkey_62_rot_007194D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbjump1 = { animation_00719A78_mdat_007195E8, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbjump1 = { AMY_OBJECTS[0], &motion_a_sbjump1 };
