/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_0070E808_mkey_0_pos_0070CB94[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 16, 0, -0.7354f, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_1_rot_0070CBB8[] = {
	{ 0, 0, 0xFFFFEAAB, 0x88E },
	{ 1, 0, 0xFFFFEAAB, 0x872 },
	{ 2, 0, 0xFFFFEAAB, 0x822 },
	{ 3, 0, 0xFFFFEAAB, 0x7A7 },
	{ 4, 0, 0xFFFFEAAB, 0x707 },
	{ 5, 0, 0xFFFFEAAB, 0x649 },
	{ 6, 0, 0xFFFFEAAB, 0x576 },
	{ 7, 0, 0xFFFFEAAB, 0x494 },
	{ 8, 0, 0xFFFFEAAB, 0x3AA },
	{ 9, 0, 0xFFFFEAAB, 0x2C1 },
	{ 10, 0, 0xFFFFEAAB, 0x1DF },
	{ 11, 0, 0xFFFFEAAB, 0x10B },
	{ 12, 0, 0xFFFFEAAB, 0x4E },
	{ 13, 0, 0xFFFFEAAB, 0xFFFFFFAF },
	{ 14, 0, 0xFFFFEAAB, 0xFFFFFF33 },
	{ 15, 0, 0xFFFFEAAB, 0xFFFFFEE4 },
	{ 16, 0, 0xFFFFEAAB, 0xFFFFFEC8 }
};

NJS_MKEY_A animation_0070E808_mkey_12_rot_0070CCC8[] = {
	{ 0, 0, 0xFFFFEAC7, 0x8875 },
	{ 1, 0, 0xFFFFEACB, 0x889E },
	{ 2, 0, 0xFFFFEAD6, 0x8913 },
	{ 3, 0, 0xFFFFEAE8, 0x89C7 },
	{ 4, 0, 0xFFFFEB01, 0x8AAF },
	{ 5, 0, 0xFFFFEB22, 0x8BBD },
	{ 6, 0, 0xFFFFEB4A, 0x8CE7 },
	{ 7, 0, 0xFFFFEB77, 0x8E20 },
	{ 8, 0, 0xFFFFEBAA, 0x8F5D },
	{ 9, 0, 0xFFFFEBDF, 0x9093 },
	{ 10, 0, 0xFFFFEC16, 0x91B8 },
	{ 11, 0, 0xFFFFEC4B, 0x92C4 },
	{ 12, 0, 0xFFFFEC7C, 0x93AF },
	{ 13, 0, 0xFFFFECA7, 0x9471 },
	{ 14, 0, 0xFFFFECC8, 0x9504 },
	{ 15, 0, 0xFFFFECDE, 0x9562 },
	{ 16, 0, 0xFFFFECE5, 0x9583 }
};

NJS_MKEY_A animation_0070E808_mkey_15_rot_0070CDD8[] = {
	{ 0, 0, 0xB6A, 0xFFFF87C1 },
	{ 1, 0, 0xB69, 0xFFFF87D3 },
	{ 2, 0, 0xB67, 0xFFFF8806 },
	{ 3, 0, 0xB63, 0xFFFF8857 },
	{ 4, 0, 0xB5E, 0xFFFF88C3 },
	{ 5, 0, 0xB59, 0xFFFF8947 },
	{ 6, 0, 0xB52, 0xFFFF89DF },
	{ 7, 0, 0xB4C, 0xFFFF8A85 },
	{ 8, 0, 0xB47, 0xFFFF8B32 },
	{ 9, 0, 0xB42, 0xFFFF8BDF },
	{ 10, 0, 0xB3E, 0xFFFF8C85 },
	{ 11, 0, 0xB3B, 0xFFFF8D1E },
	{ 12, 0, 0xB39, 0xFFFF8DA4 },
	{ 13, 0, 0xB37, 0xFFFF8E12 },
	{ 14, 0, 0xB36, 0xFFFF8E65 },
	{ 15, 0, 0xB36, 0xFFFF8E99 },
	{ 16, 0, 0xB36, 0xFFFF8EAB }
};

NJS_MKEY_A animation_0070E808_mkey_19_rot_0070CEE8[] = {
	{ 0, 0, 0xFFFFF461, 0xFFFF87BF },
	{ 1, 0, 0xFFFFF45A, 0xFFFF87D3 },
	{ 2, 0, 0xFFFFF447, 0xFFFF880B },
	{ 3, 0, 0xFFFFF42B, 0xFFFF8864 },
	{ 4, 0, 0xFFFFF40A, 0xFFFF88DA },
	{ 5, 0, 0xFFFFF3EA, 0xFFFF8968 },
	{ 6, 0, 0xFFFFF3CF, 0xFFFF8A0A },
	{ 7, 0, 0xFFFFF3BC, 0xFFFF8ABA },
	{ 8, 0, 0xFFFFF3B4, 0xFFFF8B70 },
	{ 9, 0, 0xFFFFF3B8, 0xFFFF8C25 },
	{ 10, 0, 0xFFFFF3C6, 0xFFFF8CD2 },
	{ 11, 0, 0xFFFFF3DC, 0xFFFF8D70 },
	{ 12, 0, 0xFFFFF3F7, 0xFFFF8DFB },
	{ 13, 0, 0xFFFFF413, 0xFFFF8E6D },
	{ 14, 0, 0xFFFFF42B, 0xFFFF8EC3 },
	{ 15, 0, 0xFFFFF43C, 0xFFFF8EF9 },
	{ 16, 0, 0xFFFFF442, 0xFFFF8F0C }
};

NJS_MKEY_A animation_0070E808_mkey_25_rot_0070CFF8[] = {
	{ 0, 0, 0x2A6D, 0xFFFFE10E },
	{ 1, 0, 0x2A8E, 0xFFFFE134 },
	{ 2, 0, 0x2AEB, 0xFFFFE1A1 },
	{ 3, 0, 0x2B78, 0xFFFFE24F },
	{ 4, 0, 0x2C2A, 0xFFFFE338 },
	{ 5, 0, 0x2CF4, 0xFFFFE458 },
	{ 6, 0, 0x2DCA, 0xFFFFE5A9 },
	{ 7, 0, 0x2EA2, 0xFFFFE724 },
	{ 8, 0, 0x2F73, 0xFFFFE8BF },
	{ 9, 0, 0x3036, 0xFFFFEA71 },
	{ 10, 0, 0x30E6, 0xFFFFEC29 },
	{ 11, 0, 0x317E, 0xFFFFEDD7 },
	{ 12, 0, 0x31FD, 0xFFFFEF67 },
	{ 13, 0, 0x3261, 0xFFFFF0C4 },
	{ 14, 0, 0x32AA, 0xFFFFF1D7 },
	{ 15, 0, 0x32D7, 0xFFFFF28A },
	{ 16, 0, 0x32E6, 0xFFFFF2CA }
};

NJS_MKEY_A animation_0070E808_mkey_26_rot_0070D108[] = {
	{ 0, 0, 0xD3, 0xFFFFEF92 },
	{ 1, 0, 0x102, 0xFFFFEFB4 },
	{ 2, 0, 0x184, 0xFFFFF017 },
	{ 3, 0, 0x24C, 0xFFFFF0B6 },
	{ 4, 0, 0x349, 0xFFFFF18F },
	{ 5, 0, 0x467, 0xFFFFF29D },
	{ 6, 0, 0x592, 0xFFFFF3DA },
	{ 7, 0, 0x6B6, 0xFFFFF53C },
	{ 8, 0, 0x7C3, 0xFFFFF6B8 },
	{ 9, 0, 0x8AA, 0xFFFFF83D },
	{ 10, 0, 0x965, 0xFFFFF9BD },
	{ 11, 0, 0x9F1, 0xFFFFFB25 },
	{ 12, 0, 0xA52, 0xFFFFFC68 },
	{ 13, 0, 0xA90, 0xFFFFFD76 },
	{ 14, 0, 0xAB2, 0xFFFFFE45 },
	{ 15, 0, 0xAC2, 0xFFFFFEC9 },
	{ 16, 0, 0xAC7, 0xFFFFFEF7 }
};

NJS_MKEY_A animation_0070E808_mkey_27_rot_0070D218[] = {
	{ 0, 0, 0x1E3, 0xFFFFE2EE },
	{ 1, 0, 0x231, 0xFFFFE2F3 },
	{ 2, 0, 0x311, 0xFFFFE30B },
	{ 3, 0, 0x47D, 0xFFFFE34D },
	{ 4, 0, 0x669, 0xFFFFE3DB },
	{ 5, 0, 0x8C2, 0xFFFFE4DB },
	{ 6, 0, 0xB63, 0xFFFFE670 },
	{ 7, 0, 0xE15, 0xFFFFE8AC },
	{ 8, 0, 0x1096, 0xFFFFEB89 },
	{ 9, 0, 0x12A9, 0xFFFFEEE1 },
	{ 10, 0, 0x142A, 0xFFFFF270 },
	{ 11, 0, 0x1513, 0xFFFFF5E6 },
	{ 12, 0, 0x157C, 0xFFFFF8FE },
	{ 13, 0, 0x158D, 0xFFFFFB87 },
	{ 14, 0, 0x1571, 0xFFFFFD67 },
	{ 15, 0, 0x154D, 0xFFFFFE90 },
	{ 16, 0, 0x153E, 0xFFFFFEF7 }
};

NJS_MKEY_A animation_0070E808_mkey_30_rot_0070D328[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 1, 0x95, 0x18DA, 0 },
	{ 2, 0x23D, 0x18DA, 0 },
	{ 3, 0x4D0, 0x18DA, 0 },
	{ 4, 0x826, 0x18DA, 0 },
	{ 5, 0xC18, 0x18DA, 0 },
	{ 6, 0x1080, 0x18DA, 0 },
	{ 7, 0x1536, 0x18DA, 0 },
	{ 8, 0x1A13, 0x18DA, 0 },
	{ 9, 0x1EF0, 0x18DA, 0 },
	{ 10, 0x23A6, 0x18DA, 0 },
	{ 11, 0x280E, 0x18DA, 0 },
	{ 12, 0x2C00, 0x18DA, 0 },
	{ 13, 0x2F56, 0x18DA, 0 },
	{ 14, 0x31E9, 0x18DA, 0 },
	{ 15, 0x3390, 0x18DA, 0 },
	{ 16, 0x3426, 0x18DA, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_32_rot_0070D458[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 1, 0, 0x150A, 0 },
	{ 2, 0, 0x15C6, 0 },
	{ 3, 0, 0x16EC, 0 },
	{ 4, 0, 0x1868, 0 },
	{ 5, 0, 0x1A2A, 0 },
	{ 6, 0, 0x1C20, 0 },
	{ 7, 0, 0x1E39, 0 },
	{ 8, 0, 0x2064, 0 },
	{ 9, 0, 0x228E, 0 },
	{ 10, 0, 0x24A7, 0 },
	{ 11, 0, 0x269D, 0 },
	{ 12, 0, 0x285F, 0 },
	{ 13, 0, 0x29DB, 0 },
	{ 14, 0, 0x2B01, 0 },
	{ 15, 0, 0x2BBD, 0 },
	{ 16, 0, 0x2C00, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_31_rot_0070D438[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 16, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_0070E808_mkey_36_rot_0070D568[] = {
	{ 0, 0, 0xFFFFE8F9, 0xFFFFDCAA },
	{ 1, 0, 0xFFFFE8E0, 0xFFFFDD15 },
	{ 2, 0, 0xFFFFE89F, 0xFFFFDE40 },
	{ 3, 0, 0xFFFFE842, 0xFFFFE00C },
	{ 4, 0, 0xFFFFE7DB, 0xFFFFE255 },
	{ 5, 0, 0xFFFFE77A, 0xFFFFE4F6 },
	{ 6, 0, 0xFFFFE729, 0xFFFFE7C5 },
	{ 7, 0, 0xFFFFE6EF, 0xFFFFEA9E },
	{ 8, 0, 0xFFFFE6CE, 0xFFFFED5F },
	{ 9, 0, 0xFFFFE6C4, 0xFFFFEFEE },
	{ 10, 0, 0xFFFFE6CB, 0xFFFFF23B },
	{ 11, 0, 0xFFFFE6DE, 0xFFFFF438 },
	{ 12, 0, 0xFFFFE6F7, 0xFFFFF5E1 },
	{ 13, 0, 0xFFFFE711, 0xFFFFF732 },
	{ 14, 0, 0xFFFFE727, 0xFFFFF829 },
	{ 15, 0, 0xFFFFE736, 0xFFFFF8C2 },
	{ 16, 0, 0xFFFFE73C, 0xFFFFF8F7 }
};

NJS_MKEY_A animation_0070E808_mkey_37_rot_0070D678[] = {
	{ 0, 0, 0xFFFFEE74, 0xFFFFEBF0 },
	{ 1, 0, 0xFFFFEE28, 0xFFFFEC13 },
	{ 2, 0, 0xFFFFED54, 0xFFFFEC83 },
	{ 3, 0, 0xFFFFEC16, 0xFFFFED53 },
	{ 4, 0, 0xFFFFEA94, 0xFFFFEE9A },
	{ 5, 0, 0xFFFFE8FF, 0xFFFFF06B },
	{ 6, 0, 0xFFFFE789, 0xFFFFF2C1 },
	{ 7, 0, 0xFFFFE65E, 0xFFFFF581 },
	{ 8, 0, 0xFFFFE599, 0xFFFFF873 },
	{ 9, 0, 0xFFFFE53C, 0xFFFFFB5B },
	{ 10, 0, 0xFFFFE536, 0xFFFFFE04 },
	{ 11, 0, 0xFFFFE56E, 0x4A },
	{ 12, 0, 0xFFFFE5C5, 0x222 },
	{ 13, 0, 0xFFFFE624, 0x38B },
	{ 14, 0, 0xFFFFE677, 0x489 },
	{ 15, 0, 0xFFFFE6B0, 0x522 },
	{ 16, 0, 0xFFFFE6C5, 0x556 }
};

NJS_MKEY_A animation_0070E808_mkey_38_rot_0070D788[] = {
	{ 0, 0, 0xFFFFEED4, 0xFFFFECC1 },
	{ 1, 0, 0xFFFFEE77, 0xFFFFECE6 },
	{ 2, 0, 0xFFFFED75, 0xFFFFED5F },
	{ 3, 0, 0xFFFFEBF8, 0xFFFFEE47 },
	{ 4, 0, 0xFFFFEA35, 0xFFFFEFC2 },
	{ 5, 0, 0xFFFFE86D, 0xFFFFF1EA },
	{ 6, 0, 0xFFFFE6E1, 0xFFFFF4C0 },
	{ 7, 0, 0xFFFFE5CC, 0xFFFFF817 },
	{ 8, 0, 0xFFFFE548, 0xFFFFFB9B },
	{ 9, 0, 0xFFFFE54E, 0xFFFFFEEA },
	{ 10, 0, 0xFFFFE5B7, 0x1BF },
	{ 11, 0, 0xFFFFE655, 0x3FE },
	{ 12, 0, 0xFFFFE6FF, 0x5AB },
	{ 13, 0, 0xFFFFE799, 0x6DB },
	{ 14, 0, 0xFFFFE813, 0x7A4 },
	{ 15, 0, 0xFFFFE861, 0x817 },
	{ 16, 0, 0xFFFFE87C, 0x83E }
};

NJS_MKEY_A animation_0070E808_mkey_41_rot_0070D898[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0xFFFFFF84, 0, 0 },
	{ 2, 0xFFFFFE25, 0, 0 },
	{ 3, 0xFFFFFC04, 0, 0 },
	{ 4, 0xFFFFF941, 0, 0 },
	{ 5, 0xFFFFF5FC, 0, 0 },
	{ 6, 0xFFFFF256, 0, 0 },
	{ 7, 0xFFFFEE70, 0, 0 },
	{ 8, 0xFFFFEA68, 0, 0 },
	{ 9, 0xFFFFE661, 0, 0 },
	{ 10, 0xFFFFE27B, 0, 0 },
	{ 11, 0xFFFFDED5, 0, 0 },
	{ 12, 0xFFFFDB90, 0, 0 },
	{ 13, 0xFFFFD8CD, 0, 0 },
	{ 14, 0xFFFFD6AC, 0, 0 },
	{ 15, 0xFFFFD54D, 0, 0 },
	{ 16, 0xFFFFD4D0, 0, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_43_rot_0070DAB8[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 16, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_42_rot_0070D9A8[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 1, 0, 0xFFFFE3A3, 0 },
	{ 2, 0, 0xFFFFE2ED, 0 },
	{ 3, 0, 0xFFFFE1D2, 0 },
	{ 4, 0, 0xFFFFE063, 0 },
	{ 5, 0, 0xFFFFDEB1, 0 },
	{ 6, 0, 0xFFFFDCCD, 0 },
	{ 7, 0, 0xFFFFDAC6, 0 },
	{ 8, 0, 0xFFFFD8AF, 0 },
	{ 9, 0, 0xFFFFD698, 0 },
	{ 10, 0, 0xFFFFD492, 0 },
	{ 11, 0, 0xFFFFD2AE, 0 },
	{ 12, 0, 0xFFFFD0FB, 0 },
	{ 13, 0, 0xFFFFCF8C, 0 },
	{ 14, 0, 0xFFFFCE72, 0 },
	{ 15, 0, 0xFFFFCDBB, 0 },
	{ 16, 0, 0xFFFFCD7B, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_46_rot_0070DAD8[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 16, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_0070E808_mkey_47_rot_0070DAF8[] = {
	{ 0, 0xFFFFFEB9, 0x20C, 0xFFFFB848 },
	{ 1, 0xFFFFFEAF, 0x21F, 0xFFFFB871 },
	{ 2, 0xFFFFFE93, 0x255, 0xFFFFB8E8 },
	{ 3, 0xFFFFFE69, 0x2AB, 0xFFFFB9A3 },
	{ 4, 0xFFFFFE37, 0x31B, 0xFFFFBA9B },
	{ 5, 0xFFFFFE00, 0x3A2, 0xFFFFBBC8 },
	{ 6, 0xFFFFFDCA, 0x43B, 0xFFFFBD23 },
	{ 7, 0xFFFFFD97, 0x4E1, 0xFFFFBE9C },
	{ 8, 0xFFFFFD70, 0x590, 0xFFFFC042 },
	{ 9, 0xFFFFFD53, 0x642, 0xFFFFC1ED },
	{ 10, 0xFFFFFD49, 0x6F3, 0xFFFFC3BE },
	{ 11, 0xFFFFFD4F, 0x79C, 0xFFFFC595 },
	{ 12, 0xFFFFFD65, 0x835, 0xFFFFC75F },
	{ 13, 0xFFFFFD85, 0x8B9, 0xFFFFC903 },
	{ 14, 0xFFFFFDAC, 0x920, 0xFFFFCA6E },
	{ 15, 0xFFFFFDCC, 0x962, 0xFFFFCB6C },
	{ 16, 0xFFFFFDD9, 0x97A, 0xFFFFCBCA }
};

NJS_MKEY_A animation_0070E808_mkey_48_rot_0070DC08[] = {
	{ 0, 0, 0, 0x171C },
	{ 1, 0, 0, 0x1704 },
	{ 2, 0, 0, 0x16BF },
	{ 3, 0, 0, 0x1651 },
	{ 4, 0, 0, 0x15BF },
	{ 5, 0, 0, 0x150A },
	{ 6, 0, 0, 0x1436 },
	{ 7, 0, 0, 0x1375 },
	{ 8, 0, 0, 0x1262 },
	{ 9, 0, 0, 0x1150 },
	{ 10, 0, 0, 0x1015 },
	{ 11, 0, 0, 0xED4 },
	{ 12, 0, 0, 0xD90 },
	{ 13, 0, 0, 0xC6F },
	{ 14, 0, 0, 0xB5C },
	{ 15, 0, 0, 0xA99 },
	{ 16, 0, 0, 0xA50 }
};

NJS_MKEY_A animation_0070E808_mkey_49_rot_0070DD18[] = {
	{ 0, 0, 0, 0x1536 },
	{ 1, 0, 0, 0x151A },
	{ 2, 0, 0, 0x14C9 },
	{ 3, 0, 0, 0x1448 },
	{ 4, 0, 0, 0x139C },
	{ 5, 0, 0, 0x12C8 },
	{ 6, 0, 0, 0x11CF },
	{ 7, 0, 0, 0x1086 },
	{ 8, 0, 0, 0xF5A },
	{ 9, 0, 0, 0xE27 },
	{ 10, 0, 0, 0xCCD },
	{ 11, 0, 0, 0xB61 },
	{ 12, 0, 0, 0x9FF },
	{ 13, 0, 0, 0x89F },
	{ 14, 0, 0, 0x785 },
	{ 15, 0, 0, 0x6BC },
	{ 16, 0, 0, 0x671 }
};

NJS_MKEY_A animation_0070E808_mkey_52_rot_0070DE28[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFD539 },
	{ 1, 0x1C1C, 0xFFFFF766, 0xFFFFD553 },
	{ 2, 0x1C1C, 0xFFFFF745, 0xFFFFD59B },
	{ 3, 0x1C1C, 0xFFFFF712, 0xFFFFD60D },
	{ 4, 0x1C1C, 0xFFFFF6CF, 0xFFFFD69F },
	{ 5, 0x1C1C, 0xFFFFF680, 0xFFFFD74D },
	{ 6, 0x1C1C, 0xFFFFF628, 0xFFFFD80F },
	{ 7, 0x1C1C, 0xFFFFF5CA, 0xFFFFD8DE },
	{ 8, 0x1C1C, 0xFFFFF569, 0xFFFFD9B4 },
	{ 9, 0x1C1C, 0xFFFFF507, 0xFFFFDA8A },
	{ 10, 0x1C1C, 0xFFFFF4A9, 0xFFFFDB59 },
	{ 11, 0x1C1C, 0xFFFFF451, 0xFFFFDC1B },
	{ 12, 0x1C1C, 0xFFFFF402, 0xFFFFDCC9 },
	{ 13, 0x1C1C, 0xFFFFF3BF, 0xFFFFDD5C },
	{ 14, 0x1C1C, 0xFFFFF38C, 0xFFFFDDCD },
	{ 15, 0x1C1C, 0xFFFFF36B, 0xFFFFDE16 },
	{ 16, 0x1C1C, 0xFFFFF35F, 0xFFFFDE2F }
};

NJS_MKEY_A animation_0070E808_mkey_57_rot_0070DF38[] = {
	{ 0, 0x64F, 0xFFFFF89F, 0xFFFF8541 },
	{ 1, 0x64A, 0xFFFFF8AB, 0xFFFF854C },
	{ 2, 0x63C, 0xFFFFF8CC, 0xFFFF856C },
	{ 3, 0x624, 0xFFFFF900, 0xFFFF859F },
	{ 4, 0x604, 0xFFFFF942, 0xFFFF85E2 },
	{ 5, 0x5DC, 0xFFFFF991, 0xFFFF8633 },
	{ 6, 0x5AC, 0xFFFFF9E8, 0xFFFF868F },
	{ 7, 0x575, 0xFFFFFA45, 0xFFFF86F4 },
	{ 8, 0x539, 0xFFFFFAA3, 0xFFFF8760 },
	{ 9, 0x4F9, 0xFFFFFB02, 0xFFFF87CD },
	{ 10, 0x4B8, 0xFFFFFB5C, 0xFFFF8839 },
	{ 11, 0x477, 0xFFFFFBAF, 0xFFFF88AC },
	{ 12, 0x43B, 0xFFFFFBF9, 0xFFFF8909 },
	{ 13, 0x408, 0xFFFFFC38, 0xFFFF8959 },
	{ 14, 0x3DF, 0xFFFFFC68, 0xFFFF8997 },
	{ 15, 0x3C4, 0xFFFFFC87, 0xFFFF89BF },
	{ 16, 0x3BB, 0xFFFFFC92, 0xFFFF89CE }
};

NJS_MKEY_A animation_0070E808_mkey_58_rot_0070E048[] = {
	{ 0, 0, 0, 0x18FD },
	{ 1, 0, 0, 0x190C },
	{ 2, 0, 0, 0x1936 },
	{ 3, 0, 0, 0x1976 },
	{ 4, 0, 0, 0x19C9 },
	{ 5, 0, 0, 0x1A28 },
	{ 6, 0, 0, 0x1A90 },
	{ 7, 0, 0, 0x1AFC },
	{ 8, 0, 0, 0x1B66 },
	{ 9, 0, 0, 0x1BD0 },
	{ 10, 0, 0, 0x1C34 },
	{ 11, 0, 0, 0x1C85 },
	{ 12, 0, 0, 0x1CD5 },
	{ 13, 0, 0, 0x1D17 },
	{ 14, 0, 0, 0x1D49 },
	{ 15, 0, 0, 0x1D69 },
	{ 16, 0, 0, 0x1D75 }
};

NJS_MKEY_A animation_0070E808_mkey_59_rot_0070E158[] = {
	{ 0, 0, 0, 0x21A9 },
	{ 1, 0, 0, 0x21BE },
	{ 2, 0, 0, 0x21F9 },
	{ 3, 0, 0, 0x2254 },
	{ 4, 0, 0, 0x22C8 },
	{ 5, 0, 0, 0x234E },
	{ 6, 0, 0, 0x23E0 },
	{ 7, 0, 0, 0x2478 },
	{ 8, 0, 0, 0x2515 },
	{ 9, 0, 0, 0x25AB },
	{ 10, 0, 0, 0x2639 },
	{ 11, 0, 0, 0x26AD },
	{ 12, 0, 0, 0x271E },
	{ 13, 0, 0, 0x277C },
	{ 14, 0, 0, 0x27C4 },
	{ 15, 0, 0, 0x27F1 },
	{ 16, 0, 0, 0x2801 }
};

NJS_MKEY_A animation_0070E808_mkey_62_rot_0070E268[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF843 },
	{ 1, 0x10B4, 0x3F7, 0xFFFFF81C },
	{ 2, 0x10B4, 0x3E3, 0xFFFFF7AF },
	{ 3, 0x10B4, 0x3C4, 0xFFFFF705 },
	{ 4, 0x10B4, 0x39C, 0xFFFFF629 },
	{ 5, 0x10B4, 0x36D, 0xFFFFF524 },
	{ 6, 0x10B4, 0x338, 0xFFFFF402 },
	{ 7, 0x10B4, 0x2FF, 0xFFFFF2CB },
	{ 8, 0x10B4, 0x2C5, 0xFFFFF18A },
	{ 9, 0x10B4, 0x28A, 0xFFFFF049 },
	{ 10, 0x10B4, 0x252, 0xFFFFEF12 },
	{ 11, 0x10B4, 0x21D, 0xFFFFEDEF },
	{ 12, 0x10B4, 0x1EE, 0xFFFFECEB },
	{ 13, 0x10B4, 0x1C6, 0xFFFFEC0E },
	{ 14, 0x10B4, 0x1A7, 0xFFFFEB65 },
	{ 15, 0x10B4, 0x193, 0xFFFFEAF7 },
	{ 16, 0x10B4, 0x18C, 0xFFFFEAD1 }
};

NJS_MDATA2 animation_0070E808_mdat_0070E378[] = {
	{ animation_0070E808_mkey_0_pos_0070CB94, NULL, LengthOfArray<Uint32>(animation_0070E808_mkey_0_pos_0070CB94), 0 },
	{ NULL, animation_0070E808_mkey_1_rot_0070CBB8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_1_rot_0070CBB8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_12_rot_0070CCC8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_12_rot_0070CCC8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_15_rot_0070CDD8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_15_rot_0070CDD8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_19_rot_0070CEE8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_19_rot_0070CEE8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_25_rot_0070CFF8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_25_rot_0070CFF8) },
	{ NULL, animation_0070E808_mkey_26_rot_0070D108, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_26_rot_0070D108) },
	{ NULL, animation_0070E808_mkey_27_rot_0070D218, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_27_rot_0070D218) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_30_rot_0070D328, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_30_rot_0070D328) },
	{ NULL, animation_0070E808_mkey_32_rot_0070D458, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_32_rot_0070D458) },
	{ NULL, animation_0070E808_mkey_31_rot_0070D438, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_31_rot_0070D438) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_36_rot_0070D568, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_36_rot_0070D568) },
	{ NULL, animation_0070E808_mkey_37_rot_0070D678, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_37_rot_0070D678) },
	{ NULL, animation_0070E808_mkey_38_rot_0070D788, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_38_rot_0070D788) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_41_rot_0070D898, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_41_rot_0070D898) },
	{ NULL, animation_0070E808_mkey_43_rot_0070DAB8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_43_rot_0070DAB8) },
	{ NULL, animation_0070E808_mkey_42_rot_0070D9A8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_42_rot_0070D9A8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_46_rot_0070DAD8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_46_rot_0070DAD8) },
	{ NULL, animation_0070E808_mkey_47_rot_0070DAF8, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_47_rot_0070DAF8) },
	{ NULL, animation_0070E808_mkey_48_rot_0070DC08, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_48_rot_0070DC08) },
	{ NULL, animation_0070E808_mkey_49_rot_0070DD18, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_49_rot_0070DD18) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_52_rot_0070DE28, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_52_rot_0070DE28) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_57_rot_0070DF38, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_57_rot_0070DF38) },
	{ NULL, animation_0070E808_mkey_58_rot_0070E048, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_58_rot_0070E048) },
	{ NULL, animation_0070E808_mkey_59_rot_0070E158, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_59_rot_0070E158) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0070E808_mkey_62_rot_0070E268, 0, LengthOfArray<Uint32>(animation_0070E808_mkey_62_rot_0070E268) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbdown0 = { animation_0070E808_mdat_0070E378, 17, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbdown0 = { AMY_OBJECTS[0], &motion_a_sbdown0 };
