/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_0072A1E8_mkey_0_pos_00729374[] = {
	{ 0, 0, -1.8759f, 0 },
	{ 15, 0, -1.8759f, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_0_rot_00729398[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0xFFF, 0 },
	{ 2, 0, 0x1FFF, 0 },
	{ 3, 0, 0x2FFF, 0 },
	{ 4, 0, 0x3FFF, 0 },
	{ 5, 0, 0x4FFF, 0 },
	{ 6, 0, 0x5FFF, 0 },
	{ 7, 0, 0x6FFF, 0 },
	{ 8, 0, 0x7FFF, 0 },
	{ 9, 0, 0x8FFF, 0 },
	{ 10, 0, 0x9FFF, 0 },
	{ 11, 0, 0xAFFF, 0 },
	{ 12, 0, 0xBFFF, 0 },
	{ 13, 0, 0xCFFF, 0 },
	{ 14, 0, 0xDFFF, 0 },
	{ 15, 0, 0xEFFF, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_1_rot_00729498[] = {
	{ 0, 0, 0xFFFFCEF7, 0x88E },
	{ 15, 0, 0xFFFFCEF7, 0x88E }
};

NJS_MKEY_A animation_0072A1E8_mkey_11_rot_007294B8[] = {
	{ 0, 0xFFFFFF98, 0xB68, 0 },
	{ 15, 0xFFFFFF98, 0xB68, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_12_rot_007294D8[] = {
	{ 0, 0, 0xFFFFF60B, 0x87A7 },
	{ 1, 0, 0xFFFFF41A, 0x8675 },
	{ 2, 0, 0xFFFFEEF3, 0x830F },
	{ 3, 0, 0xFFFFE7FA, 0x7D9C },
	{ 4, 0, 0xFFFFE142, 0x7694 },
	{ 5, 0, 0xFFFFDC6F, 0x6F43 },
	{ 6, 0, 0xFFFFD9CE, 0x6998 },
	{ 7, 0, 0xFFFFD8FB, 0x675F },
	{ 8, 0, 0xFFFFD97A, 0x68BF },
	{ 9, 0, 0xFFFFDB03, 0x6C6C },
	{ 10, 0, 0xFFFFDDC9, 0x719E },
	{ 11, 0, 0xFFFFE1EE, 0x7768 },
	{ 12, 0, 0xFFFFE72E, 0x7CE4 },
	{ 13, 0, 0xFFFFECBC, 0x8175 },
	{ 14, 0, 0xFFFFF191, 0x84D4 },
	{ 15, 0, 0xFFFFF4D9, 0x86EB }
};

NJS_MKEY_A animation_0072A1E8_mkey_15_rot_007295D8[] = {
	{ 0, 0, 0xC02, 0xFFFF8854 },
	{ 1, 0, 0xBA2, 0xFFFF88F2 },
	{ 2, 0, 0xAC7, 0xFFFF89FF },
	{ 3, 0, 0x9D5, 0xFFFF8A17 },
	{ 4, 0, 0x96D, 0xFFFF88D6 },
	{ 5, 0, 0x9CB, 0xFFFF87CC },
	{ 6, 0, 0xA50, 0xFFFF8781 },
	{ 7, 0, 0xA88, 0xFFFF87AD },
	{ 8, 0, 0xA3E, 0xFFFF883B },
	{ 9, 0, 0x9A1, 0xFFFF8939 },
	{ 10, 0, 0x91F, 0xFFFF8A8A },
	{ 11, 0, 0x932, 0xFFFF8BA2 },
	{ 12, 0, 0x9C8, 0xFFFF8BB4 },
	{ 13, 0, 0xA7B, 0xFFFF8AEB },
	{ 14, 0, 0xB32, 0xFFFF89C4 },
	{ 15, 0, 0xBC5, 0xFFFF88C1 }
};

NJS_MKEY_A animation_0072A1E8_mkey_19_rot_007296D8[] = {
	{ 0, 0, 0xFFFFF4D7, 0xFFFF8730 },
	{ 1, 0, 0xFFFFF258, 0xFFFF88AC },
	{ 2, 0, 0xFFFFEC4E, 0xFFFF8B66 },
	{ 3, 0, 0xFFFFE798, 0xFFFF8BB0 },
	{ 4, 0, 0xFFFFE636, 0xFFFF89E2 },
	{ 5, 0, 0xFFFFE58B, 0xFFFF8787 },
	{ 6, 0, 0xFFFFE515, 0xFFFF8566 },
	{ 7, 0, 0xFFFFE4A9, 0xFFFF84C1 },
	{ 8, 0, 0xFFFFE4B9, 0xFFFF85ED },
	{ 9, 0, 0xFFFFE581, 0xFFFF8825 },
	{ 10, 0, 0xFFFFE6AF, 0xFFFF8AC3 },
	{ 11, 0, 0xFFFFE7CF, 0xFFFF8D74 },
	{ 12, 0, 0xFFFFE9BB, 0xFFFF8F21 },
	{ 13, 0, 0xFFFFED2A, 0xFFFF8E14 },
	{ 14, 0, 0xFFFFF0F1, 0xFFFF8B30 },
	{ 15, 0, 0xFFFFF3C7, 0xFFFF885E }
};

NJS_MKEY_A animation_0072A1E8_mkey_25_rot_007297D8[] = {
	{ 0, 0, 0x2F9B, 0xFFFFAD1F },
	{ 1, 0, 0x2EAB, 0xFFFFB0C9 },
	{ 2, 0, 0x2BD9, 0xFFFFB877 },
	{ 3, 0, 0x278A, 0xFFFFBFB3 },
	{ 4, 0, 0x22E0, 0xFFFFC4D8 },
	{ 5, 0, 0x1EEE, 0xFFFFC812 },
	{ 6, 0, 0x1C51, 0xFFFFC9DC },
	{ 7, 0, 0x1B5E, 0xFFFFCA74 },
	{ 8, 0, 0x1BF4, 0xFFFFCA17 },
	{ 9, 0, 0x1D95, 0xFFFFC906 },
	{ 10, 0, 0x201F, 0xFFFFC72D },
	{ 11, 0, 0x2360, 0xFFFFC460 },
	{ 12, 0, 0x2704, 0xFFFFC061 },
	{ 13, 0, 0x2A87, 0xFFFFBB11 },
	{ 14, 0, 0x2D55, 0xFFFFB4E5 },
	{ 15, 0, 0x2F0A, 0xFFFFAF70 }
};

NJS_MKEY_A animation_0072A1E8_mkey_26_rot_007298D8[] = {
	{ 0, 0, 0xFFFFFD4C, 0xFFFFEDAF },
	{ 1, 0, 0xFFFFFE6B, 0xFFFFEDC8 },
	{ 2, 0, 0x50, 0xFFFFEE97 },
	{ 3, 0, 0x10B, 0xFFFFF05C },
	{ 4, 0, 0x76, 0xFFFFF287 },
	{ 5, 0, 0xFFFFFF82, 0xFFFFF46C },
	{ 6, 0, 0xFFFFFED1, 0xFFFFF5AB },
	{ 7, 0, 0xFFFFFE92, 0xFFFFF61D },
	{ 8, 0, 0xFFFFFEB9, 0xFFFFF5D7 },
	{ 9, 0, 0xFFFFFF27, 0xFFFFF511 },
	{ 10, 0, 0xFFFFFFD1, 0xFFFFF3DA },
	{ 11, 0, 0x90, 0xFFFFF24A },
	{ 12, 0, 0x107, 0xFFFFF098 },
	{ 13, 0, 0xBC, 0xFFFFEF17 },
	{ 14, 0, 0xFFFFFF88, 0xFFFFEE1A },
	{ 15, 0, 0xFFFFFE04, 0xFFFFEDBA }
};

NJS_MKEY_A animation_0072A1E8_mkey_27_rot_007299D8[] = {
	{ 0, 0, 0xFFFFF802, 0xFFFFEF82 },
	{ 1, 0, 0xFFFFF87A, 0xFFFFEF03 },
	{ 2, 0, 0xFFFFF905, 0xFFFFEE67 },
	{ 3, 0, 0xFFFFF87C, 0xFFFFEEFA },
	{ 4, 0, 0xFFFFF740, 0xFFFFF10B },
	{ 5, 0, 0xFFFFF66D, 0xFFFFF388 },
	{ 6, 0, 0xFFFFF632, 0xFFFFF551 },
	{ 7, 0, 0xFFFFF62F, 0xFFFFF5F6 },
	{ 8, 0, 0xFFFFF630, 0xFFFFF591 },
	{ 9, 0, 0xFFFFF645, 0xFFFFF474 },
	{ 10, 0, 0xFFFFF69F, 0xFFFFF2BD },
	{ 11, 0, 0xFFFFF762, 0xFFFFF0C4 },
	{ 12, 0, 0xFFFFF85C, 0xFFFFEF25 },
	{ 13, 0, 0xFFFFF8FB, 0xFFFFEE6B },
	{ 14, 0, 0xFFFFF8DE, 0xFFFFEE98 },
	{ 15, 0, 0xFFFFF851, 0xFFFFEF2F }
};

NJS_MKEY_A animation_0072A1E8_mkey_30_rot_00729AD8[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 15, 0, 0x18DA, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_32_rot_00729B18[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 15, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_31_rot_00729AF8[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 15, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_0072A1E8_mkey_36_rot_00729B38[] = {
	{ 0, 0, 0xFFFFF75D, 0xFFFFA305 },
	{ 15, 0, 0xFFFFF75D, 0xFFFFA305 }
};

NJS_MKEY_A animation_0072A1E8_mkey_37_rot_00729B58[] = {
	{ 0, 0, 0xFFFFF9A7, 0xFFFFF8C2 },
	{ 15, 0, 0xFFFFF9A7, 0xFFFFF8C2 }
};

NJS_MKEY_A animation_0072A1E8_mkey_38_rot_00729B78[] = {
	{ 0, 0, 0x148F, 0x7E0 },
	{ 15, 0, 0x148F, 0x7E0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_41_rot_00729B98[] = {
	{ 0, 0x4A8F, 0xFFFFF70A, 0 },
	{ 15, 0x4A8F, 0xFFFFF70A, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_43_rot_00729BD8[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 15, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_42_rot_00729BB8[] = {
	{ 0, 0, 0xFFFFF70A, 0 },
	{ 15, 0, 0xFFFFF70A, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_46_rot_00729BF8[] = {
	{ 0, 0, 0xFFFFF1C8, 0 },
	{ 15, 0, 0xFFFFF1C8, 0 }
};

NJS_MKEY_A animation_0072A1E8_mkey_47_rot_00729C18[] = {
	{ 0, 0xFFFFF720, 0x429, 0xFFFFAC70 },
	{ 15, 0xFFFFF720, 0x429, 0xFFFFAC70 }
};

NJS_MKEY_A animation_0072A1E8_mkey_48_rot_00729C38[] = {
	{ 0, 0, 0, 0x26D4 },
	{ 15, 0, 0, 0x26D4 }
};

NJS_MKEY_A animation_0072A1E8_mkey_49_rot_00729C58[] = {
	{ 0, 0, 0, 0x2A81 },
	{ 15, 0, 0, 0x2A81 }
};

NJS_MKEY_A animation_0072A1E8_mkey_52_rot_00729C78[] = {
	{ 0, 0x1C1C, 0xFFFFF772, 0xFFFFCA39 },
	{ 15, 0x1C1C, 0xFFFFF772, 0xFFFFCA39 }
};

NJS_MKEY_A animation_0072A1E8_mkey_53_rot_00729C98[] = {
	{ 0, 0, 0, 0xFFFFEB39 },
	{ 15, 0, 0, 0xFFFFEB39 }
};

NJS_MKEY_A animation_0072A1E8_mkey_57_rot_00729CB8[] = {
	{ 0, 0x1E26, 0xFFFFE503, 0xFFFF63F2 },
	{ 15, 0x1E26, 0xFFFFE503, 0xFFFF63F2 }
};

NJS_MKEY_A animation_0072A1E8_mkey_58_rot_00729CD8[] = {
	{ 0, 0, 0, 0x1889 },
	{ 15, 0, 0, 0x1889 }
};

NJS_MKEY_A animation_0072A1E8_mkey_59_rot_00729CF8[] = {
	{ 0, 0, 0, 0x20EA },
	{ 15, 0, 0, 0x20EA }
};

NJS_MKEY_A animation_0072A1E8_mkey_62_rot_00729D18[] = {
	{ 0, 0x10B4, 0x3FE, 0x413 },
	{ 15, 0x10B4, 0x3FE, 0x413 }
};

NJS_MKEY_A animation_0072A1E8_mkey_63_rot_00729D38[] = {
	{ 0, 0, 0, 0xFFFFEAD1 },
	{ 15, 0, 0, 0xFFFFEAD1 }
};

NJS_MDATA2 animation_0072A1E8_mdat_00729D58[] = {
	{ animation_0072A1E8_mkey_0_pos_00729374, animation_0072A1E8_mkey_0_rot_00729398, LengthOfArray<Uint32>(animation_0072A1E8_mkey_0_pos_00729374), LengthOfArray<Uint32>(animation_0072A1E8_mkey_0_rot_00729398) },
	{ NULL, animation_0072A1E8_mkey_1_rot_00729498, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_1_rot_00729498) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_11_rot_007294B8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_11_rot_007294B8) },
	{ NULL, animation_0072A1E8_mkey_12_rot_007294D8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_12_rot_007294D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_15_rot_007295D8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_15_rot_007295D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_19_rot_007296D8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_19_rot_007296D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_25_rot_007297D8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_25_rot_007297D8) },
	{ NULL, animation_0072A1E8_mkey_26_rot_007298D8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_26_rot_007298D8) },
	{ NULL, animation_0072A1E8_mkey_27_rot_007299D8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_27_rot_007299D8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_30_rot_00729AD8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_30_rot_00729AD8) },
	{ NULL, animation_0072A1E8_mkey_32_rot_00729B18, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_32_rot_00729B18) },
	{ NULL, animation_0072A1E8_mkey_31_rot_00729AF8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_31_rot_00729AF8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_36_rot_00729B38, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_36_rot_00729B38) },
	{ NULL, animation_0072A1E8_mkey_37_rot_00729B58, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_37_rot_00729B58) },
	{ NULL, animation_0072A1E8_mkey_38_rot_00729B78, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_38_rot_00729B78) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_41_rot_00729B98, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_41_rot_00729B98) },
	{ NULL, animation_0072A1E8_mkey_43_rot_00729BD8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_43_rot_00729BD8) },
	{ NULL, animation_0072A1E8_mkey_42_rot_00729BB8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_42_rot_00729BB8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_46_rot_00729BF8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_46_rot_00729BF8) },
	{ NULL, animation_0072A1E8_mkey_47_rot_00729C18, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_47_rot_00729C18) },
	{ NULL, animation_0072A1E8_mkey_48_rot_00729C38, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_48_rot_00729C38) },
	{ NULL, animation_0072A1E8_mkey_49_rot_00729C58, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_49_rot_00729C58) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_52_rot_00729C78, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_52_rot_00729C78) },
	{ NULL, animation_0072A1E8_mkey_53_rot_00729C98, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_53_rot_00729C98) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_57_rot_00729CB8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_57_rot_00729CB8) },
	{ NULL, animation_0072A1E8_mkey_58_rot_00729CD8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_58_rot_00729CD8) },
	{ NULL, animation_0072A1E8_mkey_59_rot_00729CF8, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_59_rot_00729CF8) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_0072A1E8_mkey_62_rot_00729D18, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_62_rot_00729D18) },
	{ NULL, animation_0072A1E8_mkey_63_rot_00729D38, 0, LengthOfArray<Uint32>(animation_0072A1E8_mkey_63_rot_00729D38) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbss0 = { animation_0072A1E8_mdat_00729D58, 16, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbss0 = { AMY_OBJECTS[0], &motion_a_sbss0 };
