/* NINJA Motion
 * 
 * Generated by DataToolbox
 * 
 */

NJS_MKEY_F animation_00717FF0_mkey_0_pos_00716590[] = {
	{ 0, 0, -0.7354f, 0 },
	{ 1, 0, -0.7202f, 0 },
	{ 2, 0, -0.6809f, 0 },
	{ 3, 0, -0.6273f, 0 },
	{ 4, 0, -0.5688f, 0 },
	{ 5, 0, -0.5151f, 0 },
	{ 6, 0, -0.4759f, 0 },
	{ 7, 0, -0.4606f, 0 },
	{ 8, 0, -0.4701f, 0 },
	{ 9, 0, -0.4953f, 0 },
	{ 10, 0, -0.5319f, 0 },
	{ 11, 0, -0.5752f, 0 },
	{ 12, 0, -0.6208f, 0 },
	{ 13, 0, -0.6642f, 0 },
	{ 14, 0, -0.7007f, 0 },
	{ 15, 0, -0.726f, 0 }
};

NJS_MKEY_A animation_00717FF0_mkey_1_rot_00716690[] = {
	{ 0, 0, 0xFFFFD169, 0xFFFFEC0A },
	{ 15, 0, 0xFFFFD169, 0xFFFFEC0A }
};

NJS_MKEY_A animation_00717FF0_mkey_12_rot_007166B0[] = {
	{ 0, 0, 0xFFFFEB55, 0x7326 },
	{ 1, 0, 0xFFFFEB37, 0x72D9 },
	{ 2, 0, 0xFFFFEAE7, 0x720C },
	{ 3, 0, 0xFFFFEA79, 0x70E6 },
	{ 4, 0, 0xFFFFE9FF, 0x6F91 },
	{ 5, 0, 0xFFFFE98F, 0x6E44 },
	{ 6, 0, 0xFFFFE93C, 0x6D44 },
	{ 7, 0, 0xFFFFE91D, 0x6CDE },
	{ 8, 0, 0xFFFFE930, 0x6D1D },
	{ 9, 0, 0xFFFFE965, 0x6DC4 },
	{ 10, 0, 0xFFFFE9B2, 0x6EAE },
	{ 11, 0, 0xFFFFEA0C, 0x6FB7 },
	{ 12, 0, 0xFFFFEA6B, 0x70C1 },
	{ 13, 0, 0xFFFFEAC5, 0x71B2 },
	{ 14, 0, 0xFFFFEB0F, 0x7275 },
	{ 15, 0, 0xFFFFEB42, 0x72F6 }
};

NJS_MKEY_A animation_00717FF0_mkey_15_rot_007167B0[] = {
	{ 0, 0, 0xC4F, 0xFFFF8745 },
	{ 1, 0, 0xC55, 0xFFFF8769 },
	{ 2, 0, 0xC64, 0xFFFF87C4 },
	{ 3, 0, 0xC75, 0xFFFF883C },
	{ 4, 0, 0xC84, 0xFFFF88B4 },
	{ 5, 0, 0xC8E, 0xFFFF8917 },
	{ 6, 0, 0xC93, 0xFFFF8955 },
	{ 7, 0, 0xC94, 0xFFFF896A },
	{ 8, 0, 0xC93, 0xFFFF895D },
	{ 9, 0, 0xC90, 0xFFFF8937 },
	{ 10, 0, 0xC8B, 0xFFFF88FA },
	{ 11, 0, 0xC82, 0xFFFF88A8 },
	{ 12, 0, 0xC77, 0xFFFF8849 },
	{ 13, 0, 0xC6A, 0xFFFF87EA },
	{ 14, 0, 0xC5D, 0xFFFF8797 },
	{ 15, 0, 0xC53, 0xFFFF875C }
};

NJS_MKEY_A animation_00717FF0_mkey_19_rot_007168B0[] = {
	{ 0, 0, 0xFFFFF330, 0xFFFF86D5 },
	{ 1, 0, 0xFFFFF33B, 0xFFFF86FF },
	{ 2, 0, 0xFFFFF356, 0xFFFF876D },
	{ 3, 0, 0xFFFFF377, 0xFFFF87FC },
	{ 4, 0, 0xFFFFF396, 0xFFFF8888 },
	{ 5, 0, 0xFFFFF3AF, 0xFFFF88EE },
	{ 6, 0, 0xFFFFF3BF, 0xFFFF891B },
	{ 8, 0, 0xFFFFF3C1, 0xFFFF891F },
	{ 9, 0, 0xFFFFF3B7, 0xFFFF8909 },
	{ 10, 0, 0xFFFFF3A7, 0xFFFF88D2 },
	{ 11, 0, 0xFFFFF393, 0xFFFF887A },
	{ 12, 0, 0xFFFFF37B, 0xFFFF880C },
	{ 13, 0, 0xFFFFF361, 0xFFFF879A },
	{ 14, 0, 0xFFFFF349, 0xFFFF8736 },
	{ 15, 0, 0xFFFFF337, 0xFFFF86EF }
};

NJS_MKEY_A animation_00717FF0_mkey_25_rot_007169A0[] = {
	{ 0, 0, 0x2F56, 0xFFFFCDD9 },
	{ 1, 0, 0x2F06, 0xFFFFCDB4 },
	{ 2, 0, 0x2E3E, 0xFFFFCD5D },
	{ 3, 0, 0x2D39, 0xFFFFCCF6 },
	{ 4, 0, 0x2C2E, 0xFFFFCC97 },
	{ 5, 0, 0x2B47, 0xFFFFCC4C },
	{ 6, 0, 0x2AA6, 0xFFFFCC1B },
	{ 7, 0, 0x2A69, 0xFFFFCC0A },
	{ 8, 0, 0x2A8F, 0xFFFFCC15 },
	{ 9, 0, 0x2AF5, 0xFFFFCC33 },
	{ 10, 0, 0x2B8E, 0xFFFFCC62 },
	{ 11, 0, 0x2C4B, 0xFFFFCCA1 },
	{ 12, 0, 0x2D1B, 0xFFFFCCEB },
	{ 13, 0, 0x2DEB, 0xFFFFCD3B },
	{ 14, 0, 0x2EA2, 0xFFFFCD88 },
	{ 15, 0, 0x2F24, 0xFFFFCDC2 }
};

NJS_MKEY_A animation_00717FF0_mkey_26_rot_00716AA0[] = {
	{ 0, 0, 0xFFFFFC9C, 0xFFFFEFA0 },
	{ 1, 0, 0xFFFFFC7A, 0xFFFFEFD2 },
	{ 2, 0, 0xFFFFFC2E, 0xFFFFF04F },
	{ 3, 0, 0xFFFFFBDA, 0xFFFFF0F3 },
	{ 4, 0, 0xFFFFFB92, 0xFFFFF19B },
	{ 5, 0, 0xFFFFFB60, 0xFFFFF22C },
	{ 6, 0, 0xFFFFFB43, 0xFFFFF291 },
	{ 7, 0, 0xFFFFFB3A, 0xFFFFF2B7 },
	{ 8, 0, 0xFFFFFB3F, 0xFFFFF2A0 },
	{ 9, 0, 0xFFFFFB51, 0xFFFFF260 },
	{ 10, 0, 0xFFFFFB6E, 0xFFFFF200 },
	{ 11, 0, 0xFFFFFB99, 0xFFFFF189 },
	{ 12, 0, 0xFFFFFBD1, 0xFFFFF106 },
	{ 13, 0, 0xFFFFFC12, 0xFFFFF083 },
	{ 14, 0, 0xFFFFFC53, 0xFFFFF011 },
	{ 15, 0, 0xFFFFFC87, 0xFFFFEFBF }
};

NJS_MKEY_A animation_00717FF0_mkey_27_rot_00716BA0[] = {
	{ 0, 0, 0xFFFFFC83, 0xFFFFEA9F },
	{ 1, 0, 0xFFFFFC5B, 0xFFFFEAF0 },
	{ 2, 0, 0xFFFFFBFF, 0xFFFFEBBB },
	{ 3, 0, 0xFFFFFB9B, 0xFFFFECC5 },
	{ 4, 0, 0xFFFFFB48, 0xFFFFEDD6 },
	{ 5, 0, 0xFFFFFB0F, 0xFFFFEEBF },
	{ 6, 0, 0xFFFFFAF0, 0xFFFFEF61 },
	{ 7, 0, 0xFFFFFAE6, 0xFFFFEF9D },
	{ 8, 0, 0xFFFFFAEC, 0xFFFFEF78 },
	{ 9, 0, 0xFFFFFAFF, 0xFFFFEF12 },
	{ 10, 0, 0xFFFFFB1F, 0xFFFFEE78 },
	{ 11, 0, 0xFFFFFB50, 0xFFFFEDB8 },
	{ 12, 0, 0xFFFFFB90, 0xFFFFECE4 },
	{ 13, 0, 0xFFFFFBDD, 0xFFFFEC10 },
	{ 14, 0, 0xFFFFFC2C, 0xFFFFEB56 },
	{ 15, 0, 0xFFFFFC6A, 0xFFFFEAD1 }
};

NJS_MKEY_A animation_00717FF0_mkey_30_rot_00716CA0[] = {
	{ 0, 0, 0x18DA, 0 },
	{ 1, 0, 0x180A, 0xB8 },
	{ 2, 0, 0x15F2, 0x295 },
	{ 3, 0, 0x1314, 0x521 },
	{ 4, 0, 0xFF5, 0x7E8 },
	{ 5, 0, 0xD17, 0xA73 },
	{ 6, 0, 0xAFF, 0xC50 },
	{ 7, 0, 0xA2F, 0xD09 },
	{ 8, 0, 0xAB0, 0xC97 },
	{ 9, 0, 0xC09, 0xB64 },
	{ 10, 0, 0xDFD, 0x9A8 },
	{ 11, 0, 0x104D, 0x799 },
	{ 12, 0, 0x12BC, 0x56F },
	{ 13, 0, 0x150C, 0x361 },
	{ 14, 0, 0x1700, 0x1A5 },
	{ 15, 0, 0x1859, 0x72 }
};

NJS_MKEY_A animation_00717FF0_mkey_32_rot_00716DC0[] = {
	{ 0, 0, 0x14C7, 0 },
	{ 15, 0, 0x14C7, 0 }
};

NJS_MKEY_A animation_00717FF0_mkey_31_rot_00716DA0[] = {
	{ 0, 0x1326, 0, 0xFFFFE7F7 },
	{ 15, 0x1326, 0, 0xFFFFE7F7 }
};

NJS_MKEY_A animation_00717FF0_mkey_36_rot_00716DE0[] = {
	{ 0, 0, 0xFFFFF5E3, 0xFFFFE2A1 },
	{ 1, 0, 0xFFFFF635, 0xFFFFE24F },
	{ 2, 0, 0xFFFFF702, 0xFFFFE186 },
	{ 3, 0, 0xFFFFF80D, 0xFFFFE082 },
	{ 4, 0, 0xFFFFF91F, 0xFFFFDF7C },
	{ 5, 0, 0xFFFFFA0C, 0xFFFFDE9C },
	{ 6, 0, 0xFFFFFAB1, 0xFFFFDE01 },
	{ 7, 0, 0xFFFFFAEF, 0xFFFFDDC8 },
	{ 8, 0, 0xFFFFFAC9, 0xFFFFDDEB },
	{ 9, 0, 0xFFFFFA60, 0xFFFFDE4D },
	{ 10, 0, 0xFFFFF9C4, 0xFFFFDEE0 },
	{ 11, 0, 0xFFFFF902, 0xFFFFDF98 },
	{ 12, 0, 0xFFFFF82C, 0xFFFFE064 },
	{ 13, 0, 0xFFFFF757, 0xFFFFE133 },
	{ 14, 0, 0xFFFFF69B, 0xFFFFE1EA },
	{ 15, 0, 0xFFFFF616, 0xFFFFE26E }
};

NJS_MKEY_A animation_00717FF0_mkey_37_rot_00716EE0[] = {
	{ 0, 0, 0xFFFFF2CE, 0xFFFFE3BE },
	{ 1, 0, 0xFFFFF32B, 0xFFFFE3F7 },
	{ 2, 0, 0xFFFFF40D, 0xFFFFE48A },
	{ 3, 0, 0xFFFFF525, 0xFFFFE559 },
	{ 4, 0, 0xFFFFF632, 0xFFFFE63C },
	{ 5, 0, 0xFFFFF70C, 0xFFFFE70B },
	{ 6, 0, 0xFFFFF79C, 0xFFFFE7A0 },
	{ 7, 0, 0xFFFFF7D0, 0xFFFFE7D9 },
	{ 8, 0, 0xFFFFF7B0, 0xFFFFE7B5 },
	{ 9, 0, 0xFFFFF756, 0xFFFFE756 },
	{ 10, 0, 0xFFFFF6CB, 0xFFFFE6CA },
	{ 11, 0, 0xFFFFF616, 0xFFFFE623 },
	{ 12, 0, 0xFFFFF544, 0xFFFFE572 },
	{ 13, 0, 0xFFFFF468, 0xFFFFE4CB },
	{ 14, 0, 0xFFFFF39E, 0xFFFFE43F },
	{ 15, 0, 0xFFFFF308, 0xFFFFE3E1 }
};

NJS_MKEY_A animation_00717FF0_mkey_38_rot_00716FE0[] = {
	{ 0, 0, 0xFFFFFDE3, 0xFFFFE5AA },
	{ 1, 0, 0xFFFFFE42, 0xFFFFE5F8 },
	{ 2, 0, 0xFFFFFF26, 0xFFFFE6C6 },
	{ 3, 0, 0x33, 0xFFFFE7E6 },
	{ 4, 0, 0x128, 0xFFFFE91F },
	{ 5, 0, 0x1E0, 0xFFFFEA39 },
	{ 6, 0, 0x252, 0xFFFFEB01 },
	{ 7, 0, 0x27A, 0xFFFFEB4D },
	{ 8, 0, 0x261, 0xFFFFEB1E },
	{ 9, 0, 0x21C, 0xFFFFEA9E },
	{ 10, 0, 0x1AA, 0xFFFFE9E2 },
	{ 11, 0, 0x10F, 0xFFFFE8FD },
	{ 12, 0, 0x50, 0xFFFFE808 },
	{ 13, 0, 0xFFFFFF7F, 0xFFFFE720 },
	{ 14, 0, 0xFFFFFEB6, 0xFFFFE65E },
	{ 15, 0, 0xFFFFFE1E, 0xFFFFE5DB }
};

NJS_MKEY_A animation_00717FF0_mkey_41_rot_007170E0[] = {
	{ 0, 0, 0, 0 },
	{ 1, 0, 0xA1, 0x120 },
	{ 2, 0, 0x242, 0x409 },
	{ 3, 0, 0x47D, 0x804 },
	{ 4, 0, 0x6EB, 0xC5A },
	{ 5, 0, 0x925, 0x1055 },
	{ 6, 0, 0xAC6, 0x133E },
	{ 7, 0, 0xB68, 0x145F },
	{ 8, 0, 0xB04, 0x13AC },
	{ 9, 0, 0x9F7, 0x11CC },
	{ 10, 0, 0x873, 0xF17 },
	{ 11, 0, 0x6A6, 0xBE0 },
	{ 12, 0, 0x4C1, 0x87E },
	{ 13, 0, 0x2F5, 0x548 },
	{ 14, 0, 0x170, 0x292 },
	{ 15, 0, 0x64, 0xB2 }
};

NJS_MKEY_A animation_00717FF0_mkey_43_rot_00717200[] = {
	{ 0, 0xFFFFEDAB, 0, 0 },
	{ 15, 0xFFFFEDAB, 0, 0 }
};

NJS_MKEY_A animation_00717FF0_mkey_42_rot_007171E0[] = {
	{ 0, 0, 0xFFFFE3E4, 0 },
	{ 15, 0, 0xFFFFE3E4, 0 }
};

NJS_MKEY_A animation_00717FF0_mkey_46_rot_00717220[] = {
	{ 0, 0, 0xFFFFEA72, 0 },
	{ 15, 0, 0xFFFFEA72, 0 }
};

NJS_MKEY_A animation_00717FF0_mkey_47_rot_00717240[] = {
	{ 0, 0xFFFFD490, 0x207E, 0xFFFF9C77 },
	{ 1, 0xFFFFD51E, 0x20CF, 0xFFFF9CA8 },
	{ 2, 0xFFFFD699, 0x21A5, 0xFFFF9D4F },
	{ 3, 0xFFFFD8CA, 0x22D3, 0xFFFF9E93 },
	{ 4, 0xFFFFDB75, 0x2428, 0xFFFFA07B },
	{ 5, 0xFFFFDE49, 0x2571, 0xFFFFA2D2 },
	{ 6, 0xFFFFE09F, 0x2663, 0xFFFFA4EB },
	{ 7, 0xFFFFE1A6, 0x26C8, 0xFFFFA5E4 },
	{ 8, 0xFFFFE102, 0x2689, 0xFFFFA548 },
	{ 9, 0xFFFFDF73, 0x25EE, 0xFFFFA3DB },
	{ 10, 0xFFFFDD5B, 0x2508, 0xFFFFA205 },
	{ 11, 0xFFFFDB25, 0x2401, 0xFFFFA03D },
	{ 12, 0xFFFFD90F, 0x22F6, 0xFFFF9EBF },
	{ 13, 0xFFFFD742, 0x2203, 0xFFFF9DA8 },
	{ 14, 0xFFFFD5D7, 0x2139, 0xFFFF9CF3 },
	{ 15, 0xFFFFD4E7, 0x20B0, 0xFFFF9C94 }
};

NJS_MKEY_A animation_00717FF0_mkey_48_rot_00717340[] = {
	{ 0, 0, 0, 0x1CB0 },
	{ 1, 0, 0, 0x1C42 },
	{ 2, 0, 0, 0x1B1B },
	{ 3, 0, 0, 0x196C },
	{ 4, 0, 0, 0x1772 },
	{ 5, 0, 0, 0x1564 },
	{ 6, 0, 0, 0x13EB },
	{ 7, 0, 0, 0x1332 },
	{ 8, 0, 0, 0x13A5 },
	{ 9, 0, 0, 0x1491 },
	{ 10, 0, 0, 0x160F },
	{ 11, 0, 0, 0x17AE },
	{ 12, 0, 0, 0x1940 },
	{ 13, 0, 0, 0x1A98 },
	{ 14, 0, 0, 0x1BB2 },
	{ 15, 0, 0, 0x1C6C }
};

NJS_MKEY_A animation_00717FF0_mkey_49_rot_00717440[] = {
	{ 0, 0, 0, 0x1BDB },
	{ 1, 0, 0, 0x1B5A },
	{ 2, 0, 0, 0x19FF },
	{ 3, 0, 0, 0x1803 },
	{ 4, 0, 0, 0x159B },
	{ 5, 0, 0, 0x1331 },
	{ 6, 0, 0, 0x1106 },
	{ 7, 0, 0, 0x103D },
	{ 8, 0, 0, 0x10BB },
	{ 9, 0, 0, 0x123A },
	{ 10, 0, 0, 0x13FA },
	{ 11, 0, 0, 0x15E1 },
	{ 12, 0, 0, 0x17B9 },
	{ 13, 0, 0, 0x1965 },
	{ 14, 0, 0, 0x1AB0 },
	{ 15, 0, 0, 0x1B8B }
};

NJS_MKEY_A animation_00717FF0_mkey_52_rot_00717540[] = {
	{ 0, 0x1C1C, 0xFFFFEA68, 0xFFFFE930 },
	{ 1, 0x1C1C, 0xFFFFEAED, 0xFFFFE9B4 },
	{ 2, 0x1C1C, 0xFFFFEC44, 0xFFFFEB0B },
	{ 3, 0x1C1C, 0xFFFFEE19, 0xFFFFECE0 },
	{ 4, 0x1C1C, 0xFFFFF017, 0xFFFFEEDE },
	{ 5, 0x1C1C, 0xFFFFF1EC, 0xFFFFF0B3 },
	{ 6, 0x1C1C, 0xFFFFF343, 0xFFFFF20A },
	{ 7, 0x1C1C, 0xFFFFF3C7, 0xFFFFF28F },
	{ 8, 0x1C1C, 0xFFFFF375, 0xFFFFF23C },
	{ 9, 0x1C1C, 0xFFFFF299, 0xFFFFF160 },
	{ 10, 0x1C1C, 0xFFFFF159, 0xFFFFF021 },
	{ 11, 0x1C1C, 0xFFFFEFDF, 0xFFFFEEA6 },
	{ 12, 0x1C1C, 0xFFFFEE51, 0xFFFFED18 },
	{ 13, 0x1C1C, 0xFFFFECD6, 0xFFFFEB9E },
	{ 14, 0x1C1C, 0xFFFFEB97, 0xFFFFEA5E },
	{ 15, 0x1C1C, 0xFFFFEABB, 0xFFFFE982 }
};

NJS_MKEY_A animation_00717FF0_mkey_56_rot_00717640[] = {
	{ 0, 0, 0xE38, 0 },
	{ 15, 0, 0xE38, 0 }
};

NJS_MKEY_A animation_00717FF0_mkey_57_rot_00717660[] = {
	{ 0, 0xFFFFFB88, 0x541, 0xFFFFAAB2 },
	{ 1, 0xFFFFFB90, 0x55F, 0xFFFFAB55 },
	{ 2, 0xFFFFFBAB, 0x5AB, 0xFFFFAD07 },
	{ 3, 0xFFFFFBDD, 0x615, 0xFFFFAF7D },
	{ 4, 0xFFFFFC28, 0x688, 0xFFFFB260 },
	{ 5, 0xFFFFFC89, 0x6F4, 0xFFFFB569 },
	{ 6, 0xFFFFFCE5, 0x745, 0xFFFFB7EE },
	{ 7, 0xFFFFFD0C, 0x762, 0xFFFFB8EC },
	{ 8, 0xFFFFFCF5, 0x750, 0xFFFFB855 },
	{ 9, 0xFFFFFCB5, 0x71D, 0xFFFFB6A4 },
	{ 10, 0xFFFFFC68, 0x6D2, 0xFFFFB46C },
	{ 11, 0xFFFFFC1E, 0x67B, 0xFFFFB209 },
	{ 12, 0xFFFFFBE4, 0x621, 0xFFFFAFCC },
	{ 13, 0xFFFFFBB8, 0x5CC, 0xFFFFADC7 },
	{ 14, 0xFFFFFB9C, 0x584, 0xFFFFAC29 },
	{ 15, 0xFFFFFB8D, 0x553, 0xFFFFAB16 }
};

NJS_MKEY_A animation_00717FF0_mkey_58_rot_00717760[] = {
	{ 0, 0, 0, 0x1905 },
	{ 1, 0, 0, 0x1884 },
	{ 2, 0, 0, 0x172B },
	{ 3, 0, 0, 0x1535 },
	{ 4, 0, 0, 0x1301 },
	{ 5, 0, 0, 0x1082 },
	{ 6, 0, 0, 0xE6E },
	{ 7, 0, 0, 0xD9E },
	{ 8, 0, 0, 0xE19 },
	{ 9, 0, 0, 0xF7E },
	{ 10, 0, 0, 0x1153 },
	{ 11, 0, 0, 0x1349 },
	{ 12, 0, 0, 0x14F6 },
	{ 13, 0, 0, 0x1692 },
	{ 14, 0, 0, 0x17DB },
	{ 15, 0, 0, 0x18B5 }
};

NJS_MKEY_A animation_00717FF0_mkey_59_rot_00717860[] = {
	{ 0, 0, 0, 0x21B4 },
	{ 1, 0, 0, 0x20FF },
	{ 2, 0, 0, 0x1F1B },
	{ 3, 0, 0, 0x1C59 },
	{ 4, 0, 0, 0x18E9 },
	{ 5, 0, 0, 0x158D },
	{ 6, 0, 0, 0x12BF },
	{ 7, 0, 0, 0x11A3 },
	{ 8, 0, 0, 0x124C },
	{ 9, 0, 0, 0x142F },
	{ 10, 0, 0, 0x16A6 },
	{ 11, 0, 0, 0x1949 },
	{ 12, 0, 0, 0x1C00 },
	{ 13, 0, 0, 0x1E45 },
	{ 14, 0, 0, 0x2012 },
	{ 15, 0, 0, 0x2144 }
};

NJS_MKEY_A animation_00717FF0_mkey_62_rot_00717960[] = {
	{ 0, 0x10B4, 0x3FE, 0xFFFFF569 },
	{ 1, 0x10B4, 0x3E7, 0xFFFFF5E8 },
	{ 2, 0x10B4, 0x3AB, 0xFFFFF730 },
	{ 3, 0x10B4, 0x359, 0xFFFFF8F0 },
	{ 4, 0x10B4, 0x301, 0xFFFFFAD8 },
	{ 5, 0x10B4, 0x2AF, 0xFFFFFC98 },
	{ 6, 0x10B4, 0x274, 0xFFFFFDE0 },
	{ 7, 0x10B4, 0x25C, 0xFFFFFE5F },
	{ 8, 0x10B4, 0x26B, 0xFFFFFE11 },
	{ 9, 0x10B4, 0x291, 0xFFFFFD3E },
	{ 10, 0x10B4, 0x2C9, 0xFFFFFC0C },
	{ 11, 0x10B4, 0x30A, 0xFFFFFAA2 },
	{ 12, 0x10B4, 0x350, 0xFFFFF926 },
	{ 13, 0x10B4, 0x391, 0xFFFFF7BC },
	{ 14, 0x10B4, 0x3C9, 0xFFFFF68A },
	{ 15, 0x10B4, 0x3EF, 0xFFFFF5B7 }
};

NJS_MKEY_A animation_00717FF0_mkey_67_rot_00717A60[] = {
	{ 0, 0, 0, 0xFFFFE4D4 },
	{ 1, 0, 0xC2, 0xFFFFE3CF },
	{ 2, 0, 0x2A3, 0xFFFFE145 },
	{ 3, 0, 0x502, 0xFFFFDE07 },
	{ 4, 0, 0x74E, 0xFFFFDACD },
	{ 5, 0, 0x925, 0xFFFFD81E },
	{ 6, 0, 0xA57, 0xFFFFD650 },
	{ 7, 0, 0xAC6, 0xFFFFD5A6 },
	{ 8, 0, 0xA82, 0xFFFFD60F },
	{ 9, 0, 0x9C3, 0xFFFFD731 },
	{ 10, 0, 0x899, 0xFFFFD8ED },
	{ 11, 0, 0x711, 0xFFFFDB24 },
	{ 12, 0, 0x547, 0xFFFFDDA8 },
	{ 13, 0, 0x368, 0xFFFFE03A },
	{ 14, 0, 0x1B4, 0xFFFFE288 },
	{ 15, 0, 0x78, 0xFFFFE432 }
};

NJS_MDATA2 animation_00717FF0_mdat_00717B60[] = {
	{ animation_00717FF0_mkey_0_pos_00716590, NULL, LengthOfArray<Uint32>(animation_00717FF0_mkey_0_pos_00716590), 0 },
	{ NULL, animation_00717FF0_mkey_1_rot_00716690, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_1_rot_00716690) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_12_rot_007166B0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_12_rot_007166B0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_15_rot_007167B0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_15_rot_007167B0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_19_rot_007168B0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_19_rot_007168B0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_25_rot_007169A0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_25_rot_007169A0) },
	{ NULL, animation_00717FF0_mkey_26_rot_00716AA0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_26_rot_00716AA0) },
	{ NULL, animation_00717FF0_mkey_27_rot_00716BA0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_27_rot_00716BA0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_30_rot_00716CA0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_30_rot_00716CA0) },
	{ NULL, animation_00717FF0_mkey_32_rot_00716DC0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_32_rot_00716DC0) },
	{ NULL, animation_00717FF0_mkey_31_rot_00716DA0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_31_rot_00716DA0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_36_rot_00716DE0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_36_rot_00716DE0) },
	{ NULL, animation_00717FF0_mkey_37_rot_00716EE0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_37_rot_00716EE0) },
	{ NULL, animation_00717FF0_mkey_38_rot_00716FE0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_38_rot_00716FE0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_41_rot_007170E0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_41_rot_007170E0) },
	{ NULL, animation_00717FF0_mkey_43_rot_00717200, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_43_rot_00717200) },
	{ NULL, animation_00717FF0_mkey_42_rot_007171E0, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_42_rot_007171E0) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_46_rot_00717220, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_46_rot_00717220) },
	{ NULL, animation_00717FF0_mkey_47_rot_00717240, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_47_rot_00717240) },
	{ NULL, animation_00717FF0_mkey_48_rot_00717340, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_48_rot_00717340) },
	{ NULL, animation_00717FF0_mkey_49_rot_00717440, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_49_rot_00717440) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_52_rot_00717540, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_52_rot_00717540) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_56_rot_00717640, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_56_rot_00717640) },
	{ NULL, animation_00717FF0_mkey_57_rot_00717660, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_57_rot_00717660) },
	{ NULL, animation_00717FF0_mkey_58_rot_00717760, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_58_rot_00717760) },
	{ NULL, animation_00717FF0_mkey_59_rot_00717860, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_59_rot_00717860) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_62_rot_00717960, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_62_rot_00717960) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, animation_00717FF0_mkey_67_rot_00717A60, 0, LengthOfArray<Uint32>(animation_00717FF0_mkey_67_rot_00717A60) },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 },
	{ NULL, NULL, 0, 0 }
};

NJS_MOTION motion_a_sbjump0 = { animation_00717FF0_mdat_00717B60, 16, NJD_MTYPE_POS_0 | NJD_MTYPE_ANG_1, NJD_MTYPE_LINER | 2 };

NJS_ACTION action_a_sbjump0 = { AMY_OBJECTS[0], &motion_a_sbjump0 };
